
import type { Dictionary } from '@godot/builtins/dictionary';
import type { GDArray } from '@godot/builtins/gd_array';
import type { PackedColorArray } from '@godot/builtins/packed_color_array';
import type { PackedFloat32Array } from '@godot/builtins/packed_float32_array';
import type { PackedFloat64Array } from '@godot/builtins/packed_float64_array';
import type { PackedInt32Array } from '@godot/builtins/packed_int32_array';
import type { PackedInt64Array } from '@godot/builtins/packed_int64_array';
import type { PackedVector2Array } from '@godot/builtins/packed_vector2_array';
import type { PackedVector3Array } from '@godot/builtins/packed_vector3_array';
import type { PackedVector4Array } from '@godot/builtins/packed_vector4_array';


export declare class PackedByteArray {
    constructor();
    constructor(_from: PackedByteArray);
    constructor(_from: GDArray);


    public get(index: number): number;
    public set(index: number, value: number): void;
    public size(): number;
    public is_empty(): boolean;
    public push_back(value: number): boolean;
    public append(value: number): boolean;
    public append_array(array: PackedByteArray): void;
    public remove_at(index: number): void;
    public insert(at_index: number, value: number): number;
    public fill(value: number): void;
    public resize(new_size: number): number;
    public clear(): void;
    public has(value: number): boolean;
    public reverse(): void;
    public slice(begin: number, end: number): PackedByteArray;
    public sort(): void;
    public bsearch(value: number, before: boolean): number;
    public duplicate(): PackedByteArray;
    public find(value: number, _from: number): number;
    public rfind(value: number, _from: number): number;
    public count(value: number): number;
    public erase(value: number): boolean;
    public get_string_from_ascii(): GDString;
    public get_string_from_utf8(): GDString;
    public get_string_from_utf16(): GDString;
    public get_string_from_utf32(): GDString;
    public get_string_from_wchar(): GDString;
    public get_string_from_multibyte_char(encoding: GDString | StringName | string): GDString;
    public hex_encode(): GDString;
    public compress(compression_mode: number): PackedByteArray;
    public decompress(buffer_size: number, compression_mode: number): PackedByteArray;
    public decompress_dynamic(max_output_size: number, compression_mode: number): PackedByteArray;
    public decode_u8(byte_offset: number): number;
    public decode_s8(byte_offset: number): number;
    public decode_u16(byte_offset: number): number;
    public decode_s16(byte_offset: number): number;
    public decode_u32(byte_offset: number): number;
    public decode_s32(byte_offset: number): number;
    public decode_u64(byte_offset: number): number;
    public decode_s64(byte_offset: number): number;
    public decode_half(byte_offset: number): number;
    public decode_float(byte_offset: number): number;
    public decode_double(byte_offset: number): number;
    public has_encoded_var(byte_offset: number, allow_objects: boolean): boolean;
    public decode_var(byte_offset: number, allow_objects: boolean): any;
    public decode_var_size(byte_offset: number, allow_objects: boolean): number;
    public to_int32_array(): PackedInt32Array;
    public to_int64_array(): PackedInt64Array;
    public to_float32_array(): PackedFloat32Array;
    public to_float64_array(): PackedFloat64Array;
    public to_vector2_array(): PackedVector2Array;
    public to_vector3_array(): PackedVector3Array;
    public to_vector4_array(): PackedVector4Array;
    public to_color_array(): PackedColorArray;
    public bswap16(offset: number, count: number): void;
    public bswap32(offset: number, count: number): void;
    public bswap64(offset: number, count: number): void;
    public encode_u8(byte_offset: number, value: number): void;
    public encode_s8(byte_offset: number, value: number): void;
    public encode_u16(byte_offset: number, value: number): void;
    public encode_s16(byte_offset: number, value: number): void;
    public encode_u32(byte_offset: number, value: number): void;
    public encode_s32(byte_offset: number, value: number): void;
    public encode_u64(byte_offset: number, value: number): void;
    public encode_s64(byte_offset: number, value: number): void;
    public encode_half(byte_offset: number, value: number): void;
    public encode_float(byte_offset: number, value: number): void;
    public encode_double(byte_offset: number, value: number): void;
    public encode_var(byte_offset: number, value: any, allow_objects: boolean): number;

}