

declare global {
    declare class StringName {
        constructor();
        constructor(_from: GDString | StringName | string);
        constructor(_from: GDString | StringName | string);


        public casecmp_to(to: GDString | StringName | string): number;
        public nocasecmp_to(to: GDString | StringName | string): number;
        public naturalcasecmp_to(to: GDString | StringName | string): number;
        public naturalnocasecmp_to(to: GDString | StringName | string): number;
        public filecasecmp_to(to: GDString | StringName | string): number;
        public filenocasecmp_to(to: GDString | StringName | string): number;
        public length(): number;
        public substr(_from: number, len: number): GDString;
        public get_slice(delimiter: GDString | StringName | string, slice: number): GDString;
        public get_slicec(delimiter: number, slice: number): GDString;
        public get_slice_count(delimiter: GDString | StringName | string): number;
        public find(what: GDString | StringName | string, _from: number): number;
        public findn(what: GDString | StringName | string, _from: number): number;
        public count(what: GDString | StringName | string, _from: number, to: number): number;
        public countn(what: GDString | StringName | string, _from: number, to: number): number;
        public rfind(what: GDString | StringName | string, _from: number): number;
        public rfindn(what: GDString | StringName | string, _from: number): number;
        public match(expr: GDString | StringName | string): boolean;
        public matchn(expr: GDString | StringName | string): boolean;
        public begins_with(text: GDString | StringName | string): boolean;
        public ends_with(text: GDString | StringName | string): boolean;
        public is_subsequence_of(text: GDString | StringName | string): boolean;
        public is_subsequence_ofn(text: GDString | StringName | string): boolean;
        public bigrams(): PackedStringArray;
        public similarity(text: GDString | StringName | string): number;
        public format(values: any, placeholder: GDString | StringName | string): GDString;
        public replace(what: GDString | StringName | string, forwhat: GDString | StringName | string): GDString;
        public replacen(what: GDString | StringName | string, forwhat: GDString | StringName | string): GDString;
        public replace_char(key: number, _with: number): GDString;
        public replace_chars(keys: GDString | StringName | string, _with: number): GDString;
        public remove_char(what: number): GDString;
        public remove_chars(chars: GDString | StringName | string): GDString;
        public repeat(count: number): GDString;
        public reverse(): GDString;
        public insert(position: number, what: GDString | StringName | string): GDString;
        public erase(position: number, chars: number): GDString;
        public capitalize(): GDString;
        public to_camel_case(): GDString;
        public to_pascal_case(): GDString;
        public to_snake_case(): GDString;
        public to_kebab_case(): GDString;
        public split(delimiter: GDString | StringName | string, allowEmpty: boolean, maxsplit: number): PackedStringArray;
        public rsplit(delimiter: GDString | StringName | string, allowEmpty: boolean, maxsplit: number): PackedStringArray;
        public split_floats(delimiter: GDString | StringName | string, allowEmpty: boolean): PackedFloat64Array;
        public join(parts: PackedStringArray): GDString;
        public to_upper(): GDString;
        public to_lower(): GDString;
        public left(length: number): GDString;
        public right(length: number): GDString;
        public strip_edges(left: boolean, right: boolean): GDString;
        public strip_escapes(): GDString;
        public lstrip(chars: GDString | StringName | string): GDString;
        public rstrip(chars: GDString | StringName | string): GDString;
        public get_extension(): GDString;
        public get_basename(): GDString;
        public path_join(path: GDString | StringName | string): GDString;
        public unicode_at(at: number): number;
        public indent(prefix: GDString | StringName | string): GDString;
        public dedent(): GDString;
        public md5_text(): GDString;
        public sha1_text(): GDString;
        public sha256_text(): GDString;
        public md5_buffer(): PackedByteArray;
        public sha1_buffer(): PackedByteArray;
        public sha256_buffer(): PackedByteArray;
        public is_empty(): boolean;
        public contains(what: GDString | StringName | string): boolean;
        public containsn(what: GDString | StringName | string): boolean;
        public is_absolute_path(): boolean;
        public is_relative_path(): boolean;
        public simplify_path(): GDString;
        public get_base_dir(): GDString;
        public get_file(): GDString;
        public xml_escape(escapeQuotes: boolean): GDString;
        public xml_unescape(): GDString;
        public uri_encode(): GDString;
        public uri_decode(): GDString;
        public uri_file_decode(): GDString;
        public c_escape(): GDString;
        public c_unescape(): GDString;
        public json_escape(): GDString;
        public validate_node_name(): GDString;
        public validate_filename(): GDString;
        public is_valid_ascii_identifier(): boolean;
        public is_valid_unicode_identifier(): boolean;
        public is_valid_identifier(): boolean;
        public is_valid_int(): boolean;
        public is_valid_float(): boolean;
        public is_valid_hex_number(withPrefix: boolean): boolean;
        public is_valid_html_color(): boolean;
        public is_valid_ip_address(): boolean;
        public is_valid_filename(): boolean;
        public to_int(): number;
        public to_float(): number;
        public hex_to_int(): number;
        public bin_to_int(): number;
        public lpad(minLength: number, character: GDString | StringName | string): GDString;
        public rpad(minLength: number, character: GDString | StringName | string): GDString;
        public pad_decimals(digits: number): GDString;
        public pad_zeros(digits: number): GDString;
        public trim_prefix(prefix: GDString | StringName | string): GDString;
        public trim_suffix(suffix: GDString | StringName | string): GDString;
        public to_ascii_buffer(): PackedByteArray;
        public to_utf8_buffer(): PackedByteArray;
        public to_utf16_buffer(): PackedByteArray;
        public to_utf32_buffer(): PackedByteArray;
        public to_wchar_buffer(): PackedByteArray;
        public to_multibyte_char_buffer(encoding: GDString | StringName | string): PackedByteArray;
        public hex_decode(): PackedByteArray;
        public hash(): number;

    }
}

export {};