
import type { AABB } from '@godot/builtins/aabb';
import type { Basis } from '@godot/builtins/basis';
import type { Callable } from '@godot/builtins/callable';
import type { Color } from '@godot/builtins/color';
import type { Dictionary } from '@godot/builtins/dictionary';
import type { GDArray } from '@godot/builtins/gd_array';
import type { GDString } from '@godot/classes/gd_string';
import type { NodePath } from '@godot/builtins/node_path';
import type { PackedByteArray } from '@godot/builtins/packed_byte_array';
import type { PackedColorArray } from '@godot/builtins/packed_color_array';
import type { PackedFloat32Array } from '@godot/builtins/packed_float32_array';
import type { PackedFloat64Array } from '@godot/builtins/packed_float64_array';
import type { PackedInt32Array } from '@godot/builtins/packed_int32_array';
import type { PackedInt64Array } from '@godot/builtins/packed_int64_array';
import type { PackedStringArray } from '@godot/builtins/packed_string_array';
import type { PackedVector2Array } from '@godot/builtins/packed_vector2_array';
import type { PackedVector3Array } from '@godot/builtins/packed_vector3_array';
import type { PackedVector4Array } from '@godot/builtins/packed_vector4_array';
import type { Plane } from '@godot/builtins/plane';
import type { Projection } from '@godot/builtins/projection';
import type { Quaternion } from '@godot/builtins/quaternion';
import type { RID } from '@godot/builtins/rid';
import type { Rect2 } from '@godot/builtins/rect2';
import type { Rect2i } from '@godot/builtins/rect2i';
import type { Signal } from '@godot/builtins/signal';
import type { Transform2D } from '@godot/builtins/transform2d';
import type { Transform3D } from '@godot/builtins/transform3d';
import type { Vector2 } from '@godot/builtins/vector2';
import type { Vector2i } from '@godot/builtins/vector2i';
import type { Vector3 } from '@godot/builtins/vector3';
import type { Vector3i } from '@godot/builtins/vector3i';
import type { Vector4 } from '@godot/builtins/vector4';
import type { Vector4i } from '@godot/builtins/vector4i';


export declare class StringName {
    constructor();
    constructor(_from: GDString | StringName | string);
    constructor(_from: GDString | StringName | string);


    public casecmp_to(to: GDString | StringName | string): number;
    public nocasecmp_to(to: GDString | StringName | string): number;
    public naturalcasecmp_to(to: GDString | StringName | string): number;
    public naturalnocasecmp_to(to: GDString | StringName | string): number;
    public filecasecmp_to(to: GDString | StringName | string): number;
    public filenocasecmp_to(to: GDString | StringName | string): number;
    public length(): number;
    public substr(_from: number, len: number): GDString;
    public get_slice(delimiter: GDString | StringName | string, slice: number): GDString;
    public get_slicec(delimiter: number, slice: number): GDString;
    public get_slice_count(delimiter: GDString | StringName | string): number;
    public find(what: GDString | StringName | string, _from: number): number;
    public findn(what: GDString | StringName | string, _from: number): number;
    public count(what: GDString | StringName | string, _from: number, to: number): number;
    public countn(what: GDString | StringName | string, _from: number, to: number): number;
    public rfind(what: GDString | StringName | string, _from: number): number;
    public rfindn(what: GDString | StringName | string, _from: number): number;
    public match(expr: GDString | StringName | string): boolean;
    public matchn(expr: GDString | StringName | string): boolean;
    public begins_with(text: GDString | StringName | string): boolean;
    public ends_with(text: GDString | StringName | string): boolean;
    public is_subsequence_of(text: GDString | StringName | string): boolean;
    public is_subsequence_ofn(text: GDString | StringName | string): boolean;
    public bigrams(): PackedStringArray;
    public similarity(text: GDString | StringName | string): number;
    public format(values: any, placeholder: GDString | StringName | string): GDString;
    public replace(what: GDString | StringName | string, forwhat: GDString | StringName | string): GDString;
    public replacen(what: GDString | StringName | string, forwhat: GDString | StringName | string): GDString;
    public replace_char(key: number, _with: number): GDString;
    public replace_chars(keys: GDString | StringName | string, _with: number): GDString;
    public remove_char(what: number): GDString;
    public remove_chars(chars: GDString | StringName | string): GDString;
    public repeat(count: number): GDString;
    public reverse(): GDString;
    public insert(position: number, what: GDString | StringName | string): GDString;
    public erase(position: number, chars: number): GDString;
    public capitalize(): GDString;
    public to_camel_case(): GDString;
    public to_pascal_case(): GDString;
    public to_snake_case(): GDString;
    public to_kebab_case(): GDString;
    public split(delimiter: GDString | StringName | string, allow_empty: boolean, maxsplit: number): PackedStringArray;
    public rsplit(delimiter: GDString | StringName | string, allow_empty: boolean, maxsplit: number): PackedStringArray;
    public split_floats(delimiter: GDString | StringName | string, allow_empty: boolean): PackedFloat64Array;
    public join(parts: PackedStringArray): GDString;
    public to_upper(): GDString;
    public to_lower(): GDString;
    public left(length: number): GDString;
    public right(length: number): GDString;
    public strip_edges(left: boolean, right: boolean): GDString;
    public strip_escapes(): GDString;
    public lstrip(chars: GDString | StringName | string): GDString;
    public rstrip(chars: GDString | StringName | string): GDString;
    public get_extension(): GDString;
    public get_basename(): GDString;
    public path_join(path: GDString | StringName | string): GDString;
    public unicode_at(at: number): number;
    public indent(prefix: GDString | StringName | string): GDString;
    public dedent(): GDString;
    public md5_text(): GDString;
    public sha1_text(): GDString;
    public sha256_text(): GDString;
    public md5_buffer(): PackedByteArray;
    public sha1_buffer(): PackedByteArray;
    public sha256_buffer(): PackedByteArray;
    public is_empty(): boolean;
    public contains(what: GDString | StringName | string): boolean;
    public containsn(what: GDString | StringName | string): boolean;
    public is_absolute_path(): boolean;
    public is_relative_path(): boolean;
    public simplify_path(): GDString;
    public get_base_dir(): GDString;
    public get_file(): GDString;
    public xml_escape(escape_quotes: boolean): GDString;
    public xml_unescape(): GDString;
    public uri_encode(): GDString;
    public uri_decode(): GDString;
    public uri_file_decode(): GDString;
    public c_escape(): GDString;
    public c_unescape(): GDString;
    public json_escape(): GDString;
    public validate_node_name(): GDString;
    public validate_filename(): GDString;
    public is_valid_ascii_identifier(): boolean;
    public is_valid_unicode_identifier(): boolean;
    public is_valid_identifier(): boolean;
    public is_valid_int(): boolean;
    public is_valid_float(): boolean;
    public is_valid_hex_number(with_prefix: boolean): boolean;
    public is_valid_html_color(): boolean;
    public is_valid_ip_address(): boolean;
    public is_valid_filename(): boolean;
    public to_int(): number;
    public to_float(): number;
    public hex_to_int(): number;
    public bin_to_int(): number;
    public lpad(min_length: number, character: GDString | StringName | string): GDString;
    public rpad(min_length: number, character: GDString | StringName | string): GDString;
    public pad_decimals(digits: number): GDString;
    public pad_zeros(digits: number): GDString;
    public trim_prefix(prefix: GDString | StringName | string): GDString;
    public trim_suffix(suffix: GDString | StringName | string): GDString;
    public to_ascii_buffer(): PackedByteArray;
    public to_utf8_buffer(): PackedByteArray;
    public to_utf16_buffer(): PackedByteArray;
    public to_utf32_buffer(): PackedByteArray;
    public to_wchar_buffer(): PackedByteArray;
    public to_multibyte_char_buffer(encoding: GDString | StringName | string): PackedByteArray;
    public hex_decode(): PackedByteArray;
    public hash(): number;

    public equals(right: any): boolean;
    public not_equals(right: any): boolean;
    public module(right: any): GDString;
    public op_not(): boolean;
    public module(right: boolean): GDString;
    public module(right: number): GDString;
    public module(right: number): GDString;
    public equals(right: GDString): boolean;
    public not_equals(right: GDString): boolean;
    public add(right: GDString): GDString;
    public module(right: GDString): GDString;
    public in_op(right: GDString): boolean;
    public module(right: Vector2): GDString;
    public module(right: Vector2i): GDString;
    public module(right: Rect2): GDString;
    public module(right: Rect2i): GDString;
    public module(right: Vector3): GDString;
    public module(right: Vector3i): GDString;
    public module(right: Transform2D): GDString;
    public module(right: Vector4): GDString;
    public module(right: Vector4i): GDString;
    public module(right: Plane): GDString;
    public module(right: Quaternion): GDString;
    public module(right: AABB): GDString;
    public module(right: Basis): GDString;
    public module(right: Transform3D): GDString;
    public module(right: Projection): GDString;
    public module(right: Color): GDString;
    public equals(right: StringName): boolean;
    public not_equals(right: StringName): boolean;
    public less(right: StringName): boolean;
    public less_equal(right: StringName): boolean;
    public greater(right: StringName): boolean;
    public greater_equal(right: StringName): boolean;
    public add(right: StringName): GDString;
    public module(right: StringName): GDString;
    public in_op(right: StringName): boolean;
    public module(right: NodePath): GDString;
    public module(right: RID): GDString;
    public module(right: GodotObject): GDString;
    public in_op(right: GodotObject): boolean;
    public module(right: Callable): GDString;
    public module(right: Signal): GDString;
    public module(right: Dictionary): GDString;
    public in_op(right: Dictionary): boolean;
    public module(right: GDArray): GDString;
    public in_op(right: GDArray): boolean;
    public module(right: PackedByteArray): GDString;
    public module(right: PackedInt32Array): GDString;
    public module(right: PackedInt64Array): GDString;
    public module(right: PackedFloat32Array): GDString;
    public module(right: PackedFloat64Array): GDString;
    public module(right: PackedStringArray): GDString;
    public in_op(right: PackedStringArray): boolean;
    public module(right: PackedVector2Array): GDString;
    public module(right: PackedVector3Array): GDString;
    public module(right: PackedColorArray): GDString;
    public module(right: PackedVector4Array): GDString;

}