export const GDExtensionVariantType = {
  GDEXTENSION_VARIANT_TYPE_NIL: 0,

  /*  atomic types */
  GDEXTENSION_VARIANT_TYPE_BOOL: 1,
  GDEXTENSION_VARIANT_TYPE_INT: 2,
  GDEXTENSION_VARIANT_TYPE_FLOAT: 3,
  GDEXTENSION_VARIANT_TYPE_STRING: 4,

  /* math types */
  GDEXTENSION_VARIANT_TYPE_VECTOR2: 5,
  GDEXTENSION_VARIANT_TYPE_VECTOR2I: 6,
  GDEXTENSION_VARIANT_TYPE_RECT2: 7,
  GDEXTENSION_VARIANT_TYPE_RECT2I: 8,
  GDEXTENSION_VARIANT_TYPE_VECTOR3: 9,
  GDEXTENSION_VARIANT_TYPE_VECTOR3I: 10,
  GDEXTENSION_VARIANT_TYPE_TRANSFORM2D: 11,
  GDEXTENSION_VARIANT_TYPE_VECTOR4: 12,
  GDEXTENSION_VARIANT_TYPE_VECTOR4I: 13,
  GDEXTENSION_VARIANT_TYPE_PLANE: 14,
  GDEXTENSION_VARIANT_TYPE_QUATERNION: 15,
  GDEXTENSION_VARIANT_TYPE_AABB: 16,
  GDEXTENSION_VARIANT_TYPE_BASIS: 17,
  GDEXTENSION_VARIANT_TYPE_TRANSFORM3D: 18,
  GDEXTENSION_VARIANT_TYPE_PROJECTION: 19,

  /* misc types */
  GDEXTENSION_VARIANT_TYPE_COLOR: 20,
  GDEXTENSION_VARIANT_TYPE_STRING_NAME: 21,
  GDEXTENSION_VARIANT_TYPE_NODE_PATH: 22,
  GDEXTENSION_VARIANT_TYPE_RID: 23,
  GDEXTENSION_VARIANT_TYPE_OBJECT: 24,
  GDEXTENSION_VARIANT_TYPE_CALLABLE: 25,
  GDEXTENSION_VARIANT_TYPE_SIGNAL: 26,
  GDEXTENSION_VARIANT_TYPE_DICTIONARY: 27,
  GDEXTENSION_VARIANT_TYPE_ARRAY: 28,

  /* typed arrays */
  GDEXTENSION_VARIANT_TYPE_PACKED_BYTE_ARRAY: 29,
  GDEXTENSION_VARIANT_TYPE_PACKED_INT32_ARRAY: 30,
  GDEXTENSION_VARIANT_TYPE_PACKED_INT64_ARRAY: 31,
  GDEXTENSION_VARIANT_TYPE_PACKED_FLOAT32_ARRAY: 32,
  GDEXTENSION_VARIANT_TYPE_PACKED_FLOAT64_ARRAY: 33,
  GDEXTENSION_VARIANT_TYPE_PACKED_STRING_ARRAY: 34,
  GDEXTENSION_VARIANT_TYPE_PACKED_VECTOR2_ARRAY: 35,
  GDEXTENSION_VARIANT_TYPE_PACKED_VECTOR3_ARRAY: 36,
  GDEXTENSION_VARIANT_TYPE_PACKED_COLOR_ARRAY: 37,
  GDEXTENSION_VARIANT_TYPE_PACKED_VECTOR4_ARRAY: 38,

  GDEXTENSION_VARIANT_TYPE_VARIANT_MAX: 39
}
