
import { SpriteFrames } from "@godot/classes/sprite_frames";
import { Node2D } from "@godot/classes/node2d";
export declare class AnimatedSprite2D extends Node2D{
  public set_sprite_frames(_sprite_frames: SpriteFrames): void;
  public get_sprite_frames(): SpriteFrames;
  public set_animation(_name: GDString | StringName | string): void;
  public get_animation(): StringName;
  public set_autoplay(_name: GDString | StringName | string): void;
  public get_autoplay(): String;
  public is_playing(): boolean;
  public play(_name: GDString | StringName | string = "", _custom_speed: number = 1.0, _from_end: boolean = false): void;
  public play_backwards(_name: GDString | StringName | string = ""): void;
  public pause(): void;
  public stop(): void;
  public set_centered(_centered: boolean): void;
  public is_centered(): boolean;
  public set_offset(_offset: Vector2): void;
  public get_offset(): Vector2;
  public set_flip_h(_flip_h: boolean): void;
  public is_flipped_h(): boolean;
  public set_flip_v(_flip_v: boolean): void;
  public is_flipped_v(): boolean;
  public set_frame(_frame: number): void;
  public get_frame(): number;
  public set_frame_progress(_progress: number): void;
  public get_frame_progress(): number;
  public set_frame_and_progress(_frame: number, _progress: number): void;
  public set_speed_scale(_speed_scale: number): void;
  public get_speed_scale(): number;
  public get_playing_speed(): number;
  public get sprite_frames(): SpriteFrames;
  public set sprite_frames(value): void;
  public get animation(): StringName;
  public set animation(value): void;
  public get autoplay(): StringName;
  public set autoplay(value): void;
  public get frame(): number;
  public set frame(value): void;
  public get frame_progress(): number;
  public set frame_progress(value): void;
  public get speed_scale(): number;
  public set speed_scale(value): void;
  public get centered(): boolean;
  public set centered(value): void;
  public get offset(): Vector2;
  public set offset(value): void;
  public get flip_h(): boolean;
  public set flip_h(value): void;
  public get flip_v(): boolean;
  public set flip_v(value): void;
  public get sprite_frames_changed(): Signal;
  public get animation_changed(): Signal;
  public get frame_changed(): Signal;
  public get animation_looped(): Signal;
  public get animation_finished(): Signal;
}