
import { SpriteFrames } from "@godot/classes/sprite_frames";
import { SpriteBase3D } from "@godot/classes/sprite_base3d";
export declare class AnimatedSprite3D extends SpriteBase3D{
  public set_sprite_frames(_sprite_frames: SpriteFrames): void;
  public get_sprite_frames(): SpriteFrames;
  public set_animation(_name: GDString | StringName | string): void;
  public get_animation(): StringName;
  public set_autoplay(_name: GDString | StringName | string): void;
  public get_autoplay(): String;
  public is_playing(): boolean;
  public play(_name: GDString | StringName | string = "", _custom_speed: number = 1.0, _from_end: boolean = false): void;
  public play_backwards(_name: GDString | StringName | string = ""): void;
  public pause(): void;
  public stop(): void;
  public set_frame(_frame: number): void;
  public get_frame(): number;
  public set_frame_progress(_progress: number): void;
  public get_frame_progress(): number;
  public set_frame_and_progress(_frame: number, _progress: number): void;
  public set_speed_scale(_speed_scale: number): void;
  public get_speed_scale(): number;
  public get_playing_speed(): number;
  public get sprite_frames(): SpriteFrames;
  public set sprite_frames(value): void;
  public get animation(): StringName;
  public set animation(value): void;
  public get autoplay(): StringName;
  public set autoplay(value): void;
  public get frame(): number;
  public set frame(value): void;
  public get frame_progress(): number;
  public set frame_progress(value): void;
  public get speed_scale(): number;
  public set speed_scale(value): void;
  public get sprite_frames_changed(): Signal;
  public get animation_changed(): Signal;
  public get frame_changed(): Signal;
  public get animation_looped(): Signal;
  public get animation_finished(): Signal;
}