
import { AudioStreamPlayback } from "@godot/classes/audio_stream_playback";
import { Node2D } from "@godot/classes/node2d";
import { AudioStream } from "@godot/classes/audio_stream";


export declare class AudioStreamPlayer2D extends Node2D{
  public set_stream(_stream: AudioStream): void;
  public get_stream(): AudioStream;
  public set_volume_db(_volume_db: number): void;
  public get_volume_db(): number;
  public set_pitch_scale(_pitch_scale: number): void;
  public get_pitch_scale(): number;
  public play(_from_position: number): void;
  public seek(_to_position: number): void;
  public stop(): void;
  public is_playing(): boolean;
  public get_playback_position(): number;
  public set_bus(_bus: GDString | StringName | string): void;
  public get_bus(): StringName;
  public set_autoplay(_enable: boolean): void;
  public is_autoplay_enabled(): boolean;
  public set_max_distance(_pixels: number): void;
  public get_max_distance(): number;
  public set_attenuation(_curve: number): void;
  public get_attenuation(): number;
  public set_area_mask(_mask: number): void;
  public get_area_mask(): number;
  public set_stream_paused(_pause: boolean): void;
  public get_stream_paused(): boolean;
  public set_max_polyphony(_max_polyphony: number): void;
  public get_max_polyphony(): number;
  public set_panning_strength(_panning_strength: number): void;
  public get_panning_strength(): number;
  public has_stream_playback(): boolean;
  public get_stream_playback(): AudioStreamPlayback;
  public set_playback_type(_playback_type: number): void;
  public get_playback_type(): number;
  public get stream(): AudioStream;
  public set stream(value): void;
  public get volume_db(): number;
  public set volume_db(value): void;
  public get pitch_scale(): number;
  public set pitch_scale(value): void;
  public get playing(): boolean;
  public set playing(value): void;
  public get autoplay(): boolean;
  public set autoplay(value): void;
  public get stream_paused(): boolean;
  public set stream_paused(value): void;
  public get max_distance(): number;
  public set max_distance(value): void;
  public get attenuation(): number;
  public set attenuation(value): void;
  public get max_polyphony(): number;
  public set max_polyphony(value): void;
  public get panning_strength(): number;
  public set panning_strength(value): void;
  public get bus(): StringName;
  public set bus(value): void;
  public get area_mask(): number;
  public set area_mask(value): void;
  public get playback_type(): number;
  public set playback_type(value): void;
  public get finished(): Signal;
}