
import { BaseButton } from "@godot/classes/base_button";
import { Texture2D } from "@godot/classes/texture2d";
export declare class Button extends BaseButton{
  public set_text(_text: GDString | StringName | string): void;
  public get_text(): String;
  public set_text_overrun_behavior(_overrun_behavior: number): void;
  public get_text_overrun_behavior(): number;
  public set_autowrap_mode(_autowrap_mode: number): void;
  public get_autowrap_mode(): number;
  public set_text_direction(_direction: number): void;
  public get_text_direction(): number;
  public set_language(_language: GDString | StringName | string): void;
  public get_language(): String;
  public set_button_icon(_texture: Texture2D): void;
  public get_button_icon(): Texture2D;
  public set_flat(_enabled: boolean): void;
  public is_flat(): boolean;
  public set_clip_text(_enabled: boolean): void;
  public get_clip_text(): boolean;
  public set_text_alignment(_alignment: number): void;
  public get_text_alignment(): number;
  public set_icon_alignment(_icon_alignment: number): void;
  public get_icon_alignment(): number;
  public set_vertical_icon_alignment(_vertical_icon_alignment: number): void;
  public get_vertical_icon_alignment(): number;
  public set_expand_icon(_enabled: boolean): void;
  public is_expand_icon(): boolean;
  public get text(): String;
  public set text(value): void;
  public get icon(): Texture2D;
  public set icon(value): void;
  public get flat(): boolean;
  public set flat(value): void;
  public get alignment(): number;
  public set alignment(value): void;
  public get text_overrun_behavior(): number;
  public set text_overrun_behavior(value): void;
  public get autowrap_mode(): number;
  public set autowrap_mode(value): void;
  public get clip_text(): boolean;
  public set clip_text(value): void;
  public get icon_alignment(): number;
  public set icon_alignment(value): void;
  public get vertical_icon_alignment(): number;
  public set vertical_icon_alignment(value): void;
  public get expand_icon(): boolean;
  public set expand_icon(value): void;
  public get text_direction(): number;
  public set text_direction(value): void;
  public get language(): String;
  public set language(value): void;
}