
import { CameraAttributes } from "@godot/classes/camera_attributes";
export declare class CameraAttributesPractical extends CameraAttributes{
  public set_dof_blur_far_enabled(_enabled: boolean): void;
  public is_dof_blur_far_enabled(): boolean;
  public set_dof_blur_far_distance(_distance: number): void;
  public get_dof_blur_far_distance(): number;
  public set_dof_blur_far_transition(_distance: number): void;
  public get_dof_blur_far_transition(): number;
  public set_dof_blur_near_enabled(_enabled: boolean): void;
  public is_dof_blur_near_enabled(): boolean;
  public set_dof_blur_near_distance(_distance: number): void;
  public get_dof_blur_near_distance(): number;
  public set_dof_blur_near_transition(_distance: number): void;
  public get_dof_blur_near_transition(): number;
  public set_dof_blur_amount(_amount: number): void;
  public get_dof_blur_amount(): number;
  public set_auto_exposure_max_sensitivity(_max_sensitivity: number): void;
  public get_auto_exposure_max_sensitivity(): number;
  public set_auto_exposure_min_sensitivity(_min_sensitivity: number): void;
  public get_auto_exposure_min_sensitivity(): number;
  public get dof_blur_far_enabled(): boolean;
  public set dof_blur_far_enabled(value): void;
  public get dof_blur_far_distance(): number;
  public set dof_blur_far_distance(value): void;
  public get dof_blur_far_transition(): number;
  public set dof_blur_far_transition(value): void;
  public get dof_blur_near_enabled(): boolean;
  public set dof_blur_near_enabled(value): void;
  public get dof_blur_near_distance(): number;
  public set dof_blur_near_distance(value): void;
  public get dof_blur_near_transition(): number;
  public set dof_blur_near_transition(value): void;
  public get dof_blur_amount(): number;
  public set dof_blur_amount(value): void;
  public get auto_exposure_min_sensitivity(): number;
  public set auto_exposure_min_sensitivity(value): void;
  public get auto_exposure_max_sensitivity(): number;
  public set auto_exposure_max_sensitivity(value): void;
}