
import type { GodotObject } from '@godot/classes/godot_object';
import type { Image } from '@godot/classes/image';
import type { Resource } from '@godot/classes/resource';
import type { Texture2D } from '@godot/classes/texture2d';


export declare class DisplayServer extends GodotObject {


    public has_feature(feature: number): boolean;
    public get_name(): GDString;
    public help_set_search_callbacks(searchCallback: Callable | Function, actionCallback: Callable | Function): void;
    public global_menu_set_popup_callbacks(menuRoot: GDString | StringName | string, openCallback: Callable | Function, closeCallback: Callable | Function): void;
    public global_menu_add_submenu_item(menuRoot: GDString | StringName | string, label: GDString | StringName | string, submenu: GDString | StringName | string, index: number = -1): number;
    public global_menu_add_item(menuRoot: GDString | StringName | string, label: GDString | StringName | string, callback: Callable | Function = Callable(), keyCallback: Callable | Function = Callable(), tag: any = null, accelerator: number = 0, index: number = -1): number;
    public global_menu_add_check_item(menuRoot: GDString | StringName | string, label: GDString | StringName | string, callback: Callable | Function = Callable(), keyCallback: Callable | Function = Callable(), tag: any = null, accelerator: number = 0, index: number = -1): number;
    public global_menu_add_icon_item(menuRoot: GDString | StringName | string, icon: Texture2D, label: GDString | StringName | string, callback: Callable | Function = Callable(), keyCallback: Callable | Function = Callable(), tag: any = null, accelerator: number = 0, index: number = -1): number;
    public global_menu_add_icon_check_item(menuRoot: GDString | StringName | string, icon: Texture2D, label: GDString | StringName | string, callback: Callable | Function = Callable(), keyCallback: Callable | Function = Callable(), tag: any = null, accelerator: number = 0, index: number = -1): number;
    public global_menu_add_radio_check_item(menuRoot: GDString | StringName | string, label: GDString | StringName | string, callback: Callable | Function = Callable(), keyCallback: Callable | Function = Callable(), tag: any = null, accelerator: number = 0, index: number = -1): number;
    public global_menu_add_icon_radio_check_item(menuRoot: GDString | StringName | string, icon: Texture2D, label: GDString | StringName | string, callback: Callable | Function = Callable(), keyCallback: Callable | Function = Callable(), tag: any = null, accelerator: number = 0, index: number = -1): number;
    public global_menu_add_multistate_item(menuRoot: GDString | StringName | string, label: GDString | StringName | string, maxStates: number, defaultState: number, callback: Callable | Function = Callable(), keyCallback: Callable | Function = Callable(), tag: any = null, accelerator: number = 0, index: number = -1): number;
    public global_menu_add_separator(menuRoot: GDString | StringName | string, index: number = -1): number;
    public global_menu_get_item_index_from_text(menuRoot: GDString | StringName | string, text: GDString | StringName | string): number;
    public global_menu_get_item_index_from_tag(menuRoot: GDString | StringName | string, tag: any): number;
    public global_menu_is_item_checked(menuRoot: GDString | StringName | string, idx: number): boolean;
    public global_menu_is_item_checkable(menuRoot: GDString | StringName | string, idx: number): boolean;
    public global_menu_is_item_radio_checkable(menuRoot: GDString | StringName | string, idx: number): boolean;
    public global_menu_get_item_callback(menuRoot: GDString | StringName | string, idx: number): Callable;
    public global_menu_get_item_key_callback(menuRoot: GDString | StringName | string, idx: number): Callable;
    public global_menu_get_item_tag(menuRoot: GDString | StringName | string, idx: number): any;
    public global_menu_get_item_text(menuRoot: GDString | StringName | string, idx: number): GDString;
    public global_menu_get_item_submenu(menuRoot: GDString | StringName | string, idx: number): GDString;
    public global_menu_get_item_accelerator(menuRoot: GDString | StringName | string, idx: number): number;
    public global_menu_is_item_disabled(menuRoot: GDString | StringName | string, idx: number): boolean;
    public global_menu_is_item_hidden(menuRoot: GDString | StringName | string, idx: number): boolean;
    public global_menu_get_item_tooltip(menuRoot: GDString | StringName | string, idx: number): GDString;
    public global_menu_get_item_state(menuRoot: GDString | StringName | string, idx: number): number;
    public global_menu_get_item_max_states(menuRoot: GDString | StringName | string, idx: number): number;
    public global_menu_get_item_icon(menuRoot: GDString | StringName | string, idx: number): Texture2D;
    public global_menu_get_item_indentation_level(menuRoot: GDString | StringName | string, idx: number): number;
    public global_menu_set_item_checked(menuRoot: GDString | StringName | string, idx: number, checked: boolean): void;
    public global_menu_set_item_checkable(menuRoot: GDString | StringName | string, idx: number, checkable: boolean): void;
    public global_menu_set_item_radio_checkable(menuRoot: GDString | StringName | string, idx: number, checkable: boolean): void;
    public global_menu_set_item_callback(menuRoot: GDString | StringName | string, idx: number, callback: Callable | Function): void;
    public global_menu_set_item_hover_callbacks(menuRoot: GDString | StringName | string, idx: number, callback: Callable | Function): void;
    public global_menu_set_item_key_callback(menuRoot: GDString | StringName | string, idx: number, keyCallback: Callable | Function): void;
    public global_menu_set_item_tag(menuRoot: GDString | StringName | string, idx: number, tag: any): void;
    public global_menu_set_item_text(menuRoot: GDString | StringName | string, idx: number, text: GDString | StringName | string): void;
    public global_menu_set_item_submenu(menuRoot: GDString | StringName | string, idx: number, submenu: GDString | StringName | string): void;
    public global_menu_set_item_accelerator(menuRoot: GDString | StringName | string, idx: number, keycode: number): void;
    public global_menu_set_item_disabled(menuRoot: GDString | StringName | string, idx: number, disabled: boolean): void;
    public global_menu_set_item_hidden(menuRoot: GDString | StringName | string, idx: number, hidden: boolean): void;
    public global_menu_set_item_tooltip(menuRoot: GDString | StringName | string, idx: number, tooltip: GDString | StringName | string): void;
    public global_menu_set_item_state(menuRoot: GDString | StringName | string, idx: number, state: number): void;
    public global_menu_set_item_max_states(menuRoot: GDString | StringName | string, idx: number, maxStates: number): void;
    public global_menu_set_item_icon(menuRoot: GDString | StringName | string, idx: number, icon: Texture2D): void;
    public global_menu_set_item_indentation_level(menuRoot: GDString | StringName | string, idx: number, level: number): void;
    public global_menu_get_item_count(menuRoot: GDString | StringName | string): number;
    public global_menu_remove_item(menuRoot: GDString | StringName | string, idx: number): void;
    public global_menu_clear(menuRoot: GDString | StringName | string): void;
    public global_menu_get_system_menu_roots(): Dictionary;
    public tts_is_speaking(): boolean;
    public tts_is_paused(): boolean;
    public tts_get_voices(): Array<any>;
    public tts_get_voices_for_language(language: GDString | StringName | string): PackedStringArray;
    public tts_speak(text: GDString | StringName | string, voice: GDString | StringName | string, volume: number = 50, pitch: number = 1.0, rate: number = 1.0, utteranceId: number = 0, interrupt: boolean = false): void;
    public tts_pause(): void;
    public tts_resume(): void;
    public tts_stop(): void;
    public tts_set_utterance_callback(event: number, callable: Callable | Function): void;
    public is_dark_mode_supported(): boolean;
    public is_dark_mode(): boolean;
    public get_accent_color(): Color;
    public get_base_color(): Color;
    public set_system_theme_change_callback(callable: Callable | Function): void;
    public mouse_set_mode(mouseMode: number): void;
    public mouse_get_mode(): number;
    public warp_mouse(position: Vector2i): void;
    public mouse_get_position(): Vector2i;
    public mouse_get_button_state(): number;
    public clipboard_set(clipboard: GDString | StringName | string): void;
    public clipboard_get(): GDString;
    public clipboard_get_image(): Image;
    public clipboard_has(): boolean;
    public clipboard_has_image(): boolean;
    public clipboard_set_primary(clipboardPrimary: GDString | StringName | string): void;
    public clipboard_get_primary(): GDString;
    public get_display_cutouts(): Array<any>;
    public get_display_safe_area(): Rect2i;
    public get_screen_count(): number;
    public get_primary_screen(): number;
    public get_keyboard_focus_screen(): number;
    public get_screen_from_rect(rect: Rect2): number;
    public screen_get_position(screen: number = -1): Vector2i;
    public screen_get_size(screen: number = -1): Vector2i;
    public screen_get_usable_rect(screen: number = -1): Rect2i;
    public screen_get_dpi(screen: number = -1): number;
    public screen_get_scale(screen: number = -1): number;
    public is_touchscreen_available(): boolean;
    public screen_get_max_scale(): number;
    public screen_get_refresh_rate(screen: number = -1): number;
    public screen_get_pixel(position: Vector2i): Color;
    public screen_get_image(screen: number = -1): Image;
    public screen_get_image_rect(rect: Rect2i): Image;
    public screen_set_orientation(orientation: number, screen: number = -1): void;
    public screen_get_orientation(screen: number = -1): number;
    public screen_set_keep_on(enable: boolean): void;
    public screen_is_kept_on(): boolean;
    public get_window_list(): PackedInt32Array;
    public get_window_at_screen_position(position: Vector2i): number;
    public window_get_native_handle(handleType: number, windowId: number = 0): number;
    public window_get_active_popup(): number;
    public window_set_popup_safe_rect(window: number, rect: Rect2i): void;
    public window_get_popup_safe_rect(window: number): Rect2i;
    public window_set_title(title: GDString | StringName | string, windowId: number = 0): void;
    public window_get_title_size(title: GDString | StringName | string, windowId: number = 0): Vector2i;
    public window_set_mouse_passthrough(region: PackedVector2Array, windowId: number = 0): void;
    public window_get_current_screen(windowId: number = 0): number;
    public window_set_current_screen(screen: number, windowId: number = 0): void;
    public window_get_position(windowId: number = 0): Vector2i;
    public window_get_position_with_decorations(windowId: number = 0): Vector2i;
    public window_set_position(position: Vector2i, windowId: number = 0): void;
    public window_get_size(windowId: number = 0): Vector2i;
    public window_set_size(size: Vector2i, windowId: number = 0): void;
    public window_set_rect_changed_callback(callback: Callable | Function, windowId: number = 0): void;
    public window_set_window_event_callback(callback: Callable | Function, windowId: number = 0): void;
    public window_set_input_event_callback(callback: Callable | Function, windowId: number = 0): void;
    public window_set_input_text_callback(callback: Callable | Function, windowId: number = 0): void;
    public window_set_drop_files_callback(callback: Callable | Function, windowId: number = 0): void;
    public window_get_attached_instance_id(windowId: number = 0): number;
    public window_get_max_size(windowId: number = 0): Vector2i;
    public window_set_max_size(maxSize: Vector2i, windowId: number = 0): void;
    public window_get_min_size(windowId: number = 0): Vector2i;
    public window_set_min_size(minSize: Vector2i, windowId: number = 0): void;
    public window_get_size_with_decorations(windowId: number = 0): Vector2i;
    public window_get_mode(windowId: number = 0): number;
    public window_set_mode(mode: number, windowId: number = 0): void;
    public window_set_flag(flag: number, enabled: boolean, windowId: number = 0): void;
    public window_get_flag(flag: number, windowId: number = 0): boolean;
    public window_set_window_buttons_offset(offset: Vector2i, windowId: number = 0): void;
    public window_get_safe_title_margins(windowId: number = 0): Vector3i;
    public window_request_attention(windowId: number = 0): void;
    public window_move_to_foreground(windowId: number = 0): void;
    public window_is_focused(windowId: number = 0): boolean;
    public window_can_draw(windowId: number = 0): boolean;
    public window_set_transient(windowId: number, parentWindowId: number): void;
    public window_set_exclusive(windowId: number, exclusive: boolean): void;
    public window_set_ime_active(active: boolean, windowId: number = 0): void;
    public window_set_ime_position(position: Vector2i, windowId: number = 0): void;
    public window_set_vsync_mode(vsyncMode: number, windowId: number = 0): void;
    public window_get_vsync_mode(windowId: number = 0): number;
    public window_is_maximize_allowed(windowId: number = 0): boolean;
    public window_maximize_on_title_dbl_click(): boolean;
    public window_minimize_on_title_dbl_click(): boolean;
    public window_start_drag(windowId: number = 0): void;
    public window_start_resize(edge: number, windowId: number = 0): void;
    public accessibility_should_increase_contrast(): number;
    public accessibility_should_reduce_animation(): number;
    public accessibility_should_reduce_transparency(): number;
    public accessibility_screen_reader_active(): number;
    public accessibility_create_element(windowId: number, role: number): RID;
    public accessibility_create_sub_element(parentRid: RID, role: number, insertPos: number = -1): RID;
    public accessibility_create_sub_text_edit_elements(parentRid: RID, shapedText: RID, minHeight: number, insertPos: number = -1): RID;
    public accessibility_has_element(id: RID): boolean;
    public accessibility_free_element(id: RID): void;
    public accessibility_element_set_meta(id: RID, meta: any): void;
    public accessibility_element_get_meta(id: RID): any;
    public accessibility_set_window_rect(windowId: number, rectOut: Rect2, rectIn: Rect2): void;
    public accessibility_set_window_focused(windowId: number, focused: boolean): void;
    public accessibility_update_set_focus(id: RID): void;
    public accessibility_get_window_root(windowId: number): RID;
    public accessibility_update_set_role(id: RID, role: number): void;
    public accessibility_update_set_name(id: RID, name: GDString | StringName | string): void;
    public accessibility_update_set_extra_info(id: RID, name: GDString | StringName | string): void;
    public accessibility_update_set_description(id: RID, description: GDString | StringName | string): void;
    public accessibility_update_set_value(id: RID, value: GDString | StringName | string): void;
    public accessibility_update_set_tooltip(id: RID, tooltip: GDString | StringName | string): void;
    public accessibility_update_set_bounds(id: RID, rect: Rect2): void;
    public accessibility_update_set_transform(id: RID, transform: Transform2D): void;
    public accessibility_update_add_child(id: RID, childId: RID): void;
    public accessibility_update_add_related_controls(id: RID, relatedId: RID): void;
    public accessibility_update_add_related_details(id: RID, relatedId: RID): void;
    public accessibility_update_add_related_described_by(id: RID, relatedId: RID): void;
    public accessibility_update_add_related_flow_to(id: RID, relatedId: RID): void;
    public accessibility_update_add_related_labeled_by(id: RID, relatedId: RID): void;
    public accessibility_update_add_related_radio_group(id: RID, relatedId: RID): void;
    public accessibility_update_set_active_descendant(id: RID, otherId: RID): void;
    public accessibility_update_set_next_on_line(id: RID, otherId: RID): void;
    public accessibility_update_set_previous_on_line(id: RID, otherId: RID): void;
    public accessibility_update_set_member_of(id: RID, grouid: RID): void;
    public accessibility_update_set_in_page_link_target(id: RID, otherId: RID): void;
    public accessibility_update_set_error_message(id: RID, otherId: RID): void;
    public accessibility_update_set_live(id: RID, live: number): void;
    public accessibility_update_add_action(id: RID, action: number, callable: Callable | Function): void;
    public accessibility_update_add_custom_action(id: RID, actionId: number, actionDescription: GDString | StringName | string): void;
    public accessibility_update_set_table_row_count(id: RID, count: number): void;
    public accessibility_update_set_table_column_count(id: RID, count: number): void;
    public accessibility_update_set_table_row_index(id: RID, index: number): void;
    public accessibility_update_set_table_column_index(id: RID, index: number): void;
    public accessibility_update_set_table_cell_position(id: RID, rowIndex: number, columnIndex: number): void;
    public accessibility_update_set_table_cell_span(id: RID, rowSpan: number, columnSpan: number): void;
    public accessibility_update_set_list_item_count(id: RID, size: number): void;
    public accessibility_update_set_list_item_index(id: RID, index: number): void;
    public accessibility_update_set_list_item_level(id: RID, level: number): void;
    public accessibility_update_set_list_item_selected(id: RID, selected: boolean): void;
    public accessibility_update_set_list_item_expanded(id: RID, expanded: boolean): void;
    public accessibility_update_set_popup_type(id: RID, popup: number): void;
    public accessibility_update_set_checked(id: RID, checekd: boolean): void;
    public accessibility_update_set_num_value(id: RID, position: number): void;
    public accessibility_update_set_num_range(id: RID, min: number, max: number): void;
    public accessibility_update_set_num_step(id: RID, step: number): void;
    public accessibility_update_set_num_jump(id: RID, jump: number): void;
    public accessibility_update_set_scroll_x(id: RID, position: number): void;
    public accessibility_update_set_scroll_x_range(id: RID, min: number, max: number): void;
    public accessibility_update_set_scroll_y(id: RID, position: number): void;
    public accessibility_update_set_scroll_y_range(id: RID, min: number, max: number): void;
    public accessibility_update_set_text_decorations(id: RID, underline: boolean, strikethrough: boolean, overline: boolean): void;
    public accessibility_update_set_text_align(id: RID, align: number): void;
    public accessibility_update_set_text_selection(id: RID, textStartId: RID, startChar: number, textEndId: RID, endChar: number): void;
    public accessibility_update_set_flag(id: RID, flag: number, value: boolean): void;
    public accessibility_update_set_classname(id: RID, classname: GDString | StringName | string): void;
    public accessibility_update_set_placeholder(id: RID, placeholder: GDString | StringName | string): void;
    public accessibility_update_set_language(id: RID, language: GDString | StringName | string): void;
    public accessibility_update_set_text_orientation(id: RID, vertical: boolean): void;
    public accessibility_update_set_list_orientation(id: RID, vertical: boolean): void;
    public accessibility_update_set_shortcut(id: RID, shortcut: GDString | StringName | string): void;
    public accessibility_update_set_url(id: RID, url: GDString | StringName | string): void;
    public accessibility_update_set_role_description(id: RID, description: GDString | StringName | string): void;
    public accessibility_update_set_state_description(id: RID, description: GDString | StringName | string): void;
    public accessibility_update_set_color_value(id: RID, color: Color): void;
    public accessibility_update_set_background_color(id: RID, color: Color): void;
    public accessibility_update_set_foreground_color(id: RID, color: Color): void;
    public ime_get_selection(): Vector2i;
    public ime_get_text(): GDString;
    public virtual_keyboard_show(existingText: GDString | StringName | string, position: Rect2 = Rect2(0, 0, 0, 0), _type: number = 0, maxLength: number = -1, cursorStart: number = -1, cursorEnd: number = -1): void;
    public virtual_keyboard_hide(): void;
    public virtual_keyboard_get_height(): number;
    public has_hardware_keyboard(): boolean;
    public set_hardware_keyboard_connection_change_callback(callable: Callable | Function): void;
    public cursor_set_shape(shape: number): void;
    public cursor_get_shape(): number;
    public cursor_set_custom_image(cursor: Resource, shape: number = 0, hotspot: Vector2 = Vector2(0, 0)): void;
    public get_swap_cancel_ok(): boolean;
    public enable_for_stealing_focus(processId: number): void;
    public dialog_show(title: GDString | StringName | string, description: GDString | StringName | string, buttons: PackedStringArray, callback: Callable | Function): number;
    public dialog_input_text(title: GDString | StringName | string, description: GDString | StringName | string, existingText: GDString | StringName | string, callback: Callable | Function): number;
    public file_dialog_show(title: GDString | StringName | string, currentDirectory: GDString | StringName | string, filename: GDString | StringName | string, showHidden: boolean, mode: number, filters: PackedStringArray, callback: Callable | Function, parentWindowId: number = 0): number;
    public file_dialog_with_options_show(title: GDString | StringName | string, currentDirectory: GDString | StringName | string, root: GDString | StringName | string, filename: GDString | StringName | string, showHidden: boolean, mode: number, filters: PackedStringArray, options: Array<any>, callback: Callable | Function, parentWindowId: number = 0): number;
    public beep(): void;
    public keyboard_get_layout_count(): number;
    public keyboard_get_current_layout(): number;
    public keyboard_set_current_layout(index: number): void;
    public keyboard_get_layout_language(index: number): GDString;
    public keyboard_get_layout_name(index: number): GDString;
    public keyboard_get_keycode_from_physical(keycode: number): number;
    public keyboard_get_label_from_physical(keycode: number): number;
    public show_emoji_and_symbol_picker(): void;
    public color_picker(callback: Callable | Function): boolean;
    public process_events(): void;
    public force_process_and_drop_events(): void;
    public set_native_icon(filename: GDString | StringName | string): void;
    public set_icon(image: Image): void;
    public create_status_indicator(icon: Texture2D, tooltip: GDString | StringName | string, callback: Callable | Function): number;
    public status_indicator_set_icon(id: number, icon: Texture2D): void;
    public status_indicator_set_tooltip(id: number, tooltip: GDString | StringName | string): void;
    public status_indicator_set_menu(id: number, menuRid: RID): void;
    public status_indicator_set_callback(id: number, callback: Callable | Function): void;
    public status_indicator_get_rect(id: number): Rect2;
    public delete_status_indicator(id: number): void;
    public tablet_get_driver_count(): number;
    public tablet_get_driver_name(idx: number): GDString;
    public tablet_get_current_driver(): GDString;
    public tablet_set_current_driver(name: GDString | StringName | string): void;
    public is_window_transparency_available(): boolean;
    public register_additional_output(object: GodotObject): void;
    public unregister_additional_output(object: GodotObject): void;
    public has_additional_outputs(): boolean;


    public static readonly Feature: {
        FEATURE_GLOBAL_MENU: 0;
        FEATURE_SUBWINDOWS: 1;
        FEATURE_TOUCHSCREEN: 2;
        FEATURE_MOUSE: 3;
        FEATURE_MOUSE_WARP: 4;
        FEATURE_CLIPBOARD: 5;
        FEATURE_VIRTUAL_KEYBOARD: 6;
        FEATURE_CURSOR_SHAPE: 7;
        FEATURE_CUSTOM_CURSOR_SHAPE: 8;
        FEATURE_NATIVE_DIALOG: 9;
        FEATURE_IME: 10;
        FEATURE_WINDOW_TRANSPARENCY: 11;
        FEATURE_HIDPI: 12;
        FEATURE_ICON: 13;
        FEATURE_NATIVE_ICON: 14;
        FEATURE_ORIENTATION: 15;
        FEATURE_SWAP_BUFFERS: 16;
        FEATURE_CLIPBOARD_PRIMARY: 18;
        FEATURE_TEXT_TO_SPEECH: 19;
        FEATURE_EXTEND_TO_TITLE: 20;
        FEATURE_SCREEN_CAPTURE: 21;
        FEATURE_STATUS_INDICATOR: 22;
        FEATURE_NATIVE_HELP: 23;
        FEATURE_NATIVE_DIALOG_INPUT: 24;
        FEATURE_NATIVE_DIALOG_FILE: 25;
        FEATURE_NATIVE_DIALOG_FILE_EXTRA: 26;
        FEATURE_WINDOW_DRAG: 27;
        FEATURE_SCREEN_EXCLUDE_FROM_CAPTURE: 28;
        FEATURE_WINDOW_EMBEDDING: 29;
        FEATURE_NATIVE_DIALOG_FILE_MIME: 30;
        FEATURE_EMOJI_AND_SYMBOL_PICKER: 31;
        FEATURE_NATIVE_COLOR_PICKER: 32;
        FEATURE_SELF_FITTING_WINDOWS: 33;
        FEATURE_ACCESSIBILITY_SCREEN_READER: 34;
    };
    public static readonly AccessibilityRole: {
        ROLE_UNKNOWN: 0;
        ROLE_DEFAULT_BUTTON: 1;
        ROLE_AUDIO: 2;
        ROLE_VIDEO: 3;
        ROLE_STATIC_TEXT: 4;
        ROLE_CONTAINER: 5;
        ROLE_PANEL: 6;
        ROLE_BUTTON: 7;
        ROLE_LINK: 8;
        ROLE_CHECK_BOX: 9;
        ROLE_RADIO_BUTTON: 10;
        ROLE_CHECK_BUTTON: 11;
        ROLE_SCROLL_BAR: 12;
        ROLE_SCROLL_VIEW: 13;
        ROLE_SPLITTER: 14;
        ROLE_SLIDER: 15;
        ROLE_SPIN_BUTTON: 16;
        ROLE_PROGRESS_INDICATOR: 17;
        ROLE_TEXT_FIELD: 18;
        ROLE_MULTILINE_TEXT_FIELD: 19;
        ROLE_COLOR_PICKER: 20;
        ROLE_TABLE: 21;
        ROLE_CELL: 22;
        ROLE_ROW: 23;
        ROLE_ROW_GROUP: 24;
        ROLE_ROW_HEADER: 25;
        ROLE_COLUMN_HEADER: 26;
        ROLE_TREE: 27;
        ROLE_TREE_ITEM: 28;
        ROLE_LIST: 29;
        ROLE_LIST_ITEM: 30;
        ROLE_LIST_BOX: 31;
        ROLE_LIST_BOX_OPTION: 32;
        ROLE_TAB_BAR: 33;
        ROLE_TAB: 34;
        ROLE_TAB_PANEL: 35;
        ROLE_MENU_BAR: 36;
        ROLE_MENU: 37;
        ROLE_MENU_ITEM: 38;
        ROLE_MENU_ITEM_CHECK_BOX: 39;
        ROLE_MENU_ITEM_RADIO: 40;
        ROLE_IMAGE: 41;
        ROLE_WINDOW: 42;
        ROLE_TITLE_BAR: 43;
        ROLE_DIALOG: 44;
        ROLE_TOOLTIP: 45;
    };
    public static readonly AccessibilityPopupType: {
        POPUP_MENU: 0;
        POPUP_LIST: 1;
        POPUP_TREE: 2;
        POPUP_DIALOG: 3;
    };
    public static readonly AccessibilityFlags: {
        FLAG_HIDDEN: 0;
        FLAG_MULTISELECTABLE: 1;
        FLAG_REQUIRED: 2;
        FLAG_VISITED: 3;
        FLAG_BUSY: 4;
        FLAG_MODAL: 5;
        FLAG_TOUCH_PASSTHROUGH: 6;
        FLAG_READONLY: 7;
        FLAG_DISABLED: 8;
        FLAG_CLIPS_CHILDREN: 9;
    };
    public static readonly AccessibilityAction: {
        ACTION_CLICK: 0;
        ACTION_FOCUS: 1;
        ACTION_BLUR: 2;
        ACTION_COLLAPSE: 3;
        ACTION_EXPAND: 4;
        ACTION_DECREMENT: 5;
        ACTION_INCREMENT: 6;
        ACTION_HIDE_TOOLTIP: 7;
        ACTION_SHOW_TOOLTIP: 8;
        ACTION_SET_TEXT_SELECTION: 9;
        ACTION_REPLACE_SELECTED_TEXT: 10;
        ACTION_SCROLL_BACKWARD: 11;
        ACTION_SCROLL_DOWN: 12;
        ACTION_SCROLL_FORWARD: 13;
        ACTION_SCROLL_LEFT: 14;
        ACTION_SCROLL_RIGHT: 15;
        ACTION_SCROLL_UP: 16;
        ACTION_SCROLL_INTO_VIEW: 17;
        ACTION_SCROLL_TO_POINT: 18;
        ACTION_SET_SCROLL_OFFSET: 19;
        ACTION_SET_VALUE: 20;
        ACTION_SHOW_CONTEXT_MENU: 21;
        ACTION_CUSTOM: 22;
    };
    public static readonly AccessibilityLiveMode: {
        LIVE_OFF: 0;
        LIVE_POLITE: 1;
        LIVE_ASSERTIVE: 2;
    };
    public static readonly AccessibilityScrollUnit: {
        SCROLL_UNIT_ITEM: 0;
        SCROLL_UNIT_PAGE: 1;
    };
    public static readonly AccessibilityScrollHint: {
        SCROLL_HINT_TOP_LEFT: 0;
        SCROLL_HINT_BOTTOM_RIGHT: 1;
        SCROLL_HINT_TOP_EDGE: 2;
        SCROLL_HINT_BOTTOM_EDGE: 3;
        SCROLL_HINT_LEFT_EDGE: 4;
        SCROLL_HINT_RIGHT_EDGE: 5;
    };
    public static readonly MouseMode: {
        MOUSE_MODE_VISIBLE: 0;
        MOUSE_MODE_HIDDEN: 1;
        MOUSE_MODE_CAPTURED: 2;
        MOUSE_MODE_CONFINED: 3;
        MOUSE_MODE_CONFINED_HIDDEN: 4;
        MOUSE_MODE_MAX: 5;
    };
    public static readonly ScreenOrientation: {
        SCREEN_LANDSCAPE: 0;
        SCREEN_PORTRAIT: 1;
        SCREEN_REVERSE_LANDSCAPE: 2;
        SCREEN_REVERSE_PORTRAIT: 3;
        SCREEN_SENSOR_LANDSCAPE: 4;
        SCREEN_SENSOR_PORTRAIT: 5;
        SCREEN_SENSOR: 6;
    };
    public static readonly VirtualKeyboardType: {
        KEYBOARD_TYPE_DEFAULT: 0;
        KEYBOARD_TYPE_MULTILINE: 1;
        KEYBOARD_TYPE_NUMBER: 2;
        KEYBOARD_TYPE_NUMBER_DECIMAL: 3;
        KEYBOARD_TYPE_PHONE: 4;
        KEYBOARD_TYPE_EMAIL_ADDRESS: 5;
        KEYBOARD_TYPE_PASSWORD: 6;
        KEYBOARD_TYPE_URL: 7;
    };
    public static readonly CursorShape: {
        CURSOR_ARROW: 0;
        CURSOR_IBEAM: 1;
        CURSOR_POINTING_HAND: 2;
        CURSOR_CROSS: 3;
        CURSOR_WAIT: 4;
        CURSOR_BUSY: 5;
        CURSOR_DRAG: 6;
        CURSOR_CAN_DROP: 7;
        CURSOR_FORBIDDEN: 8;
        CURSOR_VSIZE: 9;
        CURSOR_HSIZE: 10;
        CURSOR_BDIAGSIZE: 11;
        CURSOR_FDIAGSIZE: 12;
        CURSOR_MOVE: 13;
        CURSOR_VSPLIT: 14;
        CURSOR_HSPLIT: 15;
        CURSOR_HELP: 16;
        CURSOR_MAX: 17;
    };
    public static readonly FileDialogMode: {
        FILE_DIALOG_MODE_OPEN_FILE: 0;
        FILE_DIALOG_MODE_OPEN_FILES: 1;
        FILE_DIALOG_MODE_OPEN_DIR: 2;
        FILE_DIALOG_MODE_OPEN_ANY: 3;
        FILE_DIALOG_MODE_SAVE_FILE: 4;
    };
    public static readonly WindowMode: {
        WINDOW_MODE_WINDOWED: 0;
        WINDOW_MODE_MINIMIZED: 1;
        WINDOW_MODE_MAXIMIZED: 2;
        WINDOW_MODE_FULLSCREEN: 3;
        WINDOW_MODE_EXCLUSIVE_FULLSCREEN: 4;
    };
    public static readonly WindowFlags: {
        WINDOW_FLAG_RESIZE_DISABLED: 0;
        WINDOW_FLAG_BORDERLESS: 1;
        WINDOW_FLAG_ALWAYS_ON_TOP: 2;
        WINDOW_FLAG_TRANSPARENT: 3;
        WINDOW_FLAG_NO_FOCUS: 4;
        WINDOW_FLAG_POPUP: 5;
        WINDOW_FLAG_EXTEND_TO_TITLE: 6;
        WINDOW_FLAG_MOUSE_PASSTHROUGH: 7;
        WINDOW_FLAG_SHARP_CORNERS: 8;
        WINDOW_FLAG_EXCLUDE_FROM_CAPTURE: 9;
        WINDOW_FLAG_POPUP_WM_HINT: 10;
        WINDOW_FLAG_MINIMIZE_DISABLED: 11;
        WINDOW_FLAG_MAXIMIZE_DISABLED: 12;
        WINDOW_FLAG_MAX: 13;
    };
    public static readonly WindowEvent: {
        WINDOW_EVENT_MOUSE_ENTER: 0;
        WINDOW_EVENT_MOUSE_EXIT: 1;
        WINDOW_EVENT_FOCUS_IN: 2;
        WINDOW_EVENT_FOCUS_OUT: 3;
        WINDOW_EVENT_CLOSE_REQUEST: 4;
        WINDOW_EVENT_GO_BACK_REQUEST: 5;
        WINDOW_EVENT_DPI_CHANGE: 6;
        WINDOW_EVENT_TITLEBAR_CHANGE: 7;
        WINDOW_EVENT_FORCE_CLOSE: 8;
    };
    public static readonly WindowResizeEdge: {
        WINDOW_EDGE_TOP_LEFT: 0;
        WINDOW_EDGE_TOP: 1;
        WINDOW_EDGE_TOP_RIGHT: 2;
        WINDOW_EDGE_LEFT: 3;
        WINDOW_EDGE_RIGHT: 4;
        WINDOW_EDGE_BOTTOM_LEFT: 5;
        WINDOW_EDGE_BOTTOM: 6;
        WINDOW_EDGE_BOTTOM_RIGHT: 7;
        WINDOW_EDGE_MAX: 8;
    };
    public static readonly VSyncMode: {
        VSYNC_DISABLED: 0;
        VSYNC_ENABLED: 1;
        VSYNC_ADAPTIVE: 2;
        VSYNC_MAILBOX: 3;
    };
    public static readonly HandleType: {
        DISPLAY_HANDLE: 0;
        WINDOW_HANDLE: 1;
        WINDOW_VIEW: 2;
        OPENGL_CONTEXT: 3;
        EGL_DISPLAY: 4;
        EGL_CONFIG: 5;
    };
    public static readonly TTSUtteranceEvent: {
        TTS_UTTERANCE_STARTED: 0;
        TTS_UTTERANCE_ENDED: 1;
        TTS_UTTERANCE_CANCELED: 2;
        TTS_UTTERANCE_BOUNDARY: 3;
    };
}


/**
 * A singleton instance of DisplayServer.
 * This is a global variable, available from anywhere.
 */
export const DisplayServer: DisplayServer;
