
import { Font } from "@godot/classes/font";
export declare class FontVariation extends Font{
  public set_base_font(_font: Font): void;
  public get_base_font(): Font;
  public set_variation_opentype(_coords: Dictionary): void;
  public get_variation_opentype(): Dictionary;
  public set_variation_embolden(_strength: number): void;
  public get_variation_embolden(): number;
  public set_variation_face_index(_face_index: number): void;
  public get_variation_face_index(): number;
  public set_variation_transform(_transform: Transform2D): void;
  public get_variation_transform(): Transform2D;
  public set_opentype_features(_features: Dictionary): void;
  public set_spacing(_spacing: number, _value: number): void;
  public set_baseline_offset(_baseline_offset: number): void;
  public get_baseline_offset(): number;
  public get base_font(): Font;
  public set base_font(value): void;
  public get variation_opentype(): Dictionary;
  public set variation_opentype(value): void;
  public get variation_face_index(): number;
  public set variation_face_index(value): void;
  public get variation_embolden(): number;
  public set variation_embolden(value): void;
  public get variation_transform(): Transform2D;
  public set variation_transform(value): void;
  public get opentype_features(): Dictionary;
  public set opentype_features(value): void;
  public get spacing_glyph(): number;
  public set spacing_glyph(value): void;
  public get spacing_space(): number;
  public set spacing_space(value): void;
  public get spacing_top(): number;
  public set spacing_top(value): void;
  public get spacing_bottom(): number;
  public set spacing_bottom(value): void;
  public get baseline_offset(): number;
  public set baseline_offset(value): void;
}