
import { Skin } from "@godot/classes/skin";
import { Resource } from "@godot/classes/resource";
export declare class GLTFSkin extends Resource{
  public get_skin_root(): number;
  public set_skin_root(_skin_root: number): void;
  public get_joints_original(): PackedInt32Array;
  public set_joints_original(_joints_original: PackedInt32Array): void;
  public get_inverse_binds(): GDArray;
  public set_inverse_binds(_inverse_binds: GDArray): void;
  public get_joints(): PackedInt32Array;
  public set_joints(_joints: PackedInt32Array): void;
  public get_non_joints(): PackedInt32Array;
  public set_non_joints(_non_joints: PackedInt32Array): void;
  public get_roots(): PackedInt32Array;
  public set_roots(_roots: PackedInt32Array): void;
  public get_skeleton(): number;
  public set_skeleton(_skeleton: number): void;
  public get_joint_i_to_bone_i(): Dictionary;
  public set_joint_i_to_bone_i(_joint_i_to_bone_i: Dictionary): void;
  public get_joint_i_to_name(): Dictionary;
  public set_joint_i_to_name(_joint_i_to_name: Dictionary): void;
  public get_godot_skin(): Skin;
  public set_godot_skin(_godot_skin: Skin): void;
  public get skin_root(): number;
  public set skin_root(value): void;
  public get joints_original(): PackedInt32Array;
  public set joints_original(value): void;
  public get inverse_binds(): GDArray;
  public set inverse_binds(value): void;
  public get joints(): PackedInt32Array;
  public set joints(value): void;
  public get non_joints(): PackedInt32Array;
  public set non_joints(value): void;
  public get roots(): PackedInt32Array;
  public set roots(value): void;
  public get skeleton(): number;
  public set skeleton(value): void;
  public get joint_i_to_bone_i(): Dictionary;
  public set joint_i_to_bone_i(value): void;
  public get joint_i_to_name(): Dictionary;
  public set joint_i_to_name(value): void;
  public get godot_skin(): Skin;
  public set godot_skin(value): void;
}