
import { Texture2D } from "@godot/classes/texture2d";
import { GLTFBufferView } from "@godot/classes/gltf_buffer_view";
import { GLTFSkeleton } from "@godot/classes/gltf_skeleton";
import { GLTFTexture } from "@godot/classes/gltf_texture";
import { GLTFCamera } from "@godot/classes/gltf_camera";
import { GLTFAccessor } from "@godot/classes/gltf_accessor";
import { Resource } from "@godot/classes/resource";
import { GLTFAnimation } from "@godot/classes/gltf_animation";
import { AnimationPlayer } from "@godot/classes/animation_player";
import { GLTFTextureSampler } from "@godot/classes/gltf_texture_sampler";
import { GLTFMesh } from "@godot/classes/gltf_mesh";
import { Material } from "@godot/classes/material";
import { Node } from "@godot/classes/node";
import { GLTFLight } from "@godot/classes/gltf_light";
import { GLTFSkin } from "@godot/classes/gltf_skin";
import { GLTFNode } from "@godot/classes/gltf_node";


export declare class GLTFState extends Resource{
  public add_used_extension(_extension_name: GDString | StringName | string, _required: boolean): void;
  public append_data_to_buffers(_data: PackedByteArray, _deduplication: boolean): number;
  public get_json(): Dictionary;
  public set_json(_json: Dictionary): void;
  public get_major_version(): number;
  public set_major_version(_major_version: number): void;
  public get_minor_version(): number;
  public set_minor_version(_minor_version: number): void;
  public get_copyright(): String;
  public set_copyright(_copyright: GDString | StringName | string): void;
  public get_glb_data(): PackedByteArray;
  public set_glb_data(_glb_data: PackedByteArray): void;
  public get_use_named_skin_binds(): boolean;
  public set_use_named_skin_binds(_use_named_skin_binds: boolean): void;
  public get_nodes(): GDArray;
  public set_nodes(_nodes: GDArray): void;
  public get_buffers(): GDArray;
  public set_buffers(_buffers: GDArray): void;
  public get_buffer_views(): GDArray;
  public set_buffer_views(_buffer_views: GDArray): void;
  public get_accessors(): GDArray;
  public set_accessors(_accessors: GDArray): void;
  public get_meshes(): GDArray;
  public set_meshes(_meshes: GDArray): void;
  public get_animation_players_count(_idx: number): number;
  public get_animation_player(_idx: number): AnimationPlayer;
  public get_materials(): GDArray;
  public set_materials(_materials: GDArray): void;
  public get_scene_name(): String;
  public set_scene_name(_scene_name: GDString | StringName | string): void;
  public get_base_path(): String;
  public set_base_path(_base_path: GDString | StringName | string): void;
  public get_filename(): String;
  public set_filename(_filename: GDString | StringName | string): void;
  public get_root_nodes(): PackedInt32Array;
  public set_root_nodes(_root_nodes: PackedInt32Array): void;
  public get_textures(): GDArray;
  public set_textures(_textures: GDArray): void;
  public get_texture_samplers(): GDArray;
  public set_texture_samplers(_texture_samplers: GDArray): void;
  public get_images(): GDArray;
  public set_images(_images: GDArray): void;
  public get_skins(): GDArray;
  public set_skins(_skins: GDArray): void;
  public get_cameras(): GDArray;
  public set_cameras(_cameras: GDArray): void;
  public get_lights(): GDArray;
  public set_lights(_lights: GDArray): void;
  public get_unique_names(): GDArray;
  public set_unique_names(_unique_names: GDArray): void;
  public get_unique_animation_names(): GDArray;
  public set_unique_animation_names(_unique_animation_names: GDArray): void;
  public get_skeletons(): GDArray;
  public set_skeletons(_skeletons: GDArray): void;
  public get_create_animations(): boolean;
  public set_create_animations(_create_animations: boolean): void;
  public get_import_as_skeleton_bones(): boolean;
  public set_import_as_skeleton_bones(_import_as_skeleton_bones: boolean): void;
  public get_animations(): GDArray;
  public set_animations(_animations: GDArray): void;
  public get_scene_node(_idx: number): Node;
  public get_node_index(_scene_node: Node): number;
  public get_additional_data(_extension_name: GDString | StringName | string): any;
  public set_additional_data(_extension_name: GDString | StringName | string, _additional_data: any): void;
  public get_handle_binary_image(): number;
  public set_handle_binary_image(_method: number): void;
  public set_bake_fps(_value: number): void;
  public get_bake_fps(): number;
  public get json(): Dictionary;
  public set json(value): void;
  public get major_version(): number;
  public set major_version(value): void;
  public get minor_version(): number;
  public set minor_version(value): void;
  public get copyright(): String;
  public set copyright(value): void;
  public get glb_data(): PackedByteArray;
  public set glb_data(value): void;
  public get use_named_skin_binds(): boolean;
  public set use_named_skin_binds(value): void;
  public get nodes(): GDArray;
  public set nodes(value): void;
  public get buffers(): GDArray;
  public set buffers(value): void;
  public get buffer_views(): GDArray;
  public set buffer_views(value): void;
  public get accessors(): GDArray;
  public set accessors(value): void;
  public get meshes(): GDArray;
  public set meshes(value): void;
  public get materials(): GDArray;
  public set materials(value): void;
  public get scene_name(): String;
  public set scene_name(value): void;
  public get base_path(): String;
  public set base_path(value): void;
  public get filename(): String;
  public set filename(value): void;
  public get root_nodes(): PackedInt32Array;
  public set root_nodes(value): void;
  public get textures(): GDArray;
  public set textures(value): void;
  public get texture_samplers(): GDArray;
  public set texture_samplers(value): void;
  public get images(): GDArray;
  public set images(value): void;
  public get skins(): GDArray;
  public set skins(value): void;
  public get cameras(): GDArray;
  public set cameras(value): void;
  public get lights(): GDArray;
  public set lights(value): void;
  public get unique_names(): GDArray;
  public set unique_names(value): void;
  public get unique_animation_names(): GDArray;
  public set unique_animation_names(value): void;
  public get skeletons(): GDArray;
  public set skeletons(value): void;
  public get create_animations(): boolean;
  public set create_animations(value): void;
  public get import_as_skeleton_bones(): boolean;
  public set import_as_skeleton_bones(value): void;
  public get animations(): GDArray;
  public set animations(value): void;
  public get handle_binary_image(): number;
  public set handle_binary_image(value): void;
  public get bake_fps(): number;
  public set bake_fps(value): void;
}