
import { InputEventFromWindow } from "@godot/classes/input_event_from_window";
export declare class InputEventScreenDrag extends InputEventFromWindow{
  public set_index(_index: number): void;
  public get_index(): number;
  public set_tilt(_tilt: Vector2): void;
  public get_tilt(): Vector2;
  public set_pressure(_pressure: number): void;
  public get_pressure(): number;
  public set_pen_inverted(_pen_inverted: boolean): void;
  public get_pen_inverted(): boolean;
  public set_position(_position: Vector2): void;
  public get_position(): Vector2;
  public set_relative(_relative: Vector2): void;
  public get_relative(): Vector2;
  public set_screen_relative(_relative: Vector2): void;
  public get_screen_relative(): Vector2;
  public set_velocity(_velocity: Vector2): void;
  public get_velocity(): Vector2;
  public set_screen_velocity(_velocity: Vector2): void;
  public get_screen_velocity(): Vector2;
  public get index(): number;
  public set index(value): void;
  public get tilt(): Vector2;
  public set tilt(value): void;
  public get pressure(): number;
  public set pressure(value): void;
  public get pen_inverted(): boolean;
  public set pen_inverted(value): void;
  public get position(): Vector2;
  public set position(value): void;
  public get relative(): Vector2;
  public set relative(value): void;
  public get screen_relative(): Vector2;
  public set screen_relative(value): void;
  public get velocity(): Vector2;
  public set velocity(value): void;
  public get screen_velocity(): Vector2;
  public set screen_velocity(value): void;
}