
import { Texture2D } from "@godot/classes/texture2d";
import { Control } from "@godot/classes/control";
import { VScrollBar } from "@godot/classes/v_scroll_bar";
export declare class ItemList extends Control{
  public add_item(_text: GDString | StringName | string, _icon: Texture2D = null, _selectable: boolean = true): number;
  public add_icon_item(_icon: Texture2D, _selectable: boolean = true): number;
  public set_item_text(_idx: number, _text: GDString | StringName | string): void;
  public get_item_text(_idx: number): String;
  public set_item_icon(_idx: number, _icon: Texture2D): void;
  public get_item_icon(_idx: number): Texture2D;
  public set_item_text_direction(_idx: number, _direction: number): void;
  public get_item_text_direction(_idx: number): number;
  public set_item_language(_idx: number, _language: GDString | StringName | string): void;
  public get_item_language(_idx: number): String;
  public set_item_icon_transposed(_idx: number, _transposed: boolean): void;
  public is_item_icon_transposed(_idx: number): boolean;
  public set_item_icon_region(_idx: number, _rect: Rect2): void;
  public get_item_icon_region(_idx: number): Rect2;
  public set_item_icon_modulate(_idx: number, _modulate: Color): void;
  public get_item_icon_modulate(_idx: number): Color;
  public set_item_selectable(_idx: number, _selectable: boolean): void;
  public is_item_selectable(_idx: number): boolean;
  public set_item_disabled(_idx: number, _disabled: boolean): void;
  public is_item_disabled(_idx: number): boolean;
  public set_item_metadata(_idx: number, _metadata: any): void;
  public get_item_metadata(_idx: number): any;
  public set_item_custom_bg_color(_idx: number, _custom_bg_color: Color): void;
  public get_item_custom_bg_color(_idx: number): Color;
  public set_item_custom_fg_color(_idx: number, _custom_fg_color: Color): void;
  public get_item_custom_fg_color(_idx: number): Color;
  public get_item_rect(_idx: number, _expand: boolean = true): Rect2;
  public set_item_tooltip_enabled(_idx: number, _enable: boolean): void;
  public is_item_tooltip_enabled(_idx: number): boolean;
  public set_item_tooltip(_idx: number, _tooltip: GDString | StringName | string): void;
  public get_item_tooltip(_idx: number): String;
  public select(_idx: number, _single: boolean = true): void;
  public deselect(_idx: number): void;
  public deselect_all(): void;
  public is_selected(_idx: number): boolean;
  public get_selected_items(): PackedInt32Array;
  public move_item(_from_idx: number, _to_idx: number): void;
  public set_item_count(_count: number): void;
  public get_item_count(): number;
  public remove_item(_idx: number): void;
  public clear(): void;
  public sort_items_by_text(): void;
  public set_fixed_column_width(_width: number): void;
  public get_fixed_column_width(): number;
  public set_same_column_width(_enable: boolean): void;
  public is_same_column_width(): boolean;
  public set_max_text_lines(_lines: number): void;
  public get_max_text_lines(): number;
  public set_max_columns(_amount: number): void;
  public get_max_columns(): number;
  public set_select_mode(_mode: number): void;
  public get_select_mode(): number;
  public set_icon_mode(_mode: number): void;
  public get_icon_mode(): number;
  public set_fixed_icon_size(_size: Vector2i): void;
  public get_fixed_icon_size(): Vector2i;
  public set_icon_scale(_scale: number): void;
  public get_icon_scale(): number;
  public set_allow_rmb_select(_allow: boolean): void;
  public get_allow_rmb_select(): boolean;
  public set_allow_reselect(_allow: boolean): void;
  public get_allow_reselect(): boolean;
  public set_allow_search(_allow: boolean): void;
  public get_allow_search(): boolean;
  public set_auto_height(_enable: boolean): void;
  public has_auto_height(): boolean;
  public is_anything_selected(): boolean;
  public get_item_at_position(_position: Vector2, _exact: boolean = false): number;
  public ensure_current_is_visible(): void;
  public get_v_scroll_bar(): VScrollBar;
  public set_text_overrun_behavior(_overrun_behavior: number): void;
  public get_text_overrun_behavior(): number;
  public force_update_list_size(): void;
  public get select_mode(): number;
  public set select_mode(value): void;
  public get allow_reselect(): boolean;
  public set allow_reselect(value): void;
  public get allow_rmb_select(): boolean;
  public set allow_rmb_select(value): void;
  public get allow_search(): boolean;
  public set allow_search(value): void;
  public get max_text_lines(): number;
  public set max_text_lines(value): void;
  public get auto_height(): boolean;
  public set auto_height(value): void;
  public get text_overrun_behavior(): number;
  public set text_overrun_behavior(value): void;
  public get item_count(): number;
  public set item_count(value): void;
  public get max_columns(): number;
  public set max_columns(value): void;
  public get same_column_width(): boolean;
  public set same_column_width(value): void;
  public get fixed_column_width(): number;
  public set fixed_column_width(value): void;
  public get icon_mode(): number;
  public set icon_mode(value): void;
  public get icon_scale(): number;
  public set icon_scale(value): void;
  public get fixed_icon_size(): Vector2i;
  public set fixed_icon_size(value): void;
  static IconMode = {
    ICON_MODE_TOP = 0,
    ICON_MODE_LEFT = 1,
  }
  static SelectMode = {
    SELECT_SINGLE = 0,
    SELECT_MULTI = 1,
  }
  public get item_selected(): Signal;
  public get empty_clicked(): Signal;
  public get item_clicked(): Signal;
  public get multi_selected(): Signal;
  public get item_activated(): Signal;
}