
import { Control } from "@godot/classes/control";
import { LabelSettings } from "@godot/classes/label_settings";
export declare class Label extends Control{
  public set_horizontal_alignment(_alignment: number): void;
  public get_horizontal_alignment(): number;
  public set_vertical_alignment(_alignment: number): void;
  public get_vertical_alignment(): number;
  public set_text(_text: GDString | StringName | string): void;
  public get_text(): String;
  public set_label_settings(_settings: LabelSettings): void;
  public get_label_settings(): LabelSettings;
  public set_text_direction(_direction: number): void;
  public get_text_direction(): number;
  public set_language(_language: GDString | StringName | string): void;
  public get_language(): String;
  public set_autowrap_mode(_autowrap_mode: number): void;
  public get_autowrap_mode(): number;
  public set_justification_flags(_justification_flags: number): void;
  public get_justification_flags(): number;
  public set_clip_text(_enable: boolean): void;
  public is_clipping_text(): boolean;
  public set_tab_stops(_tab_stops: PackedFloat32Array): void;
  public get_tab_stops(): PackedFloat32Array;
  public set_text_overrun_behavior(_overrun_behavior: number): void;
  public get_text_overrun_behavior(): number;
  public set_ellipsis_char(_char: GDString | StringName | string): void;
  public get_ellipsis_char(): String;
  public set_uppercase(_enable: boolean): void;
  public is_uppercase(): boolean;
  public get_line_height(_line: number = -1): number;
  public get_line_count(): number;
  public get_visible_line_count(): number;
  public get_total_character_count(): number;
  public set_visible_characters(_amount: number): void;
  public get_visible_characters(): number;
  public get_visible_characters_behavior(): number;
  public set_visible_characters_behavior(_behavior: number): void;
  public set_visible_ratio(_ratio: number): void;
  public get_visible_ratio(): number;
  public set_lines_skipped(_lines_skipped: number): void;
  public get_lines_skipped(): number;
  public set_max_lines_visible(_lines_visible: number): void;
  public get_max_lines_visible(): number;
  public set_structured_text_bidi_override(_parser: number): void;
  public get_structured_text_bidi_override(): number;
  public set_structured_text_bidi_override_options(_args: GDArray): void;
  public get_structured_text_bidi_override_options(): GDArray;
  public get_character_bounds(_pos: number): Rect2;
  public get text(): String;
  public set text(value): void;
  public get label_settings(): LabelSettings;
  public set label_settings(value): void;
  public get horizontal_alignment(): number;
  public set horizontal_alignment(value): void;
  public get vertical_alignment(): number;
  public set vertical_alignment(value): void;
  public get autowrap_mode(): number;
  public set autowrap_mode(value): void;
  public get justification_flags(): number;
  public set justification_flags(value): void;
  public get clip_text(): boolean;
  public set clip_text(value): void;
  public get text_overrun_behavior(): number;
  public set text_overrun_behavior(value): void;
  public get ellipsis_char(): String;
  public set ellipsis_char(value): void;
  public get uppercase(): boolean;
  public set uppercase(value): void;
  public get tab_stops(): PackedFloat32Array;
  public set tab_stops(value): void;
  public get lines_skipped(): number;
  public set lines_skipped(value): void;
  public get max_lines_visible(): number;
  public set max_lines_visible(value): void;
  public get visible_characters(): number;
  public set visible_characters(value): void;
  public get visible_characters_behavior(): number;
  public set visible_characters_behavior(value): void;
  public get visible_ratio(): number;
  public set visible_ratio(value): void;
  public get text_direction(): number;
  public set text_direction(value): void;
  public get language(): String;
  public set language(value): void;
  public get structured_text_bidi_override(): number;
  public set structured_text_bidi_override(value): void;
  public get structured_text_bidi_override_options(): GDArray;
  public set structured_text_bidi_override_options(value): void;
}