
import { PopupMenu } from "@godot/classes/popup_menu";
import { Control } from "@godot/classes/control";
export declare class MenuBar extends Control{
  public set_switch_on_hover(_enable: boolean): void;
  public is_switch_on_hover(): boolean;
  public set_disable_shortcuts(_disabled: boolean): void;
  public set_prefer_global_menu(_enabled: boolean): void;
  public is_prefer_global_menu(): boolean;
  public is_native_menu(): boolean;
  public get_menu_count(): number;
  public set_text_direction(_direction: number): void;
  public get_text_direction(): number;
  public set_language(_language: GDString | StringName | string): void;
  public get_language(): String;
  public set_flat(_enabled: boolean): void;
  public is_flat(): boolean;
  public set_start_index(_enabled: number): void;
  public get_start_index(): number;
  public set_menu_title(_menu: number, _title: GDString | StringName | string): void;
  public get_menu_title(_menu: number): String;
  public set_menu_tooltip(_menu: number, _tooltip: GDString | StringName | string): void;
  public get_menu_tooltip(_menu: number): String;
  public set_menu_disabled(_menu: number, _disabled: boolean): void;
  public is_menu_disabled(_menu: number): boolean;
  public set_menu_hidden(_menu: number, _hidden: boolean): void;
  public is_menu_hidden(_menu: number): boolean;
  public get_menu_popup(_menu: number): PopupMenu;
  public get flat(): boolean;
  public set flat(value): void;
  public get start_index(): number;
  public set start_index(value): void;
  public get switch_on_hover(): boolean;
  public set switch_on_hover(value): void;
  public get prefer_global_menu(): boolean;
  public set prefer_global_menu(value): void;
  public get text_direction(): number;
  public set text_direction(value): void;
  public get language(): String;
  public set language(value): void;
}