
import { Node } from "@godot/classes/node";
import { NavigationPathQueryResult3D } from "@godot/classes/navigation_path_query_result3d";


export declare class NavigationAgent3D extends Node{
  public get_rid(): RID;
  public set_avoidance_enabled(_enabled: boolean): void;
  public get_avoidance_enabled(): boolean;
  public set_path_desired_distance(_desired_distance: number): void;
  public get_path_desired_distance(): number;
  public set_target_desired_distance(_desired_distance: number): void;
  public get_target_desired_distance(): number;
  public set_radius(_radius: number): void;
  public get_radius(): number;
  public set_height(_height: number): void;
  public get_height(): number;
  public set_path_height_offset(_path_height_offset: number): void;
  public get_path_height_offset(): number;
  public set_use_3d_avoidance(_enabled: boolean): void;
  public get_use_3d_avoidance(): boolean;
  public set_keep_y_velocity(_enabled: boolean): void;
  public get_keep_y_velocity(): boolean;
  public set_neighbor_distance(_neighbor_distance: number): void;
  public get_neighbor_distance(): number;
  public set_max_neighbors(_max_neighbors: number): void;
  public get_max_neighbors(): number;
  public set_time_horizon_agents(_time_horizon: number): void;
  public get_time_horizon_agents(): number;
  public set_time_horizon_obstacles(_time_horizon: number): void;
  public get_time_horizon_obstacles(): number;
  public set_max_speed(_max_speed: number): void;
  public get_max_speed(): number;
  public set_path_max_distance(_max_speed: number): void;
  public get_path_max_distance(): number;
  public set_navigation_layers(_navigation_layers: number): void;
  public get_navigation_layers(): number;
  public set_navigation_layer_value(_layer_number: number, _value: boolean): void;
  public get_navigation_layer_value(_layer_number: number): boolean;
  public set_pathfinding_algorithm(_pathfinding_algorithm: number): void;
  public get_pathfinding_algorithm(): number;
  public set_path_postprocessing(_path_postprocessing: number): void;
  public get_path_postprocessing(): number;
  public set_path_metadata_flags(_flags: number): void;
  public get_path_metadata_flags(): number;
  public set_navigation_map(_navigation_map: RID): void;
  public get_navigation_map(): RID;
  public set_target_position(_position: Vector3): void;
  public get_target_position(): Vector3;
  public set_simplify_path(_enabled: boolean): void;
  public get_simplify_path(): boolean;
  public set_simplify_epsilon(_epsilon: number): void;
  public get_simplify_epsilon(): number;
  public get_next_path_position(): Vector3;
  public set_velocity_forced(_velocity: Vector3): void;
  public set_velocity(_velocity: Vector3): void;
  public get_velocity(): Vector3;
  public distance_to_target(): number;
  public get_current_navigation_result(): NavigationPathQueryResult3D;
  public get_current_navigation_path(): PackedVector3Array;
  public get_current_navigation_path_index(): number;
  public is_target_reached(): boolean;
  public is_target_reachable(): boolean;
  public is_navigation_finished(): boolean;
  public get_final_position(): Vector3;
  public set_avoidance_layers(_layers: number): void;
  public get_avoidance_layers(): number;
  public set_avoidance_mask(_mask: number): void;
  public get_avoidance_mask(): number;
  public set_avoidance_layer_value(_layer_number: number, _value: boolean): void;
  public get_avoidance_layer_value(_layer_number: number): boolean;
  public set_avoidance_mask_value(_mask_number: number, _value: boolean): void;
  public get_avoidance_mask_value(_mask_number: number): boolean;
  public set_avoidance_priority(_priority: number): void;
  public get_avoidance_priority(): number;
  public set_debug_enabled(_enabled: boolean): void;
  public get_debug_enabled(): boolean;
  public set_debug_use_custom(_enabled: boolean): void;
  public get_debug_use_custom(): boolean;
  public set_debug_path_custom_color(_color: Color): void;
  public get_debug_path_custom_color(): Color;
  public set_debug_path_custom_point_size(_point_size: number): void;
  public get_debug_path_custom_point_size(): number;
  public get target_position(): Vector3;
  public set target_position(value): void;
  public get path_desired_distance(): number;
  public set path_desired_distance(value): void;
  public get target_desired_distance(): number;
  public set target_desired_distance(value): void;
  public get path_height_offset(): number;
  public set path_height_offset(value): void;
  public get path_max_distance(): number;
  public set path_max_distance(value): void;
  public get navigation_layers(): number;
  public set navigation_layers(value): void;
  public get pathfinding_algorithm(): number;
  public set pathfinding_algorithm(value): void;
  public get path_postprocessing(): number;
  public set path_postprocessing(value): void;
  public get path_metadata_flags(): number;
  public set path_metadata_flags(value): void;
  public get simplify_path(): boolean;
  public set simplify_path(value): void;
  public get simplify_epsilon(): number;
  public set simplify_epsilon(value): void;
  public get avoidance_enabled(): boolean;
  public set avoidance_enabled(value): void;
  public get velocity(): Vector3;
  public set velocity(value): void;
  public get height(): number;
  public set height(value): void;
  public get radius(): number;
  public set radius(value): void;
  public get neighbor_distance(): number;
  public set neighbor_distance(value): void;
  public get max_neighbors(): number;
  public set max_neighbors(value): void;
  public get time_horizon_agents(): number;
  public set time_horizon_agents(value): void;
  public get time_horizon_obstacles(): number;
  public set time_horizon_obstacles(value): void;
  public get max_speed(): number;
  public set max_speed(value): void;
  public get use_3d_avoidance(): boolean;
  public set use_3d_avoidance(value): void;
  public get keep_y_velocity(): boolean;
  public set keep_y_velocity(value): void;
  public get avoidance_layers(): number;
  public set avoidance_layers(value): void;
  public get avoidance_mask(): number;
  public set avoidance_mask(value): void;
  public get avoidance_priority(): number;
  public set avoidance_priority(value): void;
  public get debug_enabled(): boolean;
  public set debug_enabled(value): void;
  public get debug_use_custom(): boolean;
  public set debug_use_custom(value): void;
  public get debug_path_custom_color(): Color;
  public set debug_path_custom_color(value): void;
  public get debug_path_custom_point_size(): number;
  public set debug_path_custom_point_size(value): void;
  public get path_changed(): Signal;
  public get target_reached(): Signal;
  public get waypoint_reached(): Signal;
  public get link_reached(): Signal;
  public get navigation_finished(): Signal;
  public get velocity_computed(): Signal;
}