
import { Node } from "@godot/classes/node";
import { CanvasItem } from "@godot/classes/canvas_item";
export declare class Node2D extends CanvasItem{
  public set_position(_position: Vector2): void;
  public set_rotation(_radians: number): void;
  public set_rotation_degrees(_degrees: number): void;
  public set_skew(_radians: number): void;
  public set_scale(_scale: Vector2): void;
  public get_position(): Vector2;
  public get_rotation(): number;
  public get_rotation_degrees(): number;
  public get_skew(): number;
  public get_scale(): Vector2;
  public rotate(_radians: number): void;
  public move_local_x(_delta: number, _scaled: boolean = false): void;
  public move_local_y(_delta: number, _scaled: boolean = false): void;
  public translate(_offset: Vector2): void;
  public global_translate(_offset: Vector2): void;
  public apply_scale(_ratio: Vector2): void;
  public set_global_position(_position: Vector2): void;
  public get_global_position(): Vector2;
  public set_global_rotation(_radians: number): void;
  public set_global_rotation_degrees(_degrees: number): void;
  public get_global_rotation(): number;
  public get_global_rotation_degrees(): number;
  public set_global_skew(_radians: number): void;
  public get_global_skew(): number;
  public set_global_scale(_scale: Vector2): void;
  public get_global_scale(): Vector2;
  public set_transform(_xform: Transform2D): void;
  public set_global_transform(_xform: Transform2D): void;
  public look_at(_point: Vector2): void;
  public get_angle_to(_point: Vector2): number;
  public to_local(_global_point: Vector2): Vector2;
  public to_global(_local_point: Vector2): Vector2;
  public get_relative_transform_to_parent(_parent: Node): Transform2D;
  public get position(): Vector2;
  public set position(value): void;
  public get rotation(): number;
  public set rotation(value): void;
  public get rotation_degrees(): number;
  public set rotation_degrees(value): void;
  public get scale(): Vector2;
  public set scale(value): void;
  public get skew(): number;
  public set skew(value): void;
  public get transform(): Transform2D;
  public set transform(value): void;
  public get global_position(): Vector2;
  public set global_position(value): void;
  public get global_rotation(): number;
  public set global_rotation(value): void;
  public get global_rotation_degrees(): number;
  public set global_rotation_degrees(value): void;
  public get global_scale(): Vector2;
  public set global_scale(value): void;
  public get global_skew(): number;
  public set global_skew(value): void;
  public get global_transform(): Transform2D;
  public set global_transform(value): void;
}