
import type { PhysicsDirectBodyState3D } from '@godot/classes/physics_direct_body_state3d';
import type { PhysicsDirectSpaceState3D } from '@godot/classes/physics_direct_space_state3d';
import type { PhysicsServer3D } from '@godot/classes/physics_server3d';
import type { PhysicsServer3DRenderingServerHandler } from '@godot/classes/physics_server3d_rendering_server_handler';


export declare class PhysicsServer3DExtension extends PhysicsServer3D {


    public _world_boundary_shape_create(): RID;
    public _separation_ray_shape_create(): RID;
    public _sphere_shape_create(): RID;
    public _box_shape_create(): RID;
    public _capsule_shape_create(): RID;
    public _cylinder_shape_create(): RID;
    public _convex_polygon_shape_create(): RID;
    public _concave_polygon_shape_create(): RID;
    public _heightmap_shape_create(): RID;
    public _custom_shape_create(): RID;
    public _shape_set_data(shape: RID, data: any): void;
    public _shape_set_custom_solver_bias(shape: RID, bias: number): void;
    public _shape_set_margin(shape: RID, margin: number): void;
    public _shape_get_margin(shape: RID): number;
    public _shape_get_type(shape: RID): number;
    public _shape_get_data(shape: RID): any;
    public _shape_get_custom_solver_bias(shape: RID): number;
    public _space_create(): RID;
    public _space_set_active(space: RID, active: boolean): void;
    public _space_is_active(space: RID): boolean;
    public _space_set_param(space: RID, param: number, value: number): void;
    public _space_get_param(space: RID, param: number): number;
    public _space_get_direct_state(space: RID): PhysicsDirectSpaceState3D;
    public _space_set_debug_contacts(space: RID, maxContacts: number): void;
    public _space_get_contacts(space: RID): PackedVector3Array;
    public _space_get_contact_count(space: RID): number;
    public _area_create(): RID;
    public _area_set_space(area: RID, space: RID): void;
    public _area_get_space(area: RID): RID;
    public _area_add_shape(area: RID, shape: RID, transform: Transform3D, disabled: boolean): void;
    public _area_set_shape(area: RID, shapeIdx: number, shape: RID): void;
    public _area_set_shape_transform(area: RID, shapeIdx: number, transform: Transform3D): void;
    public _area_set_shape_disabled(area: RID, shapeIdx: number, disabled: boolean): void;
    public _area_get_shape_count(area: RID): number;
    public _area_get_shape(area: RID, shapeIdx: number): RID;
    public _area_get_shape_transform(area: RID, shapeIdx: number): Transform3D;
    public _area_remove_shape(area: RID, shapeIdx: number): void;
    public _area_clear_shapes(area: RID): void;
    public _area_attach_object_instance_id(area: RID, id: number): void;
    public _area_get_object_instance_id(area: RID): number;
    public _area_set_param(area: RID, param: number, value: any): void;
    public _area_set_transform(area: RID, transform: Transform3D): void;
    public _area_get_param(area: RID, param: number): any;
    public _area_get_transform(area: RID): Transform3D;
    public _area_set_collision_layer(area: RID, layer: number): void;
    public _area_get_collision_layer(area: RID): number;
    public _area_set_collision_mask(area: RID, mask: number): void;
    public _area_get_collision_mask(area: RID): number;
    public _area_set_monitorable(area: RID, monitorable: boolean): void;
    public _area_set_ray_pickable(area: RID, enable: boolean): void;
    public _area_set_monitor_callback(area: RID, callback: Callable | Function): void;
    public _area_set_area_monitor_callback(area: RID, callback: Callable | Function): void;
    public _body_create(): RID;
    public _body_set_space(body: RID, space: RID): void;
    public _body_get_space(body: RID): RID;
    public _body_set_mode(body: RID, mode: number): void;
    public _body_get_mode(body: RID): number;
    public _body_add_shape(body: RID, shape: RID, transform: Transform3D, disabled: boolean): void;
    public _body_set_shape(body: RID, shapeIdx: number, shape: RID): void;
    public _body_set_shape_transform(body: RID, shapeIdx: number, transform: Transform3D): void;
    public _body_set_shape_disabled(body: RID, shapeIdx: number, disabled: boolean): void;
    public _body_get_shape_count(body: RID): number;
    public _body_get_shape(body: RID, shapeIdx: number): RID;
    public _body_get_shape_transform(body: RID, shapeIdx: number): Transform3D;
    public _body_remove_shape(body: RID, shapeIdx: number): void;
    public _body_clear_shapes(body: RID): void;
    public _body_attach_object_instance_id(body: RID, id: number): void;
    public _body_get_object_instance_id(body: RID): number;
    public _body_set_enable_continuous_collision_detection(body: RID, enable: boolean): void;
    public _body_is_continuous_collision_detection_enabled(body: RID): boolean;
    public _body_set_collision_layer(body: RID, layer: number): void;
    public _body_get_collision_layer(body: RID): number;
    public _body_set_collision_mask(body: RID, mask: number): void;
    public _body_get_collision_mask(body: RID): number;
    public _body_set_collision_priority(body: RID, priority: number): void;
    public _body_get_collision_priority(body: RID): number;
    public _body_set_user_flags(body: RID, flags: number): void;
    public _body_get_user_flags(body: RID): number;
    public _body_set_param(body: RID, param: number, value: any): void;
    public _body_get_param(body: RID, param: number): any;
    public _body_reset_mass_properties(body: RID): void;
    public _body_set_state(body: RID, state: number, value: any): void;
    public _body_get_state(body: RID, state: number): any;
    public _body_apply_central_impulse(body: RID, impulse: Vector3): void;
    public _body_apply_impulse(body: RID, impulse: Vector3, position: Vector3): void;
    public _body_apply_torque_impulse(body: RID, impulse: Vector3): void;
    public _body_apply_central_force(body: RID, force: Vector3): void;
    public _body_apply_force(body: RID, force: Vector3, position: Vector3): void;
    public _body_apply_torque(body: RID, torque: Vector3): void;
    public _body_add_constant_central_force(body: RID, force: Vector3): void;
    public _body_add_constant_force(body: RID, force: Vector3, position: Vector3): void;
    public _body_add_constant_torque(body: RID, torque: Vector3): void;
    public _body_set_constant_force(body: RID, force: Vector3): void;
    public _body_get_constant_force(body: RID): Vector3;
    public _body_set_constant_torque(body: RID, torque: Vector3): void;
    public _body_get_constant_torque(body: RID): Vector3;
    public _body_set_axis_velocity(body: RID, axisVelocity: Vector3): void;
    public _body_set_axis_lock(body: RID, axis: number, lock: boolean): void;
    public _body_is_axis_locked(body: RID, axis: number): boolean;
    public _body_add_collision_exception(body: RID, exceptedBody: RID): void;
    public _body_remove_collision_exception(body: RID, exceptedBody: RID): void;
    public _body_get_collision_exceptions(body: RID): Array<any>;
    public _body_set_max_contacts_reported(body: RID, amount: number): void;
    public _body_get_max_contacts_reported(body: RID): number;
    public _body_set_contacts_reported_depth_threshold(body: RID, threshold: number): void;
    public _body_get_contacts_reported_depth_threshold(body: RID): number;
    public _body_set_omit_force_integration(body: RID, enable: boolean): void;
    public _body_is_omitting_force_integration(body: RID): boolean;
    public _body_set_state_sync_callback(body: RID, callable: Callable | Function): void;
    public _body_set_force_integration_callback(body: RID, callable: Callable | Function, userdata: any): void;
    public _body_set_ray_pickable(body: RID, enable: boolean): void;
    public _body_test_motion(body: RID, _from: Transform3D, motion: Vector3, margin: number, maxCollisions: number, collideSeparationRay: boolean, recoveryAsCollision: boolean, result: any): boolean;
    public _body_get_direct_state(body: RID): PhysicsDirectBodyState3D;
    public _soft_body_create(): RID;
    public _soft_body_update_rendering_server(body: RID, renderingServerHandler: PhysicsServer3DRenderingServerHandler): void;
    public _soft_body_set_space(body: RID, space: RID): void;
    public _soft_body_get_space(body: RID): RID;
    public _soft_body_set_ray_pickable(body: RID, enable: boolean): void;
    public _soft_body_set_collision_layer(body: RID, layer: number): void;
    public _soft_body_get_collision_layer(body: RID): number;
    public _soft_body_set_collision_mask(body: RID, mask: number): void;
    public _soft_body_get_collision_mask(body: RID): number;
    public _soft_body_add_collision_exception(body: RID, bodyB: RID): void;
    public _soft_body_remove_collision_exception(body: RID, bodyB: RID): void;
    public _soft_body_get_collision_exceptions(body: RID): Array<any>;
    public _soft_body_set_state(body: RID, state: number, variant: any): void;
    public _soft_body_get_state(body: RID, state: number): any;
    public _soft_body_set_transform(body: RID, transform: Transform3D): void;
    public _soft_body_set_simulation_precision(body: RID, simulationPrecision: number): void;
    public _soft_body_get_simulation_precision(body: RID): number;
    public _soft_body_set_total_mass(body: RID, totalMass: number): void;
    public _soft_body_get_total_mass(body: RID): number;
    public _soft_body_set_linear_stiffness(body: RID, linearStiffness: number): void;
    public _soft_body_get_linear_stiffness(body: RID): number;
    public _soft_body_set_shrinking_factor(body: RID, shrinkingFactor: number): void;
    public _soft_body_get_shrinking_factor(body: RID): number;
    public _soft_body_set_pressure_coefficient(body: RID, pressureCoefficient: number): void;
    public _soft_body_get_pressure_coefficient(body: RID): number;
    public _soft_body_set_damping_coefficient(body: RID, dampingCoefficient: number): void;
    public _soft_body_get_damping_coefficient(body: RID): number;
    public _soft_body_set_drag_coefficient(body: RID, dragCoefficient: number): void;
    public _soft_body_get_drag_coefficient(body: RID): number;
    public _soft_body_set_mesh(body: RID, mesh: RID): void;
    public _soft_body_get_bounds(body: RID): AABB;
    public _soft_body_move_point(body: RID, pointIndex: number, globalPosition: Vector3): void;
    public _soft_body_get_point_global_position(body: RID, pointIndex: number): Vector3;
    public _soft_body_remove_all_pinned_points(body: RID): void;
    public _soft_body_pin_point(body: RID, pointIndex: number, pin: boolean): void;
    public _soft_body_is_point_pinned(body: RID, pointIndex: number): boolean;
    public _soft_body_apply_point_impulse(body: RID, pointIndex: number, impulse: Vector3): void;
    public _soft_body_apply_point_force(body: RID, pointIndex: number, force: Vector3): void;
    public _soft_body_apply_central_impulse(body: RID, impulse: Vector3): void;
    public _soft_body_apply_central_force(body: RID, force: Vector3): void;
    public _joint_create(): RID;
    public _joint_clear(joint: RID): void;
    public _joint_make_pin(joint: RID, bodyA: RID, localA: Vector3, bodyB: RID, localB: Vector3): void;
    public _pin_joint_set_param(joint: RID, param: number, value: number): void;
    public _pin_joint_get_param(joint: RID, param: number): number;
    public _pin_joint_set_local_a(joint: RID, localA: Vector3): void;
    public _pin_joint_get_local_a(joint: RID): Vector3;
    public _pin_joint_set_local_b(joint: RID, localB: Vector3): void;
    public _pin_joint_get_local_b(joint: RID): Vector3;
    public _joint_make_hinge(joint: RID, bodyA: RID, hingeA: Transform3D, bodyB: RID, hingeB: Transform3D): void;
    public _joint_make_hinge_simple(joint: RID, bodyA: RID, pivotA: Vector3, axisA: Vector3, bodyB: RID, pivotB: Vector3, axisB: Vector3): void;
    public _hinge_joint_set_param(joint: RID, param: number, value: number): void;
    public _hinge_joint_get_param(joint: RID, param: number): number;
    public _hinge_joint_set_flag(joint: RID, flag: number, enabled: boolean): void;
    public _hinge_joint_get_flag(joint: RID, flag: number): boolean;
    public _joint_make_slider(joint: RID, bodyA: RID, localRefA: Transform3D, bodyB: RID, localRefB: Transform3D): void;
    public _slider_joint_set_param(joint: RID, param: number, value: number): void;
    public _slider_joint_get_param(joint: RID, param: number): number;
    public _joint_make_cone_twist(joint: RID, bodyA: RID, localRefA: Transform3D, bodyB: RID, localRefB: Transform3D): void;
    public _cone_twist_joint_set_param(joint: RID, param: number, value: number): void;
    public _cone_twist_joint_get_param(joint: RID, param: number): number;
    public _joint_make_generic_6dof(joint: RID, bodyA: RID, localRefA: Transform3D, bodyB: RID, localRefB: Transform3D): void;
    public _generic_6dof_joint_set_param(joint: RID, axis: number, param: number, value: number): void;
    public _generic_6dof_joint_get_param(joint: RID, axis: number, param: number): number;
    public _generic_6dof_joint_set_flag(joint: RID, axis: number, flag: number, enable: boolean): void;
    public _generic_6dof_joint_get_flag(joint: RID, axis: number, flag: number): boolean;
    public _joint_get_type(joint: RID): number;
    public _joint_set_solver_priority(joint: RID, priority: number): void;
    public _joint_get_solver_priority(joint: RID): number;
    public _joint_disable_collisions_between_bodies(joint: RID, disable: boolean): void;
    public _joint_is_disabled_collisions_between_bodies(joint: RID): boolean;
    public _free_rid(rid: RID): void;
    public _set_active(active: boolean): void;
    public _init(): void;
    public _step(step: number): void;
    public _sync(): void;
    public _flush_queries(): void;
    public _end_sync(): void;
    public _finish(): void;
    public _is_flushing_queries(): boolean;
    public _get_process_info(processInfo: number): number;
    public body_test_motion_is_excluding_body(body: RID): boolean;
    public body_test_motion_is_excluding_object(object: number): boolean;


}

