
import { PhysicsDirectSpaceState3D } from "@godot/classes/physics_direct_space_state3d";
import { GodotObject } from "@godot/classes/godot_object";
export declare class PhysicsDirectBodyState3D extends GodotObject{
  public get_total_gravity(): Vector3;
  public get_total_linear_damp(): number;
  public get_total_angular_damp(): number;
  public get_center_of_mass(): Vector3;
  public get_center_of_mass_local(): Vector3;
  public get_principal_inertia_axes(): Basis;
  public get_inverse_mass(): number;
  public get_inverse_inertia(): Vector3;
  public get_inverse_inertia_tensor(): Basis;
  public set_linear_velocity(_velocity: Vector3): void;
  public get_linear_velocity(): Vector3;
  public set_angular_velocity(_velocity: Vector3): void;
  public get_angular_velocity(): Vector3;
  public set_transform(_transform: Transform3D): void;
  public get_transform(): Transform3D;
  public get_velocity_at_local_position(_local_position: Vector3): Vector3;
  public apply_central_impulse(_impulse: Vector3 = Vector3(0, 0, 0)): void;
  public apply_impulse(_impulse: Vector3, _position: Vector3 = Vector3(0, 0, 0)): void;
  public apply_torque_impulse(_impulse: Vector3): void;
  public apply_central_force(_force: Vector3 = Vector3(0, 0, 0)): void;
  public apply_force(_force: Vector3, _position: Vector3 = Vector3(0, 0, 0)): void;
  public apply_torque(_torque: Vector3): void;
  public add_constant_central_force(_force: Vector3 = Vector3(0, 0, 0)): void;
  public add_constant_force(_force: Vector3, _position: Vector3 = Vector3(0, 0, 0)): void;
  public add_constant_torque(_torque: Vector3): void;
  public set_constant_force(_force: Vector3): void;
  public get_constant_force(): Vector3;
  public set_constant_torque(_torque: Vector3): void;
  public get_constant_torque(): Vector3;
  public set_sleep_state(_enabled: boolean): void;
  public is_sleeping(): boolean;
  public get_contact_count(): number;
  public get_contact_local_position(_contact_idx: number): Vector3;
  public get_contact_local_normal(_contact_idx: number): Vector3;
  public get_contact_impulse(_contact_idx: number): Vector3;
  public get_contact_local_shape(_contact_idx: number): number;
  public get_contact_local_velocity_at_position(_contact_idx: number): Vector3;
  public get_contact_collider(_contact_idx: number): RID;
  public get_contact_collider_position(_contact_idx: number): Vector3;
  public get_contact_collider_id(_contact_idx: number): number;
  public get_contact_collider_object(_contact_idx: number): GodotObject;
  public get_contact_collider_shape(_contact_idx: number): number;
  public get_contact_collider_velocity_at_position(_contact_idx: number): Vector3;
  public get_step(): number;
  public integrate_forces(): void;
  public get_space_state(): PhysicsDirectSpaceState3D;
  public get step(): number;
  public get inverse_mass(): number;
  public get total_angular_damp(): number;
  public get total_linear_damp(): number;
  public get inverse_inertia(): Vector3;
  public get inverse_inertia_tensor(): Basis;
  public get total_gravity(): Vector3;
  public get center_of_mass(): Vector3;
  public get center_of_mass_local(): Vector3;
  public get principal_inertia_axes(): Basis;
  public get angular_velocity(): Vector3;
  public set angular_velocity(value): void;
  public get linear_velocity(): Vector3;
  public set linear_velocity(value): void;
  public get sleeping(): boolean;
  public set sleeping(value): void;
  public get transform(): Transform3D;
  public set transform(value): void;
}