
import type { Callable } from '@godot/builtins/callable';
import type { PackedVector2Array } from '@godot/builtins/packed_vector2_array';
import type { PhysicsDirectBodyState2D } from '@godot/classes/physics_direct_body_state2d';
import type { PhysicsDirectSpaceState2D } from '@godot/classes/physics_direct_space_state2d';
import type { PhysicsServer2D } from '@godot/classes/physics_server2d';
import type { RID } from '@godot/builtins/rid';
import type { Transform2D } from '@godot/builtins/transform2d';
import type { Vector2 } from '@godot/builtins/vector2';


export declare class PhysicsServer2DExtension extends PhysicsServer2D {


    public _world_boundary_shape_create(): RID;
    public _separation_ray_shape_create(): RID;
    public _segment_shape_create(): RID;
    public _circle_shape_create(): RID;
    public _rectangle_shape_create(): RID;
    public _capsule_shape_create(): RID;
    public _convex_polygon_shape_create(): RID;
    public _concave_polygon_shape_create(): RID;
    public _shape_set_data(shape: RID, data: any): void;
    public _shape_set_custom_solver_bias(shape: RID, bias: number): void;
    public _shape_get_type(shape: RID): number;
    public _shape_get_data(shape: RID): any;
    public _shape_get_custom_solver_bias(shape: RID): number;
    public _shape_collide(shapeA: RID, xformA: Transform2D, motionA: Vector2, shapeB: RID, xformB: Transform2D, motionB: Vector2, results: any, resultMax: number, resultCount: any): boolean;
    public _space_create(): RID;
    public _space_set_active(space: RID, active: boolean): void;
    public _space_is_active(space: RID): boolean;
    public _space_set_param(space: RID, param: number, value: number): void;
    public _space_get_param(space: RID, param: number): number;
    public _space_get_direct_state(space: RID): PhysicsDirectSpaceState2D;
    public _space_set_debug_contacts(space: RID, maxContacts: number): void;
    public _space_get_contacts(space: RID): PackedVector2Array;
    public _space_get_contact_count(space: RID): number;
    public _area_create(): RID;
    public _area_set_space(area: RID, space: RID): void;
    public _area_get_space(area: RID): RID;
    public _area_add_shape(area: RID, shape: RID, transform: Transform2D, disabled: boolean): void;
    public _area_set_shape(area: RID, shapeIdx: number, shape: RID): void;
    public _area_set_shape_transform(area: RID, shapeIdx: number, transform: Transform2D): void;
    public _area_set_shape_disabled(area: RID, shapeIdx: number, disabled: boolean): void;
    public _area_get_shape_count(area: RID): number;
    public _area_get_shape(area: RID, shapeIdx: number): RID;
    public _area_get_shape_transform(area: RID, shapeIdx: number): Transform2D;
    public _area_remove_shape(area: RID, shapeIdx: number): void;
    public _area_clear_shapes(area: RID): void;
    public _area_attach_object_instance_id(area: RID, id: number): void;
    public _area_get_object_instance_id(area: RID): number;
    public _area_attach_canvas_instance_id(area: RID, id: number): void;
    public _area_get_canvas_instance_id(area: RID): number;
    public _area_set_param(area: RID, param: number, value: any): void;
    public _area_set_transform(area: RID, transform: Transform2D): void;
    public _area_get_param(area: RID, param: number): any;
    public _area_get_transform(area: RID): Transform2D;
    public _area_set_collision_layer(area: RID, layer: number): void;
    public _area_get_collision_layer(area: RID): number;
    public _area_set_collision_mask(area: RID, mask: number): void;
    public _area_get_collision_mask(area: RID): number;
    public _area_set_monitorable(area: RID, monitorable: boolean): void;
    public _area_set_pickable(area: RID, pickable: boolean): void;
    public _area_set_monitor_callback(area: RID, callback: Callable): void;
    public _area_set_area_monitor_callback(area: RID, callback: Callable): void;
    public _body_create(): RID;
    public _body_set_space(body: RID, space: RID): void;
    public _body_get_space(body: RID): RID;
    public _body_set_mode(body: RID, mode: number): void;
    public _body_get_mode(body: RID): number;
    public _body_add_shape(body: RID, shape: RID, transform: Transform2D, disabled: boolean): void;
    public _body_set_shape(body: RID, shapeIdx: number, shape: RID): void;
    public _body_set_shape_transform(body: RID, shapeIdx: number, transform: Transform2D): void;
    public _body_get_shape_count(body: RID): number;
    public _body_get_shape(body: RID, shapeIdx: number): RID;
    public _body_get_shape_transform(body: RID, shapeIdx: number): Transform2D;
    public _body_set_shape_disabled(body: RID, shapeIdx: number, disabled: boolean): void;
    public _body_set_shape_as_one_way_collision(body: RID, shapeIdx: number, enable: boolean, margin: number): void;
    public _body_remove_shape(body: RID, shapeIdx: number): void;
    public _body_clear_shapes(body: RID): void;
    public _body_attach_object_instance_id(body: RID, id: number): void;
    public _body_get_object_instance_id(body: RID): number;
    public _body_attach_canvas_instance_id(body: RID, id: number): void;
    public _body_get_canvas_instance_id(body: RID): number;
    public _body_set_continuous_collision_detection_mode(body: RID, mode: number): void;
    public _body_get_continuous_collision_detection_mode(body: RID): number;
    public _body_set_collision_layer(body: RID, layer: number): void;
    public _body_get_collision_layer(body: RID): number;
    public _body_set_collision_mask(body: RID, mask: number): void;
    public _body_get_collision_mask(body: RID): number;
    public _body_set_collision_priority(body: RID, priority: number): void;
    public _body_get_collision_priority(body: RID): number;
    public _body_set_param(body: RID, param: number, value: any): void;
    public _body_get_param(body: RID, param: number): any;
    public _body_reset_mass_properties(body: RID): void;
    public _body_set_state(body: RID, state: number, value: any): void;
    public _body_get_state(body: RID, state: number): any;
    public _body_apply_central_impulse(body: RID, impulse: Vector2): void;
    public _body_apply_torque_impulse(body: RID, impulse: number): void;
    public _body_apply_impulse(body: RID, impulse: Vector2, position: Vector2): void;
    public _body_apply_central_force(body: RID, force: Vector2): void;
    public _body_apply_force(body: RID, force: Vector2, position: Vector2): void;
    public _body_apply_torque(body: RID, torque: number): void;
    public _body_add_constant_central_force(body: RID, force: Vector2): void;
    public _body_add_constant_force(body: RID, force: Vector2, position: Vector2): void;
    public _body_add_constant_torque(body: RID, torque: number): void;
    public _body_set_constant_force(body: RID, force: Vector2): void;
    public _body_get_constant_force(body: RID): Vector2;
    public _body_set_constant_torque(body: RID, torque: number): void;
    public _body_get_constant_torque(body: RID): number;
    public _body_set_axis_velocity(body: RID, axisVelocity: Vector2): void;
    public _body_add_collision_exception(body: RID, exceptedBody: RID): void;
    public _body_remove_collision_exception(body: RID, exceptedBody: RID): void;
    public _body_get_collision_exceptions(body: RID): Array<any>;
    public _body_set_max_contacts_reported(body: RID, amount: number): void;
    public _body_get_max_contacts_reported(body: RID): number;
    public _body_set_contacts_reported_depth_threshold(body: RID, threshold: number): void;
    public _body_get_contacts_reported_depth_threshold(body: RID): number;
    public _body_set_omit_force_integration(body: RID, enable: boolean): void;
    public _body_is_omitting_force_integration(body: RID): boolean;
    public _body_set_state_sync_callback(body: RID, callable: Callable): void;
    public _body_set_force_integration_callback(body: RID, callable: Callable, userdata: any): void;
    public _body_collide_shape(body: RID, bodyShape: number, shape: RID, shapeXform: Transform2D, motion: Vector2, results: any, resultMax: number, resultCount: any): boolean;
    public _body_set_pickable(body: RID, pickable: boolean): void;
    public _body_get_direct_state(body: RID): PhysicsDirectBodyState2D;
    public _body_test_motion(body: RID, _from: Transform2D, motion: Vector2, margin: number, collideSeparationRay: boolean, recoveryAsCollision: boolean, result: any): boolean;
    public _joint_create(): RID;
    public _joint_clear(joint: RID): void;
    public _joint_set_param(joint: RID, param: number, value: number): void;
    public _joint_get_param(joint: RID, param: number): number;
    public _joint_disable_collisions_between_bodies(joint: RID, disable: boolean): void;
    public _joint_is_disabled_collisions_between_bodies(joint: RID): boolean;
    public _joint_make_pin(joint: RID, anchor: Vector2, bodyA: RID, bodyB: RID): void;
    public _joint_make_groove(joint: RID, aGroove1: Vector2, aGroove2: Vector2, bAnchor: Vector2, bodyA: RID, bodyB: RID): void;
    public _joint_make_damped_spring(joint: RID, anchorA: Vector2, anchorB: Vector2, bodyA: RID, bodyB: RID): void;
    public _pin_joint_set_flag(joint: RID, flag: number, enabled: boolean): void;
    public _pin_joint_get_flag(joint: RID, flag: number): boolean;
    public _pin_joint_set_param(joint: RID, param: number, value: number): void;
    public _pin_joint_get_param(joint: RID, param: number): number;
    public _damped_spring_joint_set_param(joint: RID, param: number, value: number): void;
    public _damped_spring_joint_get_param(joint: RID, param: number): number;
    public _joint_get_type(joint: RID): number;
    public _free_rid(rid: RID): void;
    public _set_active(active: boolean): void;
    public _init(): void;
    public _step(step: number): void;
    public _sync(): void;
    public _flush_queries(): void;
    public _end_sync(): void;
    public _finish(): void;
    public _is_flushing_queries(): boolean;
    public _get_process_info(processInfo: number): number;
    public body_test_motion_is_excluding_body(body: RID): boolean;
    public body_test_motion_is_excluding_object(object: number): boolean;


}

