
import { PhysicsDirectSpaceState2D } from "@godot/classes/physics_direct_space_state2d";
import { PhysicsDirectBodyState2D } from "@godot/classes/physics_direct_body_state2d";
import { Object } from "@godot/classes/object";

export declare class PhysicsDirectBodyState2DExtension extends PhysicsDirectBodyState2D{
  public _get_total_gravity(): Vector2;
  public _get_total_linear_damp(): number;
  public _get_total_angular_damp(): number;
  public _get_center_of_mass(): Vector2;
  public _get_center_of_mass_local(): Vector2;
  public _get_inverse_mass(): number;
  public _get_inverse_inertia(): number;
  public _set_linear_velocity(_velocity: Vector2): void;
  public _get_linear_velocity(): Vector2;
  public _set_angular_velocity(_velocity: number): void;
  public _get_angular_velocity(): number;
  public _set_transform(_transform: Transform2D): void;
  public _get_transform(): Transform2D;
  public _get_velocity_at_local_position(_local_position: Vector2): Vector2;
  public _apply_central_impulse(_impulse: Vector2): void;
  public _apply_impulse(_impulse: Vector2, _position: Vector2): void;
  public _apply_torque_impulse(_impulse: number): void;
  public _apply_central_force(_force: Vector2): void;
  public _apply_force(_force: Vector2, _position: Vector2): void;
  public _apply_torque(_torque: number): void;
  public _add_constant_central_force(_force: Vector2): void;
  public _add_constant_force(_force: Vector2, _position: Vector2): void;
  public _add_constant_torque(_torque: number): void;
  public _set_constant_force(_force: Vector2): void;
  public _get_constant_force(): Vector2;
  public _set_constant_torque(_torque: number): void;
  public _get_constant_torque(): number;
  public _set_sleep_state(_enabled: boolean): void;
  public _is_sleeping(): boolean;
  public _get_contact_count(): number;
  public _get_contact_local_position(_contact_idx: number): Vector2;
  public _get_contact_local_normal(_contact_idx: number): Vector2;
  public _get_contact_local_shape(_contact_idx: number): number;
  public _get_contact_local_velocity_at_position(_contact_idx: number): Vector2;
  public _get_contact_collider(_contact_idx: number): RID;
  public _get_contact_collider_position(_contact_idx: number): Vector2;
  public _get_contact_collider_id(_contact_idx: number): number;
  public _get_contact_collider_object(_contact_idx: number): Object;
  public _get_contact_collider_shape(_contact_idx: number): number;
  public _get_contact_collider_velocity_at_position(_contact_idx: number): Vector2;
  public _get_contact_impulse(_contact_idx: number): Vector2;
  public _get_step(): number;
  public _integrate_forces(): void;
  public _get_space_state(): PhysicsDirectSpaceState2D;
}