
import type { AABB } from '@godot/builtins/aabb';
import type { Callable } from '@godot/builtins/callable';
import type { GodotObject } from '@godot/classes/godot_object';
import type { PhysicsDirectBodyState3D } from '@godot/classes/physics_direct_body_state3d';
import type { PhysicsDirectSpaceState3D } from '@godot/classes/physics_direct_space_state3d';
import type { PhysicsServer3DRenderingServerHandler } from '@godot/classes/physics_server3d_rendering_server_handler';
import type { PhysicsTestMotionParameters3D } from '@godot/classes/physics_test_motion_parameters3d';
import type { PhysicsTestMotionResult3D } from '@godot/classes/physics_test_motion_result3d';
import type { RID } from '@godot/builtins/rid';
import type { Transform3D } from '@godot/builtins/transform3d';
import type { Vector3 } from '@godot/builtins/vector3';


export declare class PhysicsServer3D extends GodotObject {


    public world_boundary_shape_create(): RID;
    public separation_ray_shape_create(): RID;
    public sphere_shape_create(): RID;
    public box_shape_create(): RID;
    public capsule_shape_create(): RID;
    public cylinder_shape_create(): RID;
    public convex_polygon_shape_create(): RID;
    public concave_polygon_shape_create(): RID;
    public heightmap_shape_create(): RID;
    public custom_shape_create(): RID;
    public shape_set_data(shape: RID, data: any): void;
    public shape_set_margin(shape: RID, margin: number): void;
    public shape_get_type(shape: RID): number;
    public shape_get_data(shape: RID): any;
    public shape_get_margin(shape: RID): number;
    public space_create(): RID;
    public space_set_active(space: RID, active: boolean): void;
    public space_is_active(space: RID): boolean;
    public space_set_param(space: RID, param: number, value: number): void;
    public space_get_param(space: RID, param: number): number;
    public space_get_direct_state(space: RID): PhysicsDirectSpaceState3D;
    public area_create(): RID;
    public area_set_space(area: RID, space: RID): void;
    public area_get_space(area: RID): RID;
    public area_add_shape(area: RID, shape: RID, transform: Transform3D = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0), disabled: boolean = false): void;
    public area_set_shape(area: RID, shapeIdx: number, shape: RID): void;
    public area_set_shape_transform(area: RID, shapeIdx: number, transform: Transform3D): void;
    public area_set_shape_disabled(area: RID, shapeIdx: number, disabled: boolean): void;
    public area_get_shape_count(area: RID): number;
    public area_get_shape(area: RID, shapeIdx: number): RID;
    public area_get_shape_transform(area: RID, shapeIdx: number): Transform3D;
    public area_remove_shape(area: RID, shapeIdx: number): void;
    public area_clear_shapes(area: RID): void;
    public area_set_collision_layer(area: RID, layer: number): void;
    public area_get_collision_layer(area: RID): number;
    public area_set_collision_mask(area: RID, mask: number): void;
    public area_get_collision_mask(area: RID): number;
    public area_set_param(area: RID, param: number, value: any): void;
    public area_set_transform(area: RID, transform: Transform3D): void;
    public area_get_param(area: RID, param: number): any;
    public area_get_transform(area: RID): Transform3D;
    public area_attach_object_instance_id(area: RID, id: number): void;
    public area_get_object_instance_id(area: RID): number;
    public area_set_monitor_callback(area: RID, callback: Callable): void;
    public area_set_area_monitor_callback(area: RID, callback: Callable): void;
    public area_set_monitorable(area: RID, monitorable: boolean): void;
    public area_set_ray_pickable(area: RID, enable: boolean): void;
    public body_create(): RID;
    public body_set_space(body: RID, space: RID): void;
    public body_get_space(body: RID): RID;
    public body_set_mode(body: RID, mode: number): void;
    public body_get_mode(body: RID): number;
    public body_set_collision_layer(body: RID, layer: number): void;
    public body_get_collision_layer(body: RID): number;
    public body_set_collision_mask(body: RID, mask: number): void;
    public body_get_collision_mask(body: RID): number;
    public body_set_collision_priority(body: RID, priority: number): void;
    public body_get_collision_priority(body: RID): number;
    public body_add_shape(body: RID, shape: RID, transform: Transform3D = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0), disabled: boolean = false): void;
    public body_set_shape(body: RID, shapeIdx: number, shape: RID): void;
    public body_set_shape_transform(body: RID, shapeIdx: number, transform: Transform3D): void;
    public body_set_shape_disabled(body: RID, shapeIdx: number, disabled: boolean): void;
    public body_get_shape_count(body: RID): number;
    public body_get_shape(body: RID, shapeIdx: number): RID;
    public body_get_shape_transform(body: RID, shapeIdx: number): Transform3D;
    public body_remove_shape(body: RID, shapeIdx: number): void;
    public body_clear_shapes(body: RID): void;
    public body_attach_object_instance_id(body: RID, id: number): void;
    public body_get_object_instance_id(body: RID): number;
    public body_set_enable_continuous_collision_detection(body: RID, enable: boolean): void;
    public body_is_continuous_collision_detection_enabled(body: RID): boolean;
    public body_set_param(body: RID, param: number, value: any): void;
    public body_get_param(body: RID, param: number): any;
    public body_reset_mass_properties(body: RID): void;
    public body_set_state(body: RID, state: number, value: any): void;
    public body_get_state(body: RID, state: number): any;
    public body_apply_central_impulse(body: RID, impulse: Vector3): void;
    public body_apply_impulse(body: RID, impulse: Vector3, position: Vector3 = Vector3(0, 0, 0)): void;
    public body_apply_torque_impulse(body: RID, impulse: Vector3): void;
    public body_apply_central_force(body: RID, force: Vector3): void;
    public body_apply_force(body: RID, force: Vector3, position: Vector3 = Vector3(0, 0, 0)): void;
    public body_apply_torque(body: RID, torque: Vector3): void;
    public body_add_constant_central_force(body: RID, force: Vector3): void;
    public body_add_constant_force(body: RID, force: Vector3, position: Vector3 = Vector3(0, 0, 0)): void;
    public body_add_constant_torque(body: RID, torque: Vector3): void;
    public body_set_constant_force(body: RID, force: Vector3): void;
    public body_get_constant_force(body: RID): Vector3;
    public body_set_constant_torque(body: RID, torque: Vector3): void;
    public body_get_constant_torque(body: RID): Vector3;
    public body_set_axis_velocity(body: RID, axisVelocity: Vector3): void;
    public body_set_axis_lock(body: RID, axis: number, lock: boolean): void;
    public body_is_axis_locked(body: RID, axis: number): boolean;
    public body_add_collision_exception(body: RID, exceptedBody: RID): void;
    public body_remove_collision_exception(body: RID, exceptedBody: RID): void;
    public body_set_max_contacts_reported(body: RID, amount: number): void;
    public body_get_max_contacts_reported(body: RID): number;
    public body_set_omit_force_integration(body: RID, enable: boolean): void;
    public body_is_omitting_force_integration(body: RID): boolean;
    public body_set_state_sync_callback(body: RID, callable: Callable): void;
    public body_set_force_integration_callback(body: RID, callable: Callable, userdata: any = null): void;
    public body_set_ray_pickable(body: RID, enable: boolean): void;
    public body_test_motion(body: RID, parameters: PhysicsTestMotionParameters3D, result: PhysicsTestMotionResult3D = null): boolean;
    public body_get_direct_state(body: RID): PhysicsDirectBodyState3D;
    public soft_body_create(): RID;
    public soft_body_update_rendering_server(body: RID, renderingServerHandler: PhysicsServer3DRenderingServerHandler): void;
    public soft_body_set_space(body: RID, space: RID): void;
    public soft_body_get_space(body: RID): RID;
    public soft_body_set_mesh(body: RID, mesh: RID): void;
    public soft_body_get_bounds(body: RID): AABB;
    public soft_body_set_collision_layer(body: RID, layer: number): void;
    public soft_body_get_collision_layer(body: RID): number;
    public soft_body_set_collision_mask(body: RID, mask: number): void;
    public soft_body_get_collision_mask(body: RID): number;
    public soft_body_add_collision_exception(body: RID, bodyB: RID): void;
    public soft_body_remove_collision_exception(body: RID, bodyB: RID): void;
    public soft_body_set_state(body: RID, state: number, variant: any): void;
    public soft_body_get_state(body: RID, state: number): any;
    public soft_body_set_transform(body: RID, transform: Transform3D): void;
    public soft_body_set_ray_pickable(body: RID, enable: boolean): void;
    public soft_body_set_simulation_precision(body: RID, simulationPrecision: number): void;
    public soft_body_get_simulation_precision(body: RID): number;
    public soft_body_set_total_mass(body: RID, totalMass: number): void;
    public soft_body_get_total_mass(body: RID): number;
    public soft_body_set_linear_stiffness(body: RID, stiffness: number): void;
    public soft_body_get_linear_stiffness(body: RID): number;
    public soft_body_set_shrinking_factor(body: RID, shrinkingFactor: number): void;
    public soft_body_get_shrinking_factor(body: RID): number;
    public soft_body_set_pressure_coefficient(body: RID, pressureCoefficient: number): void;
    public soft_body_get_pressure_coefficient(body: RID): number;
    public soft_body_set_damping_coefficient(body: RID, dampingCoefficient: number): void;
    public soft_body_get_damping_coefficient(body: RID): number;
    public soft_body_set_drag_coefficient(body: RID, dragCoefficient: number): void;
    public soft_body_get_drag_coefficient(body: RID): number;
    public soft_body_move_point(body: RID, pointIndex: number, globalPosition: Vector3): void;
    public soft_body_get_point_global_position(body: RID, pointIndex: number): Vector3;
    public soft_body_remove_all_pinned_points(body: RID): void;
    public soft_body_pin_point(body: RID, pointIndex: number, pin: boolean): void;
    public soft_body_is_point_pinned(body: RID, pointIndex: number): boolean;
    public soft_body_apply_point_impulse(body: RID, pointIndex: number, impulse: Vector3): void;
    public soft_body_apply_point_force(body: RID, pointIndex: number, force: Vector3): void;
    public soft_body_apply_central_impulse(body: RID, impulse: Vector3): void;
    public soft_body_apply_central_force(body: RID, force: Vector3): void;
    public joint_create(): RID;
    public joint_clear(joint: RID): void;
    public joint_make_pin(joint: RID, bodyA: RID, localA: Vector3, bodyB: RID, localB: Vector3): void;
    public pin_joint_set_param(joint: RID, param: number, value: number): void;
    public pin_joint_get_param(joint: RID, param: number): number;
    public pin_joint_set_local_a(joint: RID, localA: Vector3): void;
    public pin_joint_get_local_a(joint: RID): Vector3;
    public pin_joint_set_local_b(joint: RID, localB: Vector3): void;
    public pin_joint_get_local_b(joint: RID): Vector3;
    public joint_make_hinge(joint: RID, bodyA: RID, hingeA: Transform3D, bodyB: RID, hingeB: Transform3D): void;
    public hinge_joint_set_param(joint: RID, param: number, value: number): void;
    public hinge_joint_get_param(joint: RID, param: number): number;
    public hinge_joint_set_flag(joint: RID, flag: number, enabled: boolean): void;
    public hinge_joint_get_flag(joint: RID, flag: number): boolean;
    public joint_make_slider(joint: RID, bodyA: RID, localRefA: Transform3D, bodyB: RID, localRefB: Transform3D): void;
    public slider_joint_set_param(joint: RID, param: number, value: number): void;
    public slider_joint_get_param(joint: RID, param: number): number;
    public joint_make_cone_twist(joint: RID, bodyA: RID, localRefA: Transform3D, bodyB: RID, localRefB: Transform3D): void;
    public cone_twist_joint_set_param(joint: RID, param: number, value: number): void;
    public cone_twist_joint_get_param(joint: RID, param: number): number;
    public joint_get_type(joint: RID): number;
    public joint_set_solver_priority(joint: RID, priority: number): void;
    public joint_get_solver_priority(joint: RID): number;
    public joint_disable_collisions_between_bodies(joint: RID, disable: boolean): void;
    public joint_is_disabled_collisions_between_bodies(joint: RID): boolean;
    public joint_make_generic_6dof(joint: RID, bodyA: RID, localRefA: Transform3D, bodyB: RID, localRefB: Transform3D): void;
    public generic_6dof_joint_set_param(joint: RID, axis: number, param: number, value: number): void;
    public generic_6dof_joint_get_param(joint: RID, axis: number, param: number): number;
    public generic_6dof_joint_set_flag(joint: RID, axis: number, flag: number, enable: boolean): void;
    public generic_6dof_joint_get_flag(joint: RID, axis: number, flag: number): boolean;
    public free_rid(rid: RID): void;
    public set_active(active: boolean): void;
    public get_process_info(processInfo: number): number;


    public static readonly JointType: {
        JOINT_TYPE_PIN: 0;
        JOINT_TYPE_HINGE: 1;
        JOINT_TYPE_SLIDER: 2;
        JOINT_TYPE_CONE_TWIST: 3;
        JOINT_TYPE_6DOF: 4;
        JOINT_TYPE_MAX: 5;
    };
    public static readonly PinJointParam: {
        PIN_JOINT_BIAS: 0;
        PIN_JOINT_DAMPING: 1;
        PIN_JOINT_IMPULSE_CLAMP: 2;
    };
    public static readonly HingeJointParam: {
        HINGE_JOINT_BIAS: 0;
        HINGE_JOINT_LIMIT_UPPER: 1;
        HINGE_JOINT_LIMIT_LOWER: 2;
        HINGE_JOINT_LIMIT_BIAS: 3;
        HINGE_JOINT_LIMIT_SOFTNESS: 4;
        HINGE_JOINT_LIMIT_RELAXATION: 5;
        HINGE_JOINT_MOTOR_TARGET_VELOCITY: 6;
        HINGE_JOINT_MOTOR_MAX_IMPULSE: 7;
    };
    public static readonly HingeJointFlag: {
        HINGE_JOINT_FLAG_USE_LIMIT: 0;
        HINGE_JOINT_FLAG_ENABLE_MOTOR: 1;
    };
    public static readonly SliderJointParam: {
        SLIDER_JOINT_LINEAR_LIMIT_UPPER: 0;
        SLIDER_JOINT_LINEAR_LIMIT_LOWER: 1;
        SLIDER_JOINT_LINEAR_LIMIT_SOFTNESS: 2;
        SLIDER_JOINT_LINEAR_LIMIT_RESTITUTION: 3;
        SLIDER_JOINT_LINEAR_LIMIT_DAMPING: 4;
        SLIDER_JOINT_LINEAR_MOTION_SOFTNESS: 5;
        SLIDER_JOINT_LINEAR_MOTION_RESTITUTION: 6;
        SLIDER_JOINT_LINEAR_MOTION_DAMPING: 7;
        SLIDER_JOINT_LINEAR_ORTHOGONAL_SOFTNESS: 8;
        SLIDER_JOINT_LINEAR_ORTHOGONAL_RESTITUTION: 9;
        SLIDER_JOINT_LINEAR_ORTHOGONAL_DAMPING: 10;
        SLIDER_JOINT_ANGULAR_LIMIT_UPPER: 11;
        SLIDER_JOINT_ANGULAR_LIMIT_LOWER: 12;
        SLIDER_JOINT_ANGULAR_LIMIT_SOFTNESS: 13;
        SLIDER_JOINT_ANGULAR_LIMIT_RESTITUTION: 14;
        SLIDER_JOINT_ANGULAR_LIMIT_DAMPING: 15;
        SLIDER_JOINT_ANGULAR_MOTION_SOFTNESS: 16;
        SLIDER_JOINT_ANGULAR_MOTION_RESTITUTION: 17;
        SLIDER_JOINT_ANGULAR_MOTION_DAMPING: 18;
        SLIDER_JOINT_ANGULAR_ORTHOGONAL_SOFTNESS: 19;
        SLIDER_JOINT_ANGULAR_ORTHOGONAL_RESTITUTION: 20;
        SLIDER_JOINT_ANGULAR_ORTHOGONAL_DAMPING: 21;
        SLIDER_JOINT_MAX: 22;
    };
    public static readonly ConeTwistJointParam: {
        CONE_TWIST_JOINT_SWING_SPAN: 0;
        CONE_TWIST_JOINT_TWIST_SPAN: 1;
        CONE_TWIST_JOINT_BIAS: 2;
        CONE_TWIST_JOINT_SOFTNESS: 3;
        CONE_TWIST_JOINT_RELAXATION: 4;
    };
    public static readonly G6DOFJointAxisParam: {
        G6DOF_JOINT_LINEAR_LOWER_LIMIT: 0;
        G6DOF_JOINT_LINEAR_UPPER_LIMIT: 1;
        G6DOF_JOINT_LINEAR_LIMIT_SOFTNESS: 2;
        G6DOF_JOINT_LINEAR_RESTITUTION: 3;
        G6DOF_JOINT_LINEAR_DAMPING: 4;
        G6DOF_JOINT_LINEAR_MOTOR_TARGET_VELOCITY: 5;
        G6DOF_JOINT_LINEAR_MOTOR_FORCE_LIMIT: 6;
        G6DOF_JOINT_LINEAR_SPRING_STIFFNESS: 7;
        G6DOF_JOINT_LINEAR_SPRING_DAMPING: 8;
        G6DOF_JOINT_LINEAR_SPRING_EQUILIBRIUM_POINT: 9;
        G6DOF_JOINT_ANGULAR_LOWER_LIMIT: 10;
        G6DOF_JOINT_ANGULAR_UPPER_LIMIT: 11;
        G6DOF_JOINT_ANGULAR_LIMIT_SOFTNESS: 12;
        G6DOF_JOINT_ANGULAR_DAMPING: 13;
        G6DOF_JOINT_ANGULAR_RESTITUTION: 14;
        G6DOF_JOINT_ANGULAR_FORCE_LIMIT: 15;
        G6DOF_JOINT_ANGULAR_ERP: 16;
        G6DOF_JOINT_ANGULAR_MOTOR_TARGET_VELOCITY: 17;
        G6DOF_JOINT_ANGULAR_MOTOR_FORCE_LIMIT: 18;
        G6DOF_JOINT_ANGULAR_SPRING_STIFFNESS: 19;
        G6DOF_JOINT_ANGULAR_SPRING_DAMPING: 20;
        G6DOF_JOINT_ANGULAR_SPRING_EQUILIBRIUM_POINT: 21;
        G6DOF_JOINT_MAX: 22;
    };
    public static readonly G6DOFJointAxisFlag: {
        G6DOF_JOINT_FLAG_ENABLE_LINEAR_LIMIT: 0;
        G6DOF_JOINT_FLAG_ENABLE_ANGULAR_LIMIT: 1;
        G6DOF_JOINT_FLAG_ENABLE_ANGULAR_SPRING: 2;
        G6DOF_JOINT_FLAG_ENABLE_LINEAR_SPRING: 3;
        G6DOF_JOINT_FLAG_ENABLE_MOTOR: 4;
        G6DOF_JOINT_FLAG_ENABLE_LINEAR_MOTOR: 5;
        G6DOF_JOINT_FLAG_MAX: 6;
    };
    public static readonly ShapeType: {
        SHAPE_WORLD_BOUNDARY: 0;
        SHAPE_SEPARATION_RAY: 1;
        SHAPE_SPHERE: 2;
        SHAPE_BOX: 3;
        SHAPE_CAPSULE: 4;
        SHAPE_CYLINDER: 5;
        SHAPE_CONVEX_POLYGON: 6;
        SHAPE_CONCAVE_POLYGON: 7;
        SHAPE_HEIGHTMAP: 8;
        SHAPE_SOFT_BODY: 9;
        SHAPE_CUSTOM: 10;
    };
    public static readonly AreaParameter: {
        AREA_PARAM_GRAVITY_OVERRIDE_MODE: 0;
        AREA_PARAM_GRAVITY: 1;
        AREA_PARAM_GRAVITY_VECTOR: 2;
        AREA_PARAM_GRAVITY_IS_POINT: 3;
        AREA_PARAM_GRAVITY_POINT_UNIT_DISTANCE: 4;
        AREA_PARAM_LINEAR_DAMP_OVERRIDE_MODE: 5;
        AREA_PARAM_LINEAR_DAMP: 6;
        AREA_PARAM_ANGULAR_DAMP_OVERRIDE_MODE: 7;
        AREA_PARAM_ANGULAR_DAMP: 8;
        AREA_PARAM_PRIORITY: 9;
        AREA_PARAM_WIND_FORCE_MAGNITUDE: 10;
        AREA_PARAM_WIND_SOURCE: 11;
        AREA_PARAM_WIND_DIRECTION: 12;
        AREA_PARAM_WIND_ATTENUATION_FACTOR: 13;
    };
    public static readonly AreaSpaceOverrideMode: {
        AREA_SPACE_OVERRIDE_DISABLED: 0;
        AREA_SPACE_OVERRIDE_COMBINE: 1;
        AREA_SPACE_OVERRIDE_COMBINE_REPLACE: 2;
        AREA_SPACE_OVERRIDE_REPLACE: 3;
        AREA_SPACE_OVERRIDE_REPLACE_COMBINE: 4;
    };
    public static readonly BodyMode: {
        BODY_MODE_STATIC: 0;
        BODY_MODE_KINEMATIC: 1;
        BODY_MODE_RIGID: 2;
        BODY_MODE_RIGID_LINEAR: 3;
    };
    public static readonly BodyParameter: {
        BODY_PARAM_BOUNCE: 0;
        BODY_PARAM_FRICTION: 1;
        BODY_PARAM_MASS: 2;
        BODY_PARAM_INERTIA: 3;
        BODY_PARAM_CENTER_OF_MASS: 4;
        BODY_PARAM_GRAVITY_SCALE: 5;
        BODY_PARAM_LINEAR_DAMP_MODE: 6;
        BODY_PARAM_ANGULAR_DAMP_MODE: 7;
        BODY_PARAM_LINEAR_DAMP: 8;
        BODY_PARAM_ANGULAR_DAMP: 9;
        BODY_PARAM_MAX: 10;
    };
    public static readonly BodyDampMode: {
        BODY_DAMP_MODE_COMBINE: 0;
        BODY_DAMP_MODE_REPLACE: 1;
    };
    public static readonly BodyState: {
        BODY_STATE_TRANSFORM: 0;
        BODY_STATE_LINEAR_VELOCITY: 1;
        BODY_STATE_ANGULAR_VELOCITY: 2;
        BODY_STATE_SLEEPING: 3;
        BODY_STATE_CAN_SLEEP: 4;
    };
    public static readonly AreaBodyStatus: {
        AREA_BODY_ADDED: 0;
        AREA_BODY_REMOVED: 1;
    };
    public static readonly ProcessInfo: {
        INFO_ACTIVE_OBJECTS: 0;
        INFO_COLLISION_PAIRS: 1;
        INFO_ISLAND_COUNT: 2;
    };
    public static readonly SpaceParameter: {
        SPACE_PARAM_CONTACT_RECYCLE_RADIUS: 0;
        SPACE_PARAM_CONTACT_MAX_SEPARATION: 1;
        SPACE_PARAM_CONTACT_MAX_ALLOWED_PENETRATION: 2;
        SPACE_PARAM_CONTACT_DEFAULT_BIAS: 3;
        SPACE_PARAM_BODY_LINEAR_VELOCITY_SLEEP_THRESHOLD: 4;
        SPACE_PARAM_BODY_ANGULAR_VELOCITY_SLEEP_THRESHOLD: 5;
        SPACE_PARAM_BODY_TIME_TO_SLEEP: 6;
        SPACE_PARAM_SOLVER_ITERATIONS: 7;
    };
    public static readonly BodyAxis: {
        BODY_AXIS_LINEAR_X: 1;
        BODY_AXIS_LINEAR_Y: 2;
        BODY_AXIS_LINEAR_Z: 4;
        BODY_AXIS_ANGULAR_X: 8;
        BODY_AXIS_ANGULAR_Y: 16;
        BODY_AXIS_ANGULAR_Z: 32;
    };
}


/**
 * A singleton instance of PhysicsServer3D.
 * This is a global variable, available from anywhere.
 */
export const PhysicsServer3D: PhysicsServer3D;
