
import { RefCounted } from "@godot/classes/ref_counted";
import { Resource } from "@godot/classes/resource";
export declare class PhysicsShapeQueryParameters3D extends RefCounted{
  public set_shape(_shape: Resource): void;
  public get_shape(): Resource;
  public set_shape_rid(_shape: RID): void;
  public get_shape_rid(): RID;
  public set_transform(_transform: Transform3D): void;
  public get_transform(): Transform3D;
  public set_motion(_motion: Vector3): void;
  public get_motion(): Vector3;
  public set_margin(_margin: number): void;
  public get_margin(): number;
  public set_collision_mask(_collision_mask: number): void;
  public get_collision_mask(): number;
  public set_exclude(_exclude: GDArray): void;
  public get_exclude(): GDArray;
  public set_collide_with_bodies(_enable: boolean): void;
  public is_collide_with_bodies_enabled(): boolean;
  public set_collide_with_areas(_enable: boolean): void;
  public is_collide_with_areas_enabled(): boolean;
  public get collision_mask(): number;
  public set collision_mask(value): void;
  public get exclude(): GDArray;
  public set exclude(value): void;
  public get margin(): number;
  public set margin(value): void;
  public get motion(): Vector3;
  public set motion(value): void;
  public get shape(): Shape3D;
  public set shape(value): void;
  public get shape_rid(): RID;
  public set shape_rid(value): void;
  public get transform(): Transform3D;
  public set transform(value): void;
  public get collide_with_bodies(): boolean;
  public set collide_with_bodies(value): void;
  public get collide_with_areas(): boolean;
  public set collide_with_areas(value): void;
}