
import { Node2D } from "@godot/classes/node2d";
import { Texture2D } from "@godot/classes/texture2d";
export declare class Polygon2D extends Node2D{
  public set_polygon(_polygon: PackedVector2Array): void;
  public get_polygon(): PackedVector2Array;
  public set_uv(_uv: PackedVector2Array): void;
  public get_uv(): PackedVector2Array;
  public set_color(_color: Color): void;
  public get_color(): Color;
  public set_polygons(_polygons: GDArray): void;
  public get_polygons(): GDArray;
  public set_vertex_colors(_vertex_colors: PackedColorArray): void;
  public get_vertex_colors(): PackedColorArray;
  public set_texture(_texture: Texture2D): void;
  public get_texture(): Texture2D;
  public set_texture_offset(_texture_offset: Vector2): void;
  public get_texture_offset(): Vector2;
  public set_texture_rotation(_texture_rotation: number): void;
  public get_texture_rotation(): number;
  public set_texture_scale(_texture_scale: Vector2): void;
  public get_texture_scale(): Vector2;
  public set_invert_enabled(_invert: boolean): void;
  public get_invert_enabled(): boolean;
  public set_antialiased(_antialiased: boolean): void;
  public get_antialiased(): boolean;
  public set_invert_border(_invert_border: number): void;
  public get_invert_border(): number;
  public set_offset(_offset: Vector2): void;
  public get_offset(): Vector2;
  public add_bone(_path: GDString | NodePath | string, _weights: PackedFloat32Array): void;
  public get_bone_count(): number;
  public get_bone_path(_index: number): NodePath;
  public get_bone_weights(_index: number): PackedFloat32Array;
  public erase_bone(_index: number): void;
  public clear_bones(): void;
  public set_bone_path(_index: number, _path: GDString | NodePath | string): void;
  public set_bone_weights(_index: number, _weights: PackedFloat32Array): void;
  public set_skeleton(_skeleton: GDString | NodePath | string): void;
  public get_skeleton(): NodePath;
  public set_internal_vertex_count(_internal_vertex_count: number): void;
  public get_internal_vertex_count(): number;
  public get color(): Color;
  public set color(value): void;
  public get offset(): Vector2;
  public set offset(value): void;
  public get antialiased(): boolean;
  public set antialiased(value): void;
  public get texture(): Texture2D;
  public set texture(value): void;
  public get texture_offset(): Vector2;
  public set texture_offset(value): void;
  public get texture_scale(): Vector2;
  public set texture_scale(value): void;
  public get texture_rotation(): number;
  public set texture_rotation(value): void;
  public get skeleton(): NodePath;
  public set skeleton(value): void;
  public get invert_enabled(): boolean;
  public set invert_enabled(value): void;
  public get invert_border(): number;
  public set invert_border(value): void;
  public get polygon(): PackedVector2Array;
  public set polygon(value): void;
  public get uv(): PackedVector2Array;
  public set uv(value): void;
  public get vertex_colors(): PackedColorArray;
  public set vertex_colors(value): void;
  public get polygons(): GDArray;
  public set polygons(value): void;
  public get bones(): GDArray;
  public set bones(value): void;
  public get internal_vertex_count(): number;
  public set internal_vertex_count(value): void;
}