
import { RefCounted } from "@godot/classes/ref_counted";
export declare class RDPipelineDepthStencilState extends RefCounted{
  public set_enable_depth_test(_p_member: boolean): void;
  public get_enable_depth_test(): boolean;
  public set_enable_depth_write(_p_member: boolean): void;
  public get_enable_depth_write(): boolean;
  public set_depth_compare_operator(_p_member: number): void;
  public get_depth_compare_operator(): number;
  public set_enable_depth_range(_p_member: boolean): void;
  public get_enable_depth_range(): boolean;
  public set_depth_range_min(_p_member: number): void;
  public get_depth_range_min(): number;
  public set_depth_range_max(_p_member: number): void;
  public get_depth_range_max(): number;
  public set_enable_stencil(_p_member: boolean): void;
  public get_enable_stencil(): boolean;
  public set_front_op_fail(_p_member: number): void;
  public get_front_op_fail(): number;
  public set_front_op_pass(_p_member: number): void;
  public get_front_op_pass(): number;
  public set_front_op_depth_fail(_p_member: number): void;
  public get_front_op_depth_fail(): number;
  public set_front_op_compare(_p_member: number): void;
  public get_front_op_compare(): number;
  public set_front_op_compare_mask(_p_member: number): void;
  public get_front_op_compare_mask(): number;
  public set_front_op_write_mask(_p_member: number): void;
  public get_front_op_write_mask(): number;
  public set_front_op_reference(_p_member: number): void;
  public get_front_op_reference(): number;
  public set_back_op_fail(_p_member: number): void;
  public get_back_op_fail(): number;
  public set_back_op_pass(_p_member: number): void;
  public get_back_op_pass(): number;
  public set_back_op_depth_fail(_p_member: number): void;
  public get_back_op_depth_fail(): number;
  public set_back_op_compare(_p_member: number): void;
  public get_back_op_compare(): number;
  public set_back_op_compare_mask(_p_member: number): void;
  public get_back_op_compare_mask(): number;
  public set_back_op_write_mask(_p_member: number): void;
  public get_back_op_write_mask(): number;
  public set_back_op_reference(_p_member: number): void;
  public get_back_op_reference(): number;
  public get enable_depth_test(): boolean;
  public set enable_depth_test(value): void;
  public get enable_depth_write(): boolean;
  public set enable_depth_write(value): void;
  public get depth_compare_operator(): number;
  public set depth_compare_operator(value): void;
  public get enable_depth_range(): boolean;
  public set enable_depth_range(value): void;
  public get depth_range_min(): number;
  public set depth_range_min(value): void;
  public get depth_range_max(): number;
  public set depth_range_max(value): void;
  public get enable_stencil(): boolean;
  public set enable_stencil(value): void;
  public get front_op_fail(): number;
  public set front_op_fail(value): void;
  public get front_op_pass(): number;
  public set front_op_pass(value): void;
  public get front_op_depth_fail(): number;
  public set front_op_depth_fail(value): void;
  public get front_op_compare(): number;
  public set front_op_compare(value): void;
  public get front_op_compare_mask(): number;
  public set front_op_compare_mask(value): void;
  public get front_op_write_mask(): number;
  public set front_op_write_mask(value): void;
  public get front_op_reference(): number;
  public set front_op_reference(value): void;
  public get back_op_fail(): number;
  public set back_op_fail(value): void;
  public get back_op_pass(): number;
  public set back_op_pass(value): void;
  public get back_op_depth_fail(): number;
  public set back_op_depth_fail(value): void;
  public get back_op_compare(): number;
  public set back_op_compare(value): void;
  public get back_op_compare_mask(): number;
  public set back_op_compare_mask(value): void;
  public get back_op_write_mask(): number;
  public set back_op_write_mask(value): void;
  public get back_op_reference(): number;
  public set back_op_reference(value): void;
}