
import { RefCounted } from "@godot/classes/ref_counted";
export declare class RDPipelineRasterizationState extends RefCounted{
  public set_enable_depth_clamp(_p_member: boolean): void;
  public get_enable_depth_clamp(): boolean;
  public set_discard_primitives(_p_member: boolean): void;
  public get_discard_primitives(): boolean;
  public set_wireframe(_p_member: boolean): void;
  public get_wireframe(): boolean;
  public set_cull_mode(_p_member: number): void;
  public get_cull_mode(): number;
  public set_front_face(_p_member: number): void;
  public get_front_face(): number;
  public set_depth_bias_enabled(_p_member: boolean): void;
  public get_depth_bias_enabled(): boolean;
  public set_depth_bias_constant_factor(_p_member: number): void;
  public get_depth_bias_constant_factor(): number;
  public set_depth_bias_clamp(_p_member: number): void;
  public get_depth_bias_clamp(): number;
  public set_depth_bias_slope_factor(_p_member: number): void;
  public get_depth_bias_slope_factor(): number;
  public set_line_width(_p_member: number): void;
  public get_line_width(): number;
  public set_patch_control_points(_p_member: number): void;
  public get_patch_control_points(): number;
  public get enable_depth_clamp(): boolean;
  public set enable_depth_clamp(value): void;
  public get discard_primitives(): boolean;
  public set discard_primitives(value): void;
  public get wireframe(): boolean;
  public set wireframe(value): void;
  public get cull_mode(): number;
  public set cull_mode(value): void;
  public get front_face(): number;
  public set front_face(value): void;
  public get depth_bias_enabled(): boolean;
  public set depth_bias_enabled(value): void;
  public get depth_bias_constant_factor(): number;
  public set depth_bias_constant_factor(value): void;
  public get depth_bias_clamp(): number;
  public set depth_bias_clamp(value): void;
  public get depth_bias_slope_factor(): number;
  public set depth_bias_slope_factor(value): void;
  public get line_width(): number;
  public set line_width(value): void;
  public get patch_control_points(): number;
  public set patch_control_points(value): void;
}