
import type { AABB } from '@godot/builtins/aabb';
import type { Basis } from '@godot/builtins/basis';
import type { Callable } from '@godot/builtins/callable';
import type { Color } from '@godot/builtins/color';
import type { Dictionary } from '@godot/builtins/dictionary';
import type { GDArray } from '@godot/builtins/gd_array';
import type { GDString } from '@godot/builtins/gd_string';
import type { GodotObject } from '@godot/classes/godot_object';
import type { Image } from '@godot/classes/image';
import type { PackedByteArray } from '@godot/builtins/packed_byte_array';
import type { PackedColorArray } from '@godot/builtins/packed_color_array';
import type { PackedFloat32Array } from '@godot/builtins/packed_float32_array';
import type { PackedInt32Array } from '@godot/builtins/packed_int32_array';
import type { PackedInt64Array } from '@godot/builtins/packed_int64_array';
import type { PackedVector2Array } from '@godot/builtins/packed_vector2_array';
import type { PackedVector3Array } from '@godot/builtins/packed_vector3_array';
import type { RID } from '@godot/builtins/rid';
import type { Rect2 } from '@godot/builtins/rect2';
import type { RenderingDevice } from '@godot/classes/rendering_device';
import type { Signal } from '@godot/builtins/signal';
import type { StringName } from '@godot/builtins/string_name';
import type { Transform2D } from '@godot/builtins/transform2d';
import type { Transform3D } from '@godot/builtins/transform3d';
import type { Vector2 } from '@godot/builtins/vector2';
import type { Vector2i } from '@godot/builtins/vector2i';
import type { Vector3 } from '@godot/builtins/vector3';
import type { Vector3i } from '@godot/builtins/vector3i';


export declare class RenderingServer extends GodotObject {

    
    /**     * The raw type is 'bool'     */
    public render_loop_enabled: boolean;
    public texture_2d_create(image: Image): RID;
    public texture_2d_layered_create(layers: Array<any>, layeredType: number): RID;
    public texture_3d_create(format: number, width: number, height: number, depth: number, mipmaps: boolean, data: Array<any>): RID;
    public texture_proxy_create(base: RID): RID;
    public texture_create_from_native_handle(_type: number, format: number, nativeHandle: number, width: number, height: number, depth: number, layers: number = 1, layeredType: number = 0): RID;
    public texture_2d_update(texture: RID, image: Image, layer: number): void;
    public texture_3d_update(texture: RID, data: Array<any>): void;
    public texture_proxy_update(texture: RID, proxyTo: RID): void;
    public texture_2d_placeholder_create(): RID;
    public texture_2d_layered_placeholder_create(layeredType: number): RID;
    public texture_3d_placeholder_create(): RID;
    public texture_2d_get(texture: RID): Image;
    public texture_2d_layer_get(texture: RID, layer: number): Image;
    public texture_3d_get(texture: RID): Array<any>;
    public texture_replace(texture: RID, byTexture: RID): void;
    public texture_set_size_override(texture: RID, width: number, height: number): void;
    public texture_set_path(texture: RID, path: GDString | StringName | string): void;
    public texture_get_path(texture: RID): GDString;
    public texture_get_format(texture: RID): number;
    public texture_set_force_redraw_if_visible(texture: RID, enable: boolean): void;
    public texture_rd_create(rdTexture: RID, layerType: number = 0): RID;
    public texture_get_rd_texture(texture: RID, srgb: boolean = false): RID;
    public texture_get_native_handle(texture: RID, srgb: boolean = false): number;
    public shader_create(): RID;
    public shader_set_code(shader: RID, code: GDString | StringName | string): void;
    public shader_set_path_hint(shader: RID, path: GDString | StringName | string): void;
    public shader_get_code(shader: RID): GDString;
    public get_shader_parameter_list(shader: RID): Array<any>;
    public shader_get_parameter_default(shader: RID, name: GDString | StringName | string): any;
    public shader_set_default_texture_parameter(shader: RID, name: GDString | StringName | string, texture: RID, index: number = 0): void;
    public shader_get_default_texture_parameter(shader: RID, name: GDString | StringName | string, index: number = 0): RID;
    public material_create(): RID;
    public material_set_shader(shaderMaterial: RID, shader: RID): void;
    public material_set_param(material: RID, parameter: GDString | StringName | string, value: any): void;
    public material_get_param(material: RID, parameter: GDString | StringName | string): any;
    public material_set_render_priority(material: RID, priority: number): void;
    public material_set_next_pass(material: RID, nextMaterial: RID): void;
    public mesh_create_from_surfaces(surfaces: Array<any>, blendShapeCount: number = 0): RID;
    public mesh_create(): RID;
    public mesh_surface_get_format_offset(format: number, vertexCount: number, arrayIndex: number): number;
    public mesh_surface_get_format_vertex_stride(format: number, vertexCount: number): number;
    public mesh_surface_get_format_normal_tangent_stride(format: number, vertexCount: number): number;
    public mesh_surface_get_format_attribute_stride(format: number, vertexCount: number): number;
    public mesh_surface_get_format_skin_stride(format: number, vertexCount: number): number;
    public mesh_surface_get_format_index_stride(format: number, vertexCount: number): number;
    public mesh_add_surface(mesh: RID, surface: Dictionary): void;
    public mesh_add_surface_from_arrays(mesh: RID, primitive: number, arrays: GDArray, blendShapes: GDArray = [], lods: Dictionary = {}, compressFormat: number = 0): void;
    public mesh_get_blend_shape_count(mesh: RID): number;
    public mesh_set_blend_shape_mode(mesh: RID, mode: number): void;
    public mesh_get_blend_shape_mode(mesh: RID): number;
    public mesh_surface_set_material(mesh: RID, surface: number, material: RID): void;
    public mesh_surface_get_material(mesh: RID, surface: number): RID;
    public mesh_get_surface(mesh: RID, surface: number): Dictionary;
    public mesh_surface_get_arrays(mesh: RID, surface: number): GDArray;
    public mesh_surface_get_blend_shape_arrays(mesh: RID, surface: number): Array<any>;
    public mesh_get_surface_count(mesh: RID): number;
    public mesh_set_custom_aabb(mesh: RID, aabb: AABB): void;
    public mesh_get_custom_aabb(mesh: RID): AABB;
    public mesh_surface_remove(mesh: RID, surface: number): void;
    public mesh_clear(mesh: RID): void;
    public mesh_surface_update_vertex_region(mesh: RID, surface: number, offset: number, data: PackedByteArray): void;
    public mesh_surface_update_attribute_region(mesh: RID, surface: number, offset: number, data: PackedByteArray): void;
    public mesh_surface_update_skin_region(mesh: RID, surface: number, offset: number, data: PackedByteArray): void;
    public mesh_surface_update_index_region(mesh: RID, surface: number, offset: number, data: PackedByteArray): void;
    public mesh_set_shadow_mesh(mesh: RID, shadowMesh: RID): void;
    public multimesh_create(): RID;
    public multimesh_allocate_data(multimesh: RID, instances: number, transformFormat: number, colorFormat: boolean = false, customDataFormat: boolean = false, useIndirect: boolean = false): void;
    public multimesh_get_instance_count(multimesh: RID): number;
    public multimesh_set_mesh(multimesh: RID, mesh: RID): void;
    public multimesh_instance_set_transform(multimesh: RID, index: number, transform: Transform3D): void;
    public multimesh_instance_set_transform_2d(multimesh: RID, index: number, transform: Transform2D): void;
    public multimesh_instance_set_color(multimesh: RID, index: number, color: Color): void;
    public multimesh_instance_set_custom_data(multimesh: RID, index: number, customData: Color): void;
    public multimesh_get_mesh(multimesh: RID): RID;
    public multimesh_get_aabb(multimesh: RID): AABB;
    public multimesh_set_custom_aabb(multimesh: RID, aabb: AABB): void;
    public multimesh_get_custom_aabb(multimesh: RID): AABB;
    public multimesh_instance_get_transform(multimesh: RID, index: number): Transform3D;
    public multimesh_instance_get_transform_2d(multimesh: RID, index: number): Transform2D;
    public multimesh_instance_get_color(multimesh: RID, index: number): Color;
    public multimesh_instance_get_custom_data(multimesh: RID, index: number): Color;
    public multimesh_set_visible_instances(multimesh: RID, visible: number): void;
    public multimesh_get_visible_instances(multimesh: RID): number;
    public multimesh_set_buffer(multimesh: RID, buffer: PackedFloat32Array): void;
    public multimesh_get_command_buffer_rd_rid(multimesh: RID): RID;
    public multimesh_get_buffer_rd_rid(multimesh: RID): RID;
    public multimesh_get_buffer(multimesh: RID): PackedFloat32Array;
    public multimesh_set_buffer_interpolated(multimesh: RID, buffer: PackedFloat32Array, bufferPrevious: PackedFloat32Array): void;
    public multimesh_set_physics_interpolated(multimesh: RID, interpolated: boolean): void;
    public multimesh_set_physics_interpolation_quality(multimesh: RID, quality: number): void;
    public multimesh_instance_reset_physics_interpolation(multimesh: RID, index: number): void;
    public skeleton_create(): RID;
    public skeleton_allocate_data(skeleton: RID, bones: number, is2DSkeleton: boolean = false): void;
    public skeleton_get_bone_count(skeleton: RID): number;
    public skeleton_bone_set_transform(skeleton: RID, bone: number, transform: Transform3D): void;
    public skeleton_bone_get_transform(skeleton: RID, bone: number): Transform3D;
    public skeleton_bone_set_transform_2d(skeleton: RID, bone: number, transform: Transform2D): void;
    public skeleton_bone_get_transform_2d(skeleton: RID, bone: number): Transform2D;
    public skeleton_set_base_transform_2d(skeleton: RID, baseTransform: Transform2D): void;
    public directional_light_create(): RID;
    public omni_light_create(): RID;
    public spot_light_create(): RID;
    public light_set_color(light: RID, color: Color): void;
    public light_set_param(light: RID, param: number, value: number): void;
    public light_set_shadow(light: RID, enabled: boolean): void;
    public light_set_projector(light: RID, texture: RID): void;
    public light_set_negative(light: RID, enable: boolean): void;
    public light_set_cull_mask(light: RID, mask: number): void;
    public light_set_distance_fade(decal: RID, enabled: boolean, begin: number, shadow: number, length: number): void;
    public light_set_reverse_cull_face_mode(light: RID, enabled: boolean): void;
    public light_set_shadow_caster_mask(light: RID, mask: number): void;
    public light_set_bake_mode(light: RID, bakeMode: number): void;
    public light_set_max_sdfgi_cascade(light: RID, cascade: number): void;
    public light_omni_set_shadow_mode(light: RID, mode: number): void;
    public light_directional_set_shadow_mode(light: RID, mode: number): void;
    public light_directional_set_blend_splits(light: RID, enable: boolean): void;
    public light_directional_set_sky_mode(light: RID, mode: number): void;
    public light_projectors_set_filter(filter: number): void;
    public lightmaps_set_bicubic_filter(enable: boolean): void;
    public positional_soft_shadow_filter_set_quality(quality: number): void;
    public directional_soft_shadow_filter_set_quality(quality: number): void;
    public directional_shadow_atlas_set_size(size: number, is16Bits: boolean): void;
    public reflection_probe_create(): RID;
    public reflection_probe_set_update_mode(probe: RID, mode: number): void;
    public reflection_probe_set_intensity(probe: RID, intensity: number): void;
    public reflection_probe_set_blend_distance(probe: RID, blendDistance: number): void;
    public reflection_probe_set_ambient_mode(probe: RID, mode: number): void;
    public reflection_probe_set_ambient_color(probe: RID, color: Color): void;
    public reflection_probe_set_ambient_energy(probe: RID, energy: number): void;
    public reflection_probe_set_max_distance(probe: RID, distance: number): void;
    public reflection_probe_set_size(probe: RID, size: Vector3): void;
    public reflection_probe_set_origin_offset(probe: RID, offset: Vector3): void;
    public reflection_probe_set_as_interior(probe: RID, enable: boolean): void;
    public reflection_probe_set_enable_box_projection(probe: RID, enable: boolean): void;
    public reflection_probe_set_enable_shadows(probe: RID, enable: boolean): void;
    public reflection_probe_set_cull_mask(probe: RID, layers: number): void;
    public reflection_probe_set_reflection_mask(probe: RID, layers: number): void;
    public reflection_probe_set_resolution(probe: RID, resolution: number): void;
    public reflection_probe_set_mesh_lod_threshold(probe: RID, pixels: number): void;
    public decal_create(): RID;
    public decal_set_size(decal: RID, size: Vector3): void;
    public decal_set_texture(decal: RID, _type: number, texture: RID): void;
    public decal_set_emission_energy(decal: RID, energy: number): void;
    public decal_set_albedo_mix(decal: RID, albedoMix: number): void;
    public decal_set_modulate(decal: RID, color: Color): void;
    public decal_set_cull_mask(decal: RID, mask: number): void;
    public decal_set_distance_fade(decal: RID, enabled: boolean, begin: number, length: number): void;
    public decal_set_fade(decal: RID, above: number, below: number): void;
    public decal_set_normal_fade(decal: RID, fade: number): void;
    public decals_set_filter(filter: number): void;
    public gi_set_use_half_resolution(halfResolution: boolean): void;
    public voxel_gi_create(): RID;
    public voxel_gi_allocate_data(voxelGi: RID, toCellXform: Transform3D, aabb: AABB, octreeSize: Vector3i, octreeCells: PackedByteArray, dataCells: PackedByteArray, distanceField: PackedByteArray, levelCounts: PackedInt32Array): void;
    public voxel_gi_get_octree_size(voxelGi: RID): Vector3i;
    public voxel_gi_get_octree_cells(voxelGi: RID): PackedByteArray;
    public voxel_gi_get_data_cells(voxelGi: RID): PackedByteArray;
    public voxel_gi_get_distance_field(voxelGi: RID): PackedByteArray;
    public voxel_gi_get_level_counts(voxelGi: RID): PackedInt32Array;
    public voxel_gi_get_to_cell_xform(voxelGi: RID): Transform3D;
    public voxel_gi_set_dynamic_range(voxelGi: RID, range: number): void;
    public voxel_gi_set_propagation(voxelGi: RID, amount: number): void;
    public voxel_gi_set_energy(voxelGi: RID, energy: number): void;
    public voxel_gi_set_baked_exposure_normalization(voxelGi: RID, bakedExposure: number): void;
    public voxel_gi_set_bias(voxelGi: RID, bias: number): void;
    public voxel_gi_set_normal_bias(voxelGi: RID, bias: number): void;
    public voxel_gi_set_interior(voxelGi: RID, enable: boolean): void;
    public voxel_gi_set_use_two_bounces(voxelGi: RID, enable: boolean): void;
    public voxel_gi_set_quality(quality: number): void;
    public lightmap_create(): RID;
    public lightmap_set_textures(lightmap: RID, light: RID, usesSh: boolean): void;
    public lightmap_set_probe_bounds(lightmap: RID, bounds: AABB): void;
    public lightmap_set_probe_interior(lightmap: RID, interior: boolean): void;
    public lightmap_set_probe_capture_data(lightmap: RID, points: PackedVector3Array, pointSh: PackedColorArray, tetrahedra: PackedInt32Array, bstree: PackedInt32Array): void;
    public lightmap_get_probe_capture_points(lightmap: RID): PackedVector3Array;
    public lightmap_get_probe_capture_sh(lightmap: RID): PackedColorArray;
    public lightmap_get_probe_capture_tetrahedra(lightmap: RID): PackedInt32Array;
    public lightmap_get_probe_capture_bsp_tree(lightmap: RID): PackedInt32Array;
    public lightmap_set_baked_exposure_normalization(lightmap: RID, bakedExposure: number): void;
    public lightmap_set_probe_capture_update_speed(speed: number): void;
    public particles_create(): RID;
    public particles_set_mode(particles: RID, mode: number): void;
    public particles_set_emitting(particles: RID, emitting: boolean): void;
    public particles_get_emitting(particles: RID): boolean;
    public particles_set_amount(particles: RID, amount: number): void;
    public particles_set_amount_ratio(particles: RID, ratio: number): void;
    public particles_set_lifetime(particles: RID, lifetime: number): void;
    public particles_set_one_shot(particles: RID, oneShot: boolean): void;
    public particles_set_pre_process_time(particles: RID, time: number): void;
    public particles_request_process_time(particles: RID, time: number): void;
    public particles_set_explosiveness_ratio(particles: RID, ratio: number): void;
    public particles_set_randomness_ratio(particles: RID, ratio: number): void;
    public particles_set_interp_to_end(particles: RID, factor: number): void;
    public particles_set_emitter_velocity(particles: RID, velocity: Vector3): void;
    public particles_set_custom_aabb(particles: RID, aabb: AABB): void;
    public particles_set_speed_scale(particles: RID, scale: number): void;
    public particles_set_use_local_coordinates(particles: RID, enable: boolean): void;
    public particles_set_process_material(particles: RID, material: RID): void;
    public particles_set_fixed_fps(particles: RID, fps: number): void;
    public particles_set_interpolate(particles: RID, enable: boolean): void;
    public particles_set_fractional_delta(particles: RID, enable: boolean): void;
    public particles_set_collision_base_size(particles: RID, size: number): void;
    public particles_set_transform_align(particles: RID, align: number): void;
    public particles_set_trails(particles: RID, enable: boolean, lengthSec: number): void;
    public particles_set_trail_bind_poses(particles: RID, bindPoses: Array<any>): void;
    public particles_is_inactive(particles: RID): boolean;
    public particles_request_process(particles: RID): void;
    public particles_restart(particles: RID): void;
    public particles_set_subemitter(particles: RID, subemitterParticles: RID): void;
    public particles_emit(particles: RID, transform: Transform3D, velocity: Vector3, color: Color, custom: Color, emitFlags: number): void;
    public particles_set_draw_order(particles: RID, order: number): void;
    public particles_set_draw_passes(particles: RID, count: number): void;
    public particles_set_draw_pass_mesh(particles: RID, pass: number, mesh: RID): void;
    public particles_get_current_aabb(particles: RID): AABB;
    public particles_set_emission_transform(particles: RID, transform: Transform3D): void;
    public particles_collision_create(): RID;
    public particles_collision_set_collision_type(particlesCollision: RID, _type: number): void;
    public particles_collision_set_cull_mask(particlesCollision: RID, mask: number): void;
    public particles_collision_set_sphere_radius(particlesCollision: RID, radius: number): void;
    public particles_collision_set_box_extents(particlesCollision: RID, extents: Vector3): void;
    public particles_collision_set_attractor_strength(particlesCollision: RID, strength: number): void;
    public particles_collision_set_attractor_directionality(particlesCollision: RID, amount: number): void;
    public particles_collision_set_attractor_attenuation(particlesCollision: RID, curve: number): void;
    public particles_collision_set_field_texture(particlesCollision: RID, texture: RID): void;
    public particles_collision_height_field_update(particlesCollision: RID): void;
    public particles_collision_set_height_field_resolution(particlesCollision: RID, resolution: number): void;
    public particles_collision_set_height_field_mask(particlesCollision: RID, mask: number): void;
    public fog_volume_create(): RID;
    public fog_volume_set_shape(fogVolume: RID, shape: number): void;
    public fog_volume_set_size(fogVolume: RID, size: Vector3): void;
    public fog_volume_set_material(fogVolume: RID, material: RID): void;
    public visibility_notifier_create(): RID;
    public visibility_notifier_set_aabb(notifier: RID, aabb: AABB): void;
    public visibility_notifier_set_callbacks(notifier: RID, enterCallable: Callable, exitCallable: Callable): void;
    public occluder_create(): RID;
    public occluder_set_mesh(occluder: RID, vertices: PackedVector3Array, indices: PackedInt32Array): void;
    public camera_create(): RID;
    public camera_set_perspective(camera: RID, fovyDegrees: number, zNear: number, zFar: number): void;
    public camera_set_orthogonal(camera: RID, size: number, zNear: number, zFar: number): void;
    public camera_set_frustum(camera: RID, size: number, offset: Vector2, zNear: number, zFar: number): void;
    public camera_set_transform(camera: RID, transform: Transform3D): void;
    public camera_set_cull_mask(camera: RID, layers: number): void;
    public camera_set_environment(camera: RID, env: RID): void;
    public camera_set_camera_attributes(camera: RID, effects: RID): void;
    public camera_set_compositor(camera: RID, compositor: RID): void;
    public camera_set_use_vertical_aspect(camera: RID, enable: boolean): void;
    public viewport_create(): RID;
    public viewport_set_use_xr(viewport: RID, useXr: boolean): void;
    public viewport_set_size(viewport: RID, width: number, height: number): void;
    public viewport_set_active(viewport: RID, active: boolean): void;
    public viewport_set_parent_viewport(viewport: RID, parentViewport: RID): void;
    public viewport_attach_to_screen(viewport: RID, rect: Rect2 = Rect2(0, 0, 0, 0), screen: number = 0): void;
    public viewport_set_render_direct_to_screen(viewport: RID, enabled: boolean): void;
    public viewport_set_canvas_cull_mask(viewport: RID, canvasCullMask: number): void;
    public viewport_set_scaling_3d_mode(viewport: RID, scaling3DMode: number): void;
    public viewport_set_scaling_3d_scale(viewport: RID, scale: number): void;
    public viewport_set_fsr_sharpness(viewport: RID, sharpness: number): void;
    public viewport_set_texture_mipmap_bias(viewport: RID, mipmabias: number): void;
    public viewport_set_anisotropic_filtering_level(viewport: RID, anisotropicFilteringLevel: number): void;
    public viewport_set_update_mode(viewport: RID, updateMode: number): void;
    public viewport_get_update_mode(viewport: RID): number;
    public viewport_set_clear_mode(viewport: RID, clearMode: number): void;
    public viewport_get_render_target(viewport: RID): RID;
    public viewport_get_texture(viewport: RID): RID;
    public viewport_set_disable_3d(viewport: RID, disable: boolean): void;
    public viewport_set_disable_2d(viewport: RID, disable: boolean): void;
    public viewport_set_environment_mode(viewport: RID, mode: number): void;
    public viewport_attach_camera(viewport: RID, camera: RID): void;
    public viewport_set_scenario(viewport: RID, scenario: RID): void;
    public viewport_attach_canvas(viewport: RID, canvas: RID): void;
    public viewport_remove_canvas(viewport: RID, canvas: RID): void;
    public viewport_set_snap_2d_transforms_to_pixel(viewport: RID, enabled: boolean): void;
    public viewport_set_snap_2d_vertices_to_pixel(viewport: RID, enabled: boolean): void;
    public viewport_set_default_canvas_item_texture_filter(viewport: RID, filter: number): void;
    public viewport_set_default_canvas_item_texture_repeat(viewport: RID, repeat: number): void;
    public viewport_set_canvas_transform(viewport: RID, canvas: RID, offset: Transform2D): void;
    public viewport_set_canvas_stacking(viewport: RID, canvas: RID, layer: number, sublayer: number): void;
    public viewport_set_transparent_background(viewport: RID, enabled: boolean): void;
    public viewport_set_global_canvas_transform(viewport: RID, transform: Transform2D): void;
    public viewport_set_sdf_oversize_and_scale(viewport: RID, oversize: number, scale: number): void;
    public viewport_set_positional_shadow_atlas_size(viewport: RID, size: number, use16Bits: boolean = false): void;
    public viewport_set_positional_shadow_atlas_quadrant_subdivision(viewport: RID, quadrant: number, subdivision: number): void;
    public viewport_set_msaa_3d(viewport: RID, msaa: number): void;
    public viewport_set_msaa_2d(viewport: RID, msaa: number): void;
    public viewport_set_use_hdr_2d(viewport: RID, enabled: boolean): void;
    public viewport_set_screen_space_aa(viewport: RID, mode: number): void;
    public viewport_set_use_taa(viewport: RID, enable: boolean): void;
    public viewport_set_use_debanding(viewport: RID, enable: boolean): void;
    public viewport_set_use_occlusion_culling(viewport: RID, enable: boolean): void;
    public viewport_set_occlusion_rays_per_thread(raysPerThread: number): void;
    public viewport_set_occlusion_culling_build_quality(quality: number): void;
    public viewport_get_render_info(viewport: RID, _type: number, info: number): number;
    public viewport_set_debug_draw(viewport: RID, draw: number): void;
    public viewport_set_measure_render_time(viewport: RID, enable: boolean): void;
    public viewport_get_measured_render_time_cpu(viewport: RID): number;
    public viewport_get_measured_render_time_gpu(viewport: RID): number;
    public viewport_set_vrs_mode(viewport: RID, mode: number): void;
    public viewport_set_vrs_update_mode(viewport: RID, mode: number): void;
    public viewport_set_vrs_texture(viewport: RID, texture: RID): void;
    public sky_create(): RID;
    public sky_set_radiance_size(sky: RID, radianceSize: number): void;
    public sky_set_mode(sky: RID, mode: number): void;
    public sky_set_material(sky: RID, material: RID): void;
    public sky_bake_panorama(sky: RID, energy: number, bakeIrradiance: boolean, size: Vector2i): Image;
    public compositor_effect_create(): RID;
    public compositor_effect_set_enabled(effect: RID, enabled: boolean): void;
    public compositor_effect_set_callback(effect: RID, callbackType: number, callback: Callable): void;
    public compositor_effect_set_flag(effect: RID, flag: number, _set: boolean): void;
    public compositor_create(): RID;
    public compositor_set_compositor_effects(compositor: RID, effects: Array<any>): void;
    public environment_create(): RID;
    public environment_set_background(env: RID, bg: number): void;
    public environment_set_camera_id(env: RID, id: number): void;
    public environment_set_sky(env: RID, sky: RID): void;
    public environment_set_sky_custom_fov(env: RID, scale: number): void;
    public environment_set_sky_orientation(env: RID, orientation: Basis): void;
    public environment_set_bg_color(env: RID, color: Color): void;
    public environment_set_bg_energy(env: RID, multiplier: number, exposureValue: number): void;
    public environment_set_canvas_max_layer(env: RID, maxLayer: number): void;
    public environment_set_ambient_light(env: RID, color: Color, ambient: number = 0, energy: number = 1.0, skyContribution: number = 0.0, reflectionSource: number = 0): void;
    public environment_set_glow(env: RID, enable: boolean, levels: PackedFloat32Array, intensity: number, strength: number, mix: number, bloomThreshold: number, blendMode: number, hdrBleedThreshold: number, hdrBleedScale: number, hdrLuminanceCap: number, glowMastrength: number, glowMap: RID): void;
    public environment_set_tonemap(env: RID, toneMapper: number, exposure: number, white: number): void;
    public environment_set_adjustment(env: RID, enable: boolean, brightness: number, contrast: number, saturation: number, use1DColorCorrection: boolean, colorCorrection: RID): void;
    public environment_set_ssr(env: RID, enable: boolean, maxSteps: number, fadeIn: number, fadeOut: number, depthTolerance: number): void;
    public environment_set_ssao(env: RID, enable: boolean, radius: number, intensity: number, power: number, detail: number, horizon: number, sharpness: number, lightAffect: number, aoChannelAffect: number): void;
    public environment_set_fog(env: RID, enable: boolean, lightColor: Color, lightEnergy: number, sunScatter: number, density: number, height: number, heightDensity: number, aerialPerspective: number, skyAffect: number, fogMode: number = 0): void;
    public environment_set_fog_depth(env: RID, curve: number, begin: number, end: number): void;
    public environment_set_sdfgi(env: RID, enable: boolean, cascades: number, minCellSize: number, yScale: number, useOcclusion: boolean, bounceFeedback: number, readSky: boolean, energy: number, normalBias: number, probeBias: number): void;
    public environment_set_volumetric_fog(env: RID, enable: boolean, density: number, albedo: Color, emission: Color, emissionEnergy: number, anisotropy: number, length: number, detailSpread: number, giInject: number, temporalReprojection: boolean, temporalReprojectionAmount: number, ambientInject: number, skyAffect: number): void;
    public environment_glow_set_use_bicubic_upscale(enable: boolean): void;
    public environment_set_ssr_roughness_quality(quality: number): void;
    public environment_set_ssao_quality(quality: number, halfSize: boolean, adaptiveTarget: number, blurPasses: number, fadeoutFrom: number, fadeoutTo: number): void;
    public environment_set_ssil_quality(quality: number, halfSize: boolean, adaptiveTarget: number, blurPasses: number, fadeoutFrom: number, fadeoutTo: number): void;
    public environment_set_sdfgi_ray_count(rayCount: number): void;
    public environment_set_sdfgi_frames_to_converge(frames: number): void;
    public environment_set_sdfgi_frames_to_update_light(frames: number): void;
    public environment_set_volumetric_fog_volume_size(size: number, depth: number): void;
    public environment_set_volumetric_fog_filter_active(active: boolean): void;
    public environment_bake_panorama(environment: RID, bakeIrradiance: boolean, size: Vector2i): Image;
    public screen_space_roughness_limiter_set_active(enable: boolean, amount: number, limit: number): void;
    public sub_surface_scattering_set_quality(quality: number): void;
    public sub_surface_scattering_set_scale(scale: number, depthScale: number): void;
    public camera_attributes_create(): RID;
    public camera_attributes_set_dof_blur_quality(quality: number, useJitter: boolean): void;
    public camera_attributes_set_dof_blur_bokeh_shape(shape: number): void;
    public camera_attributes_set_dof_blur(cameraAttributes: RID, farEnable: boolean, farDistance: number, farTransition: number, nearEnable: boolean, nearDistance: number, nearTransition: number, amount: number): void;
    public camera_attributes_set_exposure(cameraAttributes: RID, multiplier: number, normalization: number): void;
    public camera_attributes_set_auto_exposure(cameraAttributes: RID, enable: boolean, minSensitivity: number, maxSensitivity: number, speed: number, scale: number): void;
    public scenario_create(): RID;
    public scenario_set_environment(scenario: RID, environment: RID): void;
    public scenario_set_fallback_environment(scenario: RID, environment: RID): void;
    public scenario_set_camera_attributes(scenario: RID, effects: RID): void;
    public scenario_set_compositor(scenario: RID, compositor: RID): void;
    public instance_create2(base: RID, scenario: RID): RID;
    public instance_create(): RID;
    public instance_set_base(instance: RID, base: RID): void;
    public instance_set_scenario(instance: RID, scenario: RID): void;
    public instance_set_layer_mask(instance: RID, mask: number): void;
    public instance_set_pivot_data(instance: RID, sortingOffset: number, useAabbCenter: boolean): void;
    public instance_set_transform(instance: RID, transform: Transform3D): void;
    public instance_attach_object_instance_id(instance: RID, id: number): void;
    public instance_set_blend_shape_weight(instance: RID, shape: number, weight: number): void;
    public instance_set_surface_override_material(instance: RID, surface: number, material: RID): void;
    public instance_set_visible(instance: RID, visible: boolean): void;
    public instance_geometry_set_transparency(instance: RID, transparency: number): void;
    public instance_teleport(instance: RID): void;
    public instance_set_custom_aabb(instance: RID, aabb: AABB): void;
    public instance_attach_skeleton(instance: RID, skeleton: RID): void;
    public instance_set_extra_visibility_margin(instance: RID, margin: number): void;
    public instance_set_visibility_parent(instance: RID, parent: RID): void;
    public instance_set_ignore_culling(instance: RID, enabled: boolean): void;
    public instance_geometry_set_flag(instance: RID, flag: number, enabled: boolean): void;
    public instance_geometry_set_cast_shadows_setting(instance: RID, shadowCastingSetting: number): void;
    public instance_geometry_set_material_override(instance: RID, material: RID): void;
    public instance_geometry_set_material_overlay(instance: RID, material: RID): void;
    public instance_geometry_set_visibility_range(instance: RID, min: number, max: number, minMargin: number, maxMargin: number, fadeMode: number): void;
    public instance_geometry_set_lightmap(instance: RID, lightmap: RID, lightmauvScale: Rect2, lightmaslice: number): void;
    public instance_geometry_set_lod_bias(instance: RID, lodBias: number): void;
    public instance_geometry_set_shader_parameter(instance: RID, parameter: GDString | StringName | string, value: any): void;
    public instance_geometry_get_shader_parameter(instance: RID, parameter: GDString | StringName | string): any;
    public instance_geometry_get_shader_parameter_default_value(instance: RID, parameter: GDString | StringName | string): any;
    public instance_geometry_get_shader_parameter_list(instance: RID): Array<any>;
    public instances_cull_aabb(aabb: AABB, scenario: RID = RID()): PackedInt64Array;
    public instances_cull_ray(_from: Vector3, to: Vector3, scenario: RID = RID()): PackedInt64Array;
    public instances_cull_convex(convex: Array<any>, scenario: RID = RID()): PackedInt64Array;
    public bake_render_uv2(base: RID, materialOverrides: Array<any>, imageSize: Vector2i): Array<any>;
    public canvas_create(): RID;
    public canvas_set_item_mirroring(canvas: RID, item: RID, mirroring: Vector2): void;
    public canvas_set_item_repeat(item: RID, repeatSize: Vector2, repeatTimes: number): void;
    public canvas_set_modulate(canvas: RID, color: Color): void;
    public canvas_set_disable_scale(disable: boolean): void;
    public canvas_texture_create(): RID;
    public canvas_texture_set_channel(canvasTexture: RID, channel: number, texture: RID): void;
    public canvas_texture_set_shading_parameters(canvasTexture: RID, baseColor: Color, shininess: number): void;
    public canvas_texture_set_texture_filter(canvasTexture: RID, filter: number): void;
    public canvas_texture_set_texture_repeat(canvasTexture: RID, repeat: number): void;
    public canvas_item_create(): RID;
    public canvas_item_set_parent(item: RID, parent: RID): void;
    public canvas_item_set_default_texture_filter(item: RID, filter: number): void;
    public canvas_item_set_default_texture_repeat(item: RID, repeat: number): void;
    public canvas_item_set_visible(item: RID, visible: boolean): void;
    public canvas_item_set_light_mask(item: RID, mask: number): void;
    public canvas_item_set_visibility_layer(item: RID, visibilityLayer: number): void;
    public canvas_item_set_transform(item: RID, transform: Transform2D): void;
    public canvas_item_set_clip(item: RID, clip: boolean): void;
    public canvas_item_set_distance_field_mode(item: RID, enabled: boolean): void;
    public canvas_item_set_custom_rect(item: RID, useCustomRect: boolean, rect: Rect2 = Rect2(0, 0, 0, 0)): void;
    public canvas_item_set_modulate(item: RID, color: Color): void;
    public canvas_item_set_self_modulate(item: RID, color: Color): void;
    public canvas_item_set_draw_behind_parent(item: RID, enabled: boolean): void;
    public canvas_item_set_interpolated(item: RID, interpolated: boolean): void;
    public canvas_item_reset_physics_interpolation(item: RID): void;
    public canvas_item_transform_physics_interpolation(item: RID, transform: Transform2D): void;
    public canvas_item_add_line(item: RID, _from: Vector2, to: Vector2, color: Color, width: number = -1.0, antialiased: boolean = false): void;
    public canvas_item_add_polyline(item: RID, points: PackedVector2Array, colors: PackedColorArray, width: number = -1.0, antialiased: boolean = false): void;
    public canvas_item_add_multiline(item: RID, points: PackedVector2Array, colors: PackedColorArray, width: number = -1.0, antialiased: boolean = false): void;
    public canvas_item_add_rect(item: RID, rect: Rect2, color: Color, antialiased: boolean = false): void;
    public canvas_item_add_circle(item: RID, pos: Vector2, radius: number, color: Color, antialiased: boolean = false): void;
    public canvas_item_add_texture_rect(item: RID, rect: Rect2, texture: RID, tile: boolean = false, modulate: Color = Color(1, 1, 1, 1), transpose: boolean = false): void;
    public canvas_item_add_msdf_texture_rect_region(item: RID, rect: Rect2, texture: RID, srcRect: Rect2, modulate: Color = Color(1, 1, 1, 1), outlineSize: number = 0, pxRange: number = 1.0, scale: number = 1.0): void;
    public canvas_item_add_lcd_texture_rect_region(item: RID, rect: Rect2, texture: RID, srcRect: Rect2, modulate: Color): void;
    public canvas_item_add_texture_rect_region(item: RID, rect: Rect2, texture: RID, srcRect: Rect2, modulate: Color = Color(1, 1, 1, 1), transpose: boolean = false, cliuv: boolean = true): void;
    public canvas_item_add_nine_patch(item: RID, rect: Rect2, source: Rect2, texture: RID, topleft: Vector2, bottomright: Vector2, xAxisMode: number = 0, yAxisMode: number = 0, drawCenter: boolean = true, modulate: Color = Color(1, 1, 1, 1)): void;
    public canvas_item_add_primitive(item: RID, points: PackedVector2Array, colors: PackedColorArray, uvs: PackedVector2Array, texture: RID): void;
    public canvas_item_add_polygon(item: RID, points: PackedVector2Array, colors: PackedColorArray, uvs: PackedVector2Array = PackedVector2Array(), texture: RID = RID()): void;
    public canvas_item_add_triangle_array(item: RID, indices: PackedInt32Array, points: PackedVector2Array, colors: PackedColorArray, uvs: PackedVector2Array = PackedVector2Array(), bones: PackedInt32Array = PackedInt32Array(), weights: PackedFloat32Array = PackedFloat32Array(), texture: RID = RID(), count: number = -1): void;
    public canvas_item_add_mesh(item: RID, mesh: RID, transform: Transform2D = Transform2D(1, 0, 0, 1, 0, 0), modulate: Color = Color(1, 1, 1, 1), texture: RID = RID()): void;
    public canvas_item_add_multimesh(item: RID, mesh: RID, texture: RID = RID()): void;
    public canvas_item_add_particles(item: RID, particles: RID, texture: RID): void;
    public canvas_item_add_set_transform(item: RID, transform: Transform2D): void;
    public canvas_item_add_clip_ignore(item: RID, ignore: boolean): void;
    public canvas_item_add_animation_slice(item: RID, animationLength: number, sliceBegin: number, sliceEnd: number, offset: number = 0.0): void;
    public canvas_item_set_sort_children_by_y(item: RID, enabled: boolean): void;
    public canvas_item_set_z_index(item: RID, zIndex: number): void;
    public canvas_item_set_z_as_relative_to_parent(item: RID, enabled: boolean): void;
    public canvas_item_set_copy_to_backbuffer(item: RID, enabled: boolean, rect: Rect2): void;
    public canvas_item_attach_skeleton(item: RID, skeleton: RID): void;
    public canvas_item_clear(item: RID): void;
    public canvas_item_set_draw_index(item: RID, index: number): void;
    public canvas_item_set_material(item: RID, material: RID): void;
    public canvas_item_set_use_parent_material(item: RID, enabled: boolean): void;
    public canvas_item_set_instance_shader_parameter(instance: RID, parameter: GDString | StringName | string, value: any): void;
    public canvas_item_get_instance_shader_parameter(instance: RID, parameter: GDString | StringName | string): any;
    public canvas_item_get_instance_shader_parameter_default_value(instance: RID, parameter: GDString | StringName | string): any;
    public canvas_item_get_instance_shader_parameter_list(instance: RID): Array<any>;
    public canvas_item_set_visibility_notifier(item: RID, enable: boolean, area: Rect2, enterCallable: Callable, exitCallable: Callable): void;
    public canvas_item_set_canvas_group_mode(item: RID, mode: number, clearMargin: number = 5.0, fitEmpty: boolean = false, fitMargin: number = 0.0, blurMipmaps: boolean = false): void;
    public debug_canvas_item_get_rect(item: RID): Rect2;
    public canvas_light_create(): RID;
    public canvas_light_attach_to_canvas(light: RID, canvas: RID): void;
    public canvas_light_set_enabled(light: RID, enabled: boolean): void;
    public canvas_light_set_texture_scale(light: RID, scale: number): void;
    public canvas_light_set_transform(light: RID, transform: Transform2D): void;
    public canvas_light_set_texture(light: RID, texture: RID): void;
    public canvas_light_set_texture_offset(light: RID, offset: Vector2): void;
    public canvas_light_set_color(light: RID, color: Color): void;
    public canvas_light_set_height(light: RID, height: number): void;
    public canvas_light_set_energy(light: RID, energy: number): void;
    public canvas_light_set_z_range(light: RID, minZ: number, maxZ: number): void;
    public canvas_light_set_layer_range(light: RID, minLayer: number, maxLayer: number): void;
    public canvas_light_set_item_cull_mask(light: RID, mask: number): void;
    public canvas_light_set_item_shadow_cull_mask(light: RID, mask: number): void;
    public canvas_light_set_mode(light: RID, mode: number): void;
    public canvas_light_set_shadow_enabled(light: RID, enabled: boolean): void;
    public canvas_light_set_shadow_filter(light: RID, filter: number): void;
    public canvas_light_set_shadow_color(light: RID, color: Color): void;
    public canvas_light_set_shadow_smooth(light: RID, smooth: number): void;
    public canvas_light_set_blend_mode(light: RID, mode: number): void;
    public canvas_light_set_interpolated(light: RID, interpolated: boolean): void;
    public canvas_light_reset_physics_interpolation(light: RID): void;
    public canvas_light_transform_physics_interpolation(light: RID, transform: Transform2D): void;
    public canvas_light_occluder_create(): RID;
    public canvas_light_occluder_attach_to_canvas(occluder: RID, canvas: RID): void;
    public canvas_light_occluder_set_enabled(occluder: RID, enabled: boolean): void;
    public canvas_light_occluder_set_polygon(occluder: RID, polygon: RID): void;
    public canvas_light_occluder_set_as_sdf_collision(occluder: RID, enable: boolean): void;
    public canvas_light_occluder_set_transform(occluder: RID, transform: Transform2D): void;
    public canvas_light_occluder_set_light_mask(occluder: RID, mask: number): void;
    public canvas_light_occluder_set_interpolated(occluder: RID, interpolated: boolean): void;
    public canvas_light_occluder_reset_physics_interpolation(occluder: RID): void;
    public canvas_light_occluder_transform_physics_interpolation(occluder: RID, transform: Transform2D): void;
    public canvas_occluder_polygon_create(): RID;
    public canvas_occluder_polygon_set_shape(occluderPolygon: RID, shape: PackedVector2Array, closed: boolean): void;
    public canvas_occluder_polygon_set_cull_mode(occluderPolygon: RID, mode: number): void;
    public canvas_set_shadow_texture_size(size: number): void;
    public global_shader_parameter_add(name: GDString | StringName | string, _type: number, defaultValue: any): void;
    public global_shader_parameter_remove(name: GDString | StringName | string): void;
    public global_shader_parameter_get_list(): Array<any>;
    public global_shader_parameter_set(name: GDString | StringName | string, value: any): void;
    public global_shader_parameter_set_override(name: GDString | StringName | string, value: any): void;
    public global_shader_parameter_get(name: GDString | StringName | string): any;
    public global_shader_parameter_get_type(name: GDString | StringName | string): number;
    public free_rid(rid: RID): void;
    public request_frame_drawn_callback(callable: Callable): void;
    public has_changed(): boolean;
    public get_rendering_info(info: number): number;
    public get_video_adapter_name(): GDString;
    public get_video_adapter_vendor(): GDString;
    public get_video_adapter_type(): number;
    public get_video_adapter_api_version(): GDString;
    public get_current_rendering_driver_name(): GDString;
    public get_current_rendering_method(): GDString;
    public make_sphere_mesh(latitudes: number, longitudes: number, radius: number): RID;
    public get_test_cube(): RID;
    public get_test_texture(): RID;
    public get_white_texture(): RID;
    public set_boot_image(image: Image, color: Color, scale: boolean, useFilter: boolean = true): void;
    public get_default_clear_color(): Color;
    public set_default_clear_color(color: Color): void;
    public has_os_feature(feature: GDString | StringName | string): boolean;
    public set_debug_generate_wireframes(generate: boolean): void;
    public is_render_loop_enabled(): boolean;
    public set_render_loop_enabled(enabled: boolean): void;
    public get_frame_setup_time_cpu(): number;
    public force_sync(): void;
    public force_draw(swabuffers: boolean = true, frameStep: number = 0.0): void;
    public get_rendering_device(): RenderingDevice;
    public create_local_rendering_device(): RenderingDevice;
    public is_on_render_thread(): boolean;
    public call_on_render_thread(callable: Callable): void;
    public has_feature(feature: number): boolean;

    
    public readonly frame_pre_draw: Signal<() => void>;
    public readonly frame_post_draw: Signal<() => void>;

    public static readonly TextureType: {
        TEXTURE_TYPE_2D: 0;
        TEXTURE_TYPE_LAYERED: 1;
        TEXTURE_TYPE_3D: 2;
    };
    public static readonly TextureLayeredType: {
        TEXTURE_LAYERED_2D_ARRAY: 0;
        TEXTURE_LAYERED_CUBEMAP: 1;
        TEXTURE_LAYERED_CUBEMAP_ARRAY: 2;
    };
    public static readonly CubeMapLayer: {
        CUBEMAP_LAYER_LEFT: 0;
        CUBEMAP_LAYER_RIGHT: 1;
        CUBEMAP_LAYER_BOTTOM: 2;
        CUBEMAP_LAYER_TOP: 3;
        CUBEMAP_LAYER_FRONT: 4;
        CUBEMAP_LAYER_BACK: 5;
    };
    public static readonly ShaderMode: {
        SHADER_SPATIAL: 0;
        SHADER_CANVAS_ITEM: 1;
        SHADER_PARTICLES: 2;
        SHADER_SKY: 3;
        SHADER_FOG: 4;
        SHADER_MAX: 5;
    };
    public static readonly ArrayType: {
        ARRAY_VERTEX: 0;
        ARRAY_NORMAL: 1;
        ARRAY_TANGENT: 2;
        ARRAY_COLOR: 3;
        ARRAY_TEX_UV: 4;
        ARRAY_TEX_UV2: 5;
        ARRAY_CUSTOM0: 6;
        ARRAY_CUSTOM1: 7;
        ARRAY_CUSTOM2: 8;
        ARRAY_CUSTOM3: 9;
        ARRAY_BONES: 10;
        ARRAY_WEIGHTS: 11;
        ARRAY_INDEX: 12;
        ARRAY_MAX: 13;
    };
    public static readonly ArrayCustomFormat: {
        ARRAY_CUSTOM_RGBA8_UNORM: 0;
        ARRAY_CUSTOM_RGBA8_SNORM: 1;
        ARRAY_CUSTOM_RG_HALF: 2;
        ARRAY_CUSTOM_RGBA_HALF: 3;
        ARRAY_CUSTOM_R_FLOAT: 4;
        ARRAY_CUSTOM_RG_FLOAT: 5;
        ARRAY_CUSTOM_RGB_FLOAT: 6;
        ARRAY_CUSTOM_RGBA_FLOAT: 7;
        ARRAY_CUSTOM_MAX: 8;
    };
    public static readonly ArrayFormat: {
        ARRAY_FORMAT_VERTEX: 1;
        ARRAY_FORMAT_NORMAL: 2;
        ARRAY_FORMAT_TANGENT: 4;
        ARRAY_FORMAT_COLOR: 8;
        ARRAY_FORMAT_TEX_UV: 16;
        ARRAY_FORMAT_TEX_UV2: 32;
        ARRAY_FORMAT_CUSTOM0: 64;
        ARRAY_FORMAT_CUSTOM1: 128;
        ARRAY_FORMAT_CUSTOM2: 256;
        ARRAY_FORMAT_CUSTOM3: 512;
        ARRAY_FORMAT_BONES: 1024;
        ARRAY_FORMAT_WEIGHTS: 2048;
        ARRAY_FORMAT_INDEX: 4096;
        ARRAY_FORMAT_BLEND_SHAPE_MASK: 7;
        ARRAY_FORMAT_CUSTOM_BASE: 13;
        ARRAY_FORMAT_CUSTOM_BITS: 3;
        ARRAY_FORMAT_CUSTOM0_SHIFT: 13;
        ARRAY_FORMAT_CUSTOM1_SHIFT: 16;
        ARRAY_FORMAT_CUSTOM2_SHIFT: 19;
        ARRAY_FORMAT_CUSTOM3_SHIFT: 22;
        ARRAY_FORMAT_CUSTOM_MASK: 7;
        ARRAY_COMPRESS_FLAGS_BASE: 25;
        ARRAY_FLAG_USE_2D_VERTICES: 33554432;
        ARRAY_FLAG_USE_DYNAMIC_UPDATE: 67108864;
        ARRAY_FLAG_USE_8_BONE_WEIGHTS: 134217728;
        ARRAY_FLAG_USES_EMPTY_VERTEX_ARRAY: 268435456;
        ARRAY_FLAG_COMPRESS_ATTRIBUTES: 536870912;
        ARRAY_FLAG_FORMAT_VERSION_BASE: 35;
        ARRAY_FLAG_FORMAT_VERSION_SHIFT: 35;
        ARRAY_FLAG_FORMAT_VERSION_1: 0;
        ARRAY_FLAG_FORMAT_VERSION_2: 34359738368;
        ARRAY_FLAG_FORMAT_CURRENT_VERSION: 34359738368;
        ARRAY_FLAG_FORMAT_VERSION_MASK: 255;
    };
    public static readonly PrimitiveType: {
        PRIMITIVE_POINTS: 0;
        PRIMITIVE_LINES: 1;
        PRIMITIVE_LINE_STRIP: 2;
        PRIMITIVE_TRIANGLES: 3;
        PRIMITIVE_TRIANGLE_STRIP: 4;
        PRIMITIVE_MAX: 5;
    };
    public static readonly BlendShapeMode: {
        BLEND_SHAPE_MODE_NORMALIZED: 0;
        BLEND_SHAPE_MODE_RELATIVE: 1;
    };
    public static readonly MultimeshTransformFormat: {
        MULTIMESH_TRANSFORM_2D: 0;
        MULTIMESH_TRANSFORM_3D: 1;
    };
    public static readonly MultimeshPhysicsInterpolationQuality: {
        MULTIMESH_INTERP_QUALITY_FAST: 0;
        MULTIMESH_INTERP_QUALITY_HIGH: 1;
    };
    public static readonly LightProjectorFilter: {
        LIGHT_PROJECTOR_FILTER_NEAREST: 0;
        LIGHT_PROJECTOR_FILTER_LINEAR: 1;
        LIGHT_PROJECTOR_FILTER_NEAREST_MIPMAPS: 2;
        LIGHT_PROJECTOR_FILTER_LINEAR_MIPMAPS: 3;
        LIGHT_PROJECTOR_FILTER_NEAREST_MIPMAPS_ANISOTROPIC: 4;
        LIGHT_PROJECTOR_FILTER_LINEAR_MIPMAPS_ANISOTROPIC: 5;
    };
    public static readonly LightType: {
        LIGHT_DIRECTIONAL: 0;
        LIGHT_OMNI: 1;
        LIGHT_SPOT: 2;
    };
    public static readonly LightParam: {
        LIGHT_PARAM_ENERGY: 0;
        LIGHT_PARAM_INDIRECT_ENERGY: 1;
        LIGHT_PARAM_VOLUMETRIC_FOG_ENERGY: 2;
        LIGHT_PARAM_SPECULAR: 3;
        LIGHT_PARAM_RANGE: 4;
        LIGHT_PARAM_SIZE: 5;
        LIGHT_PARAM_ATTENUATION: 6;
        LIGHT_PARAM_SPOT_ANGLE: 7;
        LIGHT_PARAM_SPOT_ATTENUATION: 8;
        LIGHT_PARAM_SHADOW_MAX_DISTANCE: 9;
        LIGHT_PARAM_SHADOW_SPLIT_1_OFFSET: 10;
        LIGHT_PARAM_SHADOW_SPLIT_2_OFFSET: 11;
        LIGHT_PARAM_SHADOW_SPLIT_3_OFFSET: 12;
        LIGHT_PARAM_SHADOW_FADE_START: 13;
        LIGHT_PARAM_SHADOW_NORMAL_BIAS: 14;
        LIGHT_PARAM_SHADOW_BIAS: 15;
        LIGHT_PARAM_SHADOW_PANCAKE_SIZE: 16;
        LIGHT_PARAM_SHADOW_OPACITY: 17;
        LIGHT_PARAM_SHADOW_BLUR: 18;
        LIGHT_PARAM_TRANSMITTANCE_BIAS: 19;
        LIGHT_PARAM_INTENSITY: 20;
        LIGHT_PARAM_MAX: 21;
    };
    public static readonly LightBakeMode: {
        LIGHT_BAKE_DISABLED: 0;
        LIGHT_BAKE_STATIC: 1;
        LIGHT_BAKE_DYNAMIC: 2;
    };
    public static readonly LightOmniShadowMode: {
        LIGHT_OMNI_SHADOW_DUAL_PARABOLOID: 0;
        LIGHT_OMNI_SHADOW_CUBE: 1;
    };
    public static readonly LightDirectionalShadowMode: {
        LIGHT_DIRECTIONAL_SHADOW_ORTHOGONAL: 0;
        LIGHT_DIRECTIONAL_SHADOW_PARALLEL_2_SPLITS: 1;
        LIGHT_DIRECTIONAL_SHADOW_PARALLEL_4_SPLITS: 2;
    };
    public static readonly LightDirectionalSkyMode: {
        LIGHT_DIRECTIONAL_SKY_MODE_LIGHT_AND_SKY: 0;
        LIGHT_DIRECTIONAL_SKY_MODE_LIGHT_ONLY: 1;
        LIGHT_DIRECTIONAL_SKY_MODE_SKY_ONLY: 2;
    };
    public static readonly ShadowQuality: {
        SHADOW_QUALITY_HARD: 0;
        SHADOW_QUALITY_SOFT_VERY_LOW: 1;
        SHADOW_QUALITY_SOFT_LOW: 2;
        SHADOW_QUALITY_SOFT_MEDIUM: 3;
        SHADOW_QUALITY_SOFT_HIGH: 4;
        SHADOW_QUALITY_SOFT_ULTRA: 5;
        SHADOW_QUALITY_MAX: 6;
    };
    public static readonly ReflectionProbeUpdateMode: {
        REFLECTION_PROBE_UPDATE_ONCE: 0;
        REFLECTION_PROBE_UPDATE_ALWAYS: 1;
    };
    public static readonly ReflectionProbeAmbientMode: {
        REFLECTION_PROBE_AMBIENT_DISABLED: 0;
        REFLECTION_PROBE_AMBIENT_ENVIRONMENT: 1;
        REFLECTION_PROBE_AMBIENT_COLOR: 2;
    };
    public static readonly DecalTexture: {
        DECAL_TEXTURE_ALBEDO: 0;
        DECAL_TEXTURE_NORMAL: 1;
        DECAL_TEXTURE_ORM: 2;
        DECAL_TEXTURE_EMISSION: 3;
        DECAL_TEXTURE_MAX: 4;
    };
    public static readonly DecalFilter: {
        DECAL_FILTER_NEAREST: 0;
        DECAL_FILTER_LINEAR: 1;
        DECAL_FILTER_NEAREST_MIPMAPS: 2;
        DECAL_FILTER_LINEAR_MIPMAPS: 3;
        DECAL_FILTER_NEAREST_MIPMAPS_ANISOTROPIC: 4;
        DECAL_FILTER_LINEAR_MIPMAPS_ANISOTROPIC: 5;
    };
    public static readonly VoxelGIQuality: {
        VOXEL_GI_QUALITY_LOW: 0;
        VOXEL_GI_QUALITY_HIGH: 1;
    };
    public static readonly ParticlesMode: {
        PARTICLES_MODE_2D: 0;
        PARTICLES_MODE_3D: 1;
    };
    public static readonly ParticlesTransformAlign: {
        PARTICLES_TRANSFORM_ALIGN_DISABLED: 0;
        PARTICLES_TRANSFORM_ALIGN_Z_BILLBOARD: 1;
        PARTICLES_TRANSFORM_ALIGN_Y_TO_VELOCITY: 2;
        PARTICLES_TRANSFORM_ALIGN_Z_BILLBOARD_Y_TO_VELOCITY: 3;
    };
    public static readonly ParticlesDrawOrder: {
        PARTICLES_DRAW_ORDER_INDEX: 0;
        PARTICLES_DRAW_ORDER_LIFETIME: 1;
        PARTICLES_DRAW_ORDER_REVERSE_LIFETIME: 2;
        PARTICLES_DRAW_ORDER_VIEW_DEPTH: 3;
    };
    public static readonly ParticlesCollisionType: {
        PARTICLES_COLLISION_TYPE_SPHERE_ATTRACT: 0;
        PARTICLES_COLLISION_TYPE_BOX_ATTRACT: 1;
        PARTICLES_COLLISION_TYPE_VECTOR_FIELD_ATTRACT: 2;
        PARTICLES_COLLISION_TYPE_SPHERE_COLLIDE: 3;
        PARTICLES_COLLISION_TYPE_BOX_COLLIDE: 4;
        PARTICLES_COLLISION_TYPE_SDF_COLLIDE: 5;
        PARTICLES_COLLISION_TYPE_HEIGHTFIELD_COLLIDE: 6;
    };
    public static readonly ParticlesCollisionHeightfieldResolution: {
        PARTICLES_COLLISION_HEIGHTFIELD_RESOLUTION_256: 0;
        PARTICLES_COLLISION_HEIGHTFIELD_RESOLUTION_512: 1;
        PARTICLES_COLLISION_HEIGHTFIELD_RESOLUTION_1024: 2;
        PARTICLES_COLLISION_HEIGHTFIELD_RESOLUTION_2048: 3;
        PARTICLES_COLLISION_HEIGHTFIELD_RESOLUTION_4096: 4;
        PARTICLES_COLLISION_HEIGHTFIELD_RESOLUTION_8192: 5;
        PARTICLES_COLLISION_HEIGHTFIELD_RESOLUTION_MAX: 6;
    };
    public static readonly FogVolumeShape: {
        FOG_VOLUME_SHAPE_ELLIPSOID: 0;
        FOG_VOLUME_SHAPE_CONE: 1;
        FOG_VOLUME_SHAPE_CYLINDER: 2;
        FOG_VOLUME_SHAPE_BOX: 3;
        FOG_VOLUME_SHAPE_WORLD: 4;
        FOG_VOLUME_SHAPE_MAX: 5;
    };
    public static readonly ViewportScaling3DMode: {
        VIEWPORT_SCALING_3D_MODE_BILINEAR: 0;
        VIEWPORT_SCALING_3D_MODE_FSR: 1;
        VIEWPORT_SCALING_3D_MODE_FSR2: 2;
        VIEWPORT_SCALING_3D_MODE_METALFX_SPATIAL: 3;
        VIEWPORT_SCALING_3D_MODE_METALFX_TEMPORAL: 4;
        VIEWPORT_SCALING_3D_MODE_MAX: 5;
    };
    public static readonly ViewportUpdateMode: {
        VIEWPORT_UPDATE_DISABLED: 0;
        VIEWPORT_UPDATE_ONCE: 1;
        VIEWPORT_UPDATE_WHEN_VISIBLE: 2;
        VIEWPORT_UPDATE_WHEN_PARENT_VISIBLE: 3;
        VIEWPORT_UPDATE_ALWAYS: 4;
    };
    public static readonly ViewportClearMode: {
        VIEWPORT_CLEAR_ALWAYS: 0;
        VIEWPORT_CLEAR_NEVER: 1;
        VIEWPORT_CLEAR_ONLY_NEXT_FRAME: 2;
    };
    public static readonly ViewportEnvironmentMode: {
        VIEWPORT_ENVIRONMENT_DISABLED: 0;
        VIEWPORT_ENVIRONMENT_ENABLED: 1;
        VIEWPORT_ENVIRONMENT_INHERIT: 2;
        VIEWPORT_ENVIRONMENT_MAX: 3;
    };
    public static readonly ViewportSDFOversize: {
        VIEWPORT_SDF_OVERSIZE_100_PERCENT: 0;
        VIEWPORT_SDF_OVERSIZE_120_PERCENT: 1;
        VIEWPORT_SDF_OVERSIZE_150_PERCENT: 2;
        VIEWPORT_SDF_OVERSIZE_200_PERCENT: 3;
        VIEWPORT_SDF_OVERSIZE_MAX: 4;
    };
    public static readonly ViewportSDFScale: {
        VIEWPORT_SDF_SCALE_100_PERCENT: 0;
        VIEWPORT_SDF_SCALE_50_PERCENT: 1;
        VIEWPORT_SDF_SCALE_25_PERCENT: 2;
        VIEWPORT_SDF_SCALE_MAX: 3;
    };
    public static readonly ViewportMSAA: {
        VIEWPORT_MSAA_DISABLED: 0;
        VIEWPORT_MSAA_2X: 1;
        VIEWPORT_MSAA_4X: 2;
        VIEWPORT_MSAA_8X: 3;
        VIEWPORT_MSAA_MAX: 4;
    };
    public static readonly ViewportAnisotropicFiltering: {
        VIEWPORT_ANISOTROPY_DISABLED: 0;
        VIEWPORT_ANISOTROPY_2X: 1;
        VIEWPORT_ANISOTROPY_4X: 2;
        VIEWPORT_ANISOTROPY_8X: 3;
        VIEWPORT_ANISOTROPY_16X: 4;
        VIEWPORT_ANISOTROPY_MAX: 5;
    };
    public static readonly ViewportScreenSpaceAA: {
        VIEWPORT_SCREEN_SPACE_AA_DISABLED: 0;
        VIEWPORT_SCREEN_SPACE_AA_FXAA: 1;
        VIEWPORT_SCREEN_SPACE_AA_SMAA: 2;
        VIEWPORT_SCREEN_SPACE_AA_MAX: 3;
    };
    public static readonly ViewportOcclusionCullingBuildQuality: {
        VIEWPORT_OCCLUSION_BUILD_QUALITY_LOW: 0;
        VIEWPORT_OCCLUSION_BUILD_QUALITY_MEDIUM: 1;
        VIEWPORT_OCCLUSION_BUILD_QUALITY_HIGH: 2;
    };
    public static readonly ViewportRenderInfo: {
        VIEWPORT_RENDER_INFO_OBJECTS_IN_FRAME: 0;
        VIEWPORT_RENDER_INFO_PRIMITIVES_IN_FRAME: 1;
        VIEWPORT_RENDER_INFO_DRAW_CALLS_IN_FRAME: 2;
        VIEWPORT_RENDER_INFO_MAX: 3;
    };
    public static readonly ViewportRenderInfoType: {
        VIEWPORT_RENDER_INFO_TYPE_VISIBLE: 0;
        VIEWPORT_RENDER_INFO_TYPE_SHADOW: 1;
        VIEWPORT_RENDER_INFO_TYPE_CANVAS: 2;
        VIEWPORT_RENDER_INFO_TYPE_MAX: 3;
    };
    public static readonly ViewportDebugDraw: {
        VIEWPORT_DEBUG_DRAW_DISABLED: 0;
        VIEWPORT_DEBUG_DRAW_UNSHADED: 1;
        VIEWPORT_DEBUG_DRAW_LIGHTING: 2;
        VIEWPORT_DEBUG_DRAW_OVERDRAW: 3;
        VIEWPORT_DEBUG_DRAW_WIREFRAME: 4;
        VIEWPORT_DEBUG_DRAW_NORMAL_BUFFER: 5;
        VIEWPORT_DEBUG_DRAW_VOXEL_GI_ALBEDO: 6;
        VIEWPORT_DEBUG_DRAW_VOXEL_GI_LIGHTING: 7;
        VIEWPORT_DEBUG_DRAW_VOXEL_GI_EMISSION: 8;
        VIEWPORT_DEBUG_DRAW_SHADOW_ATLAS: 9;
        VIEWPORT_DEBUG_DRAW_DIRECTIONAL_SHADOW_ATLAS: 10;
        VIEWPORT_DEBUG_DRAW_SCENE_LUMINANCE: 11;
        VIEWPORT_DEBUG_DRAW_SSAO: 12;
        VIEWPORT_DEBUG_DRAW_SSIL: 13;
        VIEWPORT_DEBUG_DRAW_PSSM_SPLITS: 14;
        VIEWPORT_DEBUG_DRAW_DECAL_ATLAS: 15;
        VIEWPORT_DEBUG_DRAW_SDFGI: 16;
        VIEWPORT_DEBUG_DRAW_SDFGI_PROBES: 17;
        VIEWPORT_DEBUG_DRAW_GI_BUFFER: 18;
        VIEWPORT_DEBUG_DRAW_DISABLE_LOD: 19;
        VIEWPORT_DEBUG_DRAW_CLUSTER_OMNI_LIGHTS: 20;
        VIEWPORT_DEBUG_DRAW_CLUSTER_SPOT_LIGHTS: 21;
        VIEWPORT_DEBUG_DRAW_CLUSTER_DECALS: 22;
        VIEWPORT_DEBUG_DRAW_CLUSTER_REFLECTION_PROBES: 23;
        VIEWPORT_DEBUG_DRAW_OCCLUDERS: 24;
        VIEWPORT_DEBUG_DRAW_MOTION_VECTORS: 25;
        VIEWPORT_DEBUG_DRAW_INTERNAL_BUFFER: 26;
    };
    public static readonly ViewportVRSMode: {
        VIEWPORT_VRS_DISABLED: 0;
        VIEWPORT_VRS_TEXTURE: 1;
        VIEWPORT_VRS_XR: 2;
        VIEWPORT_VRS_MAX: 3;
    };
    public static readonly ViewportVRSUpdateMode: {
        VIEWPORT_VRS_UPDATE_DISABLED: 0;
        VIEWPORT_VRS_UPDATE_ONCE: 1;
        VIEWPORT_VRS_UPDATE_ALWAYS: 2;
        VIEWPORT_VRS_UPDATE_MAX: 3;
    };
    public static readonly SkyMode: {
        SKY_MODE_AUTOMATIC: 0;
        SKY_MODE_QUALITY: 1;
        SKY_MODE_INCREMENTAL: 2;
        SKY_MODE_REALTIME: 3;
    };
    public static readonly CompositorEffectFlags: {
        COMPOSITOR_EFFECT_FLAG_ACCESS_RESOLVED_COLOR: 1;
        COMPOSITOR_EFFECT_FLAG_ACCESS_RESOLVED_DEPTH: 2;
        COMPOSITOR_EFFECT_FLAG_NEEDS_MOTION_VECTORS: 4;
        COMPOSITOR_EFFECT_FLAG_NEEDS_ROUGHNESS: 8;
        COMPOSITOR_EFFECT_FLAG_NEEDS_SEPARATE_SPECULAR: 16;
    };
    public static readonly CompositorEffectCallbackType: {
        COMPOSITOR_EFFECT_CALLBACK_TYPE_PRE_OPAQUE: 0;
        COMPOSITOR_EFFECT_CALLBACK_TYPE_POST_OPAQUE: 1;
        COMPOSITOR_EFFECT_CALLBACK_TYPE_POST_SKY: 2;
        COMPOSITOR_EFFECT_CALLBACK_TYPE_PRE_TRANSPARENT: 3;
        COMPOSITOR_EFFECT_CALLBACK_TYPE_POST_TRANSPARENT: 4;
        COMPOSITOR_EFFECT_CALLBACK_TYPE_ANY: -1;
    };
    public static readonly EnvironmentBG: {
        ENV_BG_CLEAR_COLOR: 0;
        ENV_BG_COLOR: 1;
        ENV_BG_SKY: 2;
        ENV_BG_CANVAS: 3;
        ENV_BG_KEEP: 4;
        ENV_BG_CAMERA_FEED: 5;
        ENV_BG_MAX: 6;
    };
    public static readonly EnvironmentAmbientSource: {
        ENV_AMBIENT_SOURCE_BG: 0;
        ENV_AMBIENT_SOURCE_DISABLED: 1;
        ENV_AMBIENT_SOURCE_COLOR: 2;
        ENV_AMBIENT_SOURCE_SKY: 3;
    };
    public static readonly EnvironmentReflectionSource: {
        ENV_REFLECTION_SOURCE_BG: 0;
        ENV_REFLECTION_SOURCE_DISABLED: 1;
        ENV_REFLECTION_SOURCE_SKY: 2;
    };
    public static readonly EnvironmentGlowBlendMode: {
        ENV_GLOW_BLEND_MODE_ADDITIVE: 0;
        ENV_GLOW_BLEND_MODE_SCREEN: 1;
        ENV_GLOW_BLEND_MODE_SOFTLIGHT: 2;
        ENV_GLOW_BLEND_MODE_REPLACE: 3;
        ENV_GLOW_BLEND_MODE_MIX: 4;
    };
    public static readonly EnvironmentFogMode: {
        ENV_FOG_MODE_EXPONENTIAL: 0;
        ENV_FOG_MODE_DEPTH: 1;
    };
    public static readonly EnvironmentToneMapper: {
        ENV_TONE_MAPPER_LINEAR: 0;
        ENV_TONE_MAPPER_REINHARD: 1;
        ENV_TONE_MAPPER_FILMIC: 2;
        ENV_TONE_MAPPER_ACES: 3;
        ENV_TONE_MAPPER_AGX: 4;
    };
    public static readonly EnvironmentSSRRoughnessQuality: {
        ENV_SSR_ROUGHNESS_QUALITY_DISABLED: 0;
        ENV_SSR_ROUGHNESS_QUALITY_LOW: 1;
        ENV_SSR_ROUGHNESS_QUALITY_MEDIUM: 2;
        ENV_SSR_ROUGHNESS_QUALITY_HIGH: 3;
    };
    public static readonly EnvironmentSSAOQuality: {
        ENV_SSAO_QUALITY_VERY_LOW: 0;
        ENV_SSAO_QUALITY_LOW: 1;
        ENV_SSAO_QUALITY_MEDIUM: 2;
        ENV_SSAO_QUALITY_HIGH: 3;
        ENV_SSAO_QUALITY_ULTRA: 4;
    };
    public static readonly EnvironmentSSILQuality: {
        ENV_SSIL_QUALITY_VERY_LOW: 0;
        ENV_SSIL_QUALITY_LOW: 1;
        ENV_SSIL_QUALITY_MEDIUM: 2;
        ENV_SSIL_QUALITY_HIGH: 3;
        ENV_SSIL_QUALITY_ULTRA: 4;
    };
    public static readonly EnvironmentSDFGIYScale: {
        ENV_SDFGI_Y_SCALE_50_PERCENT: 0;
        ENV_SDFGI_Y_SCALE_75_PERCENT: 1;
        ENV_SDFGI_Y_SCALE_100_PERCENT: 2;
    };
    public static readonly EnvironmentSDFGIRayCount: {
        ENV_SDFGI_RAY_COUNT_4: 0;
        ENV_SDFGI_RAY_COUNT_8: 1;
        ENV_SDFGI_RAY_COUNT_16: 2;
        ENV_SDFGI_RAY_COUNT_32: 3;
        ENV_SDFGI_RAY_COUNT_64: 4;
        ENV_SDFGI_RAY_COUNT_96: 5;
        ENV_SDFGI_RAY_COUNT_128: 6;
        ENV_SDFGI_RAY_COUNT_MAX: 7;
    };
    public static readonly EnvironmentSDFGIFramesToConverge: {
        ENV_SDFGI_CONVERGE_IN_5_FRAMES: 0;
        ENV_SDFGI_CONVERGE_IN_10_FRAMES: 1;
        ENV_SDFGI_CONVERGE_IN_15_FRAMES: 2;
        ENV_SDFGI_CONVERGE_IN_20_FRAMES: 3;
        ENV_SDFGI_CONVERGE_IN_25_FRAMES: 4;
        ENV_SDFGI_CONVERGE_IN_30_FRAMES: 5;
        ENV_SDFGI_CONVERGE_MAX: 6;
    };
    public static readonly EnvironmentSDFGIFramesToUpdateLight: {
        ENV_SDFGI_UPDATE_LIGHT_IN_1_FRAME: 0;
        ENV_SDFGI_UPDATE_LIGHT_IN_2_FRAMES: 1;
        ENV_SDFGI_UPDATE_LIGHT_IN_4_FRAMES: 2;
        ENV_SDFGI_UPDATE_LIGHT_IN_8_FRAMES: 3;
        ENV_SDFGI_UPDATE_LIGHT_IN_16_FRAMES: 4;
        ENV_SDFGI_UPDATE_LIGHT_MAX: 5;
    };
    public static readonly SubSurfaceScatteringQuality: {
        SUB_SURFACE_SCATTERING_QUALITY_DISABLED: 0;
        SUB_SURFACE_SCATTERING_QUALITY_LOW: 1;
        SUB_SURFACE_SCATTERING_QUALITY_MEDIUM: 2;
        SUB_SURFACE_SCATTERING_QUALITY_HIGH: 3;
    };
    public static readonly DOFBokehShape: {
        DOF_BOKEH_BOX: 0;
        DOF_BOKEH_HEXAGON: 1;
        DOF_BOKEH_CIRCLE: 2;
    };
    public static readonly DOFBlurQuality: {
        DOF_BLUR_QUALITY_VERY_LOW: 0;
        DOF_BLUR_QUALITY_LOW: 1;
        DOF_BLUR_QUALITY_MEDIUM: 2;
        DOF_BLUR_QUALITY_HIGH: 3;
    };
    public static readonly InstanceType: {
        INSTANCE_NONE: 0;
        INSTANCE_MESH: 1;
        INSTANCE_MULTIMESH: 2;
        INSTANCE_PARTICLES: 3;
        INSTANCE_PARTICLES_COLLISION: 4;
        INSTANCE_LIGHT: 5;
        INSTANCE_REFLECTION_PROBE: 6;
        INSTANCE_DECAL: 7;
        INSTANCE_VOXEL_GI: 8;
        INSTANCE_LIGHTMAP: 9;
        INSTANCE_OCCLUDER: 10;
        INSTANCE_VISIBLITY_NOTIFIER: 11;
        INSTANCE_FOG_VOLUME: 12;
        INSTANCE_MAX: 13;
        INSTANCE_GEOMETRY_MASK: 14;
    };
    public static readonly InstanceFlags: {
        INSTANCE_FLAG_USE_BAKED_LIGHT: 0;
        INSTANCE_FLAG_USE_DYNAMIC_GI: 1;
        INSTANCE_FLAG_DRAW_NEXT_FRAME_IF_VISIBLE: 2;
        INSTANCE_FLAG_IGNORE_OCCLUSION_CULLING: 3;
        INSTANCE_FLAG_MAX: 4;
    };
    public static readonly ShadowCastingSetting: {
        SHADOW_CASTING_SETTING_OFF: 0;
        SHADOW_CASTING_SETTING_ON: 1;
        SHADOW_CASTING_SETTING_DOUBLE_SIDED: 2;
        SHADOW_CASTING_SETTING_SHADOWS_ONLY: 3;
    };
    public static readonly VisibilityRangeFadeMode: {
        VISIBILITY_RANGE_FADE_DISABLED: 0;
        VISIBILITY_RANGE_FADE_SELF: 1;
        VISIBILITY_RANGE_FADE_DEPENDENCIES: 2;
    };
    public static readonly BakeChannels: {
        BAKE_CHANNEL_ALBEDO_ALPHA: 0;
        BAKE_CHANNEL_NORMAL: 1;
        BAKE_CHANNEL_ORM: 2;
        BAKE_CHANNEL_EMISSION: 3;
    };
    public static readonly CanvasTextureChannel: {
        CANVAS_TEXTURE_CHANNEL_DIFFUSE: 0;
        CANVAS_TEXTURE_CHANNEL_NORMAL: 1;
        CANVAS_TEXTURE_CHANNEL_SPECULAR: 2;
    };
    public static readonly NinePatchAxisMode: {
        NINE_PATCH_STRETCH: 0;
        NINE_PATCH_TILE: 1;
        NINE_PATCH_TILE_FIT: 2;
    };
    public static readonly CanvasItemTextureFilter: {
        CANVAS_ITEM_TEXTURE_FILTER_DEFAULT: 0;
        CANVAS_ITEM_TEXTURE_FILTER_NEAREST: 1;
        CANVAS_ITEM_TEXTURE_FILTER_LINEAR: 2;
        CANVAS_ITEM_TEXTURE_FILTER_NEAREST_WITH_MIPMAPS: 3;
        CANVAS_ITEM_TEXTURE_FILTER_LINEAR_WITH_MIPMAPS: 4;
        CANVAS_ITEM_TEXTURE_FILTER_NEAREST_WITH_MIPMAPS_ANISOTROPIC: 5;
        CANVAS_ITEM_TEXTURE_FILTER_LINEAR_WITH_MIPMAPS_ANISOTROPIC: 6;
        CANVAS_ITEM_TEXTURE_FILTER_MAX: 7;
    };
    public static readonly CanvasItemTextureRepeat: {
        CANVAS_ITEM_TEXTURE_REPEAT_DEFAULT: 0;
        CANVAS_ITEM_TEXTURE_REPEAT_DISABLED: 1;
        CANVAS_ITEM_TEXTURE_REPEAT_ENABLED: 2;
        CANVAS_ITEM_TEXTURE_REPEAT_MIRROR: 3;
        CANVAS_ITEM_TEXTURE_REPEAT_MAX: 4;
    };
    public static readonly CanvasGroupMode: {
        CANVAS_GROUP_MODE_DISABLED: 0;
        CANVAS_GROUP_MODE_CLIP_ONLY: 1;
        CANVAS_GROUP_MODE_CLIP_AND_DRAW: 2;
        CANVAS_GROUP_MODE_TRANSPARENT: 3;
    };
    public static readonly CanvasLightMode: {
        CANVAS_LIGHT_MODE_POINT: 0;
        CANVAS_LIGHT_MODE_DIRECTIONAL: 1;
    };
    public static readonly CanvasLightBlendMode: {
        CANVAS_LIGHT_BLEND_MODE_ADD: 0;
        CANVAS_LIGHT_BLEND_MODE_SUB: 1;
        CANVAS_LIGHT_BLEND_MODE_MIX: 2;
    };
    public static readonly CanvasLightShadowFilter: {
        CANVAS_LIGHT_FILTER_NONE: 0;
        CANVAS_LIGHT_FILTER_PCF5: 1;
        CANVAS_LIGHT_FILTER_PCF13: 2;
        CANVAS_LIGHT_FILTER_MAX: 3;
    };
    public static readonly CanvasOccluderPolygonCullMode: {
        CANVAS_OCCLUDER_POLYGON_CULL_DISABLED: 0;
        CANVAS_OCCLUDER_POLYGON_CULL_CLOCKWISE: 1;
        CANVAS_OCCLUDER_POLYGON_CULL_COUNTER_CLOCKWISE: 2;
    };
    public static readonly GlobalShaderParameterType: {
        GLOBAL_VAR_TYPE_BOOL: 0;
        GLOBAL_VAR_TYPE_BVEC2: 1;
        GLOBAL_VAR_TYPE_BVEC3: 2;
        GLOBAL_VAR_TYPE_BVEC4: 3;
        GLOBAL_VAR_TYPE_INT: 4;
        GLOBAL_VAR_TYPE_IVEC2: 5;
        GLOBAL_VAR_TYPE_IVEC3: 6;
        GLOBAL_VAR_TYPE_IVEC4: 7;
        GLOBAL_VAR_TYPE_RECT2I: 8;
        GLOBAL_VAR_TYPE_UINT: 9;
        GLOBAL_VAR_TYPE_UVEC2: 10;
        GLOBAL_VAR_TYPE_UVEC3: 11;
        GLOBAL_VAR_TYPE_UVEC4: 12;
        GLOBAL_VAR_TYPE_FLOAT: 13;
        GLOBAL_VAR_TYPE_VEC2: 14;
        GLOBAL_VAR_TYPE_VEC3: 15;
        GLOBAL_VAR_TYPE_VEC4: 16;
        GLOBAL_VAR_TYPE_COLOR: 17;
        GLOBAL_VAR_TYPE_RECT2: 18;
        GLOBAL_VAR_TYPE_MAT2: 19;
        GLOBAL_VAR_TYPE_MAT3: 20;
        GLOBAL_VAR_TYPE_MAT4: 21;
        GLOBAL_VAR_TYPE_TRANSFORM_2D: 22;
        GLOBAL_VAR_TYPE_TRANSFORM: 23;
        GLOBAL_VAR_TYPE_SAMPLER2D: 24;
        GLOBAL_VAR_TYPE_SAMPLER2DARRAY: 25;
        GLOBAL_VAR_TYPE_SAMPLER3D: 26;
        GLOBAL_VAR_TYPE_SAMPLERCUBE: 27;
        GLOBAL_VAR_TYPE_SAMPLEREXT: 28;
        GLOBAL_VAR_TYPE_MAX: 29;
    };
    public static readonly RenderingInfo: {
        RENDERING_INFO_TOTAL_OBJECTS_IN_FRAME: 0;
        RENDERING_INFO_TOTAL_PRIMITIVES_IN_FRAME: 1;
        RENDERING_INFO_TOTAL_DRAW_CALLS_IN_FRAME: 2;
        RENDERING_INFO_TEXTURE_MEM_USED: 3;
        RENDERING_INFO_BUFFER_MEM_USED: 4;
        RENDERING_INFO_VIDEO_MEM_USED: 5;
        RENDERING_INFO_PIPELINE_COMPILATIONS_CANVAS: 6;
        RENDERING_INFO_PIPELINE_COMPILATIONS_MESH: 7;
        RENDERING_INFO_PIPELINE_COMPILATIONS_SURFACE: 8;
        RENDERING_INFO_PIPELINE_COMPILATIONS_DRAW: 9;
        RENDERING_INFO_PIPELINE_COMPILATIONS_SPECIALIZATION: 10;
    };
    public static readonly PipelineSource: {
        PIPELINE_SOURCE_CANVAS: 0;
        PIPELINE_SOURCE_MESH: 1;
        PIPELINE_SOURCE_SURFACE: 2;
        PIPELINE_SOURCE_DRAW: 3;
        PIPELINE_SOURCE_SPECIALIZATION: 4;
        PIPELINE_SOURCE_MAX: 5;
    };
    public static readonly Features: {
        FEATURE_SHADERS: 0;
        FEATURE_MULTITHREADED: 1;
    };
}


/**
 * A singleton instance of RenderingServer.
 * This is a global variable, available from anywhere.
 */
export const RenderingServer: RenderingServer;
