
import type { Callable } from '@godot/builtins/callable';
import type { Color } from '@godot/builtins/color';
import type { GDString } from '@godot/builtins/gd_string';
import type { GodotObject } from '@godot/classes/godot_object';
import type { PackedByteArray } from '@godot/builtins/packed_byte_array';
import type { PackedColorArray } from '@godot/builtins/packed_color_array';
import type { PackedInt64Array } from '@godot/builtins/packed_int64_array';
import type { RDPipelineColorBlendState } from '@godot/classes/rd_pipeline_color_blend_state';
import type { RDPipelineDepthStencilState } from '@godot/classes/rd_pipeline_depth_stencil_state';
import type { RDPipelineMultisampleState } from '@godot/classes/rd_pipeline_multisample_state';
import type { RDPipelineRasterizationState } from '@godot/classes/rd_pipeline_rasterization_state';
import type { RDSamplerState } from '@godot/classes/rd_sampler_state';
import type { RDShaderSPIRV } from '@godot/classes/rd_shader_spirv';
import type { RDShaderSource } from '@godot/classes/rd_shader_source';
import type { RDTextureFormat } from '@godot/classes/rd_texture_format';
import type { RDTextureView } from '@godot/classes/rd_texture_view';
import type { RID } from '@godot/builtins/rid';
import type { Rect2 } from '@godot/builtins/rect2';
import type { Vector2i } from '@godot/builtins/vector2i';
import type { Vector3 } from '@godot/builtins/vector3';


export declare class RenderingDevice extends GodotObject {


    public texture_create(format: RDTextureFormat, view: RDTextureView, data: Array<any> = []): RID;
    public texture_create_shared(view: RDTextureView, withTexture: RID): RID;
    public texture_create_shared_from_slice(view: RDTextureView, withTexture: RID, layer: number, mipmap: number, mipmaps: number = 1, sliceType: number = 0): RID;
    public texture_create_from_extension(_type: number, format: number, samples: number, usageFlags: number, image: number, width: number, height: number, depth: number, layers: number, mipmaps: number = 1): RID;
    public texture_update(texture: RID, layer: number, data: PackedByteArray): number;
    public texture_get_data(texture: RID, layer: number): PackedByteArray;
    public texture_get_data_async(texture: RID, layer: number, callback: Callable | Function): number;
    public texture_is_format_supported_for_usage(format: number, usageFlags: number): boolean;
    public texture_is_shared(texture: RID): boolean;
    public texture_is_valid(texture: RID): boolean;
    public texture_set_discardable(texture: RID, discardable: boolean): void;
    public texture_is_discardable(texture: RID): boolean;
    public texture_copy(fromTexture: RID, toTexture: RID, fromPos: Vector3, toPos: Vector3, size: Vector3, srcMipmap: number, dstMipmap: number, srcLayer: number, dstLayer: number): number;
    public texture_clear(texture: RID, color: Color, baseMipmap: number, mipmacount: number, baseLayer: number, layerCount: number): number;
    public texture_resolve_multisample(fromTexture: RID, toTexture: RID): number;
    public texture_get_format(texture: RID): RDTextureFormat;
    public texture_get_native_handle(texture: RID): number;
    public framebuffer_format_create(attachments: Array<any>, viewCount: number = 1): number;
    public framebuffer_format_create_multipass(attachments: Array<any>, passes: Array<any>, viewCount: number = 1): number;
    public framebuffer_format_create_empty(samples: number = 0): number;
    public framebuffer_format_get_texture_samples(format: number, renderPass: number = 0): number;
    public framebuffer_create(textures: Array<any>, validateWithFormat: number = -1, viewCount: number = 1): RID;
    public framebuffer_create_multipass(textures: Array<any>, passes: Array<any>, validateWithFormat: number = -1, viewCount: number = 1): RID;
    public framebuffer_create_empty(size: Vector2i, samples: number = 0, validateWithFormat: number = -1): RID;
    public framebuffer_get_format(framebuffer: RID): number;
    public framebuffer_is_valid(framebuffer: RID): boolean;
    public sampler_create(state: RDSamplerState): RID;
    public sampler_is_format_supported_for_filter(format: number, samplerFilter: number): boolean;
    public vertex_buffer_create(sizeBytes: number, data: PackedByteArray = PackedByteArray(), creationBits: number = 0): RID;
    public vertex_format_create(vertexDescriptions: Array<any>): number;
    public vertex_array_create(vertexCount: number, vertexFormat: number, srcBuffers: Array<any>, offsets: PackedInt64Array = PackedInt64Array()): RID;
    public index_buffer_create(sizeIndices: number, format: number, data: PackedByteArray = PackedByteArray(), useRestartIndices: boolean = false, creationBits: number = 0): RID;
    public index_array_create(indexBuffer: RID, indexOffset: number, indexCount: number): RID;
    public shader_compile_spirv_from_source(shaderSource: RDShaderSource, allowCache: boolean = true): RDShaderSPIRV;
    public shader_compile_binary_from_spirv(spirvData: RDShaderSPIRV, name: GDString | StringName | string = ""): PackedByteArray;
    public shader_create_from_spirv(spirvData: RDShaderSPIRV, name: GDString | StringName | string = ""): RID;
    public shader_create_from_bytecode(binaryData: PackedByteArray, placeholderRid: RID = RID()): RID;
    public shader_create_placeholder(): RID;
    public shader_get_vertex_input_attribute_mask(shader: RID): number;
    public uniform_buffer_create(sizeBytes: number, data: PackedByteArray = PackedByteArray(), creationBits: number = 0): RID;
    public storage_buffer_create(sizeBytes: number, data: PackedByteArray = PackedByteArray(), usage: number = 0, creationBits: number = 0): RID;
    public texture_buffer_create(sizeBytes: number, format: number, data: PackedByteArray = PackedByteArray()): RID;
    public uniform_set_create(uniforms: Array<any>, shader: RID, shaderSet: number): RID;
    public uniform_set_is_valid(uniformSet: RID): boolean;
    public buffer_copy(srcBuffer: RID, dstBuffer: RID, srcOffset: number, dstOffset: number, size: number): number;
    public buffer_update(buffer: RID, offset: number, sizeBytes: number, data: PackedByteArray): number;
    public buffer_clear(buffer: RID, offset: number, sizeBytes: number): number;
    public buffer_get_data(buffer: RID, offsetBytes: number = 0, sizeBytes: number = 0): PackedByteArray;
    public buffer_get_data_async(buffer: RID, callback: Callable | Function, offsetBytes: number = 0, sizeBytes: number = 0): number;
    public buffer_get_device_address(buffer: RID): number;
    public render_pipeline_create(shader: RID, framebufferFormat: number, vertexFormat: number, primitive: number, rasterizationState: RDPipelineRasterizationState, multisampleState: RDPipelineMultisampleState, stencilState: RDPipelineDepthStencilState, colorBlendState: RDPipelineColorBlendState, dynamicStateFlags: number = 0, forRenderPass: number = 0, specializationConstants: Array<any> = Array[RDPipelineSpecializationConstant]([])): RID;
    public render_pipeline_is_valid(renderPipeline: RID): boolean;
    public compute_pipeline_create(shader: RID, specializationConstants: Array<any> = Array[RDPipelineSpecializationConstant]([])): RID;
    public compute_pipeline_is_valid(computePipeline: RID): boolean;
    public screen_get_width(screen: number = 0): number;
    public screen_get_height(screen: number = 0): number;
    public screen_get_framebuffer_format(screen: number = 0): number;
    public draw_list_begin_for_screen(screen: number = 0, clearColor: Color = Color(0, 0, 0, 1)): number;
    public draw_list_begin(framebuffer: RID, drawFlags: number = 0, clearColorValues: PackedColorArray = PackedColorArray(), clearDepthValue: number = 1.0, clearStencilValue: number = 0, region: Rect2 = Rect2(0, 0, 0, 0), breadcrumb: number = 0): number;
    public draw_list_begin_split(framebuffer: RID, splits: number, initialColorAction: number, finalColorAction: number, initialDepthAction: number, finalDepthAction: number, clearColorValues: PackedColorArray = PackedColorArray(), clearDepth: number = 1.0, clearStencil: number = 0, region: Rect2 = Rect2(0, 0, 0, 0), storageTextures: Array<any> = Array[RID]([])): PackedInt64Array;
    public draw_list_set_blend_constants(drawList: number, color: Color): void;
    public draw_list_bind_render_pipeline(drawList: number, renderPipeline: RID): void;
    public draw_list_bind_uniform_set(drawList: number, uniformSet: RID, setIndex: number): void;
    public draw_list_bind_vertex_array(drawList: number, vertexArray: RID): void;
    public draw_list_bind_index_array(drawList: number, indexArray: RID): void;
    public draw_list_set_push_constant(drawList: number, buffer: PackedByteArray, sizeBytes: number): void;
    public draw_list_draw(drawList: number, useIndices: boolean, instances: number, proceduralVertexCount: number = 0): void;
    public draw_list_draw_indirect(drawList: number, useIndices: boolean, buffer: RID, offset: number = 0, drawCount: number = 1, stride: number = 0): void;
    public draw_list_enable_scissor(drawList: number, rect: Rect2 = Rect2(0, 0, 0, 0)): void;
    public draw_list_disable_scissor(drawList: number): void;
    public draw_list_switch_to_next_pass(): number;
    public draw_list_switch_to_next_pass_split(splits: number): PackedInt64Array;
    public draw_list_end(): void;
    public compute_list_begin(): number;
    public compute_list_bind_compute_pipeline(computeList: number, computePipeline: RID): void;
    public compute_list_set_push_constant(computeList: number, buffer: PackedByteArray, sizeBytes: number): void;
    public compute_list_bind_uniform_set(computeList: number, uniformSet: RID, setIndex: number): void;
    public compute_list_dispatch(computeList: number, xGroups: number, yGroups: number, zGroups: number): void;
    public compute_list_dispatch_indirect(computeList: number, buffer: RID, offset: number): void;
    public compute_list_add_barrier(computeList: number): void;
    public compute_list_end(): void;
    public free_rid(rid: RID): void;
    public capture_timestamp(name: GDString | StringName | string): void;
    public get_captured_timestamps_count(): number;
    public get_captured_timestamps_frame(): number;
    public get_captured_timestamp_gpu_time(index: number): number;
    public get_captured_timestamp_cpu_time(index: number): number;
    public get_captured_timestamp_name(index: number): GDString;
    public has_feature(feature: number): boolean;
    public limit_get(limit: number): number;
    public get_frame_delay(): number;
    public submit(): void;
    public sync(): void;
    public barrier(_from: number = 32767, to: number = 32767): void;
    public full_barrier(): void;
    public create_local_device(): RenderingDevice;
    public set_resource_name(id: RID, name: GDString | StringName | string): void;
    public draw_command_begin_label(name: GDString | StringName | string, color: Color): void;
    public draw_command_insert_label(name: GDString | StringName | string, color: Color): void;
    public draw_command_end_label(): void;
    public get_device_vendor_name(): GDString;
    public get_device_name(): GDString;
    public get_device_pipeline_cache_uuid(): GDString;
    public get_memory_usage(_type: number): number;
    public get_driver_resource(resource: number, rid: RID, index: number): number;
    public get_perf_report(): GDString;
    public get_driver_and_device_memory_report(): GDString;
    public get_tracked_object_name(typeIndex: number): GDString;
    public get_tracked_object_type_count(): number;
    public get_driver_total_memory(): number;
    public get_driver_allocation_count(): number;
    public get_driver_memory_by_object_type(_type: number): number;
    public get_driver_allocs_by_object_type(_type: number): number;
    public get_device_total_memory(): number;
    public get_device_allocation_count(): number;
    public get_device_memory_by_object_type(_type: number): number;
    public get_device_allocs_by_object_type(_type: number): number;


    public static readonly DeviceType: {
        DEVICE_TYPE_OTHER: 0;
        DEVICE_TYPE_INTEGRATED_GPU: 1;
        DEVICE_TYPE_DISCRETE_GPU: 2;
        DEVICE_TYPE_VIRTUAL_GPU: 3;
        DEVICE_TYPE_CPU: 4;
        DEVICE_TYPE_MAX: 5;
    };
    public static readonly DriverResource: {
        DRIVER_RESOURCE_LOGICAL_DEVICE: 0;
        DRIVER_RESOURCE_PHYSICAL_DEVICE: 1;
        DRIVER_RESOURCE_TOPMOST_OBJECT: 2;
        DRIVER_RESOURCE_COMMAND_QUEUE: 3;
        DRIVER_RESOURCE_QUEUE_FAMILY: 4;
        DRIVER_RESOURCE_TEXTURE: 5;
        DRIVER_RESOURCE_TEXTURE_VIEW: 6;
        DRIVER_RESOURCE_TEXTURE_DATA_FORMAT: 7;
        DRIVER_RESOURCE_SAMPLER: 8;
        DRIVER_RESOURCE_UNIFORM_SET: 9;
        DRIVER_RESOURCE_BUFFER: 10;
        DRIVER_RESOURCE_COMPUTE_PIPELINE: 11;
        DRIVER_RESOURCE_RENDER_PIPELINE: 12;
        DRIVER_RESOURCE_VULKAN_DEVICE: 0;
        DRIVER_RESOURCE_VULKAN_PHYSICAL_DEVICE: 1;
        DRIVER_RESOURCE_VULKAN_INSTANCE: 2;
        DRIVER_RESOURCE_VULKAN_QUEUE: 3;
        DRIVER_RESOURCE_VULKAN_QUEUE_FAMILY_INDEX: 4;
        DRIVER_RESOURCE_VULKAN_IMAGE: 5;
        DRIVER_RESOURCE_VULKAN_IMAGE_VIEW: 6;
        DRIVER_RESOURCE_VULKAN_IMAGE_NATIVE_TEXTURE_FORMAT: 7;
        DRIVER_RESOURCE_VULKAN_SAMPLER: 8;
        DRIVER_RESOURCE_VULKAN_DESCRIPTOR_SET: 9;
        DRIVER_RESOURCE_VULKAN_BUFFER: 10;
        DRIVER_RESOURCE_VULKAN_COMPUTE_PIPELINE: 11;
        DRIVER_RESOURCE_VULKAN_RENDER_PIPELINE: 12;
    };
    public static readonly DataFormat: {
        DATA_FORMAT_R4G4_UNORM_PACK8: 0;
        DATA_FORMAT_R4G4B4A4_UNORM_PACK16: 1;
        DATA_FORMAT_B4G4R4A4_UNORM_PACK16: 2;
        DATA_FORMAT_R5G6B5_UNORM_PACK16: 3;
        DATA_FORMAT_B5G6R5_UNORM_PACK16: 4;
        DATA_FORMAT_R5G5B5A1_UNORM_PACK16: 5;
        DATA_FORMAT_B5G5R5A1_UNORM_PACK16: 6;
        DATA_FORMAT_A1R5G5B5_UNORM_PACK16: 7;
        DATA_FORMAT_R8_UNORM: 8;
        DATA_FORMAT_R8_SNORM: 9;
        DATA_FORMAT_R8_USCALED: 10;
        DATA_FORMAT_R8_SSCALED: 11;
        DATA_FORMAT_R8_UINT: 12;
        DATA_FORMAT_R8_SINT: 13;
        DATA_FORMAT_R8_SRGB: 14;
        DATA_FORMAT_R8G8_UNORM: 15;
        DATA_FORMAT_R8G8_SNORM: 16;
        DATA_FORMAT_R8G8_USCALED: 17;
        DATA_FORMAT_R8G8_SSCALED: 18;
        DATA_FORMAT_R8G8_UINT: 19;
        DATA_FORMAT_R8G8_SINT: 20;
        DATA_FORMAT_R8G8_SRGB: 21;
        DATA_FORMAT_R8G8B8_UNORM: 22;
        DATA_FORMAT_R8G8B8_SNORM: 23;
        DATA_FORMAT_R8G8B8_USCALED: 24;
        DATA_FORMAT_R8G8B8_SSCALED: 25;
        DATA_FORMAT_R8G8B8_UINT: 26;
        DATA_FORMAT_R8G8B8_SINT: 27;
        DATA_FORMAT_R8G8B8_SRGB: 28;
        DATA_FORMAT_B8G8R8_UNORM: 29;
        DATA_FORMAT_B8G8R8_SNORM: 30;
        DATA_FORMAT_B8G8R8_USCALED: 31;
        DATA_FORMAT_B8G8R8_SSCALED: 32;
        DATA_FORMAT_B8G8R8_UINT: 33;
        DATA_FORMAT_B8G8R8_SINT: 34;
        DATA_FORMAT_B8G8R8_SRGB: 35;
        DATA_FORMAT_R8G8B8A8_UNORM: 36;
        DATA_FORMAT_R8G8B8A8_SNORM: 37;
        DATA_FORMAT_R8G8B8A8_USCALED: 38;
        DATA_FORMAT_R8G8B8A8_SSCALED: 39;
        DATA_FORMAT_R8G8B8A8_UINT: 40;
        DATA_FORMAT_R8G8B8A8_SINT: 41;
        DATA_FORMAT_R8G8B8A8_SRGB: 42;
        DATA_FORMAT_B8G8R8A8_UNORM: 43;
        DATA_FORMAT_B8G8R8A8_SNORM: 44;
        DATA_FORMAT_B8G8R8A8_USCALED: 45;
        DATA_FORMAT_B8G8R8A8_SSCALED: 46;
        DATA_FORMAT_B8G8R8A8_UINT: 47;
        DATA_FORMAT_B8G8R8A8_SINT: 48;
        DATA_FORMAT_B8G8R8A8_SRGB: 49;
        DATA_FORMAT_A8B8G8R8_UNORM_PACK32: 50;
        DATA_FORMAT_A8B8G8R8_SNORM_PACK32: 51;
        DATA_FORMAT_A8B8G8R8_USCALED_PACK32: 52;
        DATA_FORMAT_A8B8G8R8_SSCALED_PACK32: 53;
        DATA_FORMAT_A8B8G8R8_UINT_PACK32: 54;
        DATA_FORMAT_A8B8G8R8_SINT_PACK32: 55;
        DATA_FORMAT_A8B8G8R8_SRGB_PACK32: 56;
        DATA_FORMAT_A2R10G10B10_UNORM_PACK32: 57;
        DATA_FORMAT_A2R10G10B10_SNORM_PACK32: 58;
        DATA_FORMAT_A2R10G10B10_USCALED_PACK32: 59;
        DATA_FORMAT_A2R10G10B10_SSCALED_PACK32: 60;
        DATA_FORMAT_A2R10G10B10_UINT_PACK32: 61;
        DATA_FORMAT_A2R10G10B10_SINT_PACK32: 62;
        DATA_FORMAT_A2B10G10R10_UNORM_PACK32: 63;
        DATA_FORMAT_A2B10G10R10_SNORM_PACK32: 64;
        DATA_FORMAT_A2B10G10R10_USCALED_PACK32: 65;
        DATA_FORMAT_A2B10G10R10_SSCALED_PACK32: 66;
        DATA_FORMAT_A2B10G10R10_UINT_PACK32: 67;
        DATA_FORMAT_A2B10G10R10_SINT_PACK32: 68;
        DATA_FORMAT_R16_UNORM: 69;
        DATA_FORMAT_R16_SNORM: 70;
        DATA_FORMAT_R16_USCALED: 71;
        DATA_FORMAT_R16_SSCALED: 72;
        DATA_FORMAT_R16_UINT: 73;
        DATA_FORMAT_R16_SINT: 74;
        DATA_FORMAT_R16_SFLOAT: 75;
        DATA_FORMAT_R16G16_UNORM: 76;
        DATA_FORMAT_R16G16_SNORM: 77;
        DATA_FORMAT_R16G16_USCALED: 78;
        DATA_FORMAT_R16G16_SSCALED: 79;
        DATA_FORMAT_R16G16_UINT: 80;
        DATA_FORMAT_R16G16_SINT: 81;
        DATA_FORMAT_R16G16_SFLOAT: 82;
        DATA_FORMAT_R16G16B16_UNORM: 83;
        DATA_FORMAT_R16G16B16_SNORM: 84;
        DATA_FORMAT_R16G16B16_USCALED: 85;
        DATA_FORMAT_R16G16B16_SSCALED: 86;
        DATA_FORMAT_R16G16B16_UINT: 87;
        DATA_FORMAT_R16G16B16_SINT: 88;
        DATA_FORMAT_R16G16B16_SFLOAT: 89;
        DATA_FORMAT_R16G16B16A16_UNORM: 90;
        DATA_FORMAT_R16G16B16A16_SNORM: 91;
        DATA_FORMAT_R16G16B16A16_USCALED: 92;
        DATA_FORMAT_R16G16B16A16_SSCALED: 93;
        DATA_FORMAT_R16G16B16A16_UINT: 94;
        DATA_FORMAT_R16G16B16A16_SINT: 95;
        DATA_FORMAT_R16G16B16A16_SFLOAT: 96;
        DATA_FORMAT_R32_UINT: 97;
        DATA_FORMAT_R32_SINT: 98;
        DATA_FORMAT_R32_SFLOAT: 99;
        DATA_FORMAT_R32G32_UINT: 100;
        DATA_FORMAT_R32G32_SINT: 101;
        DATA_FORMAT_R32G32_SFLOAT: 102;
        DATA_FORMAT_R32G32B32_UINT: 103;
        DATA_FORMAT_R32G32B32_SINT: 104;
        DATA_FORMAT_R32G32B32_SFLOAT: 105;
        DATA_FORMAT_R32G32B32A32_UINT: 106;
        DATA_FORMAT_R32G32B32A32_SINT: 107;
        DATA_FORMAT_R32G32B32A32_SFLOAT: 108;
        DATA_FORMAT_R64_UINT: 109;
        DATA_FORMAT_R64_SINT: 110;
        DATA_FORMAT_R64_SFLOAT: 111;
        DATA_FORMAT_R64G64_UINT: 112;
        DATA_FORMAT_R64G64_SINT: 113;
        DATA_FORMAT_R64G64_SFLOAT: 114;
        DATA_FORMAT_R64G64B64_UINT: 115;
        DATA_FORMAT_R64G64B64_SINT: 116;
        DATA_FORMAT_R64G64B64_SFLOAT: 117;
        DATA_FORMAT_R64G64B64A64_UINT: 118;
        DATA_FORMAT_R64G64B64A64_SINT: 119;
        DATA_FORMAT_R64G64B64A64_SFLOAT: 120;
        DATA_FORMAT_B10G11R11_UFLOAT_PACK32: 121;
        DATA_FORMAT_E5B9G9R9_UFLOAT_PACK32: 122;
        DATA_FORMAT_D16_UNORM: 123;
        DATA_FORMAT_X8_D24_UNORM_PACK32: 124;
        DATA_FORMAT_D32_SFLOAT: 125;
        DATA_FORMAT_S8_UINT: 126;
        DATA_FORMAT_D16_UNORM_S8_UINT: 127;
        DATA_FORMAT_D24_UNORM_S8_UINT: 128;
        DATA_FORMAT_D32_SFLOAT_S8_UINT: 129;
        DATA_FORMAT_BC1_RGB_UNORM_BLOCK: 130;
        DATA_FORMAT_BC1_RGB_SRGB_BLOCK: 131;
        DATA_FORMAT_BC1_RGBA_UNORM_BLOCK: 132;
        DATA_FORMAT_BC1_RGBA_SRGB_BLOCK: 133;
        DATA_FORMAT_BC2_UNORM_BLOCK: 134;
        DATA_FORMAT_BC2_SRGB_BLOCK: 135;
        DATA_FORMAT_BC3_UNORM_BLOCK: 136;
        DATA_FORMAT_BC3_SRGB_BLOCK: 137;
        DATA_FORMAT_BC4_UNORM_BLOCK: 138;
        DATA_FORMAT_BC4_SNORM_BLOCK: 139;
        DATA_FORMAT_BC5_UNORM_BLOCK: 140;
        DATA_FORMAT_BC5_SNORM_BLOCK: 141;
        DATA_FORMAT_BC6H_UFLOAT_BLOCK: 142;
        DATA_FORMAT_BC6H_SFLOAT_BLOCK: 143;
        DATA_FORMAT_BC7_UNORM_BLOCK: 144;
        DATA_FORMAT_BC7_SRGB_BLOCK: 145;
        DATA_FORMAT_ETC2_R8G8B8_UNORM_BLOCK: 146;
        DATA_FORMAT_ETC2_R8G8B8_SRGB_BLOCK: 147;
        DATA_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK: 148;
        DATA_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK: 149;
        DATA_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK: 150;
        DATA_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK: 151;
        DATA_FORMAT_EAC_R11_UNORM_BLOCK: 152;
        DATA_FORMAT_EAC_R11_SNORM_BLOCK: 153;
        DATA_FORMAT_EAC_R11G11_UNORM_BLOCK: 154;
        DATA_FORMAT_EAC_R11G11_SNORM_BLOCK: 155;
        DATA_FORMAT_ASTC_4x4_UNORM_BLOCK: 156;
        DATA_FORMAT_ASTC_4x4_SRGB_BLOCK: 157;
        DATA_FORMAT_ASTC_5x4_UNORM_BLOCK: 158;
        DATA_FORMAT_ASTC_5x4_SRGB_BLOCK: 159;
        DATA_FORMAT_ASTC_5x5_UNORM_BLOCK: 160;
        DATA_FORMAT_ASTC_5x5_SRGB_BLOCK: 161;
        DATA_FORMAT_ASTC_6x5_UNORM_BLOCK: 162;
        DATA_FORMAT_ASTC_6x5_SRGB_BLOCK: 163;
        DATA_FORMAT_ASTC_6x6_UNORM_BLOCK: 164;
        DATA_FORMAT_ASTC_6x6_SRGB_BLOCK: 165;
        DATA_FORMAT_ASTC_8x5_UNORM_BLOCK: 166;
        DATA_FORMAT_ASTC_8x5_SRGB_BLOCK: 167;
        DATA_FORMAT_ASTC_8x6_UNORM_BLOCK: 168;
        DATA_FORMAT_ASTC_8x6_SRGB_BLOCK: 169;
        DATA_FORMAT_ASTC_8x8_UNORM_BLOCK: 170;
        DATA_FORMAT_ASTC_8x8_SRGB_BLOCK: 171;
        DATA_FORMAT_ASTC_10x5_UNORM_BLOCK: 172;
        DATA_FORMAT_ASTC_10x5_SRGB_BLOCK: 173;
        DATA_FORMAT_ASTC_10x6_UNORM_BLOCK: 174;
        DATA_FORMAT_ASTC_10x6_SRGB_BLOCK: 175;
        DATA_FORMAT_ASTC_10x8_UNORM_BLOCK: 176;
        DATA_FORMAT_ASTC_10x8_SRGB_BLOCK: 177;
        DATA_FORMAT_ASTC_10x10_UNORM_BLOCK: 178;
        DATA_FORMAT_ASTC_10x10_SRGB_BLOCK: 179;
        DATA_FORMAT_ASTC_12x10_UNORM_BLOCK: 180;
        DATA_FORMAT_ASTC_12x10_SRGB_BLOCK: 181;
        DATA_FORMAT_ASTC_12x12_UNORM_BLOCK: 182;
        DATA_FORMAT_ASTC_12x12_SRGB_BLOCK: 183;
        DATA_FORMAT_G8B8G8R8_422_UNORM: 184;
        DATA_FORMAT_B8G8R8G8_422_UNORM: 185;
        DATA_FORMAT_G8_B8_R8_3PLANE_420_UNORM: 186;
        DATA_FORMAT_G8_B8R8_2PLANE_420_UNORM: 187;
        DATA_FORMAT_G8_B8_R8_3PLANE_422_UNORM: 188;
        DATA_FORMAT_G8_B8R8_2PLANE_422_UNORM: 189;
        DATA_FORMAT_G8_B8_R8_3PLANE_444_UNORM: 190;
        DATA_FORMAT_R10X6_UNORM_PACK16: 191;
        DATA_FORMAT_R10X6G10X6_UNORM_2PACK16: 192;
        DATA_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16: 193;
        DATA_FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16: 194;
        DATA_FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16: 195;
        DATA_FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16: 196;
        DATA_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16: 197;
        DATA_FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16: 198;
        DATA_FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16: 199;
        DATA_FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16: 200;
        DATA_FORMAT_R12X4_UNORM_PACK16: 201;
        DATA_FORMAT_R12X4G12X4_UNORM_2PACK16: 202;
        DATA_FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16: 203;
        DATA_FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16: 204;
        DATA_FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16: 205;
        DATA_FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16: 206;
        DATA_FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16: 207;
        DATA_FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16: 208;
        DATA_FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16: 209;
        DATA_FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16: 210;
        DATA_FORMAT_G16B16G16R16_422_UNORM: 211;
        DATA_FORMAT_B16G16R16G16_422_UNORM: 212;
        DATA_FORMAT_G16_B16_R16_3PLANE_420_UNORM: 213;
        DATA_FORMAT_G16_B16R16_2PLANE_420_UNORM: 214;
        DATA_FORMAT_G16_B16_R16_3PLANE_422_UNORM: 215;
        DATA_FORMAT_G16_B16R16_2PLANE_422_UNORM: 216;
        DATA_FORMAT_G16_B16_R16_3PLANE_444_UNORM: 217;
        DATA_FORMAT_ASTC_4x4_SFLOAT_BLOCK: 218;
        DATA_FORMAT_ASTC_5x4_SFLOAT_BLOCK: 219;
        DATA_FORMAT_ASTC_5x5_SFLOAT_BLOCK: 220;
        DATA_FORMAT_ASTC_6x5_SFLOAT_BLOCK: 221;
        DATA_FORMAT_ASTC_6x6_SFLOAT_BLOCK: 222;
        DATA_FORMAT_ASTC_8x5_SFLOAT_BLOCK: 223;
        DATA_FORMAT_ASTC_8x6_SFLOAT_BLOCK: 224;
        DATA_FORMAT_ASTC_8x8_SFLOAT_BLOCK: 225;
        DATA_FORMAT_ASTC_10x5_SFLOAT_BLOCK: 226;
        DATA_FORMAT_ASTC_10x6_SFLOAT_BLOCK: 227;
        DATA_FORMAT_ASTC_10x8_SFLOAT_BLOCK: 228;
        DATA_FORMAT_ASTC_10x10_SFLOAT_BLOCK: 229;
        DATA_FORMAT_ASTC_12x10_SFLOAT_BLOCK: 230;
        DATA_FORMAT_ASTC_12x12_SFLOAT_BLOCK: 231;
        DATA_FORMAT_MAX: 232;
    };
    public static readonly BarrierMask: {
        BARRIER_MASK_VERTEX: 1;
        BARRIER_MASK_FRAGMENT: 8;
        BARRIER_MASK_COMPUTE: 2;
        BARRIER_MASK_TRANSFER: 4;
        BARRIER_MASK_RASTER: 9;
        BARRIER_MASK_ALL_BARRIERS: 32767;
        BARRIER_MASK_NO_BARRIER: 32768;
    };
    public static readonly TextureType: {
        TEXTURE_TYPE_1D: 0;
        TEXTURE_TYPE_2D: 1;
        TEXTURE_TYPE_3D: 2;
        TEXTURE_TYPE_CUBE: 3;
        TEXTURE_TYPE_1D_ARRAY: 4;
        TEXTURE_TYPE_2D_ARRAY: 5;
        TEXTURE_TYPE_CUBE_ARRAY: 6;
        TEXTURE_TYPE_MAX: 7;
    };
    public static readonly TextureSamples: {
        TEXTURE_SAMPLES_1: 0;
        TEXTURE_SAMPLES_2: 1;
        TEXTURE_SAMPLES_4: 2;
        TEXTURE_SAMPLES_8: 3;
        TEXTURE_SAMPLES_16: 4;
        TEXTURE_SAMPLES_32: 5;
        TEXTURE_SAMPLES_64: 6;
        TEXTURE_SAMPLES_MAX: 7;
    };
    public static readonly TextureUsageBits: {
        TEXTURE_USAGE_SAMPLING_BIT: 1;
        TEXTURE_USAGE_COLOR_ATTACHMENT_BIT: 2;
        TEXTURE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT: 4;
        TEXTURE_USAGE_STORAGE_BIT: 8;
        TEXTURE_USAGE_STORAGE_ATOMIC_BIT: 16;
        TEXTURE_USAGE_CPU_READ_BIT: 32;
        TEXTURE_USAGE_CAN_UPDATE_BIT: 64;
        TEXTURE_USAGE_CAN_COPY_FROM_BIT: 128;
        TEXTURE_USAGE_CAN_COPY_TO_BIT: 256;
        TEXTURE_USAGE_INPUT_ATTACHMENT_BIT: 512;
    };
    public static readonly TextureSwizzle: {
        TEXTURE_SWIZZLE_IDENTITY: 0;
        TEXTURE_SWIZZLE_ZERO: 1;
        TEXTURE_SWIZZLE_ONE: 2;
        TEXTURE_SWIZZLE_R: 3;
        TEXTURE_SWIZZLE_G: 4;
        TEXTURE_SWIZZLE_B: 5;
        TEXTURE_SWIZZLE_A: 6;
        TEXTURE_SWIZZLE_MAX: 7;
    };
    public static readonly TextureSliceType: {
        TEXTURE_SLICE_2D: 0;
        TEXTURE_SLICE_CUBEMAP: 1;
        TEXTURE_SLICE_3D: 2;
    };
    public static readonly SamplerFilter: {
        SAMPLER_FILTER_NEAREST: 0;
        SAMPLER_FILTER_LINEAR: 1;
    };
    public static readonly SamplerRepeatMode: {
        SAMPLER_REPEAT_MODE_REPEAT: 0;
        SAMPLER_REPEAT_MODE_MIRRORED_REPEAT: 1;
        SAMPLER_REPEAT_MODE_CLAMP_TO_EDGE: 2;
        SAMPLER_REPEAT_MODE_CLAMP_TO_BORDER: 3;
        SAMPLER_REPEAT_MODE_MIRROR_CLAMP_TO_EDGE: 4;
        SAMPLER_REPEAT_MODE_MAX: 5;
    };
    public static readonly SamplerBorderColor: {
        SAMPLER_BORDER_COLOR_FLOAT_TRANSPARENT_BLACK: 0;
        SAMPLER_BORDER_COLOR_INT_TRANSPARENT_BLACK: 1;
        SAMPLER_BORDER_COLOR_FLOAT_OPAQUE_BLACK: 2;
        SAMPLER_BORDER_COLOR_INT_OPAQUE_BLACK: 3;
        SAMPLER_BORDER_COLOR_FLOAT_OPAQUE_WHITE: 4;
        SAMPLER_BORDER_COLOR_INT_OPAQUE_WHITE: 5;
        SAMPLER_BORDER_COLOR_MAX: 6;
    };
    public static readonly VertexFrequency: {
        VERTEX_FREQUENCY_VERTEX: 0;
        VERTEX_FREQUENCY_INSTANCE: 1;
    };
    public static readonly IndexBufferFormat: {
        INDEX_BUFFER_FORMAT_UINT16: 0;
        INDEX_BUFFER_FORMAT_UINT32: 1;
    };
    public static readonly StorageBufferUsage: {
        STORAGE_BUFFER_USAGE_DISPATCH_INDIRECT: 1;
    };
    public static readonly BufferCreationBits: {
        BUFFER_CREATION_DEVICE_ADDRESS_BIT: 1;
        BUFFER_CREATION_AS_STORAGE_BIT: 2;
    };
    public static readonly UniformType: {
        UNIFORM_TYPE_SAMPLER: 0;
        UNIFORM_TYPE_SAMPLER_WITH_TEXTURE: 1;
        UNIFORM_TYPE_TEXTURE: 2;
        UNIFORM_TYPE_IMAGE: 3;
        UNIFORM_TYPE_TEXTURE_BUFFER: 4;
        UNIFORM_TYPE_SAMPLER_WITH_TEXTURE_BUFFER: 5;
        UNIFORM_TYPE_IMAGE_BUFFER: 6;
        UNIFORM_TYPE_UNIFORM_BUFFER: 7;
        UNIFORM_TYPE_STORAGE_BUFFER: 8;
        UNIFORM_TYPE_INPUT_ATTACHMENT: 9;
        UNIFORM_TYPE_MAX: 10;
    };
    public static readonly RenderPrimitive: {
        RENDER_PRIMITIVE_POINTS: 0;
        RENDER_PRIMITIVE_LINES: 1;
        RENDER_PRIMITIVE_LINES_WITH_ADJACENCY: 2;
        RENDER_PRIMITIVE_LINESTRIPS: 3;
        RENDER_PRIMITIVE_LINESTRIPS_WITH_ADJACENCY: 4;
        RENDER_PRIMITIVE_TRIANGLES: 5;
        RENDER_PRIMITIVE_TRIANGLES_WITH_ADJACENCY: 6;
        RENDER_PRIMITIVE_TRIANGLE_STRIPS: 7;
        RENDER_PRIMITIVE_TRIANGLE_STRIPS_WITH_AJACENCY: 8;
        RENDER_PRIMITIVE_TRIANGLE_STRIPS_WITH_RESTART_INDEX: 9;
        RENDER_PRIMITIVE_TESSELATION_PATCH: 10;
        RENDER_PRIMITIVE_MAX: 11;
    };
    public static readonly PolygonCullMode: {
        POLYGON_CULL_DISABLED: 0;
        POLYGON_CULL_FRONT: 1;
        POLYGON_CULL_BACK: 2;
    };
    public static readonly PolygonFrontFace: {
        POLYGON_FRONT_FACE_CLOCKWISE: 0;
        POLYGON_FRONT_FACE_COUNTER_CLOCKWISE: 1;
    };
    public static readonly StencilOperation: {
        STENCIL_OP_KEEP: 0;
        STENCIL_OP_ZERO: 1;
        STENCIL_OP_REPLACE: 2;
        STENCIL_OP_INCREMENT_AND_CLAMP: 3;
        STENCIL_OP_DECREMENT_AND_CLAMP: 4;
        STENCIL_OP_INVERT: 5;
        STENCIL_OP_INCREMENT_AND_WRAP: 6;
        STENCIL_OP_DECREMENT_AND_WRAP: 7;
        STENCIL_OP_MAX: 8;
    };
    public static readonly CompareOperator: {
        COMPARE_OP_NEVER: 0;
        COMPARE_OP_LESS: 1;
        COMPARE_OP_EQUAL: 2;
        COMPARE_OP_LESS_OR_EQUAL: 3;
        COMPARE_OP_GREATER: 4;
        COMPARE_OP_NOT_EQUAL: 5;
        COMPARE_OP_GREATER_OR_EQUAL: 6;
        COMPARE_OP_ALWAYS: 7;
        COMPARE_OP_MAX: 8;
    };
    public static readonly LogicOperation: {
        LOGIC_OP_CLEAR: 0;
        LOGIC_OP_AND: 1;
        LOGIC_OP_AND_REVERSE: 2;
        LOGIC_OP_COPY: 3;
        LOGIC_OP_AND_INVERTED: 4;
        LOGIC_OP_NO_OP: 5;
        LOGIC_OP_XOR: 6;
        LOGIC_OP_OR: 7;
        LOGIC_OP_NOR: 8;
        LOGIC_OP_EQUIVALENT: 9;
        LOGIC_OP_INVERT: 10;
        LOGIC_OP_OR_REVERSE: 11;
        LOGIC_OP_COPY_INVERTED: 12;
        LOGIC_OP_OR_INVERTED: 13;
        LOGIC_OP_NAND: 14;
        LOGIC_OP_SET: 15;
        LOGIC_OP_MAX: 16;
    };
    public static readonly BlendFactor: {
        BLEND_FACTOR_ZERO: 0;
        BLEND_FACTOR_ONE: 1;
        BLEND_FACTOR_SRC_COLOR: 2;
        BLEND_FACTOR_ONE_MINUS_SRC_COLOR: 3;
        BLEND_FACTOR_DST_COLOR: 4;
        BLEND_FACTOR_ONE_MINUS_DST_COLOR: 5;
        BLEND_FACTOR_SRC_ALPHA: 6;
        BLEND_FACTOR_ONE_MINUS_SRC_ALPHA: 7;
        BLEND_FACTOR_DST_ALPHA: 8;
        BLEND_FACTOR_ONE_MINUS_DST_ALPHA: 9;
        BLEND_FACTOR_CONSTANT_COLOR: 10;
        BLEND_FACTOR_ONE_MINUS_CONSTANT_COLOR: 11;
        BLEND_FACTOR_CONSTANT_ALPHA: 12;
        BLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHA: 13;
        BLEND_FACTOR_SRC_ALPHA_SATURATE: 14;
        BLEND_FACTOR_SRC1_COLOR: 15;
        BLEND_FACTOR_ONE_MINUS_SRC1_COLOR: 16;
        BLEND_FACTOR_SRC1_ALPHA: 17;
        BLEND_FACTOR_ONE_MINUS_SRC1_ALPHA: 18;
        BLEND_FACTOR_MAX: 19;
    };
    public static readonly BlendOperation: {
        BLEND_OP_ADD: 0;
        BLEND_OP_SUBTRACT: 1;
        BLEND_OP_REVERSE_SUBTRACT: 2;
        BLEND_OP_MINIMUM: 3;
        BLEND_OP_MAXIMUM: 4;
        BLEND_OP_MAX: 5;
    };
    public static readonly PipelineDynamicStateFlags: {
        DYNAMIC_STATE_LINE_WIDTH: 1;
        DYNAMIC_STATE_DEPTH_BIAS: 2;
        DYNAMIC_STATE_BLEND_CONSTANTS: 4;
        DYNAMIC_STATE_DEPTH_BOUNDS: 8;
        DYNAMIC_STATE_STENCIL_COMPARE_MASK: 16;
        DYNAMIC_STATE_STENCIL_WRITE_MASK: 32;
        DYNAMIC_STATE_STENCIL_REFERENCE: 64;
    };
    public static readonly InitialAction: {
        INITIAL_ACTION_LOAD: 0;
        INITIAL_ACTION_CLEAR: 1;
        INITIAL_ACTION_DISCARD: 2;
        INITIAL_ACTION_MAX: 3;
        INITIAL_ACTION_CLEAR_REGION: 1;
        INITIAL_ACTION_CLEAR_REGION_CONTINUE: 1;
        INITIAL_ACTION_KEEP: 0;
        INITIAL_ACTION_DROP: 2;
        INITIAL_ACTION_CONTINUE: 0;
    };
    public static readonly FinalAction: {
        FINAL_ACTION_STORE: 0;
        FINAL_ACTION_DISCARD: 1;
        FINAL_ACTION_MAX: 2;
        FINAL_ACTION_READ: 0;
        FINAL_ACTION_CONTINUE: 0;
    };
    public static readonly ShaderStage: {
        SHADER_STAGE_VERTEX: 0;
        SHADER_STAGE_FRAGMENT: 1;
        SHADER_STAGE_TESSELATION_CONTROL: 2;
        SHADER_STAGE_TESSELATION_EVALUATION: 3;
        SHADER_STAGE_COMPUTE: 4;
        SHADER_STAGE_MAX: 5;
        SHADER_STAGE_VERTEX_BIT: 1;
        SHADER_STAGE_FRAGMENT_BIT: 2;
        SHADER_STAGE_TESSELATION_CONTROL_BIT: 4;
        SHADER_STAGE_TESSELATION_EVALUATION_BIT: 8;
        SHADER_STAGE_COMPUTE_BIT: 16;
    };
    public static readonly ShaderLanguage: {
        SHADER_LANGUAGE_GLSL: 0;
        SHADER_LANGUAGE_HLSL: 1;
    };
    public static readonly PipelineSpecializationConstantType: {
        PIPELINE_SPECIALIZATION_CONSTANT_TYPE_BOOL: 0;
        PIPELINE_SPECIALIZATION_CONSTANT_TYPE_INT: 1;
        PIPELINE_SPECIALIZATION_CONSTANT_TYPE_FLOAT: 2;
    };
    public static readonly Features: {
        SUPPORTS_METALFX_SPATIAL: 3;
        SUPPORTS_METALFX_TEMPORAL: 4;
        SUPPORTS_BUFFER_DEVICE_ADDRESS: 6;
        SUPPORTS_IMAGE_ATOMIC_32_BIT: 7;
    };
    public static readonly Limit: {
        LIMIT_MAX_BOUND_UNIFORM_SETS: 0;
        LIMIT_MAX_FRAMEBUFFER_COLOR_ATTACHMENTS: 1;
        LIMIT_MAX_TEXTURES_PER_UNIFORM_SET: 2;
        LIMIT_MAX_SAMPLERS_PER_UNIFORM_SET: 3;
        LIMIT_MAX_STORAGE_BUFFERS_PER_UNIFORM_SET: 4;
        LIMIT_MAX_STORAGE_IMAGES_PER_UNIFORM_SET: 5;
        LIMIT_MAX_UNIFORM_BUFFERS_PER_UNIFORM_SET: 6;
        LIMIT_MAX_DRAW_INDEXED_INDEX: 7;
        LIMIT_MAX_FRAMEBUFFER_HEIGHT: 8;
        LIMIT_MAX_FRAMEBUFFER_WIDTH: 9;
        LIMIT_MAX_TEXTURE_ARRAY_LAYERS: 10;
        LIMIT_MAX_TEXTURE_SIZE_1D: 11;
        LIMIT_MAX_TEXTURE_SIZE_2D: 12;
        LIMIT_MAX_TEXTURE_SIZE_3D: 13;
        LIMIT_MAX_TEXTURE_SIZE_CUBE: 14;
        LIMIT_MAX_TEXTURES_PER_SHADER_STAGE: 15;
        LIMIT_MAX_SAMPLERS_PER_SHADER_STAGE: 16;
        LIMIT_MAX_STORAGE_BUFFERS_PER_SHADER_STAGE: 17;
        LIMIT_MAX_STORAGE_IMAGES_PER_SHADER_STAGE: 18;
        LIMIT_MAX_UNIFORM_BUFFERS_PER_SHADER_STAGE: 19;
        LIMIT_MAX_PUSH_CONSTANT_SIZE: 20;
        LIMIT_MAX_UNIFORM_BUFFER_SIZE: 21;
        LIMIT_MAX_VERTEX_INPUT_ATTRIBUTE_OFFSET: 22;
        LIMIT_MAX_VERTEX_INPUT_ATTRIBUTES: 23;
        LIMIT_MAX_VERTEX_INPUT_BINDINGS: 24;
        LIMIT_MAX_VERTEX_INPUT_BINDING_STRIDE: 25;
        LIMIT_MIN_UNIFORM_BUFFER_OFFSET_ALIGNMENT: 26;
        LIMIT_MAX_COMPUTE_SHARED_MEMORY_SIZE: 27;
        LIMIT_MAX_COMPUTE_WORKGROUP_COUNT_X: 28;
        LIMIT_MAX_COMPUTE_WORKGROUP_COUNT_Y: 29;
        LIMIT_MAX_COMPUTE_WORKGROUP_COUNT_Z: 30;
        LIMIT_MAX_COMPUTE_WORKGROUP_INVOCATIONS: 31;
        LIMIT_MAX_COMPUTE_WORKGROUP_SIZE_X: 32;
        LIMIT_MAX_COMPUTE_WORKGROUP_SIZE_Y: 33;
        LIMIT_MAX_COMPUTE_WORKGROUP_SIZE_Z: 34;
        LIMIT_MAX_VIEWPORT_DIMENSIONS_X: 35;
        LIMIT_MAX_VIEWPORT_DIMENSIONS_Y: 36;
        LIMIT_METALFX_TEMPORAL_SCALER_MIN_SCALE: 46;
        LIMIT_METALFX_TEMPORAL_SCALER_MAX_SCALE: 47;
    };
    public static readonly MemoryType: {
        MEMORY_TEXTURES: 0;
        MEMORY_BUFFERS: 1;
        MEMORY_TOTAL: 2;
    };
    public static readonly BreadcrumbMarker: {
        NONE: 0;
        REFLECTION_PROBES: 65536;
        SKY_PASS: 131072;
        LIGHTMAPPER_PASS: 196608;
        SHADOW_PASS_DIRECTIONAL: 262144;
        SHADOW_PASS_CUBE: 327680;
        OPAQUE_PASS: 393216;
        ALPHA_PASS: 458752;
        TRANSPARENT_PASS: 524288;
        POST_PROCESSING_PASS: 589824;
        BLIT_PASS: 655360;
        UI_PASS: 720896;
        DEBUG_PASS: 786432;
    };
    public static readonly DrawFlags: {
        DRAW_DEFAULT_ALL: 0;
        DRAW_CLEAR_COLOR_0: 1;
        DRAW_CLEAR_COLOR_1: 2;
        DRAW_CLEAR_COLOR_2: 4;
        DRAW_CLEAR_COLOR_3: 8;
        DRAW_CLEAR_COLOR_4: 16;
        DRAW_CLEAR_COLOR_5: 32;
        DRAW_CLEAR_COLOR_6: 64;
        DRAW_CLEAR_COLOR_7: 128;
        DRAW_CLEAR_COLOR_MASK: 255;
        DRAW_CLEAR_COLOR_ALL: 255;
        DRAW_IGNORE_COLOR_0: 256;
        DRAW_IGNORE_COLOR_1: 512;
        DRAW_IGNORE_COLOR_2: 1024;
        DRAW_IGNORE_COLOR_3: 2048;
        DRAW_IGNORE_COLOR_4: 4096;
        DRAW_IGNORE_COLOR_5: 8192;
        DRAW_IGNORE_COLOR_6: 16384;
        DRAW_IGNORE_COLOR_7: 32768;
        DRAW_IGNORE_COLOR_MASK: 65280;
        DRAW_IGNORE_COLOR_ALL: 65280;
        DRAW_CLEAR_DEPTH: 65536;
        DRAW_IGNORE_DEPTH: 131072;
        DRAW_CLEAR_STENCIL: 262144;
        DRAW_IGNORE_STENCIL: 524288;
        DRAW_CLEAR_ALL: 327935;
        DRAW_IGNORE_ALL: 720640;
    };
}

