
import { MultiplayerAPI } from "@godot/classes/multiplayer_api";
export declare class SceneMultiplayer extends MultiplayerAPI{
  public set_root_path(_path: GDString | NodePath | string): void;
  public get_root_path(): NodePath;
  public clear(): void;
  public disconnect_peer(_id: number): void;
  public get_authenticating_peers(): PackedInt32Array;
  public send_auth(_id: number, _data: PackedByteArray): number;
  public complete_auth(_id: number): number;
  public set_auth_callback(_callback: Callable): void;
  public get_auth_callback(): Callable;
  public set_auth_timeout(_timeout: number): void;
  public get_auth_timeout(): number;
  public set_refuse_new_connections(_refuse: boolean): void;
  public is_refusing_new_connections(): boolean;
  public set_allow_object_decoding(_enable: boolean): void;
  public is_object_decoding_allowed(): boolean;
  public set_server_relay_enabled(_enabled: boolean): void;
  public is_server_relay_enabled(): boolean;
  public send_bytes(_bytes: PackedByteArray, _id: number = 0, _mode: number = 2, _channel: number = 0): number;
  public get_max_sync_packet_size(): number;
  public set_max_sync_packet_size(_size: number): void;
  public get_max_delta_packet_size(): number;
  public set_max_delta_packet_size(_size: number): void;
  public get root_path(): NodePath;
  public set root_path(value): void;
  public get auth_callback(): Callable;
  public set auth_callback(value): void;
  public get auth_timeout(): number;
  public set auth_timeout(value): void;
  public get allow_object_decoding(): boolean;
  public set allow_object_decoding(value): void;
  public get refuse_new_connections(): boolean;
  public set refuse_new_connections(value): void;
  public get server_relay(): boolean;
  public set server_relay(value): void;
  public get max_sync_packet_size(): number;
  public set max_sync_packet_size(value): void;
  public get max_delta_packet_size(): number;
  public set max_delta_packet_size(value): void;
  public get peer_authenticating(): Signal;
  public get peer_authentication_failed(): Signal;
  public get peer_packet(): Signal;
}