
import { Skeleton3D } from "@godot/classes/skeleton3d";
import { SkeletonModifier3D } from "@godot/classes/skeleton_modifier3d";
export declare class SkeletonIK3D extends SkeletonModifier3D{
  public set_root_bone(_root_bone: GDString | StringName | string): void;
  public get_root_bone(): StringName;
  public set_tip_bone(_tip_bone: GDString | StringName | string): void;
  public get_tip_bone(): StringName;
  public set_target_transform(_target: Transform3D): void;
  public get_target_transform(): Transform3D;
  public set_target_node(_node: GDString | NodePath | string): void;
  public get_target_node(): NodePath;
  public set_override_tip_basis(_override: boolean): void;
  public is_override_tip_basis(): boolean;
  public set_use_magnet(_use: boolean): void;
  public is_using_magnet(): boolean;
  public set_magnet_position(_local_position: Vector3): void;
  public get_magnet_position(): Vector3;
  public get_parent_skeleton(): Skeleton3D;
  public is_running(): boolean;
  public set_min_distance(_min_distance: number): void;
  public get_min_distance(): number;
  public set_max_iterations(_iterations: number): void;
  public get_max_iterations(): number;
  public start(_one_time: boolean = false): void;
  public stop(): void;
  public set_interpolation(_interpolation: number): void;
  public get_interpolation(): number;
  public get root_bone(): StringName;
  public set root_bone(value): void;
  public get tip_bone(): StringName;
  public set tip_bone(value): void;
  public get target(): Transform3D;
  public set target(value): void;
  public get override_tip_basis(): boolean;
  public set override_tip_basis(value): void;
  public get use_magnet(): boolean;
  public set use_magnet(value): void;
  public get magnet(): Vector3;
  public set magnet(value): void;
  public get target_node(): NodePath;
  public set target_node(value): void;
  public get min_distance(): number;
  public set min_distance(value): void;
  public get max_iterations(): number;
  public set max_iterations(value): void;
  public get interpolation(): number;
  public set interpolation(value): void;
}