
import type { Joint3D } from '@godot/classes/joint3d';


export declare class SliderJoint3D extends Joint3D {


    public set_param(param: number, value: number): void;
    public get_param(param: number): number;


    public static readonly Param: {
        PARAM_LINEAR_LIMIT_UPPER: 0;
        PARAM_LINEAR_LIMIT_LOWER: 1;
        PARAM_LINEAR_LIMIT_SOFTNESS: 2;
        PARAM_LINEAR_LIMIT_RESTITUTION: 3;
        PARAM_LINEAR_LIMIT_DAMPING: 4;
        PARAM_LINEAR_MOTION_SOFTNESS: 5;
        PARAM_LINEAR_MOTION_RESTITUTION: 6;
        PARAM_LINEAR_MOTION_DAMPING: 7;
        PARAM_LINEAR_ORTHOGONAL_SOFTNESS: 8;
        PARAM_LINEAR_ORTHOGONAL_RESTITUTION: 9;
        PARAM_LINEAR_ORTHOGONAL_DAMPING: 10;
        PARAM_ANGULAR_LIMIT_UPPER: 11;
        PARAM_ANGULAR_LIMIT_LOWER: 12;
        PARAM_ANGULAR_LIMIT_SOFTNESS: 13;
        PARAM_ANGULAR_LIMIT_RESTITUTION: 14;
        PARAM_ANGULAR_LIMIT_DAMPING: 15;
        PARAM_ANGULAR_MOTION_SOFTNESS: 16;
        PARAM_ANGULAR_MOTION_RESTITUTION: 17;
        PARAM_ANGULAR_MOTION_DAMPING: 18;
        PARAM_ANGULAR_ORTHOGONAL_SOFTNESS: 19;
        PARAM_ANGULAR_ORTHOGONAL_RESTITUTION: 20;
        PARAM_ANGULAR_ORTHOGONAL_DAMPING: 21;
        PARAM_MAX: 22;
    };
}

