
import { StyleBox } from "@godot/classes/style_box";


export declare class StyleBoxFlat extends StyleBox{
  public set_bg_color(_color: Color): void;
  public get_bg_color(): Color;
  public set_border_color(_color: Color): void;
  public get_border_color(): Color;
  public set_border_width_all(_width: number): void;
  public get_border_width_min(): number;
  public set_border_width(_margin: number, _width: number): void;
  public get_border_width(_margin: number): number;
  public set_border_blend(_blend: boolean): void;
  public get_border_blend(): boolean;
  public set_corner_radius_all(_radius: number): void;
  public set_corner_radius(_corner: number, _radius: number): void;
  public get_corner_radius(_corner: number): number;
  public set_expand_margin(_margin: number, _size: number): void;
  public set_expand_margin_all(_size: number): void;
  public get_expand_margin(_margin: number): number;
  public set_draw_center(_draw_center: boolean): void;
  public is_draw_center_enabled(): boolean;
  public set_skew(_skew: Vector2): void;
  public get_skew(): Vector2;
  public set_shadow_color(_color: Color): void;
  public get_shadow_color(): Color;
  public set_shadow_size(_size: number): void;
  public get_shadow_size(): number;
  public set_shadow_offset(_offset: Vector2): void;
  public get_shadow_offset(): Vector2;
  public set_anti_aliased(_anti_aliased: boolean): void;
  public is_anti_aliased(): boolean;
  public set_aa_size(_size: number): void;
  public get_aa_size(): number;
  public set_corner_detail(_detail: number): void;
  public get_corner_detail(): number;
  public get bg_color(): Color;
  public set bg_color(value): void;
  public get draw_center(): boolean;
  public set draw_center(value): void;
  public get skew(): Vector2;
  public set skew(value): void;
  public get border_width_left(): number;
  public set border_width_left(value): void;
  public get border_width_top(): number;
  public set border_width_top(value): void;
  public get border_width_right(): number;
  public set border_width_right(value): void;
  public get border_width_bottom(): number;
  public set border_width_bottom(value): void;
  public get border_color(): Color;
  public set border_color(value): void;
  public get border_blend(): boolean;
  public set border_blend(value): void;
  public get corner_radius_top_left(): number;
  public set corner_radius_top_left(value): void;
  public get corner_radius_top_right(): number;
  public set corner_radius_top_right(value): void;
  public get corner_radius_bottom_right(): number;
  public set corner_radius_bottom_right(value): void;
  public get corner_radius_bottom_left(): number;
  public set corner_radius_bottom_left(value): void;
  public get corner_detail(): number;
  public set corner_detail(value): void;
  public get expand_margin_left(): number;
  public set expand_margin_left(value): void;
  public get expand_margin_top(): number;
  public set expand_margin_top(value): void;
  public get expand_margin_right(): number;
  public set expand_margin_right(value): void;
  public get expand_margin_bottom(): number;
  public set expand_margin_bottom(value): void;
  public get shadow_color(): Color;
  public set shadow_color(value): void;
  public get shadow_size(): number;
  public set shadow_size(value): void;
  public get shadow_offset(): Vector2;
  public set shadow_offset(value): void;
  public get anti_aliasing(): boolean;
  public set anti_aliasing(value): void;
  public get anti_aliasing_size(): number;
  public set anti_aliasing_size(value): void;
}