
import { Font } from "@godot/classes/font";


export declare class SystemFont extends Font{
  public set_antialiasing(_antialiasing: number): void;
  public get_antialiasing(): number;
  public set_disable_embedded_bitmaps(_disable_embedded_bitmaps: boolean): void;
  public get_disable_embedded_bitmaps(): boolean;
  public set_generate_mipmaps(_generate_mipmaps: boolean): void;
  public get_generate_mipmaps(): boolean;
  public set_allow_system_fallback(_allow_system_fallback: boolean): void;
  public is_allow_system_fallback(): boolean;
  public set_force_autohinter(_force_autohinter: boolean): void;
  public is_force_autohinter(): boolean;
  public set_hinting(_hinting: number): void;
  public get_hinting(): number;
  public set_subpixel_positioning(_subpixel_positioning: number): void;
  public get_subpixel_positioning(): number;
  public set_multichannel_signed_distance_field(_msdf: boolean): void;
  public is_multichannel_signed_distance_field(): boolean;
  public set_msdf_pixel_range(_msdf_pixel_range: number): void;
  public get_msdf_pixel_range(): number;
  public set_msdf_size(_msdf_size: number): void;
  public get_msdf_size(): number;
  public set_oversampling(_oversampling: number): void;
  public get_oversampling(): number;
  public get_font_names(): PackedStringArray;
  public set_font_names(_names: PackedStringArray): void;
  public get_font_italic(): boolean;
  public set_font_italic(_italic: boolean): void;
  public set_font_weight(_weight: number): void;
  public set_font_stretch(_stretch: number): void;
  public get font_names(): PackedStringArray;
  public set font_names(value): void;
  public get font_italic(): boolean;
  public set font_italic(value): void;
  public get font_weight(): number;
  public set font_weight(value): void;
  public get font_stretch(): number;
  public set font_stretch(value): void;
  public get antialiasing(): number;
  public set antialiasing(value): void;
  public get generate_mipmaps(): boolean;
  public set generate_mipmaps(value): void;
  public get disable_embedded_bitmaps(): boolean;
  public set disable_embedded_bitmaps(value): void;
  public get allow_system_fallback(): boolean;
  public set allow_system_fallback(value): void;
  public get force_autohinter(): boolean;
  public set force_autohinter(value): void;
  public get hinting(): number;
  public set hinting(value): void;
  public get subpixel_positioning(): number;
  public set subpixel_positioning(value): void;
  public get multichannel_signed_distance_field(): boolean;
  public set multichannel_signed_distance_field(value): void;
  public get msdf_pixel_range(): number;
  public set msdf_pixel_range(value): void;
  public get msdf_size(): number;
  public set msdf_size(value): void;
  public get oversampling(): number;
  public set oversampling(value): void;
}