
import { Popup } from "@godot/classes/popup";
import { Container } from "@godot/classes/container";
import { TabBar } from "@godot/classes/tab_bar";
import { Node } from "@godot/classes/node";
import { Control } from "@godot/classes/control";
import { Texture2D } from "@godot/classes/texture2d";
export declare class TabContainer extends Container{
  public get_tab_count(): number;
  public set_current_tab(_tab_idx: number): void;
  public get_current_tab(): number;
  public get_previous_tab(): number;
  public select_previous_available(): boolean;
  public select_next_available(): boolean;
  public get_current_tab_control(): Control;
  public get_tab_bar(): TabBar;
  public get_tab_control(_tab_idx: number): Control;
  public set_tab_alignment(_alignment: number): void;
  public get_tab_alignment(): number;
  public set_tabs_position(_tabs_position: number): void;
  public get_tabs_position(): number;
  public set_clip_tabs(_clip_tabs: boolean): void;
  public get_clip_tabs(): boolean;
  public set_tabs_visible(_visible: boolean): void;
  public are_tabs_visible(): boolean;
  public set_all_tabs_in_front(_is_front: boolean): void;
  public is_all_tabs_in_front(): boolean;
  public set_tab_title(_tab_idx: number, _title: GDString | StringName | string): void;
  public get_tab_title(_tab_idx: number): String;
  public set_tab_tooltip(_tab_idx: number, _tooltip: GDString | StringName | string): void;
  public get_tab_tooltip(_tab_idx: number): String;
  public set_tab_icon(_tab_idx: number, _icon: Texture2D): void;
  public get_tab_icon(_tab_idx: number): Texture2D;
  public set_tab_icon_max_width(_tab_idx: number, _width: number): void;
  public get_tab_icon_max_width(_tab_idx: number): number;
  public set_tab_disabled(_tab_idx: number, _disabled: boolean): void;
  public is_tab_disabled(_tab_idx: number): boolean;
  public set_tab_hidden(_tab_idx: number, _hidden: boolean): void;
  public is_tab_hidden(_tab_idx: number): boolean;
  public set_tab_metadata(_tab_idx: number, _metadata: any): void;
  public get_tab_metadata(_tab_idx: number): any;
  public set_tab_button_icon(_tab_idx: number, _icon: Texture2D): void;
  public get_tab_button_icon(_tab_idx: number): Texture2D;
  public get_tab_idx_at_point(_point: Vector2): number;
  public get_tab_idx_from_control(_control: Control): number;
  public set_popup(_popup: Node): void;
  public get_popup(): Popup;
  public set_drag_to_rearrange_enabled(_enabled: boolean): void;
  public get_drag_to_rearrange_enabled(): boolean;
  public set_tabs_rearrange_group(_group_id: number): void;
  public get_tabs_rearrange_group(): number;
  public set_use_hidden_tabs_for_min_size(_enabled: boolean): void;
  public get_use_hidden_tabs_for_min_size(): boolean;
  public set_tab_focus_mode(_focus_mode: number): void;
  public get_tab_focus_mode(): number;
  public set_deselect_enabled(_enabled: boolean): void;
  public get_deselect_enabled(): boolean;
  public get tab_alignment(): number;
  public set tab_alignment(value): void;
  public get current_tab(): number;
  public set current_tab(value): void;
  public get tabs_position(): number;
  public set tabs_position(value): void;
  public get clip_tabs(): boolean;
  public set clip_tabs(value): void;
  public get tabs_visible(): boolean;
  public set tabs_visible(value): void;
  public get all_tabs_in_front(): boolean;
  public set all_tabs_in_front(value): void;
  public get drag_to_rearrange_enabled(): boolean;
  public set drag_to_rearrange_enabled(value): void;
  public get tabs_rearrange_group(): number;
  public set tabs_rearrange_group(value): void;
  public get use_hidden_tabs_for_min_size(): boolean;
  public set use_hidden_tabs_for_min_size(value): void;
  public get tab_focus_mode(): number;
  public set tab_focus_mode(value): void;
  public get deselect_enabled(): boolean;
  public set deselect_enabled(value): void;
  static TabPosition = {
    POSITION_TOP = 0,
    POSITION_BOTTOM = 1,
    POSITION_MAX = 2,
  }
  public get active_tab_rearranged(): Signal;
  public get tab_changed(): Signal;
  public get tab_clicked(): Signal;
  public get tab_hovered(): Signal;
  public get tab_selected(): Signal;
  public get tab_button_pressed(): Signal;
  public get pre_popup_pressed(): Signal;
}