
import type { Image } from '@godot/classes/image';
import type { RefCounted } from '@godot/classes/ref_counted';


export declare class TextServer extends RefCounted {


    public has_feature(feature: number): boolean;
    public get_name(): GDString;
    public get_features(): number;
    public load_support_data(filename: GDString | StringName | string): boolean;
    public get_support_data_filename(): GDString;
    public get_support_data_info(): GDString;
    public save_support_data(filename: GDString | StringName | string): boolean;
    public get_support_data(): PackedByteArray;
    public is_locale_right_to_left(locale: GDString | StringName | string): boolean;
    public name_to_tag(name: GDString | StringName | string): number;
    public tag_to_name(tag: number): GDString;
    public has(rid: RID): boolean;
    public free_rid(rid: RID): void;
    public create_font(): RID;
    public create_font_linked_variation(fontRid: RID): RID;
    public font_set_data(fontRid: RID, data: PackedByteArray): void;
    public font_set_face_index(fontRid: RID, faceIndex: number): void;
    public font_get_face_index(fontRid: RID): number;
    public font_get_face_count(fontRid: RID): number;
    public font_set_style(fontRid: RID, style: number): void;
    public font_get_style(fontRid: RID): number;
    public font_set_name(fontRid: RID, name: GDString | StringName | string): void;
    public font_get_name(fontRid: RID): GDString;
    public font_get_ot_name_strings(fontRid: RID): Dictionary;
    public font_set_style_name(fontRid: RID, name: GDString | StringName | string): void;
    public font_get_style_name(fontRid: RID): GDString;
    public font_set_weight(fontRid: RID, weight: number): void;
    public font_get_weight(fontRid: RID): number;
    public font_set_stretch(fontRid: RID, weight: number): void;
    public font_get_stretch(fontRid: RID): number;
    public font_set_antialiasing(fontRid: RID, antialiasing: number): void;
    public font_get_antialiasing(fontRid: RID): number;
    public font_set_disable_embedded_bitmaps(fontRid: RID, disableEmbeddedBitmaps: boolean): void;
    public font_get_disable_embedded_bitmaps(fontRid: RID): boolean;
    public font_set_generate_mipmaps(fontRid: RID, generateMipmaps: boolean): void;
    public font_get_generate_mipmaps(fontRid: RID): boolean;
    public font_set_multichannel_signed_distance_field(fontRid: RID, msdf: boolean): void;
    public font_is_multichannel_signed_distance_field(fontRid: RID): boolean;
    public font_set_msdf_pixel_range(fontRid: RID, msdfPixelRange: number): void;
    public font_get_msdf_pixel_range(fontRid: RID): number;
    public font_set_msdf_size(fontRid: RID, msdfSize: number): void;
    public font_get_msdf_size(fontRid: RID): number;
    public font_set_fixed_size(fontRid: RID, fixedSize: number): void;
    public font_get_fixed_size(fontRid: RID): number;
    public font_set_fixed_size_scale_mode(fontRid: RID, fixedSizeScaleMode: number): void;
    public font_get_fixed_size_scale_mode(fontRid: RID): number;
    public font_set_allow_system_fallback(fontRid: RID, allowSystemFallback: boolean): void;
    public font_is_allow_system_fallback(fontRid: RID): boolean;
    public font_clear_system_fallback_cache(): void;
    public font_set_force_autohinter(fontRid: RID, forceAutohinter: boolean): void;
    public font_is_force_autohinter(fontRid: RID): boolean;
    public font_set_modulate_color_glyphs(fontRid: RID, forceAutohinter: boolean): void;
    public font_is_modulate_color_glyphs(fontRid: RID): boolean;
    public font_set_hinting(fontRid: RID, hinting: number): void;
    public font_get_hinting(fontRid: RID): number;
    public font_set_subpixel_positioning(fontRid: RID, subpixelPositioning: number): void;
    public font_get_subpixel_positioning(fontRid: RID): number;
    public font_set_keep_rounding_remainders(fontRid: RID, keeroundingRemainders: boolean): void;
    public font_get_keep_rounding_remainders(fontRid: RID): boolean;
    public font_set_embolden(fontRid: RID, strength: number): void;
    public font_get_embolden(fontRid: RID): number;
    public font_set_spacing(fontRid: RID, spacing: number, value: number): void;
    public font_get_spacing(fontRid: RID, spacing: number): number;
    public font_set_baseline_offset(fontRid: RID, baselineOffset: number): void;
    public font_get_baseline_offset(fontRid: RID): number;
    public font_set_transform(fontRid: RID, transform: Transform2D): void;
    public font_get_transform(fontRid: RID): Transform2D;
    public font_set_variation_coordinates(fontRid: RID, variationCoordinates: Dictionary): void;
    public font_get_variation_coordinates(fontRid: RID): Dictionary;
    public font_set_oversampling(fontRid: RID, oversampling: number): void;
    public font_get_oversampling(fontRid: RID): number;
    public font_get_size_cache_list(fontRid: RID): Array<any>;
    public font_clear_size_cache(fontRid: RID): void;
    public font_remove_size_cache(fontRid: RID, size: Vector2i): void;
    public font_get_size_cache_info(fontRid: RID): Array<any>;
    public font_set_ascent(fontRid: RID, size: number, ascent: number): void;
    public font_get_ascent(fontRid: RID, size: number): number;
    public font_set_descent(fontRid: RID, size: number, descent: number): void;
    public font_get_descent(fontRid: RID, size: number): number;
    public font_set_underline_position(fontRid: RID, size: number, underlinePosition: number): void;
    public font_get_underline_position(fontRid: RID, size: number): number;
    public font_set_underline_thickness(fontRid: RID, size: number, underlineThickness: number): void;
    public font_get_underline_thickness(fontRid: RID, size: number): number;
    public font_set_scale(fontRid: RID, size: number, scale: number): void;
    public font_get_scale(fontRid: RID, size: number): number;
    public font_get_texture_count(fontRid: RID, size: Vector2i): number;
    public font_clear_textures(fontRid: RID, size: Vector2i): void;
    public font_remove_texture(fontRid: RID, size: Vector2i, textureIndex: number): void;
    public font_set_texture_image(fontRid: RID, size: Vector2i, textureIndex: number, image: Image): void;
    public font_get_texture_image(fontRid: RID, size: Vector2i, textureIndex: number): Image;
    public font_set_texture_offsets(fontRid: RID, size: Vector2i, textureIndex: number, offset: PackedInt32Array): void;
    public font_get_texture_offsets(fontRid: RID, size: Vector2i, textureIndex: number): PackedInt32Array;
    public font_get_glyph_list(fontRid: RID, size: Vector2i): PackedInt32Array;
    public font_clear_glyphs(fontRid: RID, size: Vector2i): void;
    public font_remove_glyph(fontRid: RID, size: Vector2i, glyph: number): void;
    public font_get_glyph_advance(fontRid: RID, size: number, glyph: number): Vector2;
    public font_set_glyph_advance(fontRid: RID, size: number, glyph: number, advance: Vector2): void;
    public font_get_glyph_offset(fontRid: RID, size: Vector2i, glyph: number): Vector2;
    public font_set_glyph_offset(fontRid: RID, size: Vector2i, glyph: number, offset: Vector2): void;
    public font_get_glyph_size(fontRid: RID, size: Vector2i, glyph: number): Vector2;
    public font_set_glyph_size(fontRid: RID, size: Vector2i, glyph: number, glSize: Vector2): void;
    public font_get_glyph_uv_rect(fontRid: RID, size: Vector2i, glyph: number): Rect2;
    public font_set_glyph_uv_rect(fontRid: RID, size: Vector2i, glyph: number, uvRect: Rect2): void;
    public font_get_glyph_texture_idx(fontRid: RID, size: Vector2i, glyph: number): number;
    public font_set_glyph_texture_idx(fontRid: RID, size: Vector2i, glyph: number, textureIdx: number): void;
    public font_get_glyph_texture_rid(fontRid: RID, size: Vector2i, glyph: number): RID;
    public font_get_glyph_texture_size(fontRid: RID, size: Vector2i, glyph: number): Vector2;
    public font_get_glyph_contours(font: RID, size: number, index: number): Dictionary;
    public font_get_kerning_list(fontRid: RID, size: number): Array<any>;
    public font_clear_kerning_map(fontRid: RID, size: number): void;
    public font_remove_kerning(fontRid: RID, size: number, glyphPair: Vector2i): void;
    public font_set_kerning(fontRid: RID, size: number, glyphPair: Vector2i, kerning: Vector2): void;
    public font_get_kerning(fontRid: RID, size: number, glyphPair: Vector2i): Vector2;
    public font_get_glyph_index(fontRid: RID, size: number, char: number, variationSelector: number): number;
    public font_get_char_from_glyph_index(fontRid: RID, size: number, glyphIndex: number): number;
    public font_has_char(fontRid: RID, char: number): boolean;
    public font_get_supported_chars(fontRid: RID): GDString;
    public font_get_supported_glyphs(fontRid: RID): PackedInt32Array;
    public font_render_range(fontRid: RID, size: Vector2i, start: number, end: number): void;
    public font_render_glyph(fontRid: RID, size: Vector2i, index: number): void;
    public font_draw_glyph(fontRid: RID, canvas: RID, size: number, pos: Vector2, index: number, color: Color = Color(1, 1, 1, 1), oversampling: number = 0.0): void;
    public font_draw_glyph_outline(fontRid: RID, canvas: RID, size: number, outlineSize: number, pos: Vector2, index: number, color: Color = Color(1, 1, 1, 1), oversampling: number = 0.0): void;
    public font_is_language_supported(fontRid: RID, language: GDString | StringName | string): boolean;
    public font_set_language_support_override(fontRid: RID, language: GDString | StringName | string, supported: boolean): void;
    public font_get_language_support_override(fontRid: RID, language: GDString | StringName | string): boolean;
    public font_remove_language_support_override(fontRid: RID, language: GDString | StringName | string): void;
    public font_get_language_support_overrides(fontRid: RID): PackedStringArray;
    public font_is_script_supported(fontRid: RID, script: GDString | StringName | string): boolean;
    public font_set_script_support_override(fontRid: RID, script: GDString | StringName | string, supported: boolean): void;
    public font_get_script_support_override(fontRid: RID, script: GDString | StringName | string): boolean;
    public font_remove_script_support_override(fontRid: RID, script: GDString | StringName | string): void;
    public font_get_script_support_overrides(fontRid: RID): PackedStringArray;
    public font_set_opentype_feature_overrides(fontRid: RID, overrides: Dictionary): void;
    public font_get_opentype_feature_overrides(fontRid: RID): Dictionary;
    public font_supported_feature_list(fontRid: RID): Dictionary;
    public font_supported_variation_list(fontRid: RID): Dictionary;
    public font_get_global_oversampling(): number;
    public font_set_global_oversampling(oversampling: number): void;
    public get_hex_code_box_size(size: number, index: number): Vector2;
    public draw_hex_code_box(canvas: RID, size: number, pos: Vector2, index: number, color: Color): void;
    public create_shaped_text(direction: number = 0, orientation: number = 0): RID;
    public shaped_text_clear(rid: RID): void;
    public shaped_text_set_direction(shaped: RID, direction: number = 0): void;
    public shaped_text_get_direction(shaped: RID): number;
    public shaped_text_get_inferred_direction(shaped: RID): number;
    public shaped_text_set_bidi_override(shaped: RID, override: GDArray): void;
    public shaped_text_set_custom_punctuation(shaped: RID, punct: GDString | StringName | string): void;
    public shaped_text_get_custom_punctuation(shaped: RID): GDString;
    public shaped_text_set_custom_ellipsis(shaped: RID, char: number): void;
    public shaped_text_get_custom_ellipsis(shaped: RID): number;
    public shaped_text_set_orientation(shaped: RID, orientation: number = 0): void;
    public shaped_text_get_orientation(shaped: RID): number;
    public shaped_text_set_preserve_invalid(shaped: RID, enabled: boolean): void;
    public shaped_text_get_preserve_invalid(shaped: RID): boolean;
    public shaped_text_set_preserve_control(shaped: RID, enabled: boolean): void;
    public shaped_text_get_preserve_control(shaped: RID): boolean;
    public shaped_text_set_spacing(shaped: RID, spacing: number, value: number): void;
    public shaped_text_get_spacing(shaped: RID, spacing: number): number;
    public shaped_text_add_string(shaped: RID, text: GDString | StringName | string, fonts: Array<any>, size: number, opentypeFeatures: Dictionary = {}, language: GDString | StringName | string = "", meta: any = null): boolean;
    public shaped_text_add_object(shaped: RID, key: any, size: Vector2, inlineAlign: number = 5, length: number = 1, baseline: number = 0.0): boolean;
    public shaped_text_resize_object(shaped: RID, key: any, size: Vector2, inlineAlign: number = 5, baseline: number = 0.0): boolean;
    public shaped_get_text(shaped: RID): GDString;
    public shaped_get_span_count(shaped: RID): number;
    public shaped_get_span_meta(shaped: RID, index: number): any;
    public shaped_get_span_embedded_object(shaped: RID, index: number): any;
    public shaped_get_span_text(shaped: RID, index: number): GDString;
    public shaped_get_span_object(shaped: RID, index: number): any;
    public shaped_set_span_update_font(shaped: RID, index: number, fonts: Array<any>, size: number, opentypeFeatures: Dictionary = {}): void;
    public shaped_get_run_count(shaped: RID): number;
    public shaped_get_run_text(shaped: RID, index: number): GDString;
    public shaped_get_run_range(shaped: RID, index: number): Vector2i;
    public shaped_get_run_font_rid(shaped: RID, index: number): RID;
    public shaped_get_run_font_size(shaped: RID, index: number): number;
    public shaped_get_run_language(shaped: RID, index: number): GDString;
    public shaped_get_run_direction(shaped: RID, index: number): number;
    public shaped_get_run_object(shaped: RID, index: number): any;
    public shaped_text_substr(shaped: RID, start: number, length: number): RID;
    public shaped_text_get_parent(shaped: RID): RID;
    public shaped_text_fit_to_width(shaped: RID, width: number, justificationFlags: number = 3): number;
    public shaped_text_tab_align(shaped: RID, tabStops: PackedFloat32Array): number;
    public shaped_text_shape(shaped: RID): boolean;
    public shaped_text_is_ready(shaped: RID): boolean;
    public shaped_text_has_visible_chars(shaped: RID): boolean;
    public shaped_text_get_glyphs(shaped: RID): Array<any>;
    public shaped_text_sort_logical(shaped: RID): Array<any>;
    public shaped_text_get_glyph_count(shaped: RID): number;
    public shaped_text_get_range(shaped: RID): Vector2i;
    public shaped_text_get_line_breaks_adv(shaped: RID, width: PackedFloat32Array, start: number = 0, once: boolean = true, breakFlags: number = 3): PackedInt32Array;
    public shaped_text_get_line_breaks(shaped: RID, width: number, start: number = 0, breakFlags: number = 3): PackedInt32Array;
    public shaped_text_get_word_breaks(shaped: RID, graphemeFlags: number = 264, skigraphemeFlags: number = 4): PackedInt32Array;
    public shaped_text_get_trim_pos(shaped: RID): number;
    public shaped_text_get_ellipsis_pos(shaped: RID): number;
    public shaped_text_get_ellipsis_glyphs(shaped: RID): Array<any>;
    public shaped_text_get_ellipsis_glyph_count(shaped: RID): number;
    public shaped_text_overrun_trim_to_width(shaped: RID, width: number = 0, overrunTrimFlags: number = 0): void;
    public shaped_text_get_objects(shaped: RID): GDArray;
    public shaped_text_get_object_rect(shaped: RID, key: any): Rect2;
    public shaped_text_get_object_range(shaped: RID, key: any): Vector2i;
    public shaped_text_get_object_glyph(shaped: RID, key: any): number;
    public shaped_text_get_size(shaped: RID): Vector2;
    public shaped_text_get_ascent(shaped: RID): number;
    public shaped_text_get_descent(shaped: RID): number;
    public shaped_text_get_width(shaped: RID): number;
    public shaped_text_get_underline_position(shaped: RID): number;
    public shaped_text_get_underline_thickness(shaped: RID): number;
    public shaped_text_get_carets(shaped: RID, position: number): Dictionary;
    public shaped_text_get_selection(shaped: RID, start: number, end: number): PackedVector2Array;
    public shaped_text_hit_test_grapheme(shaped: RID, coords: number): number;
    public shaped_text_hit_test_position(shaped: RID, coords: number): number;
    public shaped_text_get_grapheme_bounds(shaped: RID, pos: number): Vector2;
    public shaped_text_next_grapheme_pos(shaped: RID, pos: number): number;
    public shaped_text_prev_grapheme_pos(shaped: RID, pos: number): number;
    public shaped_text_get_character_breaks(shaped: RID): PackedInt32Array;
    public shaped_text_next_character_pos(shaped: RID, pos: number): number;
    public shaped_text_prev_character_pos(shaped: RID, pos: number): number;
    public shaped_text_closest_character_pos(shaped: RID, pos: number): number;
    public shaped_text_draw(shaped: RID, canvas: RID, pos: Vector2, clil: number = -1, clir: number = -1, color: Color = Color(1, 1, 1, 1), oversampling: number = 0.0): void;
    public shaped_text_draw_outline(shaped: RID, canvas: RID, pos: Vector2, clil: number = -1, clir: number = -1, outlineSize: number = 1, color: Color = Color(1, 1, 1, 1), oversampling: number = 0.0): void;
    public shaped_text_get_dominant_direction_in_range(shaped: RID, start: number, end: number): number;
    public format_number(_number: GDString | StringName | string, language: GDString | StringName | string = ""): GDString;
    public parse_number(_number: GDString | StringName | string, language: GDString | StringName | string = ""): GDString;
    public percent_sign(language: GDString | StringName | string = ""): GDString;
    public string_get_word_breaks(_string: GDString | StringName | string, language: GDString | StringName | string = "", charsPerLine: number = 0): PackedInt32Array;
    public string_get_character_breaks(_string: GDString | StringName | string, language: GDString | StringName | string = ""): PackedInt32Array;
    public is_confusable(_string: GDString | StringName | string, dict: PackedStringArray): number;
    public spoof_check(_string: GDString | StringName | string): boolean;
    public strip_diacritics(_string: GDString | StringName | string): GDString;
    public is_valid_identifier(_string: GDString | StringName | string): boolean;
    public is_valid_letter(unicode: number): boolean;
    public string_to_upper(_string: GDString | StringName | string, language: GDString | StringName | string = ""): GDString;
    public string_to_lower(_string: GDString | StringName | string, language: GDString | StringName | string = ""): GDString;
    public string_to_title(_string: GDString | StringName | string, language: GDString | StringName | string = ""): GDString;
    public parse_structured_text(parserType: number, args: GDArray, text: GDString | StringName | string): Array<any>;


    public static readonly FontAntialiasing: {
        FONT_ANTIALIASING_NONE: 0;
        FONT_ANTIALIASING_GRAY: 1;
        FONT_ANTIALIASING_LCD: 2;
    };
    public static readonly FontLCDSubpixelLayout: {
        FONT_LCD_SUBPIXEL_LAYOUT_NONE: 0;
        FONT_LCD_SUBPIXEL_LAYOUT_HRGB: 1;
        FONT_LCD_SUBPIXEL_LAYOUT_HBGR: 2;
        FONT_LCD_SUBPIXEL_LAYOUT_VRGB: 3;
        FONT_LCD_SUBPIXEL_LAYOUT_VBGR: 4;
        FONT_LCD_SUBPIXEL_LAYOUT_MAX: 5;
    };
    public static readonly Direction: {
        DIRECTION_AUTO: 0;
        DIRECTION_LTR: 1;
        DIRECTION_RTL: 2;
        DIRECTION_INHERITED: 3;
    };
    public static readonly Orientation: {
        ORIENTATION_HORIZONTAL: 0;
        ORIENTATION_VERTICAL: 1;
    };
    public static readonly JustificationFlag: {
        JUSTIFICATION_NONE: 0;
        JUSTIFICATION_KASHIDA: 1;
        JUSTIFICATION_WORD_BOUND: 2;
        JUSTIFICATION_TRIM_EDGE_SPACES: 4;
        JUSTIFICATION_AFTER_LAST_TAB: 8;
        JUSTIFICATION_CONSTRAIN_ELLIPSIS: 16;
        JUSTIFICATION_SKIP_LAST_LINE: 32;
        JUSTIFICATION_SKIP_LAST_LINE_WITH_VISIBLE_CHARS: 64;
        JUSTIFICATION_DO_NOT_SKIP_SINGLE_LINE: 128;
    };
    public static readonly AutowrapMode: {
        AUTOWRAP_OFF: 0;
        AUTOWRAP_ARBITRARY: 1;
        AUTOWRAP_WORD: 2;
        AUTOWRAP_WORD_SMART: 3;
    };
    public static readonly LineBreakFlag: {
        BREAK_NONE: 0;
        BREAK_MANDATORY: 1;
        BREAK_WORD_BOUND: 2;
        BREAK_GRAPHEME_BOUND: 4;
        BREAK_ADAPTIVE: 8;
        BREAK_TRIM_EDGE_SPACES: 16;
        BREAK_TRIM_INDENT: 32;
        BREAK_TRIM_START_EDGE_SPACES: 64;
        BREAK_TRIM_END_EDGE_SPACES: 128;
    };
    public static readonly VisibleCharactersBehavior: {
        VC_CHARS_BEFORE_SHAPING: 0;
        VC_CHARS_AFTER_SHAPING: 1;
        VC_GLYPHS_AUTO: 2;
        VC_GLYPHS_LTR: 3;
        VC_GLYPHS_RTL: 4;
    };
    public static readonly OverrunBehavior: {
        OVERRUN_NO_TRIMMING: 0;
        OVERRUN_TRIM_CHAR: 1;
        OVERRUN_TRIM_WORD: 2;
        OVERRUN_TRIM_ELLIPSIS: 3;
        OVERRUN_TRIM_WORD_ELLIPSIS: 4;
        OVERRUN_TRIM_ELLIPSIS_FORCE: 5;
        OVERRUN_TRIM_WORD_ELLIPSIS_FORCE: 6;
    };
    public static readonly TextOverrunFlag: {
        OVERRUN_NO_TRIM: 0;
        OVERRUN_TRIM: 1;
        OVERRUN_TRIM_WORD_ONLY: 2;
        OVERRUN_ADD_ELLIPSIS: 4;
        OVERRUN_ENFORCE_ELLIPSIS: 8;
        OVERRUN_JUSTIFICATION_AWARE: 16;
    };
    public static readonly GraphemeFlag: {
        GRAPHEME_IS_VALID: 1;
        GRAPHEME_IS_RTL: 2;
        GRAPHEME_IS_VIRTUAL: 4;
        GRAPHEME_IS_SPACE: 8;
        GRAPHEME_IS_BREAK_HARD: 16;
        GRAPHEME_IS_BREAK_SOFT: 32;
        GRAPHEME_IS_TAB: 64;
        GRAPHEME_IS_ELONGATION: 128;
        GRAPHEME_IS_PUNCTUATION: 256;
        GRAPHEME_IS_UNDERSCORE: 512;
        GRAPHEME_IS_CONNECTED: 1024;
        GRAPHEME_IS_SAFE_TO_INSERT_TATWEEL: 2048;
        GRAPHEME_IS_EMBEDDED_OBJECT: 4096;
        GRAPHEME_IS_SOFT_HYPHEN: 8192;
    };
    public static readonly Hinting: {
        HINTING_NONE: 0;
        HINTING_LIGHT: 1;
        HINTING_NORMAL: 2;
    };
    public static readonly SubpixelPositioning: {
        SUBPIXEL_POSITIONING_DISABLED: 0;
        SUBPIXEL_POSITIONING_AUTO: 1;
        SUBPIXEL_POSITIONING_ONE_HALF: 2;
        SUBPIXEL_POSITIONING_ONE_QUARTER: 3;
        SUBPIXEL_POSITIONING_ONE_HALF_MAX_SIZE: 20;
        SUBPIXEL_POSITIONING_ONE_QUARTER_MAX_SIZE: 16;
    };
    public static readonly Feature: {
        FEATURE_SIMPLE_LAYOUT: 1;
        FEATURE_BIDI_LAYOUT: 2;
        FEATURE_VERTICAL_LAYOUT: 4;
        FEATURE_SHAPING: 8;
        FEATURE_KASHIDA_JUSTIFICATION: 16;
        FEATURE_BREAK_ITERATORS: 32;
        FEATURE_FONT_BITMAP: 64;
        FEATURE_FONT_DYNAMIC: 128;
        FEATURE_FONT_MSDF: 256;
        FEATURE_FONT_SYSTEM: 512;
        FEATURE_FONT_VARIABLE: 1024;
        FEATURE_CONTEXT_SENSITIVE_CASE_CONVERSION: 2048;
        FEATURE_USE_SUPPORT_DATA: 4096;
        FEATURE_UNICODE_IDENTIFIERS: 8192;
        FEATURE_UNICODE_SECURITY: 16384;
    };
    public static readonly ContourPointTag: {
        CONTOUR_CURVE_TAG_ON: 1;
        CONTOUR_CURVE_TAG_OFF_CONIC: 0;
        CONTOUR_CURVE_TAG_OFF_CUBIC: 2;
    };
    public static readonly SpacingType: {
        SPACING_GLYPH: 0;
        SPACING_SPACE: 1;
        SPACING_TOP: 2;
        SPACING_BOTTOM: 3;
        SPACING_MAX: 4;
    };
    public static readonly FontStyle: {
        FONT_BOLD: 1;
        FONT_ITALIC: 2;
        FONT_FIXED_WIDTH: 4;
    };
    public static readonly StructuredTextParser: {
        STRUCTURED_TEXT_DEFAULT: 0;
        STRUCTURED_TEXT_URI: 1;
        STRUCTURED_TEXT_FILE: 2;
        STRUCTURED_TEXT_EMAIL: 3;
        STRUCTURED_TEXT_LIST: 4;
        STRUCTURED_TEXT_GDSCRIPT: 5;
        STRUCTURED_TEXT_CUSTOM: 6;
    };
    public static readonly FixedSizeScaleMode: {
        FIXED_SIZE_SCALE_DISABLE: 0;
        FIXED_SIZE_SCALE_INTEGER_ONLY: 1;
        FIXED_SIZE_SCALE_ENABLED: 2;
    };
}

