
import { PrimitiveMesh } from "@godot/classes/primitive_mesh";
import { Font } from "@godot/classes/font";
export declare class TextMesh extends PrimitiveMesh{
  public set_horizontal_alignment(_alignment: number): void;
  public get_horizontal_alignment(): number;
  public set_vertical_alignment(_alignment: number): void;
  public get_vertical_alignment(): number;
  public set_text(_text: GDString | StringName | string): void;
  public get_text(): String;
  public set_font(_font: Font): void;
  public get_font(): Font;
  public set_font_size(_font_size: number): void;
  public get_font_size(): number;
  public set_line_spacing(_line_spacing: number): void;
  public get_line_spacing(): number;
  public set_autowrap_mode(_autowrap_mode: number): void;
  public get_autowrap_mode(): number;
  public set_justification_flags(_justification_flags: number): void;
  public get_justification_flags(): number;
  public set_depth(_depth: number): void;
  public get_depth(): number;
  public set_width(_width: number): void;
  public get_width(): number;
  public set_pixel_size(_pixel_size: number): void;
  public get_pixel_size(): number;
  public set_offset(_offset: Vector2): void;
  public get_offset(): Vector2;
  public set_curve_step(_curve_step: number): void;
  public get_curve_step(): number;
  public set_text_direction(_direction: number): void;
  public get_text_direction(): number;
  public set_language(_language: GDString | StringName | string): void;
  public get_language(): String;
  public set_structured_text_bidi_override(_parser: number): void;
  public get_structured_text_bidi_override(): number;
  public set_structured_text_bidi_override_options(_args: GDArray): void;
  public get_structured_text_bidi_override_options(): GDArray;
  public set_uppercase(_enable: boolean): void;
  public is_uppercase(): boolean;
  public get text(): String;
  public set text(value): void;
  public get font(): Font;
  public set font(value): void;
  public get font_size(): number;
  public set font_size(value): void;
  public get horizontal_alignment(): number;
  public set horizontal_alignment(value): void;
  public get vertical_alignment(): number;
  public set vertical_alignment(value): void;
  public get uppercase(): boolean;
  public set uppercase(value): void;
  public get line_spacing(): number;
  public set line_spacing(value): void;
  public get autowrap_mode(): number;
  public set autowrap_mode(value): void;
  public get justification_flags(): number;
  public set justification_flags(value): void;
  public get pixel_size(): number;
  public set pixel_size(value): void;
  public get curve_step(): number;
  public set curve_step(value): void;
  public get depth(): number;
  public set depth(value): void;
  public get width(): number;
  public set width(value): void;
  public get offset(): Vector2;
  public set offset(value): void;
  public get text_direction(): number;
  public set text_direction(value): void;
  public get language(): String;
  public set language(value): void;
  public get structured_text_bidi_override(): number;
  public set structured_text_bidi_override(value): void;
  public get structured_text_bidi_override_options(): GDArray;
  public set structured_text_bidi_override_options(value): void;
}