
import type { Image } from '@godot/classes/image';
import type { TextServer } from '@godot/classes/text_server';


export declare class TextServerExtension extends TextServer {


    public _has_feature(feature: number): boolean;
    public _get_name(): GDString;
    public _get_features(): number;
    public _free_rid(rid: RID): void;
    public _has(rid: RID): boolean;
    public _load_support_data(filename: GDString | StringName | string): boolean;
    public _get_support_data_filename(): GDString;
    public _get_support_data_info(): GDString;
    public _save_support_data(filename: GDString | StringName | string): boolean;
    public _get_support_data(): PackedByteArray;
    public _is_locale_right_to_left(locale: GDString | StringName | string): boolean;
    public _name_to_tag(name: GDString | StringName | string): number;
    public _tag_to_name(tag: number): GDString;
    public _create_font(): RID;
    public _create_font_linked_variation(fontRid: RID): RID;
    public _font_set_data(fontRid: RID, data: PackedByteArray): void;
    public _font_set_data_ptr(fontRid: RID, dataPtr: any, dataSize: number): void;
    public _font_set_face_index(fontRid: RID, faceIndex: number): void;
    public _font_get_face_index(fontRid: RID): number;
    public _font_get_face_count(fontRid: RID): number;
    public _font_set_style(fontRid: RID, style: number): void;
    public _font_get_style(fontRid: RID): number;
    public _font_set_name(fontRid: RID, name: GDString | StringName | string): void;
    public _font_get_name(fontRid: RID): GDString;
    public _font_get_ot_name_strings(fontRid: RID): Dictionary;
    public _font_set_style_name(fontRid: RID, nameStyle: GDString | StringName | string): void;
    public _font_get_style_name(fontRid: RID): GDString;
    public _font_set_weight(fontRid: RID, weight: number): void;
    public _font_get_weight(fontRid: RID): number;
    public _font_set_stretch(fontRid: RID, stretch: number): void;
    public _font_get_stretch(fontRid: RID): number;
    public _font_set_antialiasing(fontRid: RID, antialiasing: number): void;
    public _font_get_antialiasing(fontRid: RID): number;
    public _font_set_disable_embedded_bitmaps(fontRid: RID, disableEmbeddedBitmaps: boolean): void;
    public _font_get_disable_embedded_bitmaps(fontRid: RID): boolean;
    public _font_set_generate_mipmaps(fontRid: RID, generateMipmaps: boolean): void;
    public _font_get_generate_mipmaps(fontRid: RID): boolean;
    public _font_set_multichannel_signed_distance_field(fontRid: RID, msdf: boolean): void;
    public _font_is_multichannel_signed_distance_field(fontRid: RID): boolean;
    public _font_set_msdf_pixel_range(fontRid: RID, msdfPixelRange: number): void;
    public _font_get_msdf_pixel_range(fontRid: RID): number;
    public _font_set_msdf_size(fontRid: RID, msdfSize: number): void;
    public _font_get_msdf_size(fontRid: RID): number;
    public _font_set_fixed_size(fontRid: RID, fixedSize: number): void;
    public _font_get_fixed_size(fontRid: RID): number;
    public _font_set_fixed_size_scale_mode(fontRid: RID, fixedSizeScaleMode: number): void;
    public _font_get_fixed_size_scale_mode(fontRid: RID): number;
    public _font_set_allow_system_fallback(fontRid: RID, allowSystemFallback: boolean): void;
    public _font_is_allow_system_fallback(fontRid: RID): boolean;
    public _font_clear_system_fallback_cache(): void;
    public _font_set_force_autohinter(fontRid: RID, forceAutohinter: boolean): void;
    public _font_is_force_autohinter(fontRid: RID): boolean;
    public _font_set_modulate_color_glyphs(fontRid: RID, modulate: boolean): void;
    public _font_is_modulate_color_glyphs(fontRid: RID): boolean;
    public _font_set_hinting(fontRid: RID, hinting: number): void;
    public _font_get_hinting(fontRid: RID): number;
    public _font_set_subpixel_positioning(fontRid: RID, subpixelPositioning: number): void;
    public _font_get_subpixel_positioning(fontRid: RID): number;
    public _font_set_keep_rounding_remainders(fontRid: RID, keeroundingRemainders: boolean): void;
    public _font_get_keep_rounding_remainders(fontRid: RID): boolean;
    public _font_set_embolden(fontRid: RID, strength: number): void;
    public _font_get_embolden(fontRid: RID): number;
    public _font_set_spacing(fontRid: RID, spacing: number, value: number): void;
    public _font_get_spacing(fontRid: RID, spacing: number): number;
    public _font_set_baseline_offset(fontRid: RID, baselineOffset: number): void;
    public _font_get_baseline_offset(fontRid: RID): number;
    public _font_set_transform(fontRid: RID, transform: Transform2D): void;
    public _font_get_transform(fontRid: RID): Transform2D;
    public _font_set_variation_coordinates(fontRid: RID, variationCoordinates: Dictionary): void;
    public _font_get_variation_coordinates(fontRid: RID): Dictionary;
    public _font_set_oversampling(fontRid: RID, oversampling: number): void;
    public _font_get_oversampling(fontRid: RID): number;
    public _font_get_size_cache_list(fontRid: RID): Array<any>;
    public _font_clear_size_cache(fontRid: RID): void;
    public _font_remove_size_cache(fontRid: RID, size: Vector2i): void;
    public _font_get_size_cache_info(fontRid: RID): Array<any>;
    public _font_set_ascent(fontRid: RID, size: number, ascent: number): void;
    public _font_get_ascent(fontRid: RID, size: number): number;
    public _font_set_descent(fontRid: RID, size: number, descent: number): void;
    public _font_get_descent(fontRid: RID, size: number): number;
    public _font_set_underline_position(fontRid: RID, size: number, underlinePosition: number): void;
    public _font_get_underline_position(fontRid: RID, size: number): number;
    public _font_set_underline_thickness(fontRid: RID, size: number, underlineThickness: number): void;
    public _font_get_underline_thickness(fontRid: RID, size: number): number;
    public _font_set_scale(fontRid: RID, size: number, scale: number): void;
    public _font_get_scale(fontRid: RID, size: number): number;
    public _font_get_texture_count(fontRid: RID, size: Vector2i): number;
    public _font_clear_textures(fontRid: RID, size: Vector2i): void;
    public _font_remove_texture(fontRid: RID, size: Vector2i, textureIndex: number): void;
    public _font_set_texture_image(fontRid: RID, size: Vector2i, textureIndex: number, image: Image): void;
    public _font_get_texture_image(fontRid: RID, size: Vector2i, textureIndex: number): Image;
    public _font_set_texture_offsets(fontRid: RID, size: Vector2i, textureIndex: number, offset: PackedInt32Array): void;
    public _font_get_texture_offsets(fontRid: RID, size: Vector2i, textureIndex: number): PackedInt32Array;
    public _font_get_glyph_list(fontRid: RID, size: Vector2i): PackedInt32Array;
    public _font_clear_glyphs(fontRid: RID, size: Vector2i): void;
    public _font_remove_glyph(fontRid: RID, size: Vector2i, glyph: number): void;
    public _font_get_glyph_advance(fontRid: RID, size: number, glyph: number): Vector2;
    public _font_set_glyph_advance(fontRid: RID, size: number, glyph: number, advance: Vector2): void;
    public _font_get_glyph_offset(fontRid: RID, size: Vector2i, glyph: number): Vector2;
    public _font_set_glyph_offset(fontRid: RID, size: Vector2i, glyph: number, offset: Vector2): void;
    public _font_get_glyph_size(fontRid: RID, size: Vector2i, glyph: number): Vector2;
    public _font_set_glyph_size(fontRid: RID, size: Vector2i, glyph: number, glSize: Vector2): void;
    public _font_get_glyph_uv_rect(fontRid: RID, size: Vector2i, glyph: number): Rect2;
    public _font_set_glyph_uv_rect(fontRid: RID, size: Vector2i, glyph: number, uvRect: Rect2): void;
    public _font_get_glyph_texture_idx(fontRid: RID, size: Vector2i, glyph: number): number;
    public _font_set_glyph_texture_idx(fontRid: RID, size: Vector2i, glyph: number, textureIdx: number): void;
    public _font_get_glyph_texture_rid(fontRid: RID, size: Vector2i, glyph: number): RID;
    public _font_get_glyph_texture_size(fontRid: RID, size: Vector2i, glyph: number): Vector2;
    public _font_get_glyph_contours(fontRid: RID, size: number, index: number): Dictionary;
    public _font_get_kerning_list(fontRid: RID, size: number): Array<any>;
    public _font_clear_kerning_map(fontRid: RID, size: number): void;
    public _font_remove_kerning(fontRid: RID, size: number, glyphPair: Vector2i): void;
    public _font_set_kerning(fontRid: RID, size: number, glyphPair: Vector2i, kerning: Vector2): void;
    public _font_get_kerning(fontRid: RID, size: number, glyphPair: Vector2i): Vector2;
    public _font_get_glyph_index(fontRid: RID, size: number, char: number, variationSelector: number): number;
    public _font_get_char_from_glyph_index(fontRid: RID, size: number, glyphIndex: number): number;
    public _font_has_char(fontRid: RID, char: number): boolean;
    public _font_get_supported_chars(fontRid: RID): GDString;
    public _font_get_supported_glyphs(fontRid: RID): PackedInt32Array;
    public _font_render_range(fontRid: RID, size: Vector2i, start: number, end: number): void;
    public _font_render_glyph(fontRid: RID, size: Vector2i, index: number): void;
    public _font_draw_glyph(fontRid: RID, canvas: RID, size: number, pos: Vector2, index: number, color: Color, oversampling: number): void;
    public _font_draw_glyph_outline(fontRid: RID, canvas: RID, size: number, outlineSize: number, pos: Vector2, index: number, color: Color, oversampling: number): void;
    public _font_is_language_supported(fontRid: RID, language: GDString | StringName | string): boolean;
    public _font_set_language_support_override(fontRid: RID, language: GDString | StringName | string, supported: boolean): void;
    public _font_get_language_support_override(fontRid: RID, language: GDString | StringName | string): boolean;
    public _font_remove_language_support_override(fontRid: RID, language: GDString | StringName | string): void;
    public _font_get_language_support_overrides(fontRid: RID): PackedStringArray;
    public _font_is_script_supported(fontRid: RID, script: GDString | StringName | string): boolean;
    public _font_set_script_support_override(fontRid: RID, script: GDString | StringName | string, supported: boolean): void;
    public _font_get_script_support_override(fontRid: RID, script: GDString | StringName | string): boolean;
    public _font_remove_script_support_override(fontRid: RID, script: GDString | StringName | string): void;
    public _font_get_script_support_overrides(fontRid: RID): PackedStringArray;
    public _font_set_opentype_feature_overrides(fontRid: RID, overrides: Dictionary): void;
    public _font_get_opentype_feature_overrides(fontRid: RID): Dictionary;
    public _font_supported_feature_list(fontRid: RID): Dictionary;
    public _font_supported_variation_list(fontRid: RID): Dictionary;
    public _font_get_global_oversampling(): number;
    public _font_set_global_oversampling(oversampling: number): void;
    public _reference_oversampling_level(oversampling: number): void;
    public _unreference_oversampling_level(oversampling: number): void;
    public _get_hex_code_box_size(size: number, index: number): Vector2;
    public _draw_hex_code_box(canvas: RID, size: number, pos: Vector2, index: number, color: Color): void;
    public _create_shaped_text(direction: number, orientation: number): RID;
    public _shaped_text_clear(shaped: RID): void;
    public _shaped_text_set_direction(shaped: RID, direction: number): void;
    public _shaped_text_get_direction(shaped: RID): number;
    public _shaped_text_get_inferred_direction(shaped: RID): number;
    public _shaped_text_set_bidi_override(shaped: RID, override: GDArray | Array): void;
    public _shaped_text_set_custom_punctuation(shaped: RID, punct: GDString | StringName | string): void;
    public _shaped_text_get_custom_punctuation(shaped: RID): GDString;
    public _shaped_text_set_custom_ellipsis(shaped: RID, char: number): void;
    public _shaped_text_get_custom_ellipsis(shaped: RID): number;
    public _shaped_text_set_orientation(shaped: RID, orientation: number): void;
    public _shaped_text_get_orientation(shaped: RID): number;
    public _shaped_text_set_preserve_invalid(shaped: RID, enabled: boolean): void;
    public _shaped_text_get_preserve_invalid(shaped: RID): boolean;
    public _shaped_text_set_preserve_control(shaped: RID, enabled: boolean): void;
    public _shaped_text_get_preserve_control(shaped: RID): boolean;
    public _shaped_text_set_spacing(shaped: RID, spacing: number, value: number): void;
    public _shaped_text_get_spacing(shaped: RID, spacing: number): number;
    public _shaped_text_add_string(shaped: RID, text: GDString | StringName | string, fonts: Array<any>, size: number, opentypeFeatures: Dictionary, language: GDString | StringName | string, meta: any): boolean;
    public _shaped_text_add_object(shaped: RID, key: any, size: Vector2, inlineAlign: number, length: number, baseline: number): boolean;
    public _shaped_text_resize_object(shaped: RID, key: any, size: Vector2, inlineAlign: number, baseline: number): boolean;
    public _shaped_get_text(shaped: RID): GDString;
    public _shaped_get_span_count(shaped: RID): number;
    public _shaped_get_span_meta(shaped: RID, index: number): any;
    public _shaped_get_span_embedded_object(shaped: RID, index: number): any;
    public _shaped_get_span_text(shaped: RID, index: number): GDString;
    public _shaped_get_span_object(shaped: RID, index: number): any;
    public _shaped_set_span_update_font(shaped: RID, index: number, fonts: Array<any>, size: number, opentypeFeatures: Dictionary): void;
    public _shaped_get_run_count(shaped: RID): number;
    public _shaped_get_run_text(shaped: RID, index: number): GDString;
    public _shaped_get_run_range(shaped: RID, index: number): Vector2i;
    public _shaped_get_run_font_rid(shaped: RID, index: number): RID;
    public _shaped_get_run_font_size(shaped: RID, index: number): number;
    public _shaped_get_run_language(shaped: RID, index: number): GDString;
    public _shaped_get_run_direction(shaped: RID, index: number): number;
    public _shaped_get_run_object(shaped: RID, index: number): any;
    public _shaped_text_substr(shaped: RID, start: number, length: number): RID;
    public _shaped_text_get_parent(shaped: RID): RID;
    public _shaped_text_fit_to_width(shaped: RID, width: number, justificationFlags: number): number;
    public _shaped_text_tab_align(shaped: RID, tabStops: PackedFloat32Array): number;
    public _shaped_text_shape(shaped: RID): boolean;
    public _shaped_text_update_breaks(shaped: RID): boolean;
    public _shaped_text_update_justification_ops(shaped: RID): boolean;
    public _shaped_text_is_ready(shaped: RID): boolean;
    public _shaped_text_get_glyphs(shaped: RID): any;
    public _shaped_text_sort_logical(shaped: RID): any;
    public _shaped_text_get_glyph_count(shaped: RID): number;
    public _shaped_text_get_range(shaped: RID): Vector2i;
    public _shaped_text_get_line_breaks_adv(shaped: RID, width: PackedFloat32Array, start: number, once: boolean, breakFlags: number): PackedInt32Array;
    public _shaped_text_get_line_breaks(shaped: RID, width: number, start: number, breakFlags: number): PackedInt32Array;
    public _shaped_text_get_word_breaks(shaped: RID, graphemeFlags: number, skigraphemeFlags: number): PackedInt32Array;
    public _shaped_text_get_trim_pos(shaped: RID): number;
    public _shaped_text_get_ellipsis_pos(shaped: RID): number;
    public _shaped_text_get_ellipsis_glyph_count(shaped: RID): number;
    public _shaped_text_get_ellipsis_glyphs(shaped: RID): any;
    public _shaped_text_overrun_trim_to_width(shaped: RID, width: number, trimFlags: number): void;
    public _shaped_text_get_objects(shaped: RID): GDArray;
    public _shaped_text_get_object_rect(shaped: RID, key: any): Rect2;
    public _shaped_text_get_object_range(shaped: RID, key: any): Vector2i;
    public _shaped_text_get_object_glyph(shaped: RID, key: any): number;
    public _shaped_text_get_size(shaped: RID): Vector2;
    public _shaped_text_get_ascent(shaped: RID): number;
    public _shaped_text_get_descent(shaped: RID): number;
    public _shaped_text_get_width(shaped: RID): number;
    public _shaped_text_get_underline_position(shaped: RID): number;
    public _shaped_text_get_underline_thickness(shaped: RID): number;
    public _shaped_text_get_dominant_direction_in_range(shaped: RID, start: number, end: number): number;
    public _shaped_text_get_carets(shaped: RID, position: number, caret: any): void;
    public _shaped_text_get_selection(shaped: RID, start: number, end: number): PackedVector2Array;
    public _shaped_text_hit_test_grapheme(shaped: RID, coord: number): number;
    public _shaped_text_hit_test_position(shaped: RID, coord: number): number;
    public _shaped_text_draw(shaped: RID, canvas: RID, pos: Vector2, clil: number, clir: number, color: Color, oversampling: number): void;
    public _shaped_text_draw_outline(shaped: RID, canvas: RID, pos: Vector2, clil: number, clir: number, outlineSize: number, color: Color, oversampling: number): void;
    public _shaped_text_get_grapheme_bounds(shaped: RID, pos: number): Vector2;
    public _shaped_text_next_grapheme_pos(shaped: RID, pos: number): number;
    public _shaped_text_prev_grapheme_pos(shaped: RID, pos: number): number;
    public _shaped_text_get_character_breaks(shaped: RID): PackedInt32Array;
    public _shaped_text_next_character_pos(shaped: RID, pos: number): number;
    public _shaped_text_prev_character_pos(shaped: RID, pos: number): number;
    public _shaped_text_closest_character_pos(shaped: RID, pos: number): number;
    public _format_number(_number: GDString | StringName | string, language: GDString | StringName | string): GDString;
    public _parse_number(_number: GDString | StringName | string, language: GDString | StringName | string): GDString;
    public _percent_sign(language: GDString | StringName | string): GDString;
    public _strip_diacritics(_string: GDString | StringName | string): GDString;
    public _is_valid_identifier(_string: GDString | StringName | string): boolean;
    public _is_valid_letter(unicode: number): boolean;
    public _string_get_word_breaks(_string: GDString | StringName | string, language: GDString | StringName | string, charsPerLine: number): PackedInt32Array;
    public _string_get_character_breaks(_string: GDString | StringName | string, language: GDString | StringName | string): PackedInt32Array;
    public _is_confusable(_string: GDString | StringName | string, dict: PackedStringArray): number;
    public _spoof_check(_string: GDString | StringName | string): boolean;
    public _string_to_upper(_string: GDString | StringName | string, language: GDString | StringName | string): GDString;
    public _string_to_lower(_string: GDString | StringName | string, language: GDString | StringName | string): GDString;
    public _string_to_title(_string: GDString | StringName | string, language: GDString | StringName | string): GDString;
    public _parse_structured_text(parserType: number, args: GDArray | Array, text: GDString | StringName | string): Array<any>;
    public _cleanup(): void;


}

