
import { RefCounted } from "@godot/classes/ref_counted";
import { Font } from "@godot/classes/font";
export declare class TextParagraph extends RefCounted{
  public clear(): void;
  public set_direction(_direction: number): void;
  public get_direction(): number;
  public set_custom_punctuation(_custom_punctuation: GDString | StringName | string): void;
  public get_custom_punctuation(): String;
  public set_orientation(_orientation: number): void;
  public get_orientation(): number;
  public set_preserve_invalid(_enabled: boolean): void;
  public get_preserve_invalid(): boolean;
  public set_preserve_control(_enabled: boolean): void;
  public get_preserve_control(): boolean;
  public set_bidi_override(_override: GDArray): void;
  public set_dropcap(_text: GDString | StringName | string, _font: Font, _font_size: number, _dropcap_margins: Rect2 = Rect2(0, 0, 0, 0), _language: GDString | StringName | string = ""): boolean;
  public clear_dropcap(): void;
  public add_string(_text: GDString | StringName | string, _font: Font, _font_size: number, _language: GDString | StringName | string = "", _meta: any = null): boolean;
  public add_object(_key: any, _size: Vector2, _inline_align: number = 5, _length: number = 1, _baseline: number = 0.0): boolean;
  public resize_object(_key: any, _size: Vector2, _inline_align: number = 5, _baseline: number = 0.0): boolean;
  public set_alignment(_alignment: number): void;
  public get_alignment(): number;
  public tab_align(_tab_stops: PackedFloat32Array): void;
  public set_break_flags(_flags: number): void;
  public get_break_flags(): number;
  public set_justification_flags(_flags: number): void;
  public get_justification_flags(): number;
  public set_text_overrun_behavior(_overrun_behavior: number): void;
  public get_text_overrun_behavior(): number;
  public set_ellipsis_char(_char: GDString | StringName | string): void;
  public get_ellipsis_char(): String;
  public set_width(_width: number): void;
  public get_width(): number;
  public get_non_wrapped_size(): Vector2;
  public get_size(): Vector2;
  public get_rid(): RID;
  public get_line_rid(_line: number): RID;
  public get_dropcap_rid(): RID;
  public get_line_count(): number;
  public set_max_lines_visible(_max_lines_visible: number): void;
  public get_max_lines_visible(): number;
  public get_line_objects(_line: number): GDArray;
  public get_line_object_rect(_line: number, _key: any): Rect2;
  public get_line_size(_line: number): Vector2;
  public get_line_range(_line: number): Vector2i;
  public get_line_ascent(_line: number): number;
  public get_line_descent(_line: number): number;
  public get_line_width(_line: number): number;
  public get_line_underline_position(_line: number): number;
  public get_line_underline_thickness(_line: number): number;
  public get_dropcap_size(): Vector2;
  public get_dropcap_lines(): number;
  public draw(_canvas: RID, _pos: Vector2, _color: Color = Color(1, 1, 1, 1), _dc_color: Color = Color(1, 1, 1, 1)): void;
  public draw_outline(_canvas: RID, _pos: Vector2, _outline_size: number = 1, _color: Color = Color(1, 1, 1, 1), _dc_color: Color = Color(1, 1, 1, 1)): void;
  public draw_line(_canvas: RID, _pos: Vector2, _line: number, _color: Color = Color(1, 1, 1, 1)): void;
  public draw_line_outline(_canvas: RID, _pos: Vector2, _line: number, _outline_size: number = 1, _color: Color = Color(1, 1, 1, 1)): void;
  public draw_dropcap(_canvas: RID, _pos: Vector2, _color: Color = Color(1, 1, 1, 1)): void;
  public draw_dropcap_outline(_canvas: RID, _pos: Vector2, _outline_size: number = 1, _color: Color = Color(1, 1, 1, 1)): void;
  public hit_test(_coords: Vector2): number;
  public get direction(): number;
  public set direction(value): void;
  public get custom_punctuation(): String;
  public set custom_punctuation(value): void;
  public get orientation(): number;
  public set orientation(value): void;
  public get preserve_invalid(): boolean;
  public set preserve_invalid(value): void;
  public get preserve_control(): boolean;
  public set preserve_control(value): void;
  public get alignment(): number;
  public set alignment(value): void;
  public get break_flags(): number;
  public set break_flags(value): void;
  public get justification_flags(): number;
  public set justification_flags(value): void;
  public get text_overrun_behavior(): number;
  public set text_overrun_behavior(value): void;
  public get ellipsis_char(): String;
  public set ellipsis_char(value): void;
  public get width(): number;
  public set width(value): void;
  public get max_lines_visible(): number;
  public set max_lines_visible(value): void;
}