
import { NavigationPolygon } from "@godot/classes/navigation_polygon";
import { OccluderPolygon2D } from "@godot/classes/occluder_polygon2d";
import { GodotObject } from "@godot/classes/godot_object";
import { Material } from "@godot/classes/material";
export declare class TileData extends GodotObject{
  public set_flip_h(_flip_h: boolean): void;
  public get_flip_h(): boolean;
  public set_flip_v(_flip_v: boolean): void;
  public get_flip_v(): boolean;
  public set_transpose(_transpose: boolean): void;
  public get_transpose(): boolean;
  public set_material(_material: Material): void;
  public get_material(): Material;
  public set_texture_origin(_texture_origin: Vector2i): void;
  public get_texture_origin(): Vector2i;
  public set_modulate(_modulate: Color): void;
  public get_modulate(): Color;
  public set_z_index(_z_index: number): void;
  public get_z_index(): number;
  public set_y_sort_origin(_y_sort_origin: number): void;
  public get_y_sort_origin(): number;
  public set_occluder(_layer_id: number, _occluder_polygon: OccluderPolygon2D): void;
  public get_occluder(_layer_id: number, _flip_h: boolean = false, _flip_v: boolean = false, _transpose: boolean = false): OccluderPolygon2D;
  public set_constant_linear_velocity(_layer_id: number, _velocity: Vector2): void;
  public get_constant_linear_velocity(_layer_id: number): Vector2;
  public set_constant_angular_velocity(_layer_id: number, _velocity: number): void;
  public get_constant_angular_velocity(_layer_id: number): number;
  public set_collision_polygons_count(_layer_id: number, _polygons_count: number): void;
  public get_collision_polygons_count(_layer_id: number): number;
  public add_collision_polygon(_layer_id: number): void;
  public remove_collision_polygon(_layer_id: number, _polygon_index: number): void;
  public set_collision_polygon_points(_layer_id: number, _polygon_index: number, _polygon: PackedVector2Array): void;
  public get_collision_polygon_points(_layer_id: number, _polygon_index: number): PackedVector2Array;
  public set_collision_polygon_one_way(_layer_id: number, _polygon_index: number, _one_way: boolean): void;
  public is_collision_polygon_one_way(_layer_id: number, _polygon_index: number): boolean;
  public set_collision_polygon_one_way_margin(_layer_id: number, _polygon_index: number, _one_way_margin: number): void;
  public get_collision_polygon_one_way_margin(_layer_id: number, _polygon_index: number): number;
  public set_terrain_set(_terrain_set: number): void;
  public get_terrain_set(): number;
  public set_terrain(_terrain: number): void;
  public get_terrain(): number;
  public set_terrain_peering_bit(_peering_bit: number, _terrain: number): void;
  public get_terrain_peering_bit(_peering_bit: number): number;
  public is_valid_terrain_peering_bit(_peering_bit: number): boolean;
  public set_navigation_polygon(_layer_id: number, _navigation_polygon: NavigationPolygon): void;
  public get_navigation_polygon(_layer_id: number, _flip_h: boolean = false, _flip_v: boolean = false, _transpose: boolean = false): NavigationPolygon;
  public set_probability(_probability: number): void;
  public get_probability(): number;
  public set_custom_data(_layer_name: GDString | StringName | string, _value: any): void;
  public get_custom_data(_layer_name: GDString | StringName | string): any;
  public set_custom_data_by_layer_id(_layer_id: number, _value: any): void;
  public get_custom_data_by_layer_id(_layer_id: number): any;
  public get flip_h(): boolean;
  public set flip_h(value): void;
  public get flip_v(): boolean;
  public set flip_v(value): void;
  public get transpose(): boolean;
  public set transpose(value): void;
  public get texture_origin(): Vector2i;
  public set texture_origin(value): void;
  public get modulate(): Color;
  public set modulate(value): void;
  public get material(): CanvasItemMaterial;
  public set material(value): void;
  public get z_index(): number;
  public set z_index(value): void;
  public get y_sort_origin(): number;
  public set y_sort_origin(value): void;
  public get terrain_set(): number;
  public set terrain_set(value): void;
  public get terrain(): number;
  public set terrain(value): void;
  public get probability(): number;
  public set probability(value): void;
  public get changed(): Signal;
}