
import { Node3D } from "@godot/classes/node3d";
export declare class VehicleWheel3D extends Node3D{
  public set_radius(_length: number): void;
  public get_radius(): number;
  public set_suspension_rest_length(_length: number): void;
  public get_suspension_rest_length(): number;
  public set_suspension_travel(_length: number): void;
  public get_suspension_travel(): number;
  public set_suspension_stiffness(_length: number): void;
  public get_suspension_stiffness(): number;
  public set_suspension_max_force(_length: number): void;
  public get_suspension_max_force(): number;
  public set_damping_compression(_length: number): void;
  public get_damping_compression(): number;
  public set_damping_relaxation(_length: number): void;
  public get_damping_relaxation(): number;
  public set_use_as_traction(_enable: boolean): void;
  public is_used_as_traction(): boolean;
  public set_use_as_steering(_enable: boolean): void;
  public is_used_as_steering(): boolean;
  public set_friction_slip(_length: number): void;
  public get_friction_slip(): number;
  public is_in_contact(): boolean;
  public get_contact_body(): Node3D;
  public set_roll_influence(_roll_influence: number): void;
  public get_roll_influence(): number;
  public get_skidinfo(): number;
  public get_rpm(): number;
  public set_engine_force(_engine_force: number): void;
  public get_engine_force(): number;
  public set_brake(_brake: number): void;
  public get_brake(): number;
  public set_steering(_steering: number): void;
  public get_steering(): number;
  public get engine_force(): number;
  public set engine_force(value): void;
  public get brake(): number;
  public set brake(value): void;
  public get steering(): number;
  public set steering(value): void;
  public get use_as_traction(): boolean;
  public set use_as_traction(value): void;
  public get use_as_steering(): boolean;
  public set use_as_steering(value): void;
  public get wheel_roll_influence(): number;
  public set wheel_roll_influence(value): void;
  public get wheel_radius(): number;
  public set wheel_radius(value): void;
  public get wheel_rest_length(): number;
  public set wheel_rest_length(value): void;
  public get wheel_friction_slip(): number;
  public set wheel_friction_slip(value): void;
  public get suspension_travel(): number;
  public set suspension_travel(value): void;
  public get suspension_stiffness(): number;
  public set suspension_stiffness(value): void;
  public get suspension_max_force(): number;
  public set suspension_max_force(value): void;
  public get damping_compression(): number;
  public set damping_compression(value): void;
  public get damping_relaxation(): number;
  public set damping_relaxation(value): void;
}