
#include <godot_cpp/classes/physics_direct_body_state3d.hpp>
#include <godot_cpp/classes/physics_direct_space_state3d.hpp>
#include <godot_cpp/classes/physics_server3d.hpp>
#include <godot_cpp/classes/physics_server3d_extension.hpp>
#include <godot_cpp/classes/physics_server3d_extension_motion_result.hpp>
#include <godot_cpp/classes/physics_server3d_rendering_server_handler.hpp>
#include <godot_cpp/variant/aabb.hpp>
#include <godot_cpp/variant/callable.hpp>
#include <godot_cpp/variant/packed_vector3_array.hpp>
#include <godot_cpp/variant/rid.hpp>
#include <godot_cpp/variant/transform3d.hpp>
#include <godot_cpp/variant/typed_array.hpp>
#include <godot_cpp/variant/variant.hpp>
#include <godot_cpp/variant/vector3.hpp>
#include <string>

#include "qjspp.hpp"
#include "register/register_classes.h"

using namespace godot;

void register_classes_PhysicsServer3DExtension() {
	qjs::Context::Module &_module = get_General_module();
	_module.class_<PhysicsServer3DExtension>("PhysicsServer3DExtension")
			.constructor<>()
			.base<PhysicsServer3D>()
			.fun<static_cast<RID (PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_world_boundary_shape_create)>((new std::string("_world_boundary_shape_create"))->c_str())
			.fun<static_cast<RID (PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_separation_ray_shape_create)>((new std::string("_separation_ray_shape_create"))->c_str())
			.fun<static_cast<RID (PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_sphere_shape_create)>((new std::string("_sphere_shape_create"))->c_str())
			.fun<static_cast<RID (PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_box_shape_create)>((new std::string("_box_shape_create"))->c_str())
			.fun<static_cast<RID (PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_capsule_shape_create)>((new std::string("_capsule_shape_create"))->c_str())
			.fun<static_cast<RID (PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_cylinder_shape_create)>((new std::string("_cylinder_shape_create"))->c_str())
			.fun<static_cast<RID (PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_convex_polygon_shape_create)>((new std::string("_convex_polygon_shape_create"))->c_str())
			.fun<static_cast<RID (PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_concave_polygon_shape_create)>((new std::string("_concave_polygon_shape_create"))->c_str())
			.fun<static_cast<RID (PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_heightmap_shape_create)>((new std::string("_heightmap_shape_create"))->c_str())
			.fun<static_cast<RID (PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_custom_shape_create)>((new std::string("_custom_shape_create"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, const Variant &)>(&PhysicsServer3DExtension::_shape_set_data)>((new std::string("_shape_set_data"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, double)>(&PhysicsServer3DExtension::_shape_set_custom_solver_bias)>((new std::string("_shape_set_custom_solver_bias"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, double)>(&PhysicsServer3DExtension::_shape_set_margin)>((new std::string("_shape_set_margin"))->c_str())
			.fun<static_cast<double (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_shape_get_margin)>((new std::string("_shape_get_margin"))->c_str())
			.fun<static_cast<PhysicsServer3D::ShapeType (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_shape_get_type)>((new std::string("_shape_get_type"))->c_str())
			.fun<static_cast<Variant (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_shape_get_data)>((new std::string("_shape_get_data"))->c_str())
			.fun<static_cast<double (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_shape_get_custom_solver_bias)>((new std::string("_shape_get_custom_solver_bias"))->c_str())
			.fun<static_cast<RID (PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_space_create)>((new std::string("_space_create"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, bool)>(&PhysicsServer3DExtension::_space_set_active)>((new std::string("_space_set_active"))->c_str())
			.fun<static_cast<bool (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_space_is_active)>((new std::string("_space_is_active"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, PhysicsServer3D::SpaceParameter, double)>(&PhysicsServer3DExtension::_space_set_param)>((new std::string("_space_set_param"))->c_str())
			.fun<static_cast<double (PhysicsServer3DExtension::*)(const RID &, PhysicsServer3D::SpaceParameter) const>(&PhysicsServer3DExtension::_space_get_param)>((new std::string("_space_get_param"))->c_str())
			.fun<static_cast<PhysicsDirectSpaceState3D *(PhysicsServer3DExtension::*)(const RID &)>(&PhysicsServer3DExtension::_space_get_direct_state)>((new std::string("_space_get_direct_state"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, int32_t)>(&PhysicsServer3DExtension::_space_set_debug_contacts)>((new std::string("_space_set_debug_contacts"))->c_str())
			.fun<static_cast<PackedVector3Array (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_space_get_contacts)>((new std::string("_space_get_contacts"))->c_str())
			.fun<static_cast<int32_t (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_space_get_contact_count)>((new std::string("_space_get_contact_count"))->c_str())
			.fun<static_cast<RID (PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_area_create)>((new std::string("_area_create"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, const RID &)>(&PhysicsServer3DExtension::_area_set_space)>((new std::string("_area_set_space"))->c_str())
			.fun<static_cast<RID (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_area_get_space)>((new std::string("_area_get_space"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, const RID &, const Transform3D &, bool)>(&PhysicsServer3DExtension::_area_add_shape)>((new std::string("_area_add_shape"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, int32_t, const RID &)>(&PhysicsServer3DExtension::_area_set_shape)>((new std::string("_area_set_shape"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, int32_t, const Transform3D &)>(&PhysicsServer3DExtension::_area_set_shape_transform)>((new std::string("_area_set_shape_transform"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, int32_t, bool)>(&PhysicsServer3DExtension::_area_set_shape_disabled)>((new std::string("_area_set_shape_disabled"))->c_str())
			.fun<static_cast<int32_t (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_area_get_shape_count)>((new std::string("_area_get_shape_count"))->c_str())
			.fun<static_cast<RID (PhysicsServer3DExtension::*)(const RID &, int32_t) const>(&PhysicsServer3DExtension::_area_get_shape)>((new std::string("_area_get_shape"))->c_str())
			.fun<static_cast<Transform3D (PhysicsServer3DExtension::*)(const RID &, int32_t) const>(&PhysicsServer3DExtension::_area_get_shape_transform)>((new std::string("_area_get_shape_transform"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, int32_t)>(&PhysicsServer3DExtension::_area_remove_shape)>((new std::string("_area_remove_shape"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &)>(&PhysicsServer3DExtension::_area_clear_shapes)>((new std::string("_area_clear_shapes"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, uint64_t)>(&PhysicsServer3DExtension::_area_attach_object_instance_id)>((new std::string("_area_attach_object_instance_id"))->c_str())
			.fun<static_cast<uint64_t (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_area_get_object_instance_id)>((new std::string("_area_get_object_instance_id"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, PhysicsServer3D::AreaParameter, const Variant &)>(&PhysicsServer3DExtension::_area_set_param)>((new std::string("_area_set_param"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, const Transform3D &)>(&PhysicsServer3DExtension::_area_set_transform)>((new std::string("_area_set_transform"))->c_str())
			.fun<static_cast<Variant (PhysicsServer3DExtension::*)(const RID &, PhysicsServer3D::AreaParameter) const>(&PhysicsServer3DExtension::_area_get_param)>((new std::string("_area_get_param"))->c_str())
			.fun<static_cast<Transform3D (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_area_get_transform)>((new std::string("_area_get_transform"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, uint32_t)>(&PhysicsServer3DExtension::_area_set_collision_layer)>((new std::string("_area_set_collision_layer"))->c_str())
			.fun<static_cast<uint32_t (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_area_get_collision_layer)>((new std::string("_area_get_collision_layer"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, uint32_t)>(&PhysicsServer3DExtension::_area_set_collision_mask)>((new std::string("_area_set_collision_mask"))->c_str())
			.fun<static_cast<uint32_t (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_area_get_collision_mask)>((new std::string("_area_get_collision_mask"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, bool)>(&PhysicsServer3DExtension::_area_set_monitorable)>((new std::string("_area_set_monitorable"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, bool)>(&PhysicsServer3DExtension::_area_set_ray_pickable)>((new std::string("_area_set_ray_pickable"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, const Callable &)>(&PhysicsServer3DExtension::_area_set_monitor_callback)>((new std::string("_area_set_monitor_callback"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, const Callable &)>(&PhysicsServer3DExtension::_area_set_area_monitor_callback)>((new std::string("_area_set_area_monitor_callback"))->c_str())
			.fun<static_cast<RID (PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_body_create)>((new std::string("_body_create"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, const RID &)>(&PhysicsServer3DExtension::_body_set_space)>((new std::string("_body_set_space"))->c_str())
			.fun<static_cast<RID (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_body_get_space)>((new std::string("_body_get_space"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, PhysicsServer3D::BodyMode)>(&PhysicsServer3DExtension::_body_set_mode)>((new std::string("_body_set_mode"))->c_str())
			.fun<static_cast<PhysicsServer3D::BodyMode (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_body_get_mode)>((new std::string("_body_get_mode"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, const RID &, const Transform3D &, bool)>(&PhysicsServer3DExtension::_body_add_shape)>((new std::string("_body_add_shape"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, int32_t, const RID &)>(&PhysicsServer3DExtension::_body_set_shape)>((new std::string("_body_set_shape"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, int32_t, const Transform3D &)>(&PhysicsServer3DExtension::_body_set_shape_transform)>((new std::string("_body_set_shape_transform"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, int32_t, bool)>(&PhysicsServer3DExtension::_body_set_shape_disabled)>((new std::string("_body_set_shape_disabled"))->c_str())
			.fun<static_cast<int32_t (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_body_get_shape_count)>((new std::string("_body_get_shape_count"))->c_str())
			.fun<static_cast<RID (PhysicsServer3DExtension::*)(const RID &, int32_t) const>(&PhysicsServer3DExtension::_body_get_shape)>((new std::string("_body_get_shape"))->c_str())
			.fun<static_cast<Transform3D (PhysicsServer3DExtension::*)(const RID &, int32_t) const>(&PhysicsServer3DExtension::_body_get_shape_transform)>((new std::string("_body_get_shape_transform"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, int32_t)>(&PhysicsServer3DExtension::_body_remove_shape)>((new std::string("_body_remove_shape"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &)>(&PhysicsServer3DExtension::_body_clear_shapes)>((new std::string("_body_clear_shapes"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, uint64_t)>(&PhysicsServer3DExtension::_body_attach_object_instance_id)>((new std::string("_body_attach_object_instance_id"))->c_str())
			.fun<static_cast<uint64_t (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_body_get_object_instance_id)>((new std::string("_body_get_object_instance_id"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, bool)>(&PhysicsServer3DExtension::_body_set_enable_continuous_collision_detection)>((new std::string("_body_set_enable_continuous_collision_detection"))->c_str())
			.fun<static_cast<bool (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_body_is_continuous_collision_detection_enabled)>((new std::string("_body_is_continuous_collision_detection_enabled"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, uint32_t)>(&PhysicsServer3DExtension::_body_set_collision_layer)>((new std::string("_body_set_collision_layer"))->c_str())
			.fun<static_cast<uint32_t (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_body_get_collision_layer)>((new std::string("_body_get_collision_layer"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, uint32_t)>(&PhysicsServer3DExtension::_body_set_collision_mask)>((new std::string("_body_set_collision_mask"))->c_str())
			.fun<static_cast<uint32_t (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_body_get_collision_mask)>((new std::string("_body_get_collision_mask"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, double)>(&PhysicsServer3DExtension::_body_set_collision_priority)>((new std::string("_body_set_collision_priority"))->c_str())
			.fun<static_cast<double (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_body_get_collision_priority)>((new std::string("_body_get_collision_priority"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, uint32_t)>(&PhysicsServer3DExtension::_body_set_user_flags)>((new std::string("_body_set_user_flags"))->c_str())
			.fun<static_cast<uint32_t (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_body_get_user_flags)>((new std::string("_body_get_user_flags"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, PhysicsServer3D::BodyParameter, const Variant &)>(&PhysicsServer3DExtension::_body_set_param)>((new std::string("_body_set_param"))->c_str())
			.fun<static_cast<Variant (PhysicsServer3DExtension::*)(const RID &, PhysicsServer3D::BodyParameter) const>(&PhysicsServer3DExtension::_body_get_param)>((new std::string("_body_get_param"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &)>(&PhysicsServer3DExtension::_body_reset_mass_properties)>((new std::string("_body_reset_mass_properties"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, PhysicsServer3D::BodyState, const Variant &)>(&PhysicsServer3DExtension::_body_set_state)>((new std::string("_body_set_state"))->c_str())
			.fun<static_cast<Variant (PhysicsServer3DExtension::*)(const RID &, PhysicsServer3D::BodyState) const>(&PhysicsServer3DExtension::_body_get_state)>((new std::string("_body_get_state"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, const Vector3 &)>(&PhysicsServer3DExtension::_body_apply_central_impulse)>((new std::string("_body_apply_central_impulse"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, const Vector3 &, const Vector3 &)>(&PhysicsServer3DExtension::_body_apply_impulse)>((new std::string("_body_apply_impulse"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, const Vector3 &)>(&PhysicsServer3DExtension::_body_apply_torque_impulse)>((new std::string("_body_apply_torque_impulse"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, const Vector3 &)>(&PhysicsServer3DExtension::_body_apply_central_force)>((new std::string("_body_apply_central_force"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, const Vector3 &, const Vector3 &)>(&PhysicsServer3DExtension::_body_apply_force)>((new std::string("_body_apply_force"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, const Vector3 &)>(&PhysicsServer3DExtension::_body_apply_torque)>((new std::string("_body_apply_torque"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, const Vector3 &)>(&PhysicsServer3DExtension::_body_add_constant_central_force)>((new std::string("_body_add_constant_central_force"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, const Vector3 &, const Vector3 &)>(&PhysicsServer3DExtension::_body_add_constant_force)>((new std::string("_body_add_constant_force"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, const Vector3 &)>(&PhysicsServer3DExtension::_body_add_constant_torque)>((new std::string("_body_add_constant_torque"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, const Vector3 &)>(&PhysicsServer3DExtension::_body_set_constant_force)>((new std::string("_body_set_constant_force"))->c_str())
			.fun<static_cast<Vector3 (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_body_get_constant_force)>((new std::string("_body_get_constant_force"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, const Vector3 &)>(&PhysicsServer3DExtension::_body_set_constant_torque)>((new std::string("_body_set_constant_torque"))->c_str())
			.fun<static_cast<Vector3 (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_body_get_constant_torque)>((new std::string("_body_get_constant_torque"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, const Vector3 &)>(&PhysicsServer3DExtension::_body_set_axis_velocity)>((new std::string("_body_set_axis_velocity"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, PhysicsServer3D::BodyAxis, bool)>(&PhysicsServer3DExtension::_body_set_axis_lock)>((new std::string("_body_set_axis_lock"))->c_str())
			.fun<static_cast<bool (PhysicsServer3DExtension::*)(const RID &, PhysicsServer3D::BodyAxis) const>(&PhysicsServer3DExtension::_body_is_axis_locked)>((new std::string("_body_is_axis_locked"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, const RID &)>(&PhysicsServer3DExtension::_body_add_collision_exception)>((new std::string("_body_add_collision_exception"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, const RID &)>(&PhysicsServer3DExtension::_body_remove_collision_exception)>((new std::string("_body_remove_collision_exception"))->c_str())
			.fun<static_cast<TypedArray<RID> (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_body_get_collision_exceptions)>((new std::string("_body_get_collision_exceptions"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, int32_t)>(&PhysicsServer3DExtension::_body_set_max_contacts_reported)>((new std::string("_body_set_max_contacts_reported"))->c_str())
			.fun<static_cast<int32_t (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_body_get_max_contacts_reported)>((new std::string("_body_get_max_contacts_reported"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, double)>(&PhysicsServer3DExtension::_body_set_contacts_reported_depth_threshold)>((new std::string("_body_set_contacts_reported_depth_threshold"))->c_str())
			.fun<static_cast<double (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_body_get_contacts_reported_depth_threshold)>((new std::string("_body_get_contacts_reported_depth_threshold"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, bool)>(&PhysicsServer3DExtension::_body_set_omit_force_integration)>((new std::string("_body_set_omit_force_integration"))->c_str())
			.fun<static_cast<bool (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_body_is_omitting_force_integration)>((new std::string("_body_is_omitting_force_integration"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, const Callable &)>(&PhysicsServer3DExtension::_body_set_state_sync_callback)>((new std::string("_body_set_state_sync_callback"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, const Callable &, const Variant &)>(&PhysicsServer3DExtension::_body_set_force_integration_callback)>((new std::string("_body_set_force_integration_callback"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, bool)>(&PhysicsServer3DExtension::_body_set_ray_pickable)>((new std::string("_body_set_ray_pickable"))->c_str())
			.fun<static_cast<bool (PhysicsServer3DExtension::*)(const RID &, const Transform3D &, const Vector3 &, double, int32_t, bool, bool, PhysicsServer3DExtensionMotionResult *) const>(&PhysicsServer3DExtension::_body_test_motion)>((new std::string("_body_test_motion"))->c_str())
			.fun<static_cast<PhysicsDirectBodyState3D *(PhysicsServer3DExtension::*)(const RID &)>(&PhysicsServer3DExtension::_body_get_direct_state)>((new std::string("_body_get_direct_state"))->c_str())
			.fun<static_cast<RID (PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_soft_body_create)>((new std::string("_soft_body_create"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, PhysicsServer3DRenderingServerHandler *)>(&PhysicsServer3DExtension::_soft_body_update_rendering_server)>((new std::string("_soft_body_update_rendering_server"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, const RID &)>(&PhysicsServer3DExtension::_soft_body_set_space)>((new std::string("_soft_body_set_space"))->c_str())
			.fun<static_cast<RID (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_soft_body_get_space)>((new std::string("_soft_body_get_space"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, bool)>(&PhysicsServer3DExtension::_soft_body_set_ray_pickable)>((new std::string("_soft_body_set_ray_pickable"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, uint32_t)>(&PhysicsServer3DExtension::_soft_body_set_collision_layer)>((new std::string("_soft_body_set_collision_layer"))->c_str())
			.fun<static_cast<uint32_t (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_soft_body_get_collision_layer)>((new std::string("_soft_body_get_collision_layer"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, uint32_t)>(&PhysicsServer3DExtension::_soft_body_set_collision_mask)>((new std::string("_soft_body_set_collision_mask"))->c_str())
			.fun<static_cast<uint32_t (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_soft_body_get_collision_mask)>((new std::string("_soft_body_get_collision_mask"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, const RID &)>(&PhysicsServer3DExtension::_soft_body_add_collision_exception)>((new std::string("_soft_body_add_collision_exception"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, const RID &)>(&PhysicsServer3DExtension::_soft_body_remove_collision_exception)>((new std::string("_soft_body_remove_collision_exception"))->c_str())
			.fun<static_cast<TypedArray<RID> (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_soft_body_get_collision_exceptions)>((new std::string("_soft_body_get_collision_exceptions"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, PhysicsServer3D::BodyState, const Variant &)>(&PhysicsServer3DExtension::_soft_body_set_state)>((new std::string("_soft_body_set_state"))->c_str())
			.fun<static_cast<Variant (PhysicsServer3DExtension::*)(const RID &, PhysicsServer3D::BodyState) const>(&PhysicsServer3DExtension::_soft_body_get_state)>((new std::string("_soft_body_get_state"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, const Transform3D &)>(&PhysicsServer3DExtension::_soft_body_set_transform)>((new std::string("_soft_body_set_transform"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, int32_t)>(&PhysicsServer3DExtension::_soft_body_set_simulation_precision)>((new std::string("_soft_body_set_simulation_precision"))->c_str())
			.fun<static_cast<int32_t (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_soft_body_get_simulation_precision)>((new std::string("_soft_body_get_simulation_precision"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, double)>(&PhysicsServer3DExtension::_soft_body_set_total_mass)>((new std::string("_soft_body_set_total_mass"))->c_str())
			.fun<static_cast<double (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_soft_body_get_total_mass)>((new std::string("_soft_body_get_total_mass"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, double)>(&PhysicsServer3DExtension::_soft_body_set_linear_stiffness)>((new std::string("_soft_body_set_linear_stiffness"))->c_str())
			.fun<static_cast<double (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_soft_body_get_linear_stiffness)>((new std::string("_soft_body_get_linear_stiffness"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, double)>(&PhysicsServer3DExtension::_soft_body_set_pressure_coefficient)>((new std::string("_soft_body_set_pressure_coefficient"))->c_str())
			.fun<static_cast<double (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_soft_body_get_pressure_coefficient)>((new std::string("_soft_body_get_pressure_coefficient"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, double)>(&PhysicsServer3DExtension::_soft_body_set_damping_coefficient)>((new std::string("_soft_body_set_damping_coefficient"))->c_str())
			.fun<static_cast<double (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_soft_body_get_damping_coefficient)>((new std::string("_soft_body_get_damping_coefficient"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, double)>(&PhysicsServer3DExtension::_soft_body_set_drag_coefficient)>((new std::string("_soft_body_set_drag_coefficient"))->c_str())
			.fun<static_cast<double (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_soft_body_get_drag_coefficient)>((new std::string("_soft_body_get_drag_coefficient"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, const RID &)>(&PhysicsServer3DExtension::_soft_body_set_mesh)>((new std::string("_soft_body_set_mesh"))->c_str())
			.fun<static_cast<AABB (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_soft_body_get_bounds)>((new std::string("_soft_body_get_bounds"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, int32_t, const Vector3 &)>(&PhysicsServer3DExtension::_soft_body_move_point)>((new std::string("_soft_body_move_point"))->c_str())
			.fun<static_cast<Vector3 (PhysicsServer3DExtension::*)(const RID &, int32_t) const>(&PhysicsServer3DExtension::_soft_body_get_point_global_position)>((new std::string("_soft_body_get_point_global_position"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &)>(&PhysicsServer3DExtension::_soft_body_remove_all_pinned_points)>((new std::string("_soft_body_remove_all_pinned_points"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, int32_t, bool)>(&PhysicsServer3DExtension::_soft_body_pin_point)>((new std::string("_soft_body_pin_point"))->c_str())
			.fun<static_cast<bool (PhysicsServer3DExtension::*)(const RID &, int32_t) const>(&PhysicsServer3DExtension::_soft_body_is_point_pinned)>((new std::string("_soft_body_is_point_pinned"))->c_str())
			.fun<static_cast<RID (PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_joint_create)>((new std::string("_joint_create"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &)>(&PhysicsServer3DExtension::_joint_clear)>((new std::string("_joint_clear"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, const RID &, const Vector3 &, const RID &, const Vector3 &)>(&PhysicsServer3DExtension::_joint_make_pin)>((new std::string("_joint_make_pin"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, PhysicsServer3D::PinJointParam, double)>(&PhysicsServer3DExtension::_pin_joint_set_param)>((new std::string("_pin_joint_set_param"))->c_str())
			.fun<static_cast<double (PhysicsServer3DExtension::*)(const RID &, PhysicsServer3D::PinJointParam) const>(&PhysicsServer3DExtension::_pin_joint_get_param)>((new std::string("_pin_joint_get_param"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, const Vector3 &)>(&PhysicsServer3DExtension::_pin_joint_set_local_a)>((new std::string("_pin_joint_set_local_a"))->c_str())
			.fun<static_cast<Vector3 (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_pin_joint_get_local_a)>((new std::string("_pin_joint_get_local_a"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, const Vector3 &)>(&PhysicsServer3DExtension::_pin_joint_set_local_b)>((new std::string("_pin_joint_set_local_b"))->c_str())
			.fun<static_cast<Vector3 (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_pin_joint_get_local_b)>((new std::string("_pin_joint_get_local_b"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, const RID &, const Transform3D &, const RID &, const Transform3D &)>(&PhysicsServer3DExtension::_joint_make_hinge)>((new std::string("_joint_make_hinge"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, const RID &, const Vector3 &, const Vector3 &, const RID &, const Vector3 &, const Vector3 &)>(&PhysicsServer3DExtension::_joint_make_hinge_simple)>((new std::string("_joint_make_hinge_simple"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, PhysicsServer3D::HingeJointParam, double)>(&PhysicsServer3DExtension::_hinge_joint_set_param)>((new std::string("_hinge_joint_set_param"))->c_str())
			.fun<static_cast<double (PhysicsServer3DExtension::*)(const RID &, PhysicsServer3D::HingeJointParam) const>(&PhysicsServer3DExtension::_hinge_joint_get_param)>((new std::string("_hinge_joint_get_param"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, PhysicsServer3D::HingeJointFlag, bool)>(&PhysicsServer3DExtension::_hinge_joint_set_flag)>((new std::string("_hinge_joint_set_flag"))->c_str())
			.fun<static_cast<bool (PhysicsServer3DExtension::*)(const RID &, PhysicsServer3D::HingeJointFlag) const>(&PhysicsServer3DExtension::_hinge_joint_get_flag)>((new std::string("_hinge_joint_get_flag"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, const RID &, const Transform3D &, const RID &, const Transform3D &)>(&PhysicsServer3DExtension::_joint_make_slider)>((new std::string("_joint_make_slider"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, PhysicsServer3D::SliderJointParam, double)>(&PhysicsServer3DExtension::_slider_joint_set_param)>((new std::string("_slider_joint_set_param"))->c_str())
			.fun<static_cast<double (PhysicsServer3DExtension::*)(const RID &, PhysicsServer3D::SliderJointParam) const>(&PhysicsServer3DExtension::_slider_joint_get_param)>((new std::string("_slider_joint_get_param"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, const RID &, const Transform3D &, const RID &, const Transform3D &)>(&PhysicsServer3DExtension::_joint_make_cone_twist)>((new std::string("_joint_make_cone_twist"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, PhysicsServer3D::ConeTwistJointParam, double)>(&PhysicsServer3DExtension::_cone_twist_joint_set_param)>((new std::string("_cone_twist_joint_set_param"))->c_str())
			.fun<static_cast<double (PhysicsServer3DExtension::*)(const RID &, PhysicsServer3D::ConeTwistJointParam) const>(&PhysicsServer3DExtension::_cone_twist_joint_get_param)>((new std::string("_cone_twist_joint_get_param"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, const RID &, const Transform3D &, const RID &, const Transform3D &)>(&PhysicsServer3DExtension::_joint_make_generic_6dof)>((new std::string("_joint_make_generic_6dof"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, Vector3::Axis, PhysicsServer3D::G6DOFJointAxisParam, double)>(&PhysicsServer3DExtension::_generic_6dof_joint_set_param)>((new std::string("_generic_6dof_joint_set_param"))->c_str())
			.fun<static_cast<double (PhysicsServer3DExtension::*)(const RID &, Vector3::Axis, PhysicsServer3D::G6DOFJointAxisParam) const>(&PhysicsServer3DExtension::_generic_6dof_joint_get_param)>((new std::string("_generic_6dof_joint_get_param"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, Vector3::Axis, PhysicsServer3D::G6DOFJointAxisFlag, bool)>(&PhysicsServer3DExtension::_generic_6dof_joint_set_flag)>((new std::string("_generic_6dof_joint_set_flag"))->c_str())
			.fun<static_cast<bool (PhysicsServer3DExtension::*)(const RID &, Vector3::Axis, PhysicsServer3D::G6DOFJointAxisFlag) const>(&PhysicsServer3DExtension::_generic_6dof_joint_get_flag)>((new std::string("_generic_6dof_joint_get_flag"))->c_str())
			.fun<static_cast<PhysicsServer3D::JointType (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_joint_get_type)>((new std::string("_joint_get_type"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, int32_t)>(&PhysicsServer3DExtension::_joint_set_solver_priority)>((new std::string("_joint_set_solver_priority"))->c_str())
			.fun<static_cast<int32_t (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_joint_get_solver_priority)>((new std::string("_joint_get_solver_priority"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &, bool)>(&PhysicsServer3DExtension::_joint_disable_collisions_between_bodies)>((new std::string("_joint_disable_collisions_between_bodies"))->c_str())
			.fun<static_cast<bool (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::_joint_is_disabled_collisions_between_bodies)>((new std::string("_joint_is_disabled_collisions_between_bodies"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(const RID &)>(&PhysicsServer3DExtension::_free_rid)>((new std::string("_free_rid"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(bool)>(&PhysicsServer3DExtension::_set_active)>((new std::string("_set_active"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_init)>((new std::string("_init"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)(double)>(&PhysicsServer3DExtension::_step)>((new std::string("_step"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_sync)>((new std::string("_sync"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_flush_queries)>((new std::string("_flush_queries"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_end_sync)>((new std::string("_end_sync"))->c_str())
			.fun<static_cast<void (PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_finish)>((new std::string("_finish"))->c_str())
			.fun<static_cast<bool (PhysicsServer3DExtension::*)() const>(&PhysicsServer3DExtension::_is_flushing_queries)>((new std::string("_is_flushing_queries"))->c_str())
			.fun<static_cast<int32_t (PhysicsServer3DExtension::*)(PhysicsServer3D::ProcessInfo)>(&PhysicsServer3DExtension::_get_process_info)>((new std::string("_get_process_info"))->c_str())
			.fun<static_cast<bool (PhysicsServer3DExtension::*)(const RID &) const>(&PhysicsServer3DExtension::body_test_motion_is_excluding_body)>((new std::string("body_test_motion_is_excluding_body"))->c_str())
			.fun<static_cast<bool (PhysicsServer3DExtension::*)(uint64_t) const>(&PhysicsServer3DExtension::body_test_motion_is_excluding_object)>((new std::string("body_test_motion_is_excluding_object"))->c_str());
}