
#include <godot_cpp/classes/caret_info.hpp>
#include <godot_cpp/classes/global_constants.hpp>
#include <godot_cpp/classes/glyph.hpp>
#include <godot_cpp/classes/image.hpp>
#include <godot_cpp/classes/ref.hpp>
#include <godot_cpp/classes/text_server.hpp>
#include <godot_cpp/classes/text_server_extension.hpp>
#include <godot_cpp/core/type_info.hpp>
#include <godot_cpp/variant/array.hpp>
#include <godot_cpp/variant/color.hpp>
#include <godot_cpp/variant/dictionary.hpp>
#include <godot_cpp/variant/packed_byte_array.hpp>
#include <godot_cpp/variant/packed_float32_array.hpp>
#include <godot_cpp/variant/packed_int32_array.hpp>
#include <godot_cpp/variant/packed_string_array.hpp>
#include <godot_cpp/variant/packed_vector2_array.hpp>
#include <godot_cpp/variant/rect2.hpp>
#include <godot_cpp/variant/rid.hpp>
#include <godot_cpp/variant/string.hpp>
#include <godot_cpp/variant/transform2d.hpp>
#include <godot_cpp/variant/typed_array.hpp>
#include <godot_cpp/variant/variant.hpp>
#include <godot_cpp/variant/vector2.hpp>
#include <godot_cpp/variant/vector2i.hpp>
#include <godot_cpp/variant/vector3i.hpp>
#include <string>

#include "qjspp.hpp"
#include "register/register_classes.h"

using namespace godot;

void register_classes_TextServerExtension() {
	qjs::Context::Module &_module = get_General_module();
	_module.class_<TextServerExtension>("TextServerExtension")
			.constructor<>()
			.base<TextServer>()
			.fun<static_cast<bool (TextServerExtension::*)(TextServer::Feature) const>(&TextServerExtension::_has_feature)>((new std::string("_has_feature"))->c_str())
			.fun<static_cast<String (TextServerExtension::*)() const>(&TextServerExtension::_get_name)>((new std::string("_get_name"))->c_str())
			.fun<static_cast<int64_t (TextServerExtension::*)() const>(&TextServerExtension::_get_features)>((new std::string("_get_features"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &)>(&TextServerExtension::_free_rid)>((new std::string("_free_rid"))->c_str())
			.fun<static_cast<bool (TextServerExtension::*)(const RID &)>(&TextServerExtension::_has)>((new std::string("_has"))->c_str())
			.fun<static_cast<bool (TextServerExtension::*)(const String &)>(&TextServerExtension::_load_support_data)>((new std::string("_load_support_data"))->c_str())
			.fun<static_cast<String (TextServerExtension::*)() const>(&TextServerExtension::_get_support_data_filename)>((new std::string("_get_support_data_filename"))->c_str())
			.fun<static_cast<String (TextServerExtension::*)() const>(&TextServerExtension::_get_support_data_info)>((new std::string("_get_support_data_info"))->c_str())
			.fun<static_cast<bool (TextServerExtension::*)(const String &) const>(&TextServerExtension::_save_support_data)>((new std::string("_save_support_data"))->c_str())
			.fun<static_cast<bool (TextServerExtension::*)(const String &) const>(&TextServerExtension::_is_locale_right_to_left)>((new std::string("_is_locale_right_to_left"))->c_str())
			.fun<static_cast<int64_t (TextServerExtension::*)(const String &) const>(&TextServerExtension::_name_to_tag)>((new std::string("_name_to_tag"))->c_str())
			.fun<static_cast<String (TextServerExtension::*)(int64_t) const>(&TextServerExtension::_tag_to_name)>((new std::string("_tag_to_name"))->c_str())
			.fun<static_cast<RID (TextServerExtension::*)()>(&TextServerExtension::_create_font)>((new std::string("_create_font"))->c_str())
			.fun<static_cast<RID (TextServerExtension::*)(const RID &)>(&TextServerExtension::_create_font_linked_variation)>((new std::string("_create_font_linked_variation"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const PackedByteArray &)>(&TextServerExtension::_font_set_data)>((new std::string("_font_set_data"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const uint8_t *, int64_t)>(&TextServerExtension::_font_set_data_ptr)>((new std::string("_font_set_data_ptr"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, int64_t)>(&TextServerExtension::_font_set_face_index)>((new std::string("_font_set_face_index"))->c_str())
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_face_index)>((new std::string("_font_get_face_index"))->c_str())
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_face_count)>((new std::string("_font_get_face_count"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, BitField<TextServer::FontStyle>)>(&TextServerExtension::_font_set_style)>((new std::string("_font_set_style"))->c_str())
			.fun<static_cast<BitField<TextServer::FontStyle> (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_style)>((new std::string("_font_get_style"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const String &)>(&TextServerExtension::_font_set_name)>((new std::string("_font_set_name"))->c_str())
			.fun<static_cast<String (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_name)>((new std::string("_font_get_name"))->c_str())
			.fun<static_cast<Dictionary (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_ot_name_strings)>((new std::string("_font_get_ot_name_strings"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const String &)>(&TextServerExtension::_font_set_style_name)>((new std::string("_font_set_style_name"))->c_str())
			.fun<static_cast<String (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_style_name)>((new std::string("_font_get_style_name"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, int64_t)>(&TextServerExtension::_font_set_weight)>((new std::string("_font_set_weight"))->c_str())
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_weight)>((new std::string("_font_get_weight"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, int64_t)>(&TextServerExtension::_font_set_stretch)>((new std::string("_font_set_stretch"))->c_str())
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_stretch)>((new std::string("_font_get_stretch"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, TextServer::FontAntialiasing)>(&TextServerExtension::_font_set_antialiasing)>((new std::string("_font_set_antialiasing"))->c_str())
			.fun<static_cast<TextServer::FontAntialiasing (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_antialiasing)>((new std::string("_font_get_antialiasing"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, bool)>(&TextServerExtension::_font_set_disable_embedded_bitmaps)>((new std::string("_font_set_disable_embedded_bitmaps"))->c_str())
			.fun<static_cast<bool (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_disable_embedded_bitmaps)>((new std::string("_font_get_disable_embedded_bitmaps"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, bool)>(&TextServerExtension::_font_set_generate_mipmaps)>((new std::string("_font_set_generate_mipmaps"))->c_str())
			.fun<static_cast<bool (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_generate_mipmaps)>((new std::string("_font_get_generate_mipmaps"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, bool)>(&TextServerExtension::_font_set_multichannel_signed_distance_field)>((new std::string("_font_set_multichannel_signed_distance_field"))->c_str())
			.fun<static_cast<bool (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_is_multichannel_signed_distance_field)>((new std::string("_font_is_multichannel_signed_distance_field"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, int64_t)>(&TextServerExtension::_font_set_msdf_pixel_range)>((new std::string("_font_set_msdf_pixel_range"))->c_str())
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_msdf_pixel_range)>((new std::string("_font_get_msdf_pixel_range"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, int64_t)>(&TextServerExtension::_font_set_msdf_size)>((new std::string("_font_set_msdf_size"))->c_str())
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_msdf_size)>((new std::string("_font_get_msdf_size"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, int64_t)>(&TextServerExtension::_font_set_fixed_size)>((new std::string("_font_set_fixed_size"))->c_str())
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_fixed_size)>((new std::string("_font_get_fixed_size"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, TextServer::FixedSizeScaleMode)>(&TextServerExtension::_font_set_fixed_size_scale_mode)>((new std::string("_font_set_fixed_size_scale_mode"))->c_str())
			.fun<static_cast<TextServer::FixedSizeScaleMode (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_fixed_size_scale_mode)>((new std::string("_font_get_fixed_size_scale_mode"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, bool)>(&TextServerExtension::_font_set_allow_system_fallback)>((new std::string("_font_set_allow_system_fallback"))->c_str())
			.fun<static_cast<bool (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_is_allow_system_fallback)>((new std::string("_font_is_allow_system_fallback"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, bool)>(&TextServerExtension::_font_set_force_autohinter)>((new std::string("_font_set_force_autohinter"))->c_str())
			.fun<static_cast<bool (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_is_force_autohinter)>((new std::string("_font_is_force_autohinter"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, TextServer::Hinting)>(&TextServerExtension::_font_set_hinting)>((new std::string("_font_set_hinting"))->c_str())
			.fun<static_cast<TextServer::Hinting (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_hinting)>((new std::string("_font_get_hinting"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, TextServer::SubpixelPositioning)>(&TextServerExtension::_font_set_subpixel_positioning)>((new std::string("_font_set_subpixel_positioning"))->c_str())
			.fun<static_cast<TextServer::SubpixelPositioning (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_subpixel_positioning)>((new std::string("_font_get_subpixel_positioning"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, double)>(&TextServerExtension::_font_set_embolden)>((new std::string("_font_set_embolden"))->c_str())
			.fun<static_cast<double (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_embolden)>((new std::string("_font_get_embolden"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, TextServer::SpacingType, int64_t)>(&TextServerExtension::_font_set_spacing)>((new std::string("_font_set_spacing"))->c_str())
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &, TextServer::SpacingType) const>(&TextServerExtension::_font_get_spacing)>((new std::string("_font_get_spacing"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, double)>(&TextServerExtension::_font_set_baseline_offset)>((new std::string("_font_set_baseline_offset"))->c_str())
			.fun<static_cast<double (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_baseline_offset)>((new std::string("_font_get_baseline_offset"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const Transform2D &)>(&TextServerExtension::_font_set_transform)>((new std::string("_font_set_transform"))->c_str())
			.fun<static_cast<Transform2D (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_transform)>((new std::string("_font_get_transform"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const Dictionary &)>(&TextServerExtension::_font_set_variation_coordinates)>((new std::string("_font_set_variation_coordinates"))->c_str())
			.fun<static_cast<Dictionary (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_variation_coordinates)>((new std::string("_font_get_variation_coordinates"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, double)>(&TextServerExtension::_font_set_oversampling)>((new std::string("_font_set_oversampling"))->c_str())
			.fun<static_cast<double (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_oversampling)>((new std::string("_font_get_oversampling"))->c_str())
			.fun<static_cast<TypedArray<Vector2i> (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_size_cache_list)>((new std::string("_font_get_size_cache_list"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &)>(&TextServerExtension::_font_clear_size_cache)>((new std::string("_font_clear_size_cache"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const Vector2i &)>(&TextServerExtension::_font_remove_size_cache)>((new std::string("_font_remove_size_cache"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, int64_t, double)>(&TextServerExtension::_font_set_ascent)>((new std::string("_font_set_ascent"))->c_str())
			.fun<static_cast<double (TextServerExtension::*)(const RID &, int64_t) const>(&TextServerExtension::_font_get_ascent)>((new std::string("_font_get_ascent"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, int64_t, double)>(&TextServerExtension::_font_set_descent)>((new std::string("_font_set_descent"))->c_str())
			.fun<static_cast<double (TextServerExtension::*)(const RID &, int64_t) const>(&TextServerExtension::_font_get_descent)>((new std::string("_font_get_descent"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, int64_t, double)>(&TextServerExtension::_font_set_underline_position)>((new std::string("_font_set_underline_position"))->c_str())
			.fun<static_cast<double (TextServerExtension::*)(const RID &, int64_t) const>(&TextServerExtension::_font_get_underline_position)>((new std::string("_font_get_underline_position"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, int64_t, double)>(&TextServerExtension::_font_set_underline_thickness)>((new std::string("_font_set_underline_thickness"))->c_str())
			.fun<static_cast<double (TextServerExtension::*)(const RID &, int64_t) const>(&TextServerExtension::_font_get_underline_thickness)>((new std::string("_font_get_underline_thickness"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, int64_t, double)>(&TextServerExtension::_font_set_scale)>((new std::string("_font_set_scale"))->c_str())
			.fun<static_cast<double (TextServerExtension::*)(const RID &, int64_t) const>(&TextServerExtension::_font_get_scale)>((new std::string("_font_get_scale"))->c_str())
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &, const Vector2i &) const>(&TextServerExtension::_font_get_texture_count)>((new std::string("_font_get_texture_count"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const Vector2i &)>(&TextServerExtension::_font_clear_textures)>((new std::string("_font_clear_textures"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const Vector2i &, int64_t)>(&TextServerExtension::_font_remove_texture)>((new std::string("_font_remove_texture"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const Vector2i &, int64_t, const Ref<Image> &)>(&TextServerExtension::_font_set_texture_image)>((new std::string("_font_set_texture_image"))->c_str())
			.fun<static_cast<Ref<Image> (TextServerExtension::*)(const RID &, const Vector2i &, int64_t) const>(&TextServerExtension::_font_get_texture_image)>((new std::string("_font_get_texture_image"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const Vector2i &, int64_t, const PackedInt32Array &)>(&TextServerExtension::_font_set_texture_offsets)>((new std::string("_font_set_texture_offsets"))->c_str())
			.fun<static_cast<PackedInt32Array (TextServerExtension::*)(const RID &, const Vector2i &, int64_t) const>(&TextServerExtension::_font_get_texture_offsets)>((new std::string("_font_get_texture_offsets"))->c_str())
			.fun<static_cast<PackedInt32Array (TextServerExtension::*)(const RID &, const Vector2i &) const>(&TextServerExtension::_font_get_glyph_list)>((new std::string("_font_get_glyph_list"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const Vector2i &)>(&TextServerExtension::_font_clear_glyphs)>((new std::string("_font_clear_glyphs"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const Vector2i &, int64_t)>(&TextServerExtension::_font_remove_glyph)>((new std::string("_font_remove_glyph"))->c_str())
			.fun<static_cast<Vector2 (TextServerExtension::*)(const RID &, int64_t, int64_t) const>(&TextServerExtension::_font_get_glyph_advance)>((new std::string("_font_get_glyph_advance"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, int64_t, int64_t, const Vector2 &)>(&TextServerExtension::_font_set_glyph_advance)>((new std::string("_font_set_glyph_advance"))->c_str())
			.fun<static_cast<Vector2 (TextServerExtension::*)(const RID &, const Vector2i &, int64_t) const>(&TextServerExtension::_font_get_glyph_offset)>((new std::string("_font_get_glyph_offset"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const Vector2i &, int64_t, const Vector2 &)>(&TextServerExtension::_font_set_glyph_offset)>((new std::string("_font_set_glyph_offset"))->c_str())
			.fun<static_cast<Vector2 (TextServerExtension::*)(const RID &, const Vector2i &, int64_t) const>(&TextServerExtension::_font_get_glyph_size)>((new std::string("_font_get_glyph_size"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const Vector2i &, int64_t, const Vector2 &)>(&TextServerExtension::_font_set_glyph_size)>((new std::string("_font_set_glyph_size"))->c_str())
			.fun<static_cast<Rect2 (TextServerExtension::*)(const RID &, const Vector2i &, int64_t) const>(&TextServerExtension::_font_get_glyph_uv_rect)>((new std::string("_font_get_glyph_uv_rect"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const Vector2i &, int64_t, const Rect2 &)>(&TextServerExtension::_font_set_glyph_uv_rect)>((new std::string("_font_set_glyph_uv_rect"))->c_str())
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &, const Vector2i &, int64_t) const>(&TextServerExtension::_font_get_glyph_texture_idx)>((new std::string("_font_get_glyph_texture_idx"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const Vector2i &, int64_t, int64_t)>(&TextServerExtension::_font_set_glyph_texture_idx)>((new std::string("_font_set_glyph_texture_idx"))->c_str())
			.fun<static_cast<RID (TextServerExtension::*)(const RID &, const Vector2i &, int64_t) const>(&TextServerExtension::_font_get_glyph_texture_rid)>((new std::string("_font_get_glyph_texture_rid"))->c_str())
			.fun<static_cast<Vector2 (TextServerExtension::*)(const RID &, const Vector2i &, int64_t) const>(&TextServerExtension::_font_get_glyph_texture_size)>((new std::string("_font_get_glyph_texture_size"))->c_str())
			.fun<static_cast<Dictionary (TextServerExtension::*)(const RID &, int64_t, int64_t) const>(&TextServerExtension::_font_get_glyph_contours)>((new std::string("_font_get_glyph_contours"))->c_str())
			.fun<static_cast<TypedArray<Vector2i> (TextServerExtension::*)(const RID &, int64_t) const>(&TextServerExtension::_font_get_kerning_list)>((new std::string("_font_get_kerning_list"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, int64_t)>(&TextServerExtension::_font_clear_kerning_map)>((new std::string("_font_clear_kerning_map"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, int64_t, const Vector2i &)>(&TextServerExtension::_font_remove_kerning)>((new std::string("_font_remove_kerning"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, int64_t, const Vector2i &, const Vector2 &)>(&TextServerExtension::_font_set_kerning)>((new std::string("_font_set_kerning"))->c_str())
			.fun<static_cast<Vector2 (TextServerExtension::*)(const RID &, int64_t, const Vector2i &) const>(&TextServerExtension::_font_get_kerning)>((new std::string("_font_get_kerning"))->c_str())
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &, int64_t, int64_t, int64_t) const>(&TextServerExtension::_font_get_glyph_index)>((new std::string("_font_get_glyph_index"))->c_str())
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &, int64_t, int64_t) const>(&TextServerExtension::_font_get_char_from_glyph_index)>((new std::string("_font_get_char_from_glyph_index"))->c_str())
			.fun<static_cast<bool (TextServerExtension::*)(const RID &, int64_t) const>(&TextServerExtension::_font_has_char)>((new std::string("_font_has_char"))->c_str())
			.fun<static_cast<String (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_supported_chars)>((new std::string("_font_get_supported_chars"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const Vector2i &, int64_t, int64_t)>(&TextServerExtension::_font_render_range)>((new std::string("_font_render_range"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const Vector2i &, int64_t)>(&TextServerExtension::_font_render_glyph)>((new std::string("_font_render_glyph"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const RID &, int64_t, const Vector2 &, int64_t, const Color &) const>(&TextServerExtension::_font_draw_glyph)>((new std::string("_font_draw_glyph"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const RID &, int64_t, int64_t, const Vector2 &, int64_t, const Color &) const>(&TextServerExtension::_font_draw_glyph_outline)>((new std::string("_font_draw_glyph_outline"))->c_str())
			.fun<static_cast<bool (TextServerExtension::*)(const RID &, const String &) const>(&TextServerExtension::_font_is_language_supported)>((new std::string("_font_is_language_supported"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const String &, bool)>(&TextServerExtension::_font_set_language_support_override)>((new std::string("_font_set_language_support_override"))->c_str())
			.fun<static_cast<bool (TextServerExtension::*)(const RID &, const String &)>(&TextServerExtension::_font_get_language_support_override)>((new std::string("_font_get_language_support_override"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const String &)>(&TextServerExtension::_font_remove_language_support_override)>((new std::string("_font_remove_language_support_override"))->c_str())
			.fun<static_cast<PackedStringArray (TextServerExtension::*)(const RID &)>(&TextServerExtension::_font_get_language_support_overrides)>((new std::string("_font_get_language_support_overrides"))->c_str())
			.fun<static_cast<bool (TextServerExtension::*)(const RID &, const String &) const>(&TextServerExtension::_font_is_script_supported)>((new std::string("_font_is_script_supported"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const String &, bool)>(&TextServerExtension::_font_set_script_support_override)>((new std::string("_font_set_script_support_override"))->c_str())
			.fun<static_cast<bool (TextServerExtension::*)(const RID &, const String &)>(&TextServerExtension::_font_get_script_support_override)>((new std::string("_font_get_script_support_override"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const String &)>(&TextServerExtension::_font_remove_script_support_override)>((new std::string("_font_remove_script_support_override"))->c_str())
			.fun<static_cast<PackedStringArray (TextServerExtension::*)(const RID &)>(&TextServerExtension::_font_get_script_support_overrides)>((new std::string("_font_get_script_support_overrides"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const Dictionary &)>(&TextServerExtension::_font_set_opentype_feature_overrides)>((new std::string("_font_set_opentype_feature_overrides"))->c_str())
			.fun<static_cast<Dictionary (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_opentype_feature_overrides)>((new std::string("_font_get_opentype_feature_overrides"))->c_str())
			.fun<static_cast<Dictionary (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_supported_feature_list)>((new std::string("_font_supported_feature_list"))->c_str())
			.fun<static_cast<Dictionary (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_supported_variation_list)>((new std::string("_font_supported_variation_list"))->c_str())
			.fun<static_cast<double (TextServerExtension::*)() const>(&TextServerExtension::_font_get_global_oversampling)>((new std::string("_font_get_global_oversampling"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(double)>(&TextServerExtension::_font_set_global_oversampling)>((new std::string("_font_set_global_oversampling"))->c_str())
			.fun<static_cast<Vector2 (TextServerExtension::*)(int64_t, int64_t) const>(&TextServerExtension::_get_hex_code_box_size)>((new std::string("_get_hex_code_box_size"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, int64_t, const Vector2 &, int64_t, const Color &) const>(&TextServerExtension::_draw_hex_code_box)>((new std::string("_draw_hex_code_box"))->c_str())
			.fun<static_cast<RID (TextServerExtension::*)(TextServer::Direction, TextServer::Orientation)>(&TextServerExtension::_create_shaped_text)>((new std::string("_create_shaped_text"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &)>(&TextServerExtension::_shaped_text_clear)>((new std::string("_shaped_text_clear"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, TextServer::Direction)>(&TextServerExtension::_shaped_text_set_direction)>((new std::string("_shaped_text_set_direction"))->c_str())
			.fun<static_cast<TextServer::Direction (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_direction)>((new std::string("_shaped_text_get_direction"))->c_str())
			.fun<static_cast<TextServer::Direction (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_inferred_direction)>((new std::string("_shaped_text_get_inferred_direction"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const Array &)>(&TextServerExtension::_shaped_text_set_bidi_override)>((new std::string("_shaped_text_set_bidi_override"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const String &)>(&TextServerExtension::_shaped_text_set_custom_punctuation)>((new std::string("_shaped_text_set_custom_punctuation"))->c_str())
			.fun<static_cast<String (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_custom_punctuation)>((new std::string("_shaped_text_get_custom_punctuation"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, int64_t)>(&TextServerExtension::_shaped_text_set_custom_ellipsis)>((new std::string("_shaped_text_set_custom_ellipsis"))->c_str())
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_custom_ellipsis)>((new std::string("_shaped_text_get_custom_ellipsis"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, TextServer::Orientation)>(&TextServerExtension::_shaped_text_set_orientation)>((new std::string("_shaped_text_set_orientation"))->c_str())
			.fun<static_cast<TextServer::Orientation (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_orientation)>((new std::string("_shaped_text_get_orientation"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, bool)>(&TextServerExtension::_shaped_text_set_preserve_invalid)>((new std::string("_shaped_text_set_preserve_invalid"))->c_str())
			.fun<static_cast<bool (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_preserve_invalid)>((new std::string("_shaped_text_get_preserve_invalid"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, bool)>(&TextServerExtension::_shaped_text_set_preserve_control)>((new std::string("_shaped_text_set_preserve_control"))->c_str())
			.fun<static_cast<bool (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_preserve_control)>((new std::string("_shaped_text_get_preserve_control"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, TextServer::SpacingType, int64_t)>(&TextServerExtension::_shaped_text_set_spacing)>((new std::string("_shaped_text_set_spacing"))->c_str())
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &, TextServer::SpacingType) const>(&TextServerExtension::_shaped_text_get_spacing)>((new std::string("_shaped_text_get_spacing"))->c_str())
			.fun<static_cast<bool (TextServerExtension::*)(const RID &, const String &, const TypedArray<RID> &, int64_t, const Dictionary &, const String &, const Variant &)>(&TextServerExtension::_shaped_text_add_string)>((new std::string("_shaped_text_add_string"))->c_str())
			.fun<static_cast<bool (TextServerExtension::*)(const RID &, const Variant &, const Vector2 &, InlineAlignment, int64_t, double)>(&TextServerExtension::_shaped_text_add_object)>((new std::string("_shaped_text_add_object"))->c_str())
			.fun<static_cast<bool (TextServerExtension::*)(const RID &, const Variant &, const Vector2 &, InlineAlignment, double)>(&TextServerExtension::_shaped_text_resize_object)>((new std::string("_shaped_text_resize_object"))->c_str())
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_get_span_count)>((new std::string("_shaped_get_span_count"))->c_str())
			.fun<static_cast<Variant (TextServerExtension::*)(const RID &, int64_t) const>(&TextServerExtension::_shaped_get_span_meta)>((new std::string("_shaped_get_span_meta"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, int64_t, const TypedArray<RID> &, int64_t, const Dictionary &)>(&TextServerExtension::_shaped_set_span_update_font)>((new std::string("_shaped_set_span_update_font"))->c_str())
			.fun<static_cast<RID (TextServerExtension::*)(const RID &, int64_t, int64_t) const>(&TextServerExtension::_shaped_text_substr)>((new std::string("_shaped_text_substr"))->c_str())
			.fun<static_cast<RID (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_parent)>((new std::string("_shaped_text_get_parent"))->c_str())
			.fun<static_cast<double (TextServerExtension::*)(const RID &, double, BitField<TextServer::JustificationFlag>)>(&TextServerExtension::_shaped_text_fit_to_width)>((new std::string("_shaped_text_fit_to_width"))->c_str())
			.fun<static_cast<double (TextServerExtension::*)(const RID &, const PackedFloat32Array &)>(&TextServerExtension::_shaped_text_tab_align)>((new std::string("_shaped_text_tab_align"))->c_str())
			.fun<static_cast<bool (TextServerExtension::*)(const RID &)>(&TextServerExtension::_shaped_text_shape)>((new std::string("_shaped_text_shape"))->c_str())
			.fun<static_cast<bool (TextServerExtension::*)(const RID &)>(&TextServerExtension::_shaped_text_update_breaks)>((new std::string("_shaped_text_update_breaks"))->c_str())
			.fun<static_cast<bool (TextServerExtension::*)(const RID &)>(&TextServerExtension::_shaped_text_update_justification_ops)>((new std::string("_shaped_text_update_justification_ops"))->c_str())
			.fun<static_cast<bool (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_is_ready)>((new std::string("_shaped_text_is_ready"))->c_str())
			.fun<static_cast<const Glyph *(TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_glyphs)>((new std::string("_shaped_text_get_glyphs"))->c_str())
			.fun<static_cast<const Glyph *(TextServerExtension::*)(const RID &)>(&TextServerExtension::_shaped_text_sort_logical)>((new std::string("_shaped_text_sort_logical"))->c_str())
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_glyph_count)>((new std::string("_shaped_text_get_glyph_count"))->c_str())
			.fun<static_cast<Vector2i (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_range)>((new std::string("_shaped_text_get_range"))->c_str())
			.fun<static_cast<PackedInt32Array (TextServerExtension::*)(const RID &, const PackedFloat32Array &, int64_t, bool, BitField<TextServer::LineBreakFlag>) const>(&TextServerExtension::_shaped_text_get_line_breaks_adv)>((new std::string("_shaped_text_get_line_breaks_adv"))->c_str())
			.fun<static_cast<PackedInt32Array (TextServerExtension::*)(const RID &, double, int64_t, BitField<TextServer::LineBreakFlag>) const>(&TextServerExtension::_shaped_text_get_line_breaks)>((new std::string("_shaped_text_get_line_breaks"))->c_str())
			.fun<static_cast<PackedInt32Array (TextServerExtension::*)(const RID &, BitField<TextServer::GraphemeFlag>, BitField<TextServer::GraphemeFlag>) const>(&TextServerExtension::_shaped_text_get_word_breaks)>((new std::string("_shaped_text_get_word_breaks"))->c_str())
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_trim_pos)>((new std::string("_shaped_text_get_trim_pos"))->c_str())
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_ellipsis_pos)>((new std::string("_shaped_text_get_ellipsis_pos"))->c_str())
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_ellipsis_glyph_count)>((new std::string("_shaped_text_get_ellipsis_glyph_count"))->c_str())
			.fun<static_cast<const Glyph *(TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_ellipsis_glyphs)>((new std::string("_shaped_text_get_ellipsis_glyphs"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, double, BitField<TextServer::TextOverrunFlag>)>(&TextServerExtension::_shaped_text_overrun_trim_to_width)>((new std::string("_shaped_text_overrun_trim_to_width"))->c_str())
			.fun<static_cast<Array (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_objects)>((new std::string("_shaped_text_get_objects"))->c_str())
			.fun<static_cast<Rect2 (TextServerExtension::*)(const RID &, const Variant &) const>(&TextServerExtension::_shaped_text_get_object_rect)>((new std::string("_shaped_text_get_object_rect"))->c_str())
			.fun<static_cast<Vector2i (TextServerExtension::*)(const RID &, const Variant &) const>(&TextServerExtension::_shaped_text_get_object_range)>((new std::string("_shaped_text_get_object_range"))->c_str())
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &, const Variant &) const>(&TextServerExtension::_shaped_text_get_object_glyph)>((new std::string("_shaped_text_get_object_glyph"))->c_str())
			.fun<static_cast<Vector2 (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_size)>((new std::string("_shaped_text_get_size"))->c_str())
			.fun<static_cast<double (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_ascent)>((new std::string("_shaped_text_get_ascent"))->c_str())
			.fun<static_cast<double (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_descent)>((new std::string("_shaped_text_get_descent"))->c_str())
			.fun<static_cast<double (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_width)>((new std::string("_shaped_text_get_width"))->c_str())
			.fun<static_cast<double (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_underline_position)>((new std::string("_shaped_text_get_underline_position"))->c_str())
			.fun<static_cast<double (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_underline_thickness)>((new std::string("_shaped_text_get_underline_thickness"))->c_str())
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &, int64_t, int64_t) const>(&TextServerExtension::_shaped_text_get_dominant_direction_in_range)>((new std::string("_shaped_text_get_dominant_direction_in_range"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, int64_t, CaretInfo *) const>(&TextServerExtension::_shaped_text_get_carets)>((new std::string("_shaped_text_get_carets"))->c_str())
			.fun<static_cast<PackedVector2Array (TextServerExtension::*)(const RID &, int64_t, int64_t) const>(&TextServerExtension::_shaped_text_get_selection)>((new std::string("_shaped_text_get_selection"))->c_str())
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &, double) const>(&TextServerExtension::_shaped_text_hit_test_grapheme)>((new std::string("_shaped_text_hit_test_grapheme"))->c_str())
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &, double) const>(&TextServerExtension::_shaped_text_hit_test_position)>((new std::string("_shaped_text_hit_test_position"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const RID &, const Vector2 &, double, double, const Color &) const>(&TextServerExtension::_shaped_text_draw)>((new std::string("_shaped_text_draw"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const RID &, const Vector2 &, double, double, int64_t, const Color &) const>(&TextServerExtension::_shaped_text_draw_outline)>((new std::string("_shaped_text_draw_outline"))->c_str())
			.fun<static_cast<Vector2 (TextServerExtension::*)(const RID &, int64_t) const>(&TextServerExtension::_shaped_text_get_grapheme_bounds)>((new std::string("_shaped_text_get_grapheme_bounds"))->c_str())
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &, int64_t) const>(&TextServerExtension::_shaped_text_next_grapheme_pos)>((new std::string("_shaped_text_next_grapheme_pos"))->c_str())
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &, int64_t) const>(&TextServerExtension::_shaped_text_prev_grapheme_pos)>((new std::string("_shaped_text_prev_grapheme_pos"))->c_str())
			.fun<static_cast<PackedInt32Array (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_character_breaks)>((new std::string("_shaped_text_get_character_breaks"))->c_str())
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &, int64_t) const>(&TextServerExtension::_shaped_text_next_character_pos)>((new std::string("_shaped_text_next_character_pos"))->c_str())
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &, int64_t) const>(&TextServerExtension::_shaped_text_prev_character_pos)>((new std::string("_shaped_text_prev_character_pos"))->c_str())
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &, int64_t) const>(&TextServerExtension::_shaped_text_closest_character_pos)>((new std::string("_shaped_text_closest_character_pos"))->c_str())
			.fun<static_cast<String (TextServerExtension::*)(const String &, const String &) const>(&TextServerExtension::_format_number)>((new std::string("_format_number"))->c_str())
			.fun<static_cast<String (TextServerExtension::*)(const String &, const String &) const>(&TextServerExtension::_parse_number)>((new std::string("_parse_number"))->c_str())
			.fun<static_cast<String (TextServerExtension::*)(const String &) const>(&TextServerExtension::_percent_sign)>((new std::string("_percent_sign"))->c_str())
			.fun<static_cast<String (TextServerExtension::*)(const String &) const>(&TextServerExtension::_strip_diacritics)>((new std::string("_strip_diacritics"))->c_str())
			.fun<static_cast<bool (TextServerExtension::*)(const String &) const>(&TextServerExtension::_is_valid_identifier)>((new std::string("_is_valid_identifier"))->c_str())
			.fun<static_cast<bool (TextServerExtension::*)(int64_t) const>(&TextServerExtension::_is_valid_letter)>((new std::string("_is_valid_letter"))->c_str())
			.fun<static_cast<PackedInt32Array (TextServerExtension::*)(const String &, const String &, int64_t) const>(&TextServerExtension::_string_get_word_breaks)>((new std::string("_string_get_word_breaks"))->c_str())
			.fun<static_cast<PackedInt32Array (TextServerExtension::*)(const String &, const String &) const>(&TextServerExtension::_string_get_character_breaks)>((new std::string("_string_get_character_breaks"))->c_str())
			.fun<static_cast<int64_t (TextServerExtension::*)(const String &, const PackedStringArray &) const>(&TextServerExtension::_is_confusable)>((new std::string("_is_confusable"))->c_str())
			.fun<static_cast<bool (TextServerExtension::*)(const String &) const>(&TextServerExtension::_spoof_check)>((new std::string("_spoof_check"))->c_str())
			.fun<static_cast<String (TextServerExtension::*)(const String &, const String &) const>(&TextServerExtension::_string_to_upper)>((new std::string("_string_to_upper"))->c_str())
			.fun<static_cast<String (TextServerExtension::*)(const String &, const String &) const>(&TextServerExtension::_string_to_lower)>((new std::string("_string_to_lower"))->c_str())
			.fun<static_cast<String (TextServerExtension::*)(const String &, const String &) const>(&TextServerExtension::_string_to_title)>((new std::string("_string_to_title"))->c_str())
			.fun<static_cast<TypedArray<Vector3i> (TextServerExtension::*)(TextServer::StructuredTextParser, const Array &, const String &) const>(&TextServerExtension::_parse_structured_text)>((new std::string("_parse_structured_text"))->c_str())
			.fun<static_cast<void (TextServerExtension::*)()>(&TextServerExtension::_cleanup)>((new std::string("_cleanup"))->c_str());
}