
#include <godot_cpp/classes/material.hpp>
#include <godot_cpp/classes/particle_process_material.hpp>
#include <godot_cpp/classes/ref.hpp>
#include <godot_cpp/classes/texture2d.hpp>
#include <godot_cpp/variant/color.hpp>
#include <godot_cpp/variant/vector2.hpp>
#include <godot_cpp/variant/vector3.hpp>
#include <string>
#include <utility>

#include "qjspp.hpp"
#include "qjspp/utils.h"
#include "register/register_classes.h"

using namespace godot;

void register_classes_ParticleProcessMaterial() {
	qjs::Context::Module &_module = get_General_module();
	_module.class_<ParticleProcessMaterial>("ParticleProcessMaterial")
			.constructor<>()
			.base<Material>()
			.property<static_cast<double (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::get_lifetime_randomness), static_cast<void (ParticleProcessMaterial::*)(double)>(&ParticleProcessMaterial::set_lifetime_randomness)>((new std::string("lifetime_randomness"))->c_str())
			.property<static_cast<bool (ParticleProcessMaterial::*)(ParticleProcessMaterial::ParticleFlags) const>(&ParticleProcessMaterial::get_particle_flag), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::ParticleFlags, bool)>(&ParticleProcessMaterial::set_particle_flag)>((new std::string("particle_flag_align_y"))->c_str())
			.property<static_cast<bool (ParticleProcessMaterial::*)(ParticleProcessMaterial::ParticleFlags) const>(&ParticleProcessMaterial::get_particle_flag), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::ParticleFlags, bool)>(&ParticleProcessMaterial::set_particle_flag)>((new std::string("particle_flag_rotate_y"))->c_str())
			.property<static_cast<bool (ParticleProcessMaterial::*)(ParticleProcessMaterial::ParticleFlags) const>(&ParticleProcessMaterial::get_particle_flag), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::ParticleFlags, bool)>(&ParticleProcessMaterial::set_particle_flag)>((new std::string("particle_flag_disable_z"))->c_str())
			.property<static_cast<bool (ParticleProcessMaterial::*)(ParticleProcessMaterial::ParticleFlags) const>(&ParticleProcessMaterial::get_particle_flag), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::ParticleFlags, bool)>(&ParticleProcessMaterial::set_particle_flag)>((new std::string("particle_flag_damping_as_friction"))->c_str())
			.property<static_cast<Vector3 (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::get_emission_shape_offset), static_cast<void (ParticleProcessMaterial::*)(const Vector3 &)>(&ParticleProcessMaterial::set_emission_shape_offset)>((new std::string("emission_shape_offset"))->c_str())
			.property<static_cast<Vector3 (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::get_emission_shape_scale), static_cast<void (ParticleProcessMaterial::*)(const Vector3 &)>(&ParticleProcessMaterial::set_emission_shape_scale)>((new std::string("emission_shape_scale"))->c_str())
			.property<static_cast<ParticleProcessMaterial::EmissionShape (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::get_emission_shape), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::EmissionShape)>(&ParticleProcessMaterial::set_emission_shape)>((new std::string("emission_shape"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::get_emission_sphere_radius), static_cast<void (ParticleProcessMaterial::*)(double)>(&ParticleProcessMaterial::set_emission_sphere_radius)>((new std::string("emission_sphere_radius"))->c_str())
			.property<static_cast<Vector3 (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::get_emission_box_extents), static_cast<void (ParticleProcessMaterial::*)(const Vector3 &)>(&ParticleProcessMaterial::set_emission_box_extents)>((new std::string("emission_box_extents"))->c_str())
			.property<static_cast<Ref<Texture2D> (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::get_emission_point_texture), static_cast<void (ParticleProcessMaterial::*)(const Ref<Texture2D> &)>(&ParticleProcessMaterial::set_emission_point_texture)>((new std::string("emission_point_texture"))->c_str())
			.property<static_cast<Ref<Texture2D> (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::get_emission_normal_texture), static_cast<void (ParticleProcessMaterial::*)(const Ref<Texture2D> &)>(&ParticleProcessMaterial::set_emission_normal_texture)>((new std::string("emission_normal_texture"))->c_str())
			.property<static_cast<Ref<Texture2D> (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::get_emission_color_texture), static_cast<void (ParticleProcessMaterial::*)(const Ref<Texture2D> &)>(&ParticleProcessMaterial::set_emission_color_texture)>((new std::string("emission_color_texture"))->c_str())
			.property<static_cast<int32_t (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::get_emission_point_count), static_cast<void (ParticleProcessMaterial::*)(int32_t)>(&ParticleProcessMaterial::set_emission_point_count)>((new std::string("emission_point_count"))->c_str())
			.property<static_cast<Vector3 (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::get_emission_ring_axis), static_cast<void (ParticleProcessMaterial::*)(const Vector3 &)>(&ParticleProcessMaterial::set_emission_ring_axis)>((new std::string("emission_ring_axis"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::get_emission_ring_height), static_cast<void (ParticleProcessMaterial::*)(double)>(&ParticleProcessMaterial::set_emission_ring_height)>((new std::string("emission_ring_height"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::get_emission_ring_radius), static_cast<void (ParticleProcessMaterial::*)(double)>(&ParticleProcessMaterial::set_emission_ring_radius)>((new std::string("emission_ring_radius"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::get_emission_ring_inner_radius), static_cast<void (ParticleProcessMaterial::*)(double)>(&ParticleProcessMaterial::set_emission_ring_inner_radius)>((new std::string("emission_ring_inner_radius"))->c_str())
			.property<static_cast<Vector2 (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, const Vector2 &)>(&ParticleProcessMaterial::set_param)>((new std::string("angle"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_min), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, double)>(&ParticleProcessMaterial::set_param_min)>((new std::string("angle_min"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_max), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, double)>(&ParticleProcessMaterial::set_param_max)>((new std::string("angle_max"))->c_str())
			.property<static_cast<Ref<Texture2D> (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_texture), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, const Ref<Texture2D> &)>(&ParticleProcessMaterial::set_param_texture)>((new std::string("angle_curve"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)()>(&ParticleProcessMaterial::get_inherit_velocity_ratio), static_cast<void (ParticleProcessMaterial::*)(double)>(&ParticleProcessMaterial::set_inherit_velocity_ratio)>((new std::string("inherit_velocity_ratio"))->c_str())
			.property<static_cast<Vector3 (ParticleProcessMaterial::*)()>(&ParticleProcessMaterial::get_velocity_pivot), static_cast<void (ParticleProcessMaterial::*)(const Vector3 &)>(&ParticleProcessMaterial::set_velocity_pivot)>((new std::string("velocity_pivot"))->c_str())
			.property<static_cast<Vector3 (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::get_direction), static_cast<void (ParticleProcessMaterial::*)(const Vector3 &)>(&ParticleProcessMaterial::set_direction)>((new std::string("direction"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::get_spread), static_cast<void (ParticleProcessMaterial::*)(double)>(&ParticleProcessMaterial::set_spread)>((new std::string("spread"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::get_flatness), static_cast<void (ParticleProcessMaterial::*)(double)>(&ParticleProcessMaterial::set_flatness)>((new std::string("flatness"))->c_str())
			.property<static_cast<Vector2 (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, const Vector2 &)>(&ParticleProcessMaterial::set_param)>((new std::string("initial_velocity"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_min), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, double)>(&ParticleProcessMaterial::set_param_min)>((new std::string("initial_velocity_min"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_max), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, double)>(&ParticleProcessMaterial::set_param_max)>((new std::string("initial_velocity_max"))->c_str())
			.property<static_cast<Vector2 (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, const Vector2 &)>(&ParticleProcessMaterial::set_param)>((new std::string("angular_velocity"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_min), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, double)>(&ParticleProcessMaterial::set_param_min)>((new std::string("angular_velocity_min"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_max), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, double)>(&ParticleProcessMaterial::set_param_max)>((new std::string("angular_velocity_max"))->c_str())
			.property<static_cast<Ref<Texture2D> (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_texture), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, const Ref<Texture2D> &)>(&ParticleProcessMaterial::set_param_texture)>((new std::string("angular_velocity_curve"))->c_str())
			.property<static_cast<Vector2 (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, const Vector2 &)>(&ParticleProcessMaterial::set_param)>((new std::string("directional_velocity"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_min), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, double)>(&ParticleProcessMaterial::set_param_min)>((new std::string("directional_velocity_min"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_max), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, double)>(&ParticleProcessMaterial::set_param_max)>((new std::string("directional_velocity_max"))->c_str())
			.property<static_cast<Ref<Texture2D> (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_texture), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, const Ref<Texture2D> &)>(&ParticleProcessMaterial::set_param_texture)>((new std::string("directional_velocity_curve"))->c_str())
			.property<static_cast<Vector2 (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, const Vector2 &)>(&ParticleProcessMaterial::set_param)>((new std::string("orbit_velocity"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_min), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, double)>(&ParticleProcessMaterial::set_param_min)>((new std::string("orbit_velocity_min"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_max), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, double)>(&ParticleProcessMaterial::set_param_max)>((new std::string("orbit_velocity_max"))->c_str())
			.property<static_cast<Ref<Texture2D> (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_texture), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, const Ref<Texture2D> &)>(&ParticleProcessMaterial::set_param_texture)>((new std::string("orbit_velocity_curve"))->c_str())
			.property<static_cast<Vector2 (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, const Vector2 &)>(&ParticleProcessMaterial::set_param)>((new std::string("radial_velocity"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_min), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, double)>(&ParticleProcessMaterial::set_param_min)>((new std::string("radial_velocity_min"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_max), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, double)>(&ParticleProcessMaterial::set_param_max)>((new std::string("radial_velocity_max"))->c_str())
			.property<static_cast<Ref<Texture2D> (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_texture), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, const Ref<Texture2D> &)>(&ParticleProcessMaterial::set_param_texture)>((new std::string("radial_velocity_curve"))->c_str())
			.property<static_cast<Ref<Texture2D> (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::get_velocity_limit_curve), static_cast<void (ParticleProcessMaterial::*)(const Ref<Texture2D> &)>(&ParticleProcessMaterial::set_velocity_limit_curve)>((new std::string("velocity_limit_curve"))->c_str())
			.property<static_cast<Vector3 (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::get_gravity), static_cast<void (ParticleProcessMaterial::*)(const Vector3 &)>(&ParticleProcessMaterial::set_gravity)>((new std::string("gravity"))->c_str())
			.property<static_cast<Vector2 (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, const Vector2 &)>(&ParticleProcessMaterial::set_param)>((new std::string("linear_accel"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_min), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, double)>(&ParticleProcessMaterial::set_param_min)>((new std::string("linear_accel_min"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_max), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, double)>(&ParticleProcessMaterial::set_param_max)>((new std::string("linear_accel_max"))->c_str())
			.property<static_cast<Ref<Texture2D> (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_texture), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, const Ref<Texture2D> &)>(&ParticleProcessMaterial::set_param_texture)>((new std::string("linear_accel_curve"))->c_str())
			.property<static_cast<Vector2 (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, const Vector2 &)>(&ParticleProcessMaterial::set_param)>((new std::string("radial_accel"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_min), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, double)>(&ParticleProcessMaterial::set_param_min)>((new std::string("radial_accel_min"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_max), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, double)>(&ParticleProcessMaterial::set_param_max)>((new std::string("radial_accel_max"))->c_str())
			.property<static_cast<Ref<Texture2D> (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_texture), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, const Ref<Texture2D> &)>(&ParticleProcessMaterial::set_param_texture)>((new std::string("radial_accel_curve"))->c_str())
			.property<static_cast<Vector2 (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, const Vector2 &)>(&ParticleProcessMaterial::set_param)>((new std::string("tangential_accel"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_min), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, double)>(&ParticleProcessMaterial::set_param_min)>((new std::string("tangential_accel_min"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_max), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, double)>(&ParticleProcessMaterial::set_param_max)>((new std::string("tangential_accel_max"))->c_str())
			.property<static_cast<Ref<Texture2D> (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_texture), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, const Ref<Texture2D> &)>(&ParticleProcessMaterial::set_param_texture)>((new std::string("tangential_accel_curve"))->c_str())
			.property<static_cast<Vector2 (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, const Vector2 &)>(&ParticleProcessMaterial::set_param)>((new std::string("damping"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_min), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, double)>(&ParticleProcessMaterial::set_param_min)>((new std::string("damping_min"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_max), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, double)>(&ParticleProcessMaterial::set_param_max)>((new std::string("damping_max"))->c_str())
			.property<static_cast<Ref<Texture2D> (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_texture), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, const Ref<Texture2D> &)>(&ParticleProcessMaterial::set_param_texture)>((new std::string("damping_curve"))->c_str())
			.property<static_cast<bool (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::is_attractor_interaction_enabled), static_cast<void (ParticleProcessMaterial::*)(bool)>(&ParticleProcessMaterial::set_attractor_interaction_enabled)>((new std::string("attractor_interaction_enabled"))->c_str())
			.property<static_cast<Vector2 (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, const Vector2 &)>(&ParticleProcessMaterial::set_param)>((new std::string("scale"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_min), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, double)>(&ParticleProcessMaterial::set_param_min)>((new std::string("scale_min"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_max), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, double)>(&ParticleProcessMaterial::set_param_max)>((new std::string("scale_max"))->c_str())
			.property<static_cast<Ref<Texture2D> (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_texture), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, const Ref<Texture2D> &)>(&ParticleProcessMaterial::set_param_texture)>((new std::string("scale_curve"))->c_str())
			.property<static_cast<Vector2 (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, const Vector2 &)>(&ParticleProcessMaterial::set_param)>((new std::string("scale_over_velocity"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_min), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, double)>(&ParticleProcessMaterial::set_param_min)>((new std::string("scale_over_velocity_min"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_max), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, double)>(&ParticleProcessMaterial::set_param_max)>((new std::string("scale_over_velocity_max"))->c_str())
			.property<static_cast<Ref<Texture2D> (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_texture), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, const Ref<Texture2D> &)>(&ParticleProcessMaterial::set_param_texture)>((new std::string("scale_over_velocity_curve"))->c_str())
			.property<static_cast<Color (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::get_color), static_cast<void (ParticleProcessMaterial::*)(const Color &)>(&ParticleProcessMaterial::set_color)>((new std::string("color"))->c_str())
			.property<static_cast<Ref<Texture2D> (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::get_color_ramp), static_cast<void (ParticleProcessMaterial::*)(const Ref<Texture2D> &)>(&ParticleProcessMaterial::set_color_ramp)>((new std::string("color_ramp"))->c_str())
			.property<static_cast<Ref<Texture2D> (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::get_color_initial_ramp), static_cast<void (ParticleProcessMaterial::*)(const Ref<Texture2D> &)>(&ParticleProcessMaterial::set_color_initial_ramp)>((new std::string("color_initial_ramp"))->c_str())
			.property<static_cast<Ref<Texture2D> (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::get_alpha_curve), static_cast<void (ParticleProcessMaterial::*)(const Ref<Texture2D> &)>(&ParticleProcessMaterial::set_alpha_curve)>((new std::string("alpha_curve"))->c_str())
			.property<static_cast<Ref<Texture2D> (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::get_emission_curve), static_cast<void (ParticleProcessMaterial::*)(const Ref<Texture2D> &)>(&ParticleProcessMaterial::set_emission_curve)>((new std::string("emission_curve"))->c_str())
			.property<static_cast<Vector2 (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, const Vector2 &)>(&ParticleProcessMaterial::set_param)>((new std::string("hue_variation"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_min), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, double)>(&ParticleProcessMaterial::set_param_min)>((new std::string("hue_variation_min"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_max), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, double)>(&ParticleProcessMaterial::set_param_max)>((new std::string("hue_variation_max"))->c_str())
			.property<static_cast<Ref<Texture2D> (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_texture), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, const Ref<Texture2D> &)>(&ParticleProcessMaterial::set_param_texture)>((new std::string("hue_variation_curve"))->c_str())
			.property<static_cast<Vector2 (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, const Vector2 &)>(&ParticleProcessMaterial::set_param)>((new std::string("anim_speed"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_min), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, double)>(&ParticleProcessMaterial::set_param_min)>((new std::string("anim_speed_min"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_max), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, double)>(&ParticleProcessMaterial::set_param_max)>((new std::string("anim_speed_max"))->c_str())
			.property<static_cast<Ref<Texture2D> (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_texture), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, const Ref<Texture2D> &)>(&ParticleProcessMaterial::set_param_texture)>((new std::string("anim_speed_curve"))->c_str())
			.property<static_cast<Vector2 (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, const Vector2 &)>(&ParticleProcessMaterial::set_param)>((new std::string("anim_offset"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_min), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, double)>(&ParticleProcessMaterial::set_param_min)>((new std::string("anim_offset_min"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_max), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, double)>(&ParticleProcessMaterial::set_param_max)>((new std::string("anim_offset_max"))->c_str())
			.property<static_cast<Ref<Texture2D> (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_texture), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, const Ref<Texture2D> &)>(&ParticleProcessMaterial::set_param_texture)>((new std::string("anim_offset_curve"))->c_str())
			.property<static_cast<bool (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::get_turbulence_enabled), static_cast<void (ParticleProcessMaterial::*)(bool)>(&ParticleProcessMaterial::set_turbulence_enabled)>((new std::string("turbulence_enabled"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::get_turbulence_noise_strength), static_cast<void (ParticleProcessMaterial::*)(double)>(&ParticleProcessMaterial::set_turbulence_noise_strength)>((new std::string("turbulence_noise_strength"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::get_turbulence_noise_scale), static_cast<void (ParticleProcessMaterial::*)(double)>(&ParticleProcessMaterial::set_turbulence_noise_scale)>((new std::string("turbulence_noise_scale"))->c_str())
			.property<static_cast<Vector3 (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::get_turbulence_noise_speed), static_cast<void (ParticleProcessMaterial::*)(const Vector3 &)>(&ParticleProcessMaterial::set_turbulence_noise_speed)>((new std::string("turbulence_noise_speed"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::get_turbulence_noise_speed_random), static_cast<void (ParticleProcessMaterial::*)(double)>(&ParticleProcessMaterial::set_turbulence_noise_speed_random)>((new std::string("turbulence_noise_speed_random"))->c_str())
			.property<static_cast<Vector2 (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, const Vector2 &)>(&ParticleProcessMaterial::set_param)>((new std::string("turbulence_influence"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_min), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, double)>(&ParticleProcessMaterial::set_param_min)>((new std::string("turbulence_influence_min"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_max), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, double)>(&ParticleProcessMaterial::set_param_max)>((new std::string("turbulence_influence_max"))->c_str())
			.property<static_cast<Vector2 (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, const Vector2 &)>(&ParticleProcessMaterial::set_param)>((new std::string("turbulence_initial_displacement"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_min), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, double)>(&ParticleProcessMaterial::set_param_min)>((new std::string("turbulence_initial_displacement_min"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_max), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, double)>(&ParticleProcessMaterial::set_param_max)>((new std::string("turbulence_initial_displacement_max"))->c_str())
			.property<static_cast<Ref<Texture2D> (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter) const>(&ParticleProcessMaterial::get_param_texture), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::Parameter, const Ref<Texture2D> &)>(&ParticleProcessMaterial::set_param_texture)>((new std::string("turbulence_influence_over_life"))->c_str())
			.property<static_cast<ParticleProcessMaterial::CollisionMode (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::get_collision_mode), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::CollisionMode)>(&ParticleProcessMaterial::set_collision_mode)>((new std::string("collision_mode"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::get_collision_friction), static_cast<void (ParticleProcessMaterial::*)(double)>(&ParticleProcessMaterial::set_collision_friction)>((new std::string("collision_friction"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::get_collision_bounce), static_cast<void (ParticleProcessMaterial::*)(double)>(&ParticleProcessMaterial::set_collision_bounce)>((new std::string("collision_bounce"))->c_str())
			.property<static_cast<bool (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::is_collision_using_scale), static_cast<void (ParticleProcessMaterial::*)(bool)>(&ParticleProcessMaterial::set_collision_use_scale)>((new std::string("collision_use_scale"))->c_str())
			.property<static_cast<ParticleProcessMaterial::SubEmitterMode (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::get_sub_emitter_mode), static_cast<void (ParticleProcessMaterial::*)(ParticleProcessMaterial::SubEmitterMode)>(&ParticleProcessMaterial::set_sub_emitter_mode)>((new std::string("sub_emitter_mode"))->c_str())
			.property<static_cast<double (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::get_sub_emitter_frequency), static_cast<void (ParticleProcessMaterial::*)(double)>(&ParticleProcessMaterial::set_sub_emitter_frequency)>((new std::string("sub_emitter_frequency"))->c_str())
			.property<static_cast<int32_t (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::get_sub_emitter_amount_at_end), static_cast<void (ParticleProcessMaterial::*)(int32_t)>(&ParticleProcessMaterial::set_sub_emitter_amount_at_end)>((new std::string("sub_emitter_amount_at_end"))->c_str())
			.property<static_cast<int32_t (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::get_sub_emitter_amount_at_collision), static_cast<void (ParticleProcessMaterial::*)(int32_t)>(&ParticleProcessMaterial::set_sub_emitter_amount_at_collision)>((new std::string("sub_emitter_amount_at_collision"))->c_str())
			.property<static_cast<bool (ParticleProcessMaterial::*)() const>(&ParticleProcessMaterial::get_sub_emitter_keep_velocity), static_cast<void (ParticleProcessMaterial::*)(bool)>(&ParticleProcessMaterial::set_sub_emitter_keep_velocity)>((new std::string("sub_emitter_keep_velocity"))->c_str());
	qjs::Value _Parameter = context->newObject();
	_Parameter[(new std::string("PARAM_INITIAL_LINEAR_VELOCITY"))->c_str()] = ParticleProcessMaterial::Parameter::PARAM_INITIAL_LINEAR_VELOCITY;
	_Parameter[(new std::string("PARAM_ANGULAR_VELOCITY"))->c_str()] = ParticleProcessMaterial::Parameter::PARAM_ANGULAR_VELOCITY;
	_Parameter[(new std::string("PARAM_ORBIT_VELOCITY"))->c_str()] = ParticleProcessMaterial::Parameter::PARAM_ORBIT_VELOCITY;
	_Parameter[(new std::string("PARAM_LINEAR_ACCEL"))->c_str()] = ParticleProcessMaterial::Parameter::PARAM_LINEAR_ACCEL;
	_Parameter[(new std::string("PARAM_RADIAL_ACCEL"))->c_str()] = ParticleProcessMaterial::Parameter::PARAM_RADIAL_ACCEL;
	_Parameter[(new std::string("PARAM_TANGENTIAL_ACCEL"))->c_str()] = ParticleProcessMaterial::Parameter::PARAM_TANGENTIAL_ACCEL;
	_Parameter[(new std::string("PARAM_DAMPING"))->c_str()] = ParticleProcessMaterial::Parameter::PARAM_DAMPING;
	_Parameter[(new std::string("PARAM_ANGLE"))->c_str()] = ParticleProcessMaterial::Parameter::PARAM_ANGLE;
	_Parameter[(new std::string("PARAM_SCALE"))->c_str()] = ParticleProcessMaterial::Parameter::PARAM_SCALE;
	_Parameter[(new std::string("PARAM_HUE_VARIATION"))->c_str()] = ParticleProcessMaterial::Parameter::PARAM_HUE_VARIATION;
	_Parameter[(new std::string("PARAM_ANIM_SPEED"))->c_str()] = ParticleProcessMaterial::Parameter::PARAM_ANIM_SPEED;
	_Parameter[(new std::string("PARAM_ANIM_OFFSET"))->c_str()] = ParticleProcessMaterial::Parameter::PARAM_ANIM_OFFSET;
	_Parameter[(new std::string("PARAM_RADIAL_VELOCITY"))->c_str()] = ParticleProcessMaterial::Parameter::PARAM_RADIAL_VELOCITY;
	_Parameter[(new std::string("PARAM_DIRECTIONAL_VELOCITY"))->c_str()] = ParticleProcessMaterial::Parameter::PARAM_DIRECTIONAL_VELOCITY;
	_Parameter[(new std::string("PARAM_SCALE_OVER_VELOCITY"))->c_str()] = ParticleProcessMaterial::Parameter::PARAM_SCALE_OVER_VELOCITY;
	_Parameter[(new std::string("PARAM_MAX"))->c_str()] = ParticleProcessMaterial::Parameter::PARAM_MAX;
	_Parameter[(new std::string("PARAM_TURB_VEL_INFLUENCE"))->c_str()] = ParticleProcessMaterial::Parameter::PARAM_TURB_VEL_INFLUENCE;
	_Parameter[(new std::string("PARAM_TURB_INIT_DISPLACEMENT"))->c_str()] = ParticleProcessMaterial::Parameter::PARAM_TURB_INIT_DISPLACEMENT;
	_Parameter[(new std::string("PARAM_TURB_INFLUENCE_OVER_LIFE"))->c_str()] = ParticleProcessMaterial::Parameter::PARAM_TURB_INFLUENCE_OVER_LIFE;
	_module.add("Parameter", std::move(_Parameter));
	qjs::Value _ParticleFlags = context->newObject();
	_ParticleFlags[(new std::string("PARTICLE_FLAG_ALIGN_Y_TO_VELOCITY"))->c_str()] = ParticleProcessMaterial::ParticleFlags::PARTICLE_FLAG_ALIGN_Y_TO_VELOCITY;
	_ParticleFlags[(new std::string("PARTICLE_FLAG_ROTATE_Y"))->c_str()] = ParticleProcessMaterial::ParticleFlags::PARTICLE_FLAG_ROTATE_Y;
	_ParticleFlags[(new std::string("PARTICLE_FLAG_DISABLE_Z"))->c_str()] = ParticleProcessMaterial::ParticleFlags::PARTICLE_FLAG_DISABLE_Z;
	_ParticleFlags[(new std::string("PARTICLE_FLAG_DAMPING_AS_FRICTION"))->c_str()] = ParticleProcessMaterial::ParticleFlags::PARTICLE_FLAG_DAMPING_AS_FRICTION;
	_ParticleFlags[(new std::string("PARTICLE_FLAG_MAX"))->c_str()] = ParticleProcessMaterial::ParticleFlags::PARTICLE_FLAG_MAX;
	_module.add("ParticleFlags", std::move(_ParticleFlags));
	qjs::Value _EmissionShape = context->newObject();
	_EmissionShape[(new std::string("EMISSION_SHAPE_POINT"))->c_str()] = ParticleProcessMaterial::EmissionShape::EMISSION_SHAPE_POINT;
	_EmissionShape[(new std::string("EMISSION_SHAPE_SPHERE"))->c_str()] = ParticleProcessMaterial::EmissionShape::EMISSION_SHAPE_SPHERE;
	_EmissionShape[(new std::string("EMISSION_SHAPE_SPHERE_SURFACE"))->c_str()] = ParticleProcessMaterial::EmissionShape::EMISSION_SHAPE_SPHERE_SURFACE;
	_EmissionShape[(new std::string("EMISSION_SHAPE_BOX"))->c_str()] = ParticleProcessMaterial::EmissionShape::EMISSION_SHAPE_BOX;
	_EmissionShape[(new std::string("EMISSION_SHAPE_POINTS"))->c_str()] = ParticleProcessMaterial::EmissionShape::EMISSION_SHAPE_POINTS;
	_EmissionShape[(new std::string("EMISSION_SHAPE_DIRECTED_POINTS"))->c_str()] = ParticleProcessMaterial::EmissionShape::EMISSION_SHAPE_DIRECTED_POINTS;
	_EmissionShape[(new std::string("EMISSION_SHAPE_RING"))->c_str()] = ParticleProcessMaterial::EmissionShape::EMISSION_SHAPE_RING;
	_EmissionShape[(new std::string("EMISSION_SHAPE_MAX"))->c_str()] = ParticleProcessMaterial::EmissionShape::EMISSION_SHAPE_MAX;
	_module.add("EmissionShape", std::move(_EmissionShape));
	qjs::Value _SubEmitterMode = context->newObject();
	_SubEmitterMode[(new std::string("SUB_EMITTER_DISABLED"))->c_str()] = ParticleProcessMaterial::SubEmitterMode::SUB_EMITTER_DISABLED;
	_SubEmitterMode[(new std::string("SUB_EMITTER_CONSTANT"))->c_str()] = ParticleProcessMaterial::SubEmitterMode::SUB_EMITTER_CONSTANT;
	_SubEmitterMode[(new std::string("SUB_EMITTER_AT_END"))->c_str()] = ParticleProcessMaterial::SubEmitterMode::SUB_EMITTER_AT_END;
	_SubEmitterMode[(new std::string("SUB_EMITTER_AT_COLLISION"))->c_str()] = ParticleProcessMaterial::SubEmitterMode::SUB_EMITTER_AT_COLLISION;
	_SubEmitterMode[(new std::string("SUB_EMITTER_MAX"))->c_str()] = ParticleProcessMaterial::SubEmitterMode::SUB_EMITTER_MAX;
	_module.add("SubEmitterMode", std::move(_SubEmitterMode));
	qjs::Value _CollisionMode = context->newObject();
	_CollisionMode[(new std::string("COLLISION_DISABLED"))->c_str()] = ParticleProcessMaterial::CollisionMode::COLLISION_DISABLED;
	_CollisionMode[(new std::string("COLLISION_RIGID"))->c_str()] = ParticleProcessMaterial::CollisionMode::COLLISION_RIGID;
	_CollisionMode[(new std::string("COLLISION_HIDE_ON_CONTACT"))->c_str()] = ParticleProcessMaterial::CollisionMode::COLLISION_HIDE_ON_CONTACT;
	_CollisionMode[(new std::string("COLLISION_MAX"))->c_str()] = ParticleProcessMaterial::CollisionMode::COLLISION_MAX;
	_module.add("CollisionMode", std::move(_CollisionMode));
}