#include <godot_cpp/classes/cpu_particles3d.hpp>
#include <godot_cpp/classes/curve.hpp>
#include <godot_cpp/classes/gradient.hpp>
#include <godot_cpp/classes/mesh.hpp>
#include <godot_cpp/classes/node.hpp>

#include "qjspp.hpp"
#include "register/register_classes.h"

using namespace godot;

void register_classes_CPUParticles3D() {
	qjs::Context::Module &_module = get_Node3D_module();
	_module.class_<CPUParticles3D>("CPUParticles3D")
			.constructor<>()
			.property<&CPUParticles3D::is_emitting, &CPUParticles3D::set_emitting>("emitting")
			.property<&CPUParticles3D::get_amount, &CPUParticles3D::set_amount>("amount")
			.property<&CPUParticles3D::get_lifetime, &CPUParticles3D::set_lifetime>("lifetime")
			.property<&CPUParticles3D::get_one_shot, &CPUParticles3D::set_one_shot>("one_shot")
			.property<&CPUParticles3D::get_pre_process_time, &CPUParticles3D::set_pre_process_time>("preprocess")
			.property<&CPUParticles3D::get_speed_scale, &CPUParticles3D::set_speed_scale>("speed_scale")
			.property<&CPUParticles3D::get_explosiveness_ratio, &CPUParticles3D::set_explosiveness_ratio>("explosiveness")
			.property<&CPUParticles3D::get_randomness_ratio, &CPUParticles3D::set_randomness_ratio>("randomness")
			.property<&CPUParticles3D::get_lifetime_randomness, &CPUParticles3D::set_lifetime_randomness>("lifetime_randomness")
			.property<&CPUParticles3D::get_fixed_fps, &CPUParticles3D::set_fixed_fps>("fixed_fps")
			.property<&CPUParticles3D::get_fractional_delta, &CPUParticles3D::set_fractional_delta>("fract_delta")
			.property<&CPUParticles3D::get_use_local_coordinates, &CPUParticles3D::set_use_local_coordinates>("local_coords")
			.property<&CPUParticles3D::get_draw_order, &CPUParticles3D::set_draw_order>("draw_order")
			.property<&CPUParticles3D::get_mesh, &CPUParticles3D::set_mesh>("mesh")
			.property<&CPUParticles3D::get_emission_shape, &CPUParticles3D::set_emission_shape>("emission_shape")
			.property<&CPUParticles3D::get_emission_sphere_radius, &CPUParticles3D::set_emission_sphere_radius>("emission_sphere_radius")
			.property<&CPUParticles3D::get_emission_box_extents, &CPUParticles3D::set_emission_box_extents>("emission_box_extents")
			.property<&CPUParticles3D::get_emission_points, &CPUParticles3D::set_emission_points>("emission_points")
			.property<&CPUParticles3D::get_emission_normals, &CPUParticles3D::set_emission_normals>("emission_normals")
			.property<&CPUParticles3D::get_emission_colors, &CPUParticles3D::set_emission_colors>("emission_colors")
			.property<&CPUParticles3D::get_emission_ring_axis, &CPUParticles3D::set_emission_ring_axis>("emission_ring_axis")
			.property<&CPUParticles3D::get_emission_ring_height, &CPUParticles3D::set_emission_ring_height>("emission_ring_height")
			.property<&CPUParticles3D::get_emission_ring_radius, &CPUParticles3D::set_emission_ring_radius>("emission_ring_radius")
			.property<&CPUParticles3D::get_emission_ring_inner_radius, &CPUParticles3D::set_emission_ring_inner_radius>("emission_ring_inner_radius")
			.property<&CPUParticles3D::get_particle_flag, &CPUParticles3D::set_particle_flag>("particle_flag_align_y")
			.property<&CPUParticles3D::get_particle_flag, &CPUParticles3D::set_particle_flag>("particle_flag_rotate_y")
			.property<&CPUParticles3D::get_particle_flag, &CPUParticles3D::set_particle_flag>("particle_flag_disable_z")
			.property<&CPUParticles3D::get_direction, &CPUParticles3D::set_direction>("direction")
			.property<&CPUParticles3D::get_spread, &CPUParticles3D::set_spread>("spread")
			.property<&CPUParticles3D::get_flatness, &CPUParticles3D::set_flatness>("flatness")
			.property<&CPUParticles3D::get_gravity, &CPUParticles3D::set_gravity>("gravity")
			.property<&CPUParticles3D::get_param_min, &CPUParticles3D::set_param_min>("initial_velocity_min")
			.property<&CPUParticles3D::get_param_max, &CPUParticles3D::set_param_max>("initial_velocity_max")
			.property<&CPUParticles3D::get_param_min, &CPUParticles3D::set_param_min>("angular_velocity_min")
			.property<&CPUParticles3D::get_param_max, &CPUParticles3D::set_param_max>("angular_velocity_max")
			.property<&CPUParticles3D::get_param_curve, &CPUParticles3D::set_param_curve>("angular_velocity_curve")
			.property<&CPUParticles3D::get_param_min, &CPUParticles3D::set_param_min>("orbit_velocity_min")
			.property<&CPUParticles3D::get_param_max, &CPUParticles3D::set_param_max>("orbit_velocity_max")
			.property<&CPUParticles3D::get_param_curve, &CPUParticles3D::set_param_curve>("orbit_velocity_curve")
			.property<&CPUParticles3D::get_param_min, &CPUParticles3D::set_param_min>("linear_accel_min")
			.property<&CPUParticles3D::get_param_max, &CPUParticles3D::set_param_max>("linear_accel_max")
			.property<&CPUParticles3D::get_param_curve, &CPUParticles3D::set_param_curve>("linear_accel_curve")
			.property<&CPUParticles3D::get_param_min, &CPUParticles3D::set_param_min>("radial_accel_min")
			.property<&CPUParticles3D::get_param_max, &CPUParticles3D::set_param_max>("radial_accel_max")
			.property<&CPUParticles3D::get_param_curve, &CPUParticles3D::set_param_curve>("radial_accel_curve")
			.property<&CPUParticles3D::get_param_min, &CPUParticles3D::set_param_min>("tangential_accel_min")
			.property<&CPUParticles3D::get_param_max, &CPUParticles3D::set_param_max>("tangential_accel_max")
			.property<&CPUParticles3D::get_param_curve, &CPUParticles3D::set_param_curve>("tangential_accel_curve")
			.property<&CPUParticles3D::get_param_min, &CPUParticles3D::set_param_min>("damping_min")
			.property<&CPUParticles3D::get_param_max, &CPUParticles3D::set_param_max>("damping_max")
			.property<&CPUParticles3D::get_param_curve, &CPUParticles3D::set_param_curve>("damping_curve")
			.property<&CPUParticles3D::get_param_min, &CPUParticles3D::set_param_min>("angle_min")
			.property<&CPUParticles3D::get_param_max, &CPUParticles3D::set_param_max>("angle_max")
			.property<&CPUParticles3D::get_param_curve, &CPUParticles3D::set_param_curve>("angle_curve")
			.property<&CPUParticles3D::get_param_min, &CPUParticles3D::set_param_min>("scale_amount_min")
			.property<&CPUParticles3D::get_param_max, &CPUParticles3D::set_param_max>("scale_amount_max")
			.property<&CPUParticles3D::get_param_curve, &CPUParticles3D::set_param_curve>("scale_amount_curve")
			.property<&CPUParticles3D::get_split_scale, &CPUParticles3D::set_split_scale>("split_scale")
			.property<&CPUParticles3D::get_scale_curve_x, &CPUParticles3D::set_scale_curve_x>("scale_curve_x")
			.property<&CPUParticles3D::get_scale_curve_y, &CPUParticles3D::set_scale_curve_y>("scale_curve_y")
			.property<&CPUParticles3D::get_scale_curve_z, &CPUParticles3D::set_scale_curve_z>("scale_curve_z")
			.property<&CPUParticles3D::get_color, &CPUParticles3D::set_color>("color")
			.property<&CPUParticles3D::get_color_ramp, &CPUParticles3D::set_color_ramp>("color_ramp")
			.property<&CPUParticles3D::get_color_initial_ramp, &CPUParticles3D::set_color_initial_ramp>("color_initial_ramp")
			.property<&CPUParticles3D::get_param_min, &CPUParticles3D::set_param_min>("hue_variation_min")
			.property<&CPUParticles3D::get_param_max, &CPUParticles3D::set_param_max>("hue_variation_max")
			.property<&CPUParticles3D::get_param_curve, &CPUParticles3D::set_param_curve>("hue_variation_curve")
			.property<&CPUParticles3D::get_param_min, &CPUParticles3D::set_param_min>("anim_speed_min")
			.property<&CPUParticles3D::get_param_max, &CPUParticles3D::set_param_max>("anim_speed_max")
			.property<&CPUParticles3D::get_param_curve, &CPUParticles3D::set_param_curve>("anim_speed_curve")
			.property<&CPUParticles3D::get_param_min, &CPUParticles3D::set_param_min>("anim_offset_min")
			.property<&CPUParticles3D::get_param_max, &CPUParticles3D::set_param_max>("anim_offset_max")
			.property<&CPUParticles3D::get_param_curve, &CPUParticles3D::set_param_curve>("anim_offset_curve")
			.fun<static_cast<void (CPUParticles3D::*)()>(&CPUParticles3D::restart)>("restart")
			.fun<static_cast<void (CPUParticles3D::*)(Node *)>(&CPUParticles3D::convert_from_particles)>("convert_from_particles");
}