#include "register/register_classes.h"
#include "register/utils.h"

using namespace godot;

void register_classes_PhysicsServer3DExtension() {
    qjs::Context::Module &_module = _System;
    _module.class_<PhysicsServer3DExtension>("PhysicsServer3DExtension")
           .constructor<>()
		   .fun<static_cast<RID(PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_world_boundary_shape_create)>("_world_boundary_shape_create")
		   .fun<static_cast<RID(PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_separation_ray_shape_create)>("_separation_ray_shape_create")
		   .fun<static_cast<RID(PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_sphere_shape_create)>("_sphere_shape_create")
		   .fun<static_cast<RID(PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_box_shape_create)>("_box_shape_create")
		   .fun<static_cast<RID(PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_capsule_shape_create)>("_capsule_shape_create")
		   .fun<static_cast<RID(PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_cylinder_shape_create)>("_cylinder_shape_create")
		   .fun<static_cast<RID(PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_convex_polygon_shape_create)>("_convex_polygon_shape_create")
		   .fun<static_cast<RID(PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_concave_polygon_shape_create)>("_concave_polygon_shape_create")
		   .fun<static_cast<RID(PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_heightmap_shape_create)>("_heightmap_shape_create")
		   .fun<static_cast<RID(PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_custom_shape_create)>("_custom_shape_create")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,const Variant &)>(&PhysicsServer3DExtension::_shape_set_data)>("_shape_set_data")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,double)>(&PhysicsServer3DExtension::_shape_set_custom_solver_bias)>("_shape_set_custom_solver_bias")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,double)>(&PhysicsServer3DExtension::_shape_set_margin)>("_shape_set_margin")
		   .fun<static_cast<double(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_shape_get_margin)>("_shape_get_margin")
		   .fun<static_cast<PhysicsServer3D::ShapeType(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_shape_get_type)>("_shape_get_type")
		   .fun<static_cast<Variant(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_shape_get_data)>("_shape_get_data")
		   .fun<static_cast<double(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_shape_get_custom_solver_bias)>("_shape_get_custom_solver_bias")
		   .fun<static_cast<RID(PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_space_create)>("_space_create")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,bool)>(&PhysicsServer3DExtension::_space_set_active)>("_space_set_active")
		   .fun<static_cast<bool(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_space_is_active)>("_space_is_active")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,PhysicsServer3D::SpaceParameter,double)>(&PhysicsServer3DExtension::_space_set_param)>("_space_set_param")
		   .fun<static_cast<double(PhysicsServer3DExtension::*)(const RID &,PhysicsServer3D::SpaceParameter)const>(&PhysicsServer3DExtension::_space_get_param)>("_space_get_param")
		   .fun<static_cast<PhysicsDirectSpaceState3D *(PhysicsServer3DExtension::*)(const RID &)>(&PhysicsServer3DExtension::_space_get_direct_state)>("_space_get_direct_state")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,int32_t)>(&PhysicsServer3DExtension::_space_set_debug_contacts)>("_space_set_debug_contacts")
		   .fun<static_cast<PackedVector3Array(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_space_get_contacts)>("_space_get_contacts")
		   .fun<static_cast<int32_t(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_space_get_contact_count)>("_space_get_contact_count")
		   .fun<static_cast<RID(PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_area_create)>("_area_create")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,const RID &)>(&PhysicsServer3DExtension::_area_set_space)>("_area_set_space")
		   .fun<static_cast<RID(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_area_get_space)>("_area_get_space")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,const RID &,const Transform3D &,bool)>(&PhysicsServer3DExtension::_area_add_shape)>("_area_add_shape")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,int32_t,const RID &)>(&PhysicsServer3DExtension::_area_set_shape)>("_area_set_shape")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,int32_t,const Transform3D &)>(&PhysicsServer3DExtension::_area_set_shape_transform)>("_area_set_shape_transform")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,int32_t,bool)>(&PhysicsServer3DExtension::_area_set_shape_disabled)>("_area_set_shape_disabled")
		   .fun<static_cast<int32_t(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_area_get_shape_count)>("_area_get_shape_count")
		   .fun<static_cast<RID(PhysicsServer3DExtension::*)(const RID &,int32_t)const>(&PhysicsServer3DExtension::_area_get_shape)>("_area_get_shape")
		   .fun<static_cast<Transform3D(PhysicsServer3DExtension::*)(const RID &,int32_t)const>(&PhysicsServer3DExtension::_area_get_shape_transform)>("_area_get_shape_transform")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,int32_t)>(&PhysicsServer3DExtension::_area_remove_shape)>("_area_remove_shape")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &)>(&PhysicsServer3DExtension::_area_clear_shapes)>("_area_clear_shapes")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,uint64_t)>(&PhysicsServer3DExtension::_area_attach_object_instance_id)>("_area_attach_object_instance_id")
		   .fun<static_cast<uint64_t(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_area_get_object_instance_id)>("_area_get_object_instance_id")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,PhysicsServer3D::AreaParameter,const Variant &)>(&PhysicsServer3DExtension::_area_set_param)>("_area_set_param")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,const Transform3D &)>(&PhysicsServer3DExtension::_area_set_transform)>("_area_set_transform")
		   .fun<static_cast<Variant(PhysicsServer3DExtension::*)(const RID &,PhysicsServer3D::AreaParameter)const>(&PhysicsServer3DExtension::_area_get_param)>("_area_get_param")
		   .fun<static_cast<Transform3D(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_area_get_transform)>("_area_get_transform")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,uint32_t)>(&PhysicsServer3DExtension::_area_set_collision_layer)>("_area_set_collision_layer")
		   .fun<static_cast<uint32_t(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_area_get_collision_layer)>("_area_get_collision_layer")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,uint32_t)>(&PhysicsServer3DExtension::_area_set_collision_mask)>("_area_set_collision_mask")
		   .fun<static_cast<uint32_t(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_area_get_collision_mask)>("_area_get_collision_mask")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,bool)>(&PhysicsServer3DExtension::_area_set_monitorable)>("_area_set_monitorable")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,bool)>(&PhysicsServer3DExtension::_area_set_ray_pickable)>("_area_set_ray_pickable")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,const Callable &)>(&PhysicsServer3DExtension::_area_set_monitor_callback)>("_area_set_monitor_callback")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,const Callable &)>(&PhysicsServer3DExtension::_area_set_area_monitor_callback)>("_area_set_area_monitor_callback")
		   .fun<static_cast<RID(PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_body_create)>("_body_create")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,const RID &)>(&PhysicsServer3DExtension::_body_set_space)>("_body_set_space")
		   .fun<static_cast<RID(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_body_get_space)>("_body_get_space")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,PhysicsServer3D::BodyMode)>(&PhysicsServer3DExtension::_body_set_mode)>("_body_set_mode")
		   .fun<static_cast<PhysicsServer3D::BodyMode(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_body_get_mode)>("_body_get_mode")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,const RID &,const Transform3D &,bool)>(&PhysicsServer3DExtension::_body_add_shape)>("_body_add_shape")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,int32_t,const RID &)>(&PhysicsServer3DExtension::_body_set_shape)>("_body_set_shape")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,int32_t,const Transform3D &)>(&PhysicsServer3DExtension::_body_set_shape_transform)>("_body_set_shape_transform")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,int32_t,bool)>(&PhysicsServer3DExtension::_body_set_shape_disabled)>("_body_set_shape_disabled")
		   .fun<static_cast<int32_t(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_body_get_shape_count)>("_body_get_shape_count")
		   .fun<static_cast<RID(PhysicsServer3DExtension::*)(const RID &,int32_t)const>(&PhysicsServer3DExtension::_body_get_shape)>("_body_get_shape")
		   .fun<static_cast<Transform3D(PhysicsServer3DExtension::*)(const RID &,int32_t)const>(&PhysicsServer3DExtension::_body_get_shape_transform)>("_body_get_shape_transform")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,int32_t)>(&PhysicsServer3DExtension::_body_remove_shape)>("_body_remove_shape")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &)>(&PhysicsServer3DExtension::_body_clear_shapes)>("_body_clear_shapes")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,uint64_t)>(&PhysicsServer3DExtension::_body_attach_object_instance_id)>("_body_attach_object_instance_id")
		   .fun<static_cast<uint64_t(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_body_get_object_instance_id)>("_body_get_object_instance_id")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,bool)>(&PhysicsServer3DExtension::_body_set_enable_continuous_collision_detection)>("_body_set_enable_continuous_collision_detection")
		   .fun<static_cast<bool(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_body_is_continuous_collision_detection_enabled)>("_body_is_continuous_collision_detection_enabled")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,uint32_t)>(&PhysicsServer3DExtension::_body_set_collision_layer)>("_body_set_collision_layer")
		   .fun<static_cast<uint32_t(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_body_get_collision_layer)>("_body_get_collision_layer")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,uint32_t)>(&PhysicsServer3DExtension::_body_set_collision_mask)>("_body_set_collision_mask")
		   .fun<static_cast<uint32_t(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_body_get_collision_mask)>("_body_get_collision_mask")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,double)>(&PhysicsServer3DExtension::_body_set_collision_priority)>("_body_set_collision_priority")
		   .fun<static_cast<double(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_body_get_collision_priority)>("_body_get_collision_priority")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,uint32_t)>(&PhysicsServer3DExtension::_body_set_user_flags)>("_body_set_user_flags")
		   .fun<static_cast<uint32_t(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_body_get_user_flags)>("_body_get_user_flags")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,PhysicsServer3D::BodyParameter,const Variant &)>(&PhysicsServer3DExtension::_body_set_param)>("_body_set_param")
		   .fun<static_cast<Variant(PhysicsServer3DExtension::*)(const RID &,PhysicsServer3D::BodyParameter)const>(&PhysicsServer3DExtension::_body_get_param)>("_body_get_param")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &)>(&PhysicsServer3DExtension::_body_reset_mass_properties)>("_body_reset_mass_properties")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,PhysicsServer3D::BodyState,const Variant &)>(&PhysicsServer3DExtension::_body_set_state)>("_body_set_state")
		   .fun<static_cast<Variant(PhysicsServer3DExtension::*)(const RID &,PhysicsServer3D::BodyState)const>(&PhysicsServer3DExtension::_body_get_state)>("_body_get_state")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,const Vector3 &)>(&PhysicsServer3DExtension::_body_apply_central_impulse)>("_body_apply_central_impulse")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,const Vector3 &,const Vector3 &)>(&PhysicsServer3DExtension::_body_apply_impulse)>("_body_apply_impulse")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,const Vector3 &)>(&PhysicsServer3DExtension::_body_apply_torque_impulse)>("_body_apply_torque_impulse")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,const Vector3 &)>(&PhysicsServer3DExtension::_body_apply_central_force)>("_body_apply_central_force")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,const Vector3 &,const Vector3 &)>(&PhysicsServer3DExtension::_body_apply_force)>("_body_apply_force")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,const Vector3 &)>(&PhysicsServer3DExtension::_body_apply_torque)>("_body_apply_torque")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,const Vector3 &)>(&PhysicsServer3DExtension::_body_add_constant_central_force)>("_body_add_constant_central_force")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,const Vector3 &,const Vector3 &)>(&PhysicsServer3DExtension::_body_add_constant_force)>("_body_add_constant_force")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,const Vector3 &)>(&PhysicsServer3DExtension::_body_add_constant_torque)>("_body_add_constant_torque")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,const Vector3 &)>(&PhysicsServer3DExtension::_body_set_constant_force)>("_body_set_constant_force")
		   .fun<static_cast<Vector3(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_body_get_constant_force)>("_body_get_constant_force")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,const Vector3 &)>(&PhysicsServer3DExtension::_body_set_constant_torque)>("_body_set_constant_torque")
		   .fun<static_cast<Vector3(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_body_get_constant_torque)>("_body_get_constant_torque")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,const Vector3 &)>(&PhysicsServer3DExtension::_body_set_axis_velocity)>("_body_set_axis_velocity")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,PhysicsServer3D::BodyAxis,bool)>(&PhysicsServer3DExtension::_body_set_axis_lock)>("_body_set_axis_lock")
		   .fun<static_cast<bool(PhysicsServer3DExtension::*)(const RID &,PhysicsServer3D::BodyAxis)const>(&PhysicsServer3DExtension::_body_is_axis_locked)>("_body_is_axis_locked")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,const RID &)>(&PhysicsServer3DExtension::_body_add_collision_exception)>("_body_add_collision_exception")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,const RID &)>(&PhysicsServer3DExtension::_body_remove_collision_exception)>("_body_remove_collision_exception")
		   .fun<static_cast<TypedArray<RID>(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_body_get_collision_exceptions)>("_body_get_collision_exceptions")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,int32_t)>(&PhysicsServer3DExtension::_body_set_max_contacts_reported)>("_body_set_max_contacts_reported")
		   .fun<static_cast<int32_t(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_body_get_max_contacts_reported)>("_body_get_max_contacts_reported")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,double)>(&PhysicsServer3DExtension::_body_set_contacts_reported_depth_threshold)>("_body_set_contacts_reported_depth_threshold")
		   .fun<static_cast<double(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_body_get_contacts_reported_depth_threshold)>("_body_get_contacts_reported_depth_threshold")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,bool)>(&PhysicsServer3DExtension::_body_set_omit_force_integration)>("_body_set_omit_force_integration")
		   .fun<static_cast<bool(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_body_is_omitting_force_integration)>("_body_is_omitting_force_integration")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,const Callable &)>(&PhysicsServer3DExtension::_body_set_state_sync_callback)>("_body_set_state_sync_callback")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,const Callable &,const Variant &)>(&PhysicsServer3DExtension::_body_set_force_integration_callback)>("_body_set_force_integration_callback")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,bool)>(&PhysicsServer3DExtension::_body_set_ray_pickable)>("_body_set_ray_pickable")
		   .fun<static_cast<bool(PhysicsServer3DExtension::*)(const RID &,const Transform3D &,const Vector3 &,double,int32_t,bool,bool,PhysicsServer3DExtensionMotionResult*)const>(&PhysicsServer3DExtension::_body_test_motion)>("_body_test_motion")
		   .fun<static_cast<PhysicsDirectBodyState3D *(PhysicsServer3DExtension::*)(const RID &)>(&PhysicsServer3DExtension::_body_get_direct_state)>("_body_get_direct_state")
		   .fun<static_cast<RID(PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_soft_body_create)>("_soft_body_create")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,PhysicsServer3DRenderingServerHandler *)>(&PhysicsServer3DExtension::_soft_body_update_rendering_server)>("_soft_body_update_rendering_server")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,const RID &)>(&PhysicsServer3DExtension::_soft_body_set_space)>("_soft_body_set_space")
		   .fun<static_cast<RID(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_soft_body_get_space)>("_soft_body_get_space")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,bool)>(&PhysicsServer3DExtension::_soft_body_set_ray_pickable)>("_soft_body_set_ray_pickable")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,uint32_t)>(&PhysicsServer3DExtension::_soft_body_set_collision_layer)>("_soft_body_set_collision_layer")
		   .fun<static_cast<uint32_t(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_soft_body_get_collision_layer)>("_soft_body_get_collision_layer")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,uint32_t)>(&PhysicsServer3DExtension::_soft_body_set_collision_mask)>("_soft_body_set_collision_mask")
		   .fun<static_cast<uint32_t(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_soft_body_get_collision_mask)>("_soft_body_get_collision_mask")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,const RID &)>(&PhysicsServer3DExtension::_soft_body_add_collision_exception)>("_soft_body_add_collision_exception")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,const RID &)>(&PhysicsServer3DExtension::_soft_body_remove_collision_exception)>("_soft_body_remove_collision_exception")
		   .fun<static_cast<TypedArray<RID>(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_soft_body_get_collision_exceptions)>("_soft_body_get_collision_exceptions")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,PhysicsServer3D::BodyState,const Variant &)>(&PhysicsServer3DExtension::_soft_body_set_state)>("_soft_body_set_state")
		   .fun<static_cast<Variant(PhysicsServer3DExtension::*)(const RID &,PhysicsServer3D::BodyState)const>(&PhysicsServer3DExtension::_soft_body_get_state)>("_soft_body_get_state")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,const Transform3D &)>(&PhysicsServer3DExtension::_soft_body_set_transform)>("_soft_body_set_transform")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,int32_t)>(&PhysicsServer3DExtension::_soft_body_set_simulation_precision)>("_soft_body_set_simulation_precision")
		   .fun<static_cast<int32_t(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_soft_body_get_simulation_precision)>("_soft_body_get_simulation_precision")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,double)>(&PhysicsServer3DExtension::_soft_body_set_total_mass)>("_soft_body_set_total_mass")
		   .fun<static_cast<double(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_soft_body_get_total_mass)>("_soft_body_get_total_mass")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,double)>(&PhysicsServer3DExtension::_soft_body_set_linear_stiffness)>("_soft_body_set_linear_stiffness")
		   .fun<static_cast<double(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_soft_body_get_linear_stiffness)>("_soft_body_get_linear_stiffness")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,double)>(&PhysicsServer3DExtension::_soft_body_set_pressure_coefficient)>("_soft_body_set_pressure_coefficient")
		   .fun<static_cast<double(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_soft_body_get_pressure_coefficient)>("_soft_body_get_pressure_coefficient")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,double)>(&PhysicsServer3DExtension::_soft_body_set_damping_coefficient)>("_soft_body_set_damping_coefficient")
		   .fun<static_cast<double(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_soft_body_get_damping_coefficient)>("_soft_body_get_damping_coefficient")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,double)>(&PhysicsServer3DExtension::_soft_body_set_drag_coefficient)>("_soft_body_set_drag_coefficient")
		   .fun<static_cast<double(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_soft_body_get_drag_coefficient)>("_soft_body_get_drag_coefficient")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,const RID &)>(&PhysicsServer3DExtension::_soft_body_set_mesh)>("_soft_body_set_mesh")
		   .fun<static_cast<AABB(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_soft_body_get_bounds)>("_soft_body_get_bounds")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,int32_t,const Vector3 &)>(&PhysicsServer3DExtension::_soft_body_move_point)>("_soft_body_move_point")
		   .fun<static_cast<Vector3(PhysicsServer3DExtension::*)(const RID &,int32_t)const>(&PhysicsServer3DExtension::_soft_body_get_point_global_position)>("_soft_body_get_point_global_position")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &)>(&PhysicsServer3DExtension::_soft_body_remove_all_pinned_points)>("_soft_body_remove_all_pinned_points")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,int32_t,bool)>(&PhysicsServer3DExtension::_soft_body_pin_point)>("_soft_body_pin_point")
		   .fun<static_cast<bool(PhysicsServer3DExtension::*)(const RID &,int32_t)const>(&PhysicsServer3DExtension::_soft_body_is_point_pinned)>("_soft_body_is_point_pinned")
		   .fun<static_cast<RID(PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_joint_create)>("_joint_create")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &)>(&PhysicsServer3DExtension::_joint_clear)>("_joint_clear")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,const RID &,const Vector3 &,const RID &,const Vector3 &)>(&PhysicsServer3DExtension::_joint_make_pin)>("_joint_make_pin")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,PhysicsServer3D::PinJointParam,double)>(&PhysicsServer3DExtension::_pin_joint_set_param)>("_pin_joint_set_param")
		   .fun<static_cast<double(PhysicsServer3DExtension::*)(const RID &,PhysicsServer3D::PinJointParam)const>(&PhysicsServer3DExtension::_pin_joint_get_param)>("_pin_joint_get_param")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,const Vector3 &)>(&PhysicsServer3DExtension::_pin_joint_set_local_a)>("_pin_joint_set_local_a")
		   .fun<static_cast<Vector3(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_pin_joint_get_local_a)>("_pin_joint_get_local_a")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,const Vector3 &)>(&PhysicsServer3DExtension::_pin_joint_set_local_b)>("_pin_joint_set_local_b")
		   .fun<static_cast<Vector3(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_pin_joint_get_local_b)>("_pin_joint_get_local_b")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,const RID &,const Transform3D &,const RID &,const Transform3D &)>(&PhysicsServer3DExtension::_joint_make_hinge)>("_joint_make_hinge")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,const RID &,const Vector3 &,const Vector3 &,const RID &,const Vector3 &,const Vector3 &)>(&PhysicsServer3DExtension::_joint_make_hinge_simple)>("_joint_make_hinge_simple")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,PhysicsServer3D::HingeJointParam,double)>(&PhysicsServer3DExtension::_hinge_joint_set_param)>("_hinge_joint_set_param")
		   .fun<static_cast<double(PhysicsServer3DExtension::*)(const RID &,PhysicsServer3D::HingeJointParam)const>(&PhysicsServer3DExtension::_hinge_joint_get_param)>("_hinge_joint_get_param")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,PhysicsServer3D::HingeJointFlag,bool)>(&PhysicsServer3DExtension::_hinge_joint_set_flag)>("_hinge_joint_set_flag")
		   .fun<static_cast<bool(PhysicsServer3DExtension::*)(const RID &,PhysicsServer3D::HingeJointFlag)const>(&PhysicsServer3DExtension::_hinge_joint_get_flag)>("_hinge_joint_get_flag")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,const RID &,const Transform3D &,const RID &,const Transform3D &)>(&PhysicsServer3DExtension::_joint_make_slider)>("_joint_make_slider")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,PhysicsServer3D::SliderJointParam,double)>(&PhysicsServer3DExtension::_slider_joint_set_param)>("_slider_joint_set_param")
		   .fun<static_cast<double(PhysicsServer3DExtension::*)(const RID &,PhysicsServer3D::SliderJointParam)const>(&PhysicsServer3DExtension::_slider_joint_get_param)>("_slider_joint_get_param")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,const RID &,const Transform3D &,const RID &,const Transform3D &)>(&PhysicsServer3DExtension::_joint_make_cone_twist)>("_joint_make_cone_twist")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,PhysicsServer3D::ConeTwistJointParam,double)>(&PhysicsServer3DExtension::_cone_twist_joint_set_param)>("_cone_twist_joint_set_param")
		   .fun<static_cast<double(PhysicsServer3DExtension::*)(const RID &,PhysicsServer3D::ConeTwistJointParam)const>(&PhysicsServer3DExtension::_cone_twist_joint_get_param)>("_cone_twist_joint_get_param")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,const RID &,const Transform3D &,const RID &,const Transform3D &)>(&PhysicsServer3DExtension::_joint_make_generic_6dof)>("_joint_make_generic_6dof")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,Vector3::Axis,PhysicsServer3D::G6DOFJointAxisParam,double)>(&PhysicsServer3DExtension::_generic_6dof_joint_set_param)>("_generic_6dof_joint_set_param")
		   .fun<static_cast<double(PhysicsServer3DExtension::*)(const RID &,Vector3::Axis,PhysicsServer3D::G6DOFJointAxisParam)const>(&PhysicsServer3DExtension::_generic_6dof_joint_get_param)>("_generic_6dof_joint_get_param")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,Vector3::Axis,PhysicsServer3D::G6DOFJointAxisFlag,bool)>(&PhysicsServer3DExtension::_generic_6dof_joint_set_flag)>("_generic_6dof_joint_set_flag")
		   .fun<static_cast<bool(PhysicsServer3DExtension::*)(const RID &,Vector3::Axis,PhysicsServer3D::G6DOFJointAxisFlag)const>(&PhysicsServer3DExtension::_generic_6dof_joint_get_flag)>("_generic_6dof_joint_get_flag")
		   .fun<static_cast<PhysicsServer3D::JointType(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_joint_get_type)>("_joint_get_type")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,int32_t)>(&PhysicsServer3DExtension::_joint_set_solver_priority)>("_joint_set_solver_priority")
		   .fun<static_cast<int32_t(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_joint_get_solver_priority)>("_joint_get_solver_priority")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &,bool)>(&PhysicsServer3DExtension::_joint_disable_collisions_between_bodies)>("_joint_disable_collisions_between_bodies")
		   .fun<static_cast<bool(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::_joint_is_disabled_collisions_between_bodies)>("_joint_is_disabled_collisions_between_bodies")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(const RID &)>(&PhysicsServer3DExtension::_free_rid)>("_free_rid")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(bool)>(&PhysicsServer3DExtension::_set_active)>("_set_active")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_init)>("_init")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)(double)>(&PhysicsServer3DExtension::_step)>("_step")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_sync)>("_sync")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_flush_queries)>("_flush_queries")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_end_sync)>("_end_sync")
		   .fun<static_cast<void(PhysicsServer3DExtension::*)()>(&PhysicsServer3DExtension::_finish)>("_finish")
		   .fun<static_cast<bool(PhysicsServer3DExtension::*)()const>(&PhysicsServer3DExtension::_is_flushing_queries)>("_is_flushing_queries")
		   .fun<static_cast<int32_t(PhysicsServer3DExtension::*)(PhysicsServer3D::ProcessInfo)>(&PhysicsServer3DExtension::_get_process_info)>("_get_process_info")
		   .fun<static_cast<bool(PhysicsServer3DExtension::*)(const RID &)const>(&PhysicsServer3DExtension::body_test_motion_is_excluding_body)>("body_test_motion_is_excluding_body")
		   .fun<static_cast<bool(PhysicsServer3DExtension::*)(uint64_t)const>(&PhysicsServer3DExtension::body_test_motion_is_excluding_object)>("body_test_motion_is_excluding_object")
;}