#include <godot_cpp/classes/caret_info.hpp>
#include <godot_cpp/classes/global_constants.hpp>
#include <godot_cpp/classes/glyph.hpp>
#include <godot_cpp/classes/image.hpp>
#include <godot_cpp/classes/ref.hpp>
#include <godot_cpp/classes/text_server.hpp>
#include <godot_cpp/classes/text_server_extension.hpp>
#include <godot_cpp/core/type_info.hpp>
#include <godot_cpp/variant/array.hpp>
#include <godot_cpp/variant/color.hpp>
#include <godot_cpp/variant/dictionary.hpp>
#include <godot_cpp/variant/packed_byte_array.hpp>
#include <godot_cpp/variant/packed_float32_array.hpp>
#include <godot_cpp/variant/packed_int32_array.hpp>
#include <godot_cpp/variant/packed_string_array.hpp>
#include <godot_cpp/variant/packed_vector2_array.hpp>
#include <godot_cpp/variant/rect2.hpp>
#include <godot_cpp/variant/rid.hpp>
#include <godot_cpp/variant/string.hpp>
#include <godot_cpp/variant/transform2d.hpp>
#include <godot_cpp/variant/typed_array.hpp>
#include <godot_cpp/variant/variant.hpp>
#include <godot_cpp/variant/vector2.hpp>
#include <godot_cpp/variant/vector2i.hpp>
#include <godot_cpp/variant/vector3i.hpp>

#include "qjspp.hpp"
#include "register/register_classes.h"

using namespace godot;

void register_classes_TextServerExtension() {
	qjs::Context::Module &_module = get_General_module();
	_module.class_<TextServerExtension>("TextServerExtension")
			.constructor<>()
			.fun<static_cast<bool (TextServerExtension::*)(TextServer::Feature) const>(&TextServerExtension::_has_feature)>("_has_feature")
			.fun<static_cast<String (TextServerExtension::*)() const>(&TextServerExtension::_get_name)>("_get_name")
			.fun<static_cast<int64_t (TextServerExtension::*)() const>(&TextServerExtension::_get_features)>("_get_features")
			.fun<static_cast<void (TextServerExtension::*)(const RID &)>(&TextServerExtension::_free_rid)>("_free_rid")
			.fun<static_cast<bool (TextServerExtension::*)(const RID &)>(&TextServerExtension::_has)>("_has")
			.fun<static_cast<bool (TextServerExtension::*)(const String &)>(&TextServerExtension::_load_support_data)>("_load_support_data")
			.fun<static_cast<String (TextServerExtension::*)() const>(&TextServerExtension::_get_support_data_filename)>("_get_support_data_filename")
			.fun<static_cast<String (TextServerExtension::*)() const>(&TextServerExtension::_get_support_data_info)>("_get_support_data_info")
			.fun<static_cast<bool (TextServerExtension::*)(const String &) const>(&TextServerExtension::_save_support_data)>("_save_support_data")
			.fun<static_cast<bool (TextServerExtension::*)(const String &) const>(&TextServerExtension::_is_locale_right_to_left)>("_is_locale_right_to_left")
			.fun<static_cast<int64_t (TextServerExtension::*)(const String &) const>(&TextServerExtension::_name_to_tag)>("_name_to_tag")
			.fun<static_cast<String (TextServerExtension::*)(int64_t) const>(&TextServerExtension::_tag_to_name)>("_tag_to_name")
			.fun<static_cast<RID (TextServerExtension::*)()>(&TextServerExtension::_create_font)>("_create_font")
			.fun<static_cast<RID (TextServerExtension::*)(const RID &)>(&TextServerExtension::_create_font_linked_variation)>("_create_font_linked_variation")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const PackedByteArray &)>(&TextServerExtension::_font_set_data)>("_font_set_data")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const uint8_t *, int64_t)>(&TextServerExtension::_font_set_data_ptr)>("_font_set_data_ptr")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, int64_t)>(&TextServerExtension::_font_set_face_index)>("_font_set_face_index")
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_face_index)>("_font_get_face_index")
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_face_count)>("_font_get_face_count")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, BitField<TextServer::FontStyle>)>(&TextServerExtension::_font_set_style)>("_font_set_style")
			.fun<static_cast<BitField<TextServer::FontStyle> (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_style)>("_font_get_style")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const String &)>(&TextServerExtension::_font_set_name)>("_font_set_name")
			.fun<static_cast<String (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_name)>("_font_get_name")
			.fun<static_cast<Dictionary (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_ot_name_strings)>("_font_get_ot_name_strings")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const String &)>(&TextServerExtension::_font_set_style_name)>("_font_set_style_name")
			.fun<static_cast<String (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_style_name)>("_font_get_style_name")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, int64_t)>(&TextServerExtension::_font_set_weight)>("_font_set_weight")
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_weight)>("_font_get_weight")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, int64_t)>(&TextServerExtension::_font_set_stretch)>("_font_set_stretch")
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_stretch)>("_font_get_stretch")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, TextServer::FontAntialiasing)>(&TextServerExtension::_font_set_antialiasing)>("_font_set_antialiasing")
			.fun<static_cast<TextServer::FontAntialiasing (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_antialiasing)>("_font_get_antialiasing")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, bool)>(&TextServerExtension::_font_set_generate_mipmaps)>("_font_set_generate_mipmaps")
			.fun<static_cast<bool (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_generate_mipmaps)>("_font_get_generate_mipmaps")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, bool)>(&TextServerExtension::_font_set_multichannel_signed_distance_field)>("_font_set_multichannel_signed_distance_field")
			.fun<static_cast<bool (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_is_multichannel_signed_distance_field)>("_font_is_multichannel_signed_distance_field")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, int64_t)>(&TextServerExtension::_font_set_msdf_pixel_range)>("_font_set_msdf_pixel_range")
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_msdf_pixel_range)>("_font_get_msdf_pixel_range")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, int64_t)>(&TextServerExtension::_font_set_msdf_size)>("_font_set_msdf_size")
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_msdf_size)>("_font_get_msdf_size")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, int64_t)>(&TextServerExtension::_font_set_fixed_size)>("_font_set_fixed_size")
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_fixed_size)>("_font_get_fixed_size")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, TextServer::FixedSizeScaleMode)>(&TextServerExtension::_font_set_fixed_size_scale_mode)>("_font_set_fixed_size_scale_mode")
			.fun<static_cast<TextServer::FixedSizeScaleMode (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_fixed_size_scale_mode)>("_font_get_fixed_size_scale_mode")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, bool)>(&TextServerExtension::_font_set_allow_system_fallback)>("_font_set_allow_system_fallback")
			.fun<static_cast<bool (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_is_allow_system_fallback)>("_font_is_allow_system_fallback")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, bool)>(&TextServerExtension::_font_set_force_autohinter)>("_font_set_force_autohinter")
			.fun<static_cast<bool (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_is_force_autohinter)>("_font_is_force_autohinter")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, TextServer::Hinting)>(&TextServerExtension::_font_set_hinting)>("_font_set_hinting")
			.fun<static_cast<TextServer::Hinting (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_hinting)>("_font_get_hinting")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, TextServer::SubpixelPositioning)>(&TextServerExtension::_font_set_subpixel_positioning)>("_font_set_subpixel_positioning")
			.fun<static_cast<TextServer::SubpixelPositioning (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_subpixel_positioning)>("_font_get_subpixel_positioning")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, double)>(&TextServerExtension::_font_set_embolden)>("_font_set_embolden")
			.fun<static_cast<double (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_embolden)>("_font_get_embolden")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, TextServer::SpacingType, int64_t)>(&TextServerExtension::_font_set_spacing)>("_font_set_spacing")
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &, TextServer::SpacingType) const>(&TextServerExtension::_font_get_spacing)>("_font_get_spacing")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const Transform2D &)>(&TextServerExtension::_font_set_transform)>("_font_set_transform")
			.fun<static_cast<Transform2D (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_transform)>("_font_get_transform")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const Dictionary &)>(&TextServerExtension::_font_set_variation_coordinates)>("_font_set_variation_coordinates")
			.fun<static_cast<Dictionary (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_variation_coordinates)>("_font_get_variation_coordinates")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, double)>(&TextServerExtension::_font_set_oversampling)>("_font_set_oversampling")
			.fun<static_cast<double (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_oversampling)>("_font_get_oversampling")
			.fun<static_cast<TypedArray<Vector2i> (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_size_cache_list)>("_font_get_size_cache_list")
			.fun<static_cast<void (TextServerExtension::*)(const RID &)>(&TextServerExtension::_font_clear_size_cache)>("_font_clear_size_cache")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const Vector2i &)>(&TextServerExtension::_font_remove_size_cache)>("_font_remove_size_cache")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, int64_t, double)>(&TextServerExtension::_font_set_ascent)>("_font_set_ascent")
			.fun<static_cast<double (TextServerExtension::*)(const RID &, int64_t) const>(&TextServerExtension::_font_get_ascent)>("_font_get_ascent")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, int64_t, double)>(&TextServerExtension::_font_set_descent)>("_font_set_descent")
			.fun<static_cast<double (TextServerExtension::*)(const RID &, int64_t) const>(&TextServerExtension::_font_get_descent)>("_font_get_descent")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, int64_t, double)>(&TextServerExtension::_font_set_underline_position)>("_font_set_underline_position")
			.fun<static_cast<double (TextServerExtension::*)(const RID &, int64_t) const>(&TextServerExtension::_font_get_underline_position)>("_font_get_underline_position")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, int64_t, double)>(&TextServerExtension::_font_set_underline_thickness)>("_font_set_underline_thickness")
			.fun<static_cast<double (TextServerExtension::*)(const RID &, int64_t) const>(&TextServerExtension::_font_get_underline_thickness)>("_font_get_underline_thickness")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, int64_t, double)>(&TextServerExtension::_font_set_scale)>("_font_set_scale")
			.fun<static_cast<double (TextServerExtension::*)(const RID &, int64_t) const>(&TextServerExtension::_font_get_scale)>("_font_get_scale")
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &, const Vector2i &) const>(&TextServerExtension::_font_get_texture_count)>("_font_get_texture_count")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const Vector2i &)>(&TextServerExtension::_font_clear_textures)>("_font_clear_textures")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const Vector2i &, int64_t)>(&TextServerExtension::_font_remove_texture)>("_font_remove_texture")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const Vector2i &, int64_t, const Ref<Image> &)>(&TextServerExtension::_font_set_texture_image)>("_font_set_texture_image")
			.fun<static_cast<Ref<Image> (TextServerExtension::*)(const RID &, const Vector2i &, int64_t) const>(&TextServerExtension::_font_get_texture_image)>("_font_get_texture_image")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const Vector2i &, int64_t, const PackedInt32Array &)>(&TextServerExtension::_font_set_texture_offsets)>("_font_set_texture_offsets")
			.fun<static_cast<PackedInt32Array (TextServerExtension::*)(const RID &, const Vector2i &, int64_t) const>(&TextServerExtension::_font_get_texture_offsets)>("_font_get_texture_offsets")
			.fun<static_cast<PackedInt32Array (TextServerExtension::*)(const RID &, const Vector2i &) const>(&TextServerExtension::_font_get_glyph_list)>("_font_get_glyph_list")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const Vector2i &)>(&TextServerExtension::_font_clear_glyphs)>("_font_clear_glyphs")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const Vector2i &, int64_t)>(&TextServerExtension::_font_remove_glyph)>("_font_remove_glyph")
			.fun<static_cast<Vector2 (TextServerExtension::*)(const RID &, int64_t, int64_t) const>(&TextServerExtension::_font_get_glyph_advance)>("_font_get_glyph_advance")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, int64_t, int64_t, const Vector2 &)>(&TextServerExtension::_font_set_glyph_advance)>("_font_set_glyph_advance")
			.fun<static_cast<Vector2 (TextServerExtension::*)(const RID &, const Vector2i &, int64_t) const>(&TextServerExtension::_font_get_glyph_offset)>("_font_get_glyph_offset")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const Vector2i &, int64_t, const Vector2 &)>(&TextServerExtension::_font_set_glyph_offset)>("_font_set_glyph_offset")
			.fun<static_cast<Vector2 (TextServerExtension::*)(const RID &, const Vector2i &, int64_t) const>(&TextServerExtension::_font_get_glyph_size)>("_font_get_glyph_size")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const Vector2i &, int64_t, const Vector2 &)>(&TextServerExtension::_font_set_glyph_size)>("_font_set_glyph_size")
			.fun<static_cast<Rect2 (TextServerExtension::*)(const RID &, const Vector2i &, int64_t) const>(&TextServerExtension::_font_get_glyph_uv_rect)>("_font_get_glyph_uv_rect")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const Vector2i &, int64_t, const Rect2 &)>(&TextServerExtension::_font_set_glyph_uv_rect)>("_font_set_glyph_uv_rect")
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &, const Vector2i &, int64_t) const>(&TextServerExtension::_font_get_glyph_texture_idx)>("_font_get_glyph_texture_idx")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const Vector2i &, int64_t, int64_t)>(&TextServerExtension::_font_set_glyph_texture_idx)>("_font_set_glyph_texture_idx")
			.fun<static_cast<RID (TextServerExtension::*)(const RID &, const Vector2i &, int64_t) const>(&TextServerExtension::_font_get_glyph_texture_rid)>("_font_get_glyph_texture_rid")
			.fun<static_cast<Vector2 (TextServerExtension::*)(const RID &, const Vector2i &, int64_t) const>(&TextServerExtension::_font_get_glyph_texture_size)>("_font_get_glyph_texture_size")
			.fun<static_cast<Dictionary (TextServerExtension::*)(const RID &, int64_t, int64_t) const>(&TextServerExtension::_font_get_glyph_contours)>("_font_get_glyph_contours")
			.fun<static_cast<TypedArray<Vector2i> (TextServerExtension::*)(const RID &, int64_t) const>(&TextServerExtension::_font_get_kerning_list)>("_font_get_kerning_list")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, int64_t)>(&TextServerExtension::_font_clear_kerning_map)>("_font_clear_kerning_map")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, int64_t, const Vector2i &)>(&TextServerExtension::_font_remove_kerning)>("_font_remove_kerning")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, int64_t, const Vector2i &, const Vector2 &)>(&TextServerExtension::_font_set_kerning)>("_font_set_kerning")
			.fun<static_cast<Vector2 (TextServerExtension::*)(const RID &, int64_t, const Vector2i &) const>(&TextServerExtension::_font_get_kerning)>("_font_get_kerning")
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &, int64_t, int64_t, int64_t) const>(&TextServerExtension::_font_get_glyph_index)>("_font_get_glyph_index")
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &, int64_t, int64_t) const>(&TextServerExtension::_font_get_char_from_glyph_index)>("_font_get_char_from_glyph_index")
			.fun<static_cast<bool (TextServerExtension::*)(const RID &, int64_t) const>(&TextServerExtension::_font_has_char)>("_font_has_char")
			.fun<static_cast<String (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_supported_chars)>("_font_get_supported_chars")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const Vector2i &, int64_t, int64_t)>(&TextServerExtension::_font_render_range)>("_font_render_range")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const Vector2i &, int64_t)>(&TextServerExtension::_font_render_glyph)>("_font_render_glyph")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const RID &, int64_t, const Vector2 &, int64_t, const Color &) const>(&TextServerExtension::_font_draw_glyph)>("_font_draw_glyph")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const RID &, int64_t, int64_t, const Vector2 &, int64_t, const Color &) const>(&TextServerExtension::_font_draw_glyph_outline)>("_font_draw_glyph_outline")
			.fun<static_cast<bool (TextServerExtension::*)(const RID &, const String &) const>(&TextServerExtension::_font_is_language_supported)>("_font_is_language_supported")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const String &, bool)>(&TextServerExtension::_font_set_language_support_override)>("_font_set_language_support_override")
			.fun<static_cast<bool (TextServerExtension::*)(const RID &, const String &)>(&TextServerExtension::_font_get_language_support_override)>("_font_get_language_support_override")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const String &)>(&TextServerExtension::_font_remove_language_support_override)>("_font_remove_language_support_override")
			.fun<static_cast<PackedStringArray (TextServerExtension::*)(const RID &)>(&TextServerExtension::_font_get_language_support_overrides)>("_font_get_language_support_overrides")
			.fun<static_cast<bool (TextServerExtension::*)(const RID &, const String &) const>(&TextServerExtension::_font_is_script_supported)>("_font_is_script_supported")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const String &, bool)>(&TextServerExtension::_font_set_script_support_override)>("_font_set_script_support_override")
			.fun<static_cast<bool (TextServerExtension::*)(const RID &, const String &)>(&TextServerExtension::_font_get_script_support_override)>("_font_get_script_support_override")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const String &)>(&TextServerExtension::_font_remove_script_support_override)>("_font_remove_script_support_override")
			.fun<static_cast<PackedStringArray (TextServerExtension::*)(const RID &)>(&TextServerExtension::_font_get_script_support_overrides)>("_font_get_script_support_overrides")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const Dictionary &)>(&TextServerExtension::_font_set_opentype_feature_overrides)>("_font_set_opentype_feature_overrides")
			.fun<static_cast<Dictionary (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_get_opentype_feature_overrides)>("_font_get_opentype_feature_overrides")
			.fun<static_cast<Dictionary (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_supported_feature_list)>("_font_supported_feature_list")
			.fun<static_cast<Dictionary (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_font_supported_variation_list)>("_font_supported_variation_list")
			.fun<static_cast<double (TextServerExtension::*)() const>(&TextServerExtension::_font_get_global_oversampling)>("_font_get_global_oversampling")
			.fun<static_cast<void (TextServerExtension::*)(double)>(&TextServerExtension::_font_set_global_oversampling)>("_font_set_global_oversampling")
			.fun<static_cast<Vector2 (TextServerExtension::*)(int64_t, int64_t) const>(&TextServerExtension::_get_hex_code_box_size)>("_get_hex_code_box_size")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, int64_t, const Vector2 &, int64_t, const Color &) const>(&TextServerExtension::_draw_hex_code_box)>("_draw_hex_code_box")
			.fun<static_cast<RID (TextServerExtension::*)(TextServer::Direction, TextServer::Orientation)>(&TextServerExtension::_create_shaped_text)>("_create_shaped_text")
			.fun<static_cast<void (TextServerExtension::*)(const RID &)>(&TextServerExtension::_shaped_text_clear)>("_shaped_text_clear")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, TextServer::Direction)>(&TextServerExtension::_shaped_text_set_direction)>("_shaped_text_set_direction")
			.fun<static_cast<TextServer::Direction (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_direction)>("_shaped_text_get_direction")
			.fun<static_cast<TextServer::Direction (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_inferred_direction)>("_shaped_text_get_inferred_direction")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const Array &)>(&TextServerExtension::_shaped_text_set_bidi_override)>("_shaped_text_set_bidi_override")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const String &)>(&TextServerExtension::_shaped_text_set_custom_punctuation)>("_shaped_text_set_custom_punctuation")
			.fun<static_cast<String (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_custom_punctuation)>("_shaped_text_get_custom_punctuation")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, TextServer::Orientation)>(&TextServerExtension::_shaped_text_set_orientation)>("_shaped_text_set_orientation")
			.fun<static_cast<TextServer::Orientation (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_orientation)>("_shaped_text_get_orientation")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, bool)>(&TextServerExtension::_shaped_text_set_preserve_invalid)>("_shaped_text_set_preserve_invalid")
			.fun<static_cast<bool (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_preserve_invalid)>("_shaped_text_get_preserve_invalid")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, bool)>(&TextServerExtension::_shaped_text_set_preserve_control)>("_shaped_text_set_preserve_control")
			.fun<static_cast<bool (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_preserve_control)>("_shaped_text_get_preserve_control")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, TextServer::SpacingType, int64_t)>(&TextServerExtension::_shaped_text_set_spacing)>("_shaped_text_set_spacing")
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &, TextServer::SpacingType) const>(&TextServerExtension::_shaped_text_get_spacing)>("_shaped_text_get_spacing")
			.fun<static_cast<bool (TextServerExtension::*)(const RID &, const String &, const TypedArray<RID> &, int64_t, const Dictionary &, const String &, const Variant &)>(&TextServerExtension::_shaped_text_add_string)>("_shaped_text_add_string")
			.fun<static_cast<bool (TextServerExtension::*)(const RID &, const Variant &, const Vector2 &, InlineAlignment, int64_t, double)>(&TextServerExtension::_shaped_text_add_object)>("_shaped_text_add_object")
			.fun<static_cast<bool (TextServerExtension::*)(const RID &, const Variant &, const Vector2 &, InlineAlignment, double)>(&TextServerExtension::_shaped_text_resize_object)>("_shaped_text_resize_object")
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_get_span_count)>("_shaped_get_span_count")
			.fun<static_cast<Variant (TextServerExtension::*)(const RID &, int64_t) const>(&TextServerExtension::_shaped_get_span_meta)>("_shaped_get_span_meta")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, int64_t, const TypedArray<RID> &, int64_t, const Dictionary &)>(&TextServerExtension::_shaped_set_span_update_font)>("_shaped_set_span_update_font")
			.fun<static_cast<RID (TextServerExtension::*)(const RID &, int64_t, int64_t) const>(&TextServerExtension::_shaped_text_substr)>("_shaped_text_substr")
			.fun<static_cast<RID (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_parent)>("_shaped_text_get_parent")
			.fun<static_cast<double (TextServerExtension::*)(const RID &, double, BitField<TextServer::JustificationFlag>)>(&TextServerExtension::_shaped_text_fit_to_width)>("_shaped_text_fit_to_width")
			.fun<static_cast<double (TextServerExtension::*)(const RID &, const PackedFloat32Array &)>(&TextServerExtension::_shaped_text_tab_align)>("_shaped_text_tab_align")
			.fun<static_cast<bool (TextServerExtension::*)(const RID &)>(&TextServerExtension::_shaped_text_shape)>("_shaped_text_shape")
			.fun<static_cast<bool (TextServerExtension::*)(const RID &)>(&TextServerExtension::_shaped_text_update_breaks)>("_shaped_text_update_breaks")
			.fun<static_cast<bool (TextServerExtension::*)(const RID &)>(&TextServerExtension::_shaped_text_update_justification_ops)>("_shaped_text_update_justification_ops")
			.fun<static_cast<bool (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_is_ready)>("_shaped_text_is_ready")
			.fun<static_cast<const Glyph *(TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_glyphs)>("_shaped_text_get_glyphs")
			.fun<static_cast<const Glyph *(TextServerExtension::*)(const RID &)>(&TextServerExtension::_shaped_text_sort_logical)>("_shaped_text_sort_logical")
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_glyph_count)>("_shaped_text_get_glyph_count")
			.fun<static_cast<Vector2i (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_range)>("_shaped_text_get_range")
			.fun<static_cast<PackedInt32Array (TextServerExtension::*)(const RID &, const PackedFloat32Array &, int64_t, bool, BitField<TextServer::LineBreakFlag>) const>(&TextServerExtension::_shaped_text_get_line_breaks_adv)>("_shaped_text_get_line_breaks_adv")
			.fun<static_cast<PackedInt32Array (TextServerExtension::*)(const RID &, double, int64_t, BitField<TextServer::LineBreakFlag>) const>(&TextServerExtension::_shaped_text_get_line_breaks)>("_shaped_text_get_line_breaks")
			.fun<static_cast<PackedInt32Array (TextServerExtension::*)(const RID &, BitField<TextServer::GraphemeFlag>, BitField<TextServer::GraphemeFlag>) const>(&TextServerExtension::_shaped_text_get_word_breaks)>("_shaped_text_get_word_breaks")
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_trim_pos)>("_shaped_text_get_trim_pos")
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_ellipsis_pos)>("_shaped_text_get_ellipsis_pos")
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_ellipsis_glyph_count)>("_shaped_text_get_ellipsis_glyph_count")
			.fun<static_cast<const Glyph *(TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_ellipsis_glyphs)>("_shaped_text_get_ellipsis_glyphs")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, double, BitField<TextServer::TextOverrunFlag>)>(&TextServerExtension::_shaped_text_overrun_trim_to_width)>("_shaped_text_overrun_trim_to_width")
			.fun<static_cast<Array (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_objects)>("_shaped_text_get_objects")
			.fun<static_cast<Rect2 (TextServerExtension::*)(const RID &, const Variant &) const>(&TextServerExtension::_shaped_text_get_object_rect)>("_shaped_text_get_object_rect")
			.fun<static_cast<Vector2 (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_size)>("_shaped_text_get_size")
			.fun<static_cast<double (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_ascent)>("_shaped_text_get_ascent")
			.fun<static_cast<double (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_descent)>("_shaped_text_get_descent")
			.fun<static_cast<double (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_width)>("_shaped_text_get_width")
			.fun<static_cast<double (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_underline_position)>("_shaped_text_get_underline_position")
			.fun<static_cast<double (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_underline_thickness)>("_shaped_text_get_underline_thickness")
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &, int64_t, int64_t) const>(&TextServerExtension::_shaped_text_get_dominant_direction_in_range)>("_shaped_text_get_dominant_direction_in_range")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, int64_t, CaretInfo *) const>(&TextServerExtension::_shaped_text_get_carets)>("_shaped_text_get_carets")
			.fun<static_cast<PackedVector2Array (TextServerExtension::*)(const RID &, int64_t, int64_t) const>(&TextServerExtension::_shaped_text_get_selection)>("_shaped_text_get_selection")
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &, double) const>(&TextServerExtension::_shaped_text_hit_test_grapheme)>("_shaped_text_hit_test_grapheme")
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &, double) const>(&TextServerExtension::_shaped_text_hit_test_position)>("_shaped_text_hit_test_position")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const RID &, const Vector2 &, double, double, const Color &) const>(&TextServerExtension::_shaped_text_draw)>("_shaped_text_draw")
			.fun<static_cast<void (TextServerExtension::*)(const RID &, const RID &, const Vector2 &, double, double, int64_t, const Color &) const>(&TextServerExtension::_shaped_text_draw_outline)>("_shaped_text_draw_outline")
			.fun<static_cast<Vector2 (TextServerExtension::*)(const RID &, int64_t) const>(&TextServerExtension::_shaped_text_get_grapheme_bounds)>("_shaped_text_get_grapheme_bounds")
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &, int64_t) const>(&TextServerExtension::_shaped_text_next_grapheme_pos)>("_shaped_text_next_grapheme_pos")
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &, int64_t) const>(&TextServerExtension::_shaped_text_prev_grapheme_pos)>("_shaped_text_prev_grapheme_pos")
			.fun<static_cast<PackedInt32Array (TextServerExtension::*)(const RID &) const>(&TextServerExtension::_shaped_text_get_character_breaks)>("_shaped_text_get_character_breaks")
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &, int64_t) const>(&TextServerExtension::_shaped_text_next_character_pos)>("_shaped_text_next_character_pos")
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &, int64_t) const>(&TextServerExtension::_shaped_text_prev_character_pos)>("_shaped_text_prev_character_pos")
			.fun<static_cast<int64_t (TextServerExtension::*)(const RID &, int64_t) const>(&TextServerExtension::_shaped_text_closest_character_pos)>("_shaped_text_closest_character_pos")
			.fun<static_cast<String (TextServerExtension::*)(const String &, const String &) const>(&TextServerExtension::_format_number)>("_format_number")
			.fun<static_cast<String (TextServerExtension::*)(const String &, const String &) const>(&TextServerExtension::_parse_number)>("_parse_number")
			.fun<static_cast<String (TextServerExtension::*)(const String &) const>(&TextServerExtension::_percent_sign)>("_percent_sign")
			.fun<static_cast<String (TextServerExtension::*)(const String &) const>(&TextServerExtension::_strip_diacritics)>("_strip_diacritics")
			.fun<static_cast<bool (TextServerExtension::*)(const String &) const>(&TextServerExtension::_is_valid_identifier)>("_is_valid_identifier")
			.fun<static_cast<PackedInt32Array (TextServerExtension::*)(const String &, const String &, int64_t) const>(&TextServerExtension::_string_get_word_breaks)>("_string_get_word_breaks")
			.fun<static_cast<PackedInt32Array (TextServerExtension::*)(const String &, const String &) const>(&TextServerExtension::_string_get_character_breaks)>("_string_get_character_breaks")
			.fun<static_cast<int64_t (TextServerExtension::*)(const String &, const PackedStringArray &) const>(&TextServerExtension::_is_confusable)>("_is_confusable")
			.fun<static_cast<bool (TextServerExtension::*)(const String &) const>(&TextServerExtension::_spoof_check)>("_spoof_check")
			.fun<static_cast<String (TextServerExtension::*)(const String &, const String &) const>(&TextServerExtension::_string_to_upper)>("_string_to_upper")
			.fun<static_cast<String (TextServerExtension::*)(const String &, const String &) const>(&TextServerExtension::_string_to_lower)>("_string_to_lower")
			.fun<static_cast<TypedArray<Vector3i> (TextServerExtension::*)(TextServer::StructuredTextParser, const Array &, const String &) const>(&TextServerExtension::_parse_structured_text)>("_parse_structured_text")
			.fun<static_cast<void (TextServerExtension::*)()>(&TextServerExtension::_cleanup)>("_cleanup");
}