#include <godot_cpp/classes/physics_direct_body_state2d.hpp>
#include <godot_cpp/classes/physics_direct_space_state2d.hpp>
#include <godot_cpp/classes/physics_server2d.hpp>
#include <godot_cpp/classes/physics_server2d_extension.hpp>
#include <godot_cpp/classes/physics_server2d_extension_motion_result.hpp>
#include <godot_cpp/variant/callable.hpp>
#include <godot_cpp/variant/packed_vector2_array.hpp>
#include <godot_cpp/variant/rid.hpp>
#include <godot_cpp/variant/transform2d.hpp>
#include <godot_cpp/variant/typed_array.hpp>
#include <godot_cpp/variant/variant.hpp>
#include <godot_cpp/variant/vector2.hpp>

#include "qjspp.hpp"
#include "register/register_classes.h"

using namespace godot;

void register_classes_PhysicsServer2DExtension() {
	qjs::Context::Module &_module = get_General_module();
	_module.class_<PhysicsServer2DExtension>("PhysicsServer2DExtension")
			.constructor<>()
			.fun<static_cast<RID (PhysicsServer2DExtension::*)()>(&PhysicsServer2DExtension::_world_boundary_shape_create)>("_world_boundary_shape_create")
			.fun<static_cast<RID (PhysicsServer2DExtension::*)()>(&PhysicsServer2DExtension::_separation_ray_shape_create)>("_separation_ray_shape_create")
			.fun<static_cast<RID (PhysicsServer2DExtension::*)()>(&PhysicsServer2DExtension::_segment_shape_create)>("_segment_shape_create")
			.fun<static_cast<RID (PhysicsServer2DExtension::*)()>(&PhysicsServer2DExtension::_circle_shape_create)>("_circle_shape_create")
			.fun<static_cast<RID (PhysicsServer2DExtension::*)()>(&PhysicsServer2DExtension::_rectangle_shape_create)>("_rectangle_shape_create")
			.fun<static_cast<RID (PhysicsServer2DExtension::*)()>(&PhysicsServer2DExtension::_capsule_shape_create)>("_capsule_shape_create")
			.fun<static_cast<RID (PhysicsServer2DExtension::*)()>(&PhysicsServer2DExtension::_convex_polygon_shape_create)>("_convex_polygon_shape_create")
			.fun<static_cast<RID (PhysicsServer2DExtension::*)()>(&PhysicsServer2DExtension::_concave_polygon_shape_create)>("_concave_polygon_shape_create")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const Variant &)>(&PhysicsServer2DExtension::_shape_set_data)>("_shape_set_data")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, double)>(&PhysicsServer2DExtension::_shape_set_custom_solver_bias)>("_shape_set_custom_solver_bias")
			.fun<static_cast<PhysicsServer2D::ShapeType (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_shape_get_type)>("_shape_get_type")
			.fun<static_cast<Variant (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_shape_get_data)>("_shape_get_data")
			.fun<static_cast<double (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_shape_get_custom_solver_bias)>("_shape_get_custom_solver_bias")
			.fun<static_cast<bool (PhysicsServer2DExtension::*)(const RID &, const Transform2D &, const Vector2 &, const RID &, const Transform2D &, const Vector2 &, void *, int32_t, int32_t *)>(&PhysicsServer2DExtension::_shape_collide)>("_shape_collide")
			.fun<static_cast<RID (PhysicsServer2DExtension::*)()>(&PhysicsServer2DExtension::_space_create)>("_space_create")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, bool)>(&PhysicsServer2DExtension::_space_set_active)>("_space_set_active")
			.fun<static_cast<bool (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_space_is_active)>("_space_is_active")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, PhysicsServer2D::SpaceParameter, double)>(&PhysicsServer2DExtension::_space_set_param)>("_space_set_param")
			.fun<static_cast<double (PhysicsServer2DExtension::*)(const RID &, PhysicsServer2D::SpaceParameter) const>(&PhysicsServer2DExtension::_space_get_param)>("_space_get_param")
			.fun<static_cast<PhysicsDirectSpaceState2D *(PhysicsServer2DExtension::*)(const RID &)>(&PhysicsServer2DExtension::_space_get_direct_state)>("_space_get_direct_state")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, int32_t)>(&PhysicsServer2DExtension::_space_set_debug_contacts)>("_space_set_debug_contacts")
			.fun<static_cast<PackedVector2Array (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_space_get_contacts)>("_space_get_contacts")
			.fun<static_cast<int32_t (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_space_get_contact_count)>("_space_get_contact_count")
			.fun<static_cast<RID (PhysicsServer2DExtension::*)()>(&PhysicsServer2DExtension::_area_create)>("_area_create")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const RID &)>(&PhysicsServer2DExtension::_area_set_space)>("_area_set_space")
			.fun<static_cast<RID (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_area_get_space)>("_area_get_space")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const RID &, const Transform2D &, bool)>(&PhysicsServer2DExtension::_area_add_shape)>("_area_add_shape")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, int32_t, const RID &)>(&PhysicsServer2DExtension::_area_set_shape)>("_area_set_shape")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, int32_t, const Transform2D &)>(&PhysicsServer2DExtension::_area_set_shape_transform)>("_area_set_shape_transform")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, int32_t, bool)>(&PhysicsServer2DExtension::_area_set_shape_disabled)>("_area_set_shape_disabled")
			.fun<static_cast<int32_t (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_area_get_shape_count)>("_area_get_shape_count")
			.fun<static_cast<RID (PhysicsServer2DExtension::*)(const RID &, int32_t) const>(&PhysicsServer2DExtension::_area_get_shape)>("_area_get_shape")
			.fun<static_cast<Transform2D (PhysicsServer2DExtension::*)(const RID &, int32_t) const>(&PhysicsServer2DExtension::_area_get_shape_transform)>("_area_get_shape_transform")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, int32_t)>(&PhysicsServer2DExtension::_area_remove_shape)>("_area_remove_shape")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &)>(&PhysicsServer2DExtension::_area_clear_shapes)>("_area_clear_shapes")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, uint64_t)>(&PhysicsServer2DExtension::_area_attach_object_instance_id)>("_area_attach_object_instance_id")
			.fun<static_cast<uint64_t (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_area_get_object_instance_id)>("_area_get_object_instance_id")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, uint64_t)>(&PhysicsServer2DExtension::_area_attach_canvas_instance_id)>("_area_attach_canvas_instance_id")
			.fun<static_cast<uint64_t (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_area_get_canvas_instance_id)>("_area_get_canvas_instance_id")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, PhysicsServer2D::AreaParameter, const Variant &)>(&PhysicsServer2DExtension::_area_set_param)>("_area_set_param")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const Transform2D &)>(&PhysicsServer2DExtension::_area_set_transform)>("_area_set_transform")
			.fun<static_cast<Variant (PhysicsServer2DExtension::*)(const RID &, PhysicsServer2D::AreaParameter) const>(&PhysicsServer2DExtension::_area_get_param)>("_area_get_param")
			.fun<static_cast<Transform2D (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_area_get_transform)>("_area_get_transform")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, uint32_t)>(&PhysicsServer2DExtension::_area_set_collision_layer)>("_area_set_collision_layer")
			.fun<static_cast<uint32_t (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_area_get_collision_layer)>("_area_get_collision_layer")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, uint32_t)>(&PhysicsServer2DExtension::_area_set_collision_mask)>("_area_set_collision_mask")
			.fun<static_cast<uint32_t (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_area_get_collision_mask)>("_area_get_collision_mask")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, bool)>(&PhysicsServer2DExtension::_area_set_monitorable)>("_area_set_monitorable")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, bool)>(&PhysicsServer2DExtension::_area_set_pickable)>("_area_set_pickable")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const Callable &)>(&PhysicsServer2DExtension::_area_set_monitor_callback)>("_area_set_monitor_callback")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const Callable &)>(&PhysicsServer2DExtension::_area_set_area_monitor_callback)>("_area_set_area_monitor_callback")
			.fun<static_cast<RID (PhysicsServer2DExtension::*)()>(&PhysicsServer2DExtension::_body_create)>("_body_create")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const RID &)>(&PhysicsServer2DExtension::_body_set_space)>("_body_set_space")
			.fun<static_cast<RID (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_body_get_space)>("_body_get_space")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, PhysicsServer2D::BodyMode)>(&PhysicsServer2DExtension::_body_set_mode)>("_body_set_mode")
			.fun<static_cast<PhysicsServer2D::BodyMode (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_body_get_mode)>("_body_get_mode")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const RID &, const Transform2D &, bool)>(&PhysicsServer2DExtension::_body_add_shape)>("_body_add_shape")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, int32_t, const RID &)>(&PhysicsServer2DExtension::_body_set_shape)>("_body_set_shape")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, int32_t, const Transform2D &)>(&PhysicsServer2DExtension::_body_set_shape_transform)>("_body_set_shape_transform")
			.fun<static_cast<int32_t (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_body_get_shape_count)>("_body_get_shape_count")
			.fun<static_cast<RID (PhysicsServer2DExtension::*)(const RID &, int32_t) const>(&PhysicsServer2DExtension::_body_get_shape)>("_body_get_shape")
			.fun<static_cast<Transform2D (PhysicsServer2DExtension::*)(const RID &, int32_t) const>(&PhysicsServer2DExtension::_body_get_shape_transform)>("_body_get_shape_transform")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, int32_t, bool)>(&PhysicsServer2DExtension::_body_set_shape_disabled)>("_body_set_shape_disabled")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, int32_t, bool, double)>(&PhysicsServer2DExtension::_body_set_shape_as_one_way_collision)>("_body_set_shape_as_one_way_collision")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, int32_t)>(&PhysicsServer2DExtension::_body_remove_shape)>("_body_remove_shape")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &)>(&PhysicsServer2DExtension::_body_clear_shapes)>("_body_clear_shapes")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, uint64_t)>(&PhysicsServer2DExtension::_body_attach_object_instance_id)>("_body_attach_object_instance_id")
			.fun<static_cast<uint64_t (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_body_get_object_instance_id)>("_body_get_object_instance_id")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, uint64_t)>(&PhysicsServer2DExtension::_body_attach_canvas_instance_id)>("_body_attach_canvas_instance_id")
			.fun<static_cast<uint64_t (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_body_get_canvas_instance_id)>("_body_get_canvas_instance_id")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, PhysicsServer2D::CCDMode)>(&PhysicsServer2DExtension::_body_set_continuous_collision_detection_mode)>("_body_set_continuous_collision_detection_mode")
			.fun<static_cast<PhysicsServer2D::CCDMode (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_body_get_continuous_collision_detection_mode)>("_body_get_continuous_collision_detection_mode")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, uint32_t)>(&PhysicsServer2DExtension::_body_set_collision_layer)>("_body_set_collision_layer")
			.fun<static_cast<uint32_t (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_body_get_collision_layer)>("_body_get_collision_layer")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, uint32_t)>(&PhysicsServer2DExtension::_body_set_collision_mask)>("_body_set_collision_mask")
			.fun<static_cast<uint32_t (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_body_get_collision_mask)>("_body_get_collision_mask")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, double)>(&PhysicsServer2DExtension::_body_set_collision_priority)>("_body_set_collision_priority")
			.fun<static_cast<double (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_body_get_collision_priority)>("_body_get_collision_priority")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, PhysicsServer2D::BodyParameter, const Variant &)>(&PhysicsServer2DExtension::_body_set_param)>("_body_set_param")
			.fun<static_cast<Variant (PhysicsServer2DExtension::*)(const RID &, PhysicsServer2D::BodyParameter) const>(&PhysicsServer2DExtension::_body_get_param)>("_body_get_param")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &)>(&PhysicsServer2DExtension::_body_reset_mass_properties)>("_body_reset_mass_properties")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, PhysicsServer2D::BodyState, const Variant &)>(&PhysicsServer2DExtension::_body_set_state)>("_body_set_state")
			.fun<static_cast<Variant (PhysicsServer2DExtension::*)(const RID &, PhysicsServer2D::BodyState) const>(&PhysicsServer2DExtension::_body_get_state)>("_body_get_state")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const Vector2 &)>(&PhysicsServer2DExtension::_body_apply_central_impulse)>("_body_apply_central_impulse")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, double)>(&PhysicsServer2DExtension::_body_apply_torque_impulse)>("_body_apply_torque_impulse")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const Vector2 &, const Vector2 &)>(&PhysicsServer2DExtension::_body_apply_impulse)>("_body_apply_impulse")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const Vector2 &)>(&PhysicsServer2DExtension::_body_apply_central_force)>("_body_apply_central_force")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const Vector2 &, const Vector2 &)>(&PhysicsServer2DExtension::_body_apply_force)>("_body_apply_force")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, double)>(&PhysicsServer2DExtension::_body_apply_torque)>("_body_apply_torque")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const Vector2 &)>(&PhysicsServer2DExtension::_body_add_constant_central_force)>("_body_add_constant_central_force")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const Vector2 &, const Vector2 &)>(&PhysicsServer2DExtension::_body_add_constant_force)>("_body_add_constant_force")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, double)>(&PhysicsServer2DExtension::_body_add_constant_torque)>("_body_add_constant_torque")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const Vector2 &)>(&PhysicsServer2DExtension::_body_set_constant_force)>("_body_set_constant_force")
			.fun<static_cast<Vector2 (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_body_get_constant_force)>("_body_get_constant_force")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, double)>(&PhysicsServer2DExtension::_body_set_constant_torque)>("_body_set_constant_torque")
			.fun<static_cast<double (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_body_get_constant_torque)>("_body_get_constant_torque")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const Vector2 &)>(&PhysicsServer2DExtension::_body_set_axis_velocity)>("_body_set_axis_velocity")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const RID &)>(&PhysicsServer2DExtension::_body_add_collision_exception)>("_body_add_collision_exception")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const RID &)>(&PhysicsServer2DExtension::_body_remove_collision_exception)>("_body_remove_collision_exception")
			.fun<static_cast<TypedArray<RID> (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_body_get_collision_exceptions)>("_body_get_collision_exceptions")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, int32_t)>(&PhysicsServer2DExtension::_body_set_max_contacts_reported)>("_body_set_max_contacts_reported")
			.fun<static_cast<int32_t (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_body_get_max_contacts_reported)>("_body_get_max_contacts_reported")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, double)>(&PhysicsServer2DExtension::_body_set_contacts_reported_depth_threshold)>("_body_set_contacts_reported_depth_threshold")
			.fun<static_cast<double (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_body_get_contacts_reported_depth_threshold)>("_body_get_contacts_reported_depth_threshold")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, bool)>(&PhysicsServer2DExtension::_body_set_omit_force_integration)>("_body_set_omit_force_integration")
			.fun<static_cast<bool (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_body_is_omitting_force_integration)>("_body_is_omitting_force_integration")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const Callable &)>(&PhysicsServer2DExtension::_body_set_state_sync_callback)>("_body_set_state_sync_callback")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const Callable &, const Variant &)>(&PhysicsServer2DExtension::_body_set_force_integration_callback)>("_body_set_force_integration_callback")
			.fun<static_cast<bool (PhysicsServer2DExtension::*)(const RID &, int32_t, const RID &, const Transform2D &, const Vector2 &, void *, int32_t, int32_t *)>(&PhysicsServer2DExtension::_body_collide_shape)>("_body_collide_shape")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, bool)>(&PhysicsServer2DExtension::_body_set_pickable)>("_body_set_pickable")
			.fun<static_cast<PhysicsDirectBodyState2D *(PhysicsServer2DExtension::*)(const RID &)>(&PhysicsServer2DExtension::_body_get_direct_state)>("_body_get_direct_state")
			.fun<static_cast<bool (PhysicsServer2DExtension::*)(const RID &, const Transform2D &, const Vector2 &, double, bool, bool, PhysicsServer2DExtensionMotionResult *) const>(&PhysicsServer2DExtension::_body_test_motion)>("_body_test_motion")
			.fun<static_cast<RID (PhysicsServer2DExtension::*)()>(&PhysicsServer2DExtension::_joint_create)>("_joint_create")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &)>(&PhysicsServer2DExtension::_joint_clear)>("_joint_clear")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, PhysicsServer2D::JointParam, double)>(&PhysicsServer2DExtension::_joint_set_param)>("_joint_set_param")
			.fun<static_cast<double (PhysicsServer2DExtension::*)(const RID &, PhysicsServer2D::JointParam) const>(&PhysicsServer2DExtension::_joint_get_param)>("_joint_get_param")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, bool)>(&PhysicsServer2DExtension::_joint_disable_collisions_between_bodies)>("_joint_disable_collisions_between_bodies")
			.fun<static_cast<bool (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_joint_is_disabled_collisions_between_bodies)>("_joint_is_disabled_collisions_between_bodies")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const Vector2 &, const RID &, const RID &)>(&PhysicsServer2DExtension::_joint_make_pin)>("_joint_make_pin")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const Vector2 &, const Vector2 &, const Vector2 &, const RID &, const RID &)>(&PhysicsServer2DExtension::_joint_make_groove)>("_joint_make_groove")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const Vector2 &, const Vector2 &, const RID &, const RID &)>(&PhysicsServer2DExtension::_joint_make_damped_spring)>("_joint_make_damped_spring")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, PhysicsServer2D::PinJointFlag, bool)>(&PhysicsServer2DExtension::_pin_joint_set_flag)>("_pin_joint_set_flag")
			.fun<static_cast<bool (PhysicsServer2DExtension::*)(const RID &, PhysicsServer2D::PinJointFlag) const>(&PhysicsServer2DExtension::_pin_joint_get_flag)>("_pin_joint_get_flag")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, PhysicsServer2D::PinJointParam, double)>(&PhysicsServer2DExtension::_pin_joint_set_param)>("_pin_joint_set_param")
			.fun<static_cast<double (PhysicsServer2DExtension::*)(const RID &, PhysicsServer2D::PinJointParam) const>(&PhysicsServer2DExtension::_pin_joint_get_param)>("_pin_joint_get_param")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, PhysicsServer2D::DampedSpringParam, double)>(&PhysicsServer2DExtension::_damped_spring_joint_set_param)>("_damped_spring_joint_set_param")
			.fun<static_cast<double (PhysicsServer2DExtension::*)(const RID &, PhysicsServer2D::DampedSpringParam) const>(&PhysicsServer2DExtension::_damped_spring_joint_get_param)>("_damped_spring_joint_get_param")
			.fun<static_cast<PhysicsServer2D::JointType (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_joint_get_type)>("_joint_get_type")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &)>(&PhysicsServer2DExtension::_free_rid)>("_free_rid")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(bool)>(&PhysicsServer2DExtension::_set_active)>("_set_active")
			.fun<static_cast<void (PhysicsServer2DExtension::*)()>(&PhysicsServer2DExtension::_init)>("_init")
			.fun<static_cast<void (PhysicsServer2DExtension::*)(double)>(&PhysicsServer2DExtension::_step)>("_step")
			.fun<static_cast<void (PhysicsServer2DExtension::*)()>(&PhysicsServer2DExtension::_sync)>("_sync")
			.fun<static_cast<void (PhysicsServer2DExtension::*)()>(&PhysicsServer2DExtension::_flush_queries)>("_flush_queries")
			.fun<static_cast<void (PhysicsServer2DExtension::*)()>(&PhysicsServer2DExtension::_end_sync)>("_end_sync")
			.fun<static_cast<void (PhysicsServer2DExtension::*)()>(&PhysicsServer2DExtension::_finish)>("_finish")
			.fun<static_cast<bool (PhysicsServer2DExtension::*)() const>(&PhysicsServer2DExtension::_is_flushing_queries)>("_is_flushing_queries")
			.fun<static_cast<int32_t (PhysicsServer2DExtension::*)(PhysicsServer2D::ProcessInfo)>(&PhysicsServer2DExtension::_get_process_info)>("_get_process_info")
			.fun<static_cast<bool (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::body_test_motion_is_excluding_body)>("body_test_motion_is_excluding_body")
			.fun<static_cast<bool (PhysicsServer2DExtension::*)(uint64_t) const>(&PhysicsServer2DExtension::body_test_motion_is_excluding_object)>("body_test_motion_is_excluding_object");
}