
#include <godot_cpp/classes/physics_direct_body_state2d.hpp>
#include <godot_cpp/classes/physics_direct_space_state2d.hpp>
#include <godot_cpp/classes/physics_server2d.hpp>
#include <godot_cpp/classes/physics_server2d_extension.hpp>
#include <godot_cpp/classes/physics_server2d_extension_motion_result.hpp>
#include <godot_cpp/variant/callable.hpp>
#include <godot_cpp/variant/packed_vector2_array.hpp>
#include <godot_cpp/variant/rid.hpp>
#include <godot_cpp/variant/transform2d.hpp>
#include <godot_cpp/variant/typed_array.hpp>
#include <godot_cpp/variant/variant.hpp>
#include <godot_cpp/variant/vector2.hpp>
#include <string>

#include "qjspp.hpp"
#include "register/register_classes.h"

using namespace godot;

void register_classes_PhysicsServer2DExtension() {
	qjs::Context::Module &_module = get_General_module();
	_module.class_<PhysicsServer2DExtension>("PhysicsServer2DExtension")
			.constructor<>()
			.base<PhysicsServer2D>()
			.fun<static_cast<RID (PhysicsServer2DExtension::*)()>(&PhysicsServer2DExtension::_world_boundary_shape_create)>((new std::string("_world_boundary_shape_create"))->c_str())
			.fun<static_cast<RID (PhysicsServer2DExtension::*)()>(&PhysicsServer2DExtension::_separation_ray_shape_create)>((new std::string("_separation_ray_shape_create"))->c_str())
			.fun<static_cast<RID (PhysicsServer2DExtension::*)()>(&PhysicsServer2DExtension::_segment_shape_create)>((new std::string("_segment_shape_create"))->c_str())
			.fun<static_cast<RID (PhysicsServer2DExtension::*)()>(&PhysicsServer2DExtension::_circle_shape_create)>((new std::string("_circle_shape_create"))->c_str())
			.fun<static_cast<RID (PhysicsServer2DExtension::*)()>(&PhysicsServer2DExtension::_rectangle_shape_create)>((new std::string("_rectangle_shape_create"))->c_str())
			.fun<static_cast<RID (PhysicsServer2DExtension::*)()>(&PhysicsServer2DExtension::_capsule_shape_create)>((new std::string("_capsule_shape_create"))->c_str())
			.fun<static_cast<RID (PhysicsServer2DExtension::*)()>(&PhysicsServer2DExtension::_convex_polygon_shape_create)>((new std::string("_convex_polygon_shape_create"))->c_str())
			.fun<static_cast<RID (PhysicsServer2DExtension::*)()>(&PhysicsServer2DExtension::_concave_polygon_shape_create)>((new std::string("_concave_polygon_shape_create"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const Variant &)>(&PhysicsServer2DExtension::_shape_set_data)>((new std::string("_shape_set_data"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, double)>(&PhysicsServer2DExtension::_shape_set_custom_solver_bias)>((new std::string("_shape_set_custom_solver_bias"))->c_str())
			.fun<static_cast<PhysicsServer2D::ShapeType (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_shape_get_type)>((new std::string("_shape_get_type"))->c_str())
			.fun<static_cast<Variant (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_shape_get_data)>((new std::string("_shape_get_data"))->c_str())
			.fun<static_cast<double (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_shape_get_custom_solver_bias)>((new std::string("_shape_get_custom_solver_bias"))->c_str())
			.fun<static_cast<bool (PhysicsServer2DExtension::*)(const RID &, const Transform2D &, const Vector2 &, const RID &, const Transform2D &, const Vector2 &, void *, int32_t, int32_t *)>(&PhysicsServer2DExtension::_shape_collide)>((new std::string("_shape_collide"))->c_str())
			.fun<static_cast<RID (PhysicsServer2DExtension::*)()>(&PhysicsServer2DExtension::_space_create)>((new std::string("_space_create"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, bool)>(&PhysicsServer2DExtension::_space_set_active)>((new std::string("_space_set_active"))->c_str())
			.fun<static_cast<bool (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_space_is_active)>((new std::string("_space_is_active"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, PhysicsServer2D::SpaceParameter, double)>(&PhysicsServer2DExtension::_space_set_param)>((new std::string("_space_set_param"))->c_str())
			.fun<static_cast<double (PhysicsServer2DExtension::*)(const RID &, PhysicsServer2D::SpaceParameter) const>(&PhysicsServer2DExtension::_space_get_param)>((new std::string("_space_get_param"))->c_str())
			.fun<static_cast<PhysicsDirectSpaceState2D *(PhysicsServer2DExtension::*)(const RID &)>(&PhysicsServer2DExtension::_space_get_direct_state)>((new std::string("_space_get_direct_state"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, int32_t)>(&PhysicsServer2DExtension::_space_set_debug_contacts)>((new std::string("_space_set_debug_contacts"))->c_str())
			.fun<static_cast<PackedVector2Array (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_space_get_contacts)>((new std::string("_space_get_contacts"))->c_str())
			.fun<static_cast<int32_t (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_space_get_contact_count)>((new std::string("_space_get_contact_count"))->c_str())
			.fun<static_cast<RID (PhysicsServer2DExtension::*)()>(&PhysicsServer2DExtension::_area_create)>((new std::string("_area_create"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const RID &)>(&PhysicsServer2DExtension::_area_set_space)>((new std::string("_area_set_space"))->c_str())
			.fun<static_cast<RID (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_area_get_space)>((new std::string("_area_get_space"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const RID &, const Transform2D &, bool)>(&PhysicsServer2DExtension::_area_add_shape)>((new std::string("_area_add_shape"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, int32_t, const RID &)>(&PhysicsServer2DExtension::_area_set_shape)>((new std::string("_area_set_shape"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, int32_t, const Transform2D &)>(&PhysicsServer2DExtension::_area_set_shape_transform)>((new std::string("_area_set_shape_transform"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, int32_t, bool)>(&PhysicsServer2DExtension::_area_set_shape_disabled)>((new std::string("_area_set_shape_disabled"))->c_str())
			.fun<static_cast<int32_t (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_area_get_shape_count)>((new std::string("_area_get_shape_count"))->c_str())
			.fun<static_cast<RID (PhysicsServer2DExtension::*)(const RID &, int32_t) const>(&PhysicsServer2DExtension::_area_get_shape)>((new std::string("_area_get_shape"))->c_str())
			.fun<static_cast<Transform2D (PhysicsServer2DExtension::*)(const RID &, int32_t) const>(&PhysicsServer2DExtension::_area_get_shape_transform)>((new std::string("_area_get_shape_transform"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, int32_t)>(&PhysicsServer2DExtension::_area_remove_shape)>((new std::string("_area_remove_shape"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &)>(&PhysicsServer2DExtension::_area_clear_shapes)>((new std::string("_area_clear_shapes"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, uint64_t)>(&PhysicsServer2DExtension::_area_attach_object_instance_id)>((new std::string("_area_attach_object_instance_id"))->c_str())
			.fun<static_cast<uint64_t (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_area_get_object_instance_id)>((new std::string("_area_get_object_instance_id"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, uint64_t)>(&PhysicsServer2DExtension::_area_attach_canvas_instance_id)>((new std::string("_area_attach_canvas_instance_id"))->c_str())
			.fun<static_cast<uint64_t (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_area_get_canvas_instance_id)>((new std::string("_area_get_canvas_instance_id"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, PhysicsServer2D::AreaParameter, const Variant &)>(&PhysicsServer2DExtension::_area_set_param)>((new std::string("_area_set_param"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const Transform2D &)>(&PhysicsServer2DExtension::_area_set_transform)>((new std::string("_area_set_transform"))->c_str())
			.fun<static_cast<Variant (PhysicsServer2DExtension::*)(const RID &, PhysicsServer2D::AreaParameter) const>(&PhysicsServer2DExtension::_area_get_param)>((new std::string("_area_get_param"))->c_str())
			.fun<static_cast<Transform2D (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_area_get_transform)>((new std::string("_area_get_transform"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, uint32_t)>(&PhysicsServer2DExtension::_area_set_collision_layer)>((new std::string("_area_set_collision_layer"))->c_str())
			.fun<static_cast<uint32_t (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_area_get_collision_layer)>((new std::string("_area_get_collision_layer"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, uint32_t)>(&PhysicsServer2DExtension::_area_set_collision_mask)>((new std::string("_area_set_collision_mask"))->c_str())
			.fun<static_cast<uint32_t (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_area_get_collision_mask)>((new std::string("_area_get_collision_mask"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, bool)>(&PhysicsServer2DExtension::_area_set_monitorable)>((new std::string("_area_set_monitorable"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, bool)>(&PhysicsServer2DExtension::_area_set_pickable)>((new std::string("_area_set_pickable"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const Callable &)>(&PhysicsServer2DExtension::_area_set_monitor_callback)>((new std::string("_area_set_monitor_callback"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const Callable &)>(&PhysicsServer2DExtension::_area_set_area_monitor_callback)>((new std::string("_area_set_area_monitor_callback"))->c_str())
			.fun<static_cast<RID (PhysicsServer2DExtension::*)()>(&PhysicsServer2DExtension::_body_create)>((new std::string("_body_create"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const RID &)>(&PhysicsServer2DExtension::_body_set_space)>((new std::string("_body_set_space"))->c_str())
			.fun<static_cast<RID (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_body_get_space)>((new std::string("_body_get_space"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, PhysicsServer2D::BodyMode)>(&PhysicsServer2DExtension::_body_set_mode)>((new std::string("_body_set_mode"))->c_str())
			.fun<static_cast<PhysicsServer2D::BodyMode (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_body_get_mode)>((new std::string("_body_get_mode"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const RID &, const Transform2D &, bool)>(&PhysicsServer2DExtension::_body_add_shape)>((new std::string("_body_add_shape"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, int32_t, const RID &)>(&PhysicsServer2DExtension::_body_set_shape)>((new std::string("_body_set_shape"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, int32_t, const Transform2D &)>(&PhysicsServer2DExtension::_body_set_shape_transform)>((new std::string("_body_set_shape_transform"))->c_str())
			.fun<static_cast<int32_t (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_body_get_shape_count)>((new std::string("_body_get_shape_count"))->c_str())
			.fun<static_cast<RID (PhysicsServer2DExtension::*)(const RID &, int32_t) const>(&PhysicsServer2DExtension::_body_get_shape)>((new std::string("_body_get_shape"))->c_str())
			.fun<static_cast<Transform2D (PhysicsServer2DExtension::*)(const RID &, int32_t) const>(&PhysicsServer2DExtension::_body_get_shape_transform)>((new std::string("_body_get_shape_transform"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, int32_t, bool)>(&PhysicsServer2DExtension::_body_set_shape_disabled)>((new std::string("_body_set_shape_disabled"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, int32_t, bool, double)>(&PhysicsServer2DExtension::_body_set_shape_as_one_way_collision)>((new std::string("_body_set_shape_as_one_way_collision"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, int32_t)>(&PhysicsServer2DExtension::_body_remove_shape)>((new std::string("_body_remove_shape"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &)>(&PhysicsServer2DExtension::_body_clear_shapes)>((new std::string("_body_clear_shapes"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, uint64_t)>(&PhysicsServer2DExtension::_body_attach_object_instance_id)>((new std::string("_body_attach_object_instance_id"))->c_str())
			.fun<static_cast<uint64_t (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_body_get_object_instance_id)>((new std::string("_body_get_object_instance_id"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, uint64_t)>(&PhysicsServer2DExtension::_body_attach_canvas_instance_id)>((new std::string("_body_attach_canvas_instance_id"))->c_str())
			.fun<static_cast<uint64_t (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_body_get_canvas_instance_id)>((new std::string("_body_get_canvas_instance_id"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, PhysicsServer2D::CCDMode)>(&PhysicsServer2DExtension::_body_set_continuous_collision_detection_mode)>((new std::string("_body_set_continuous_collision_detection_mode"))->c_str())
			.fun<static_cast<PhysicsServer2D::CCDMode (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_body_get_continuous_collision_detection_mode)>((new std::string("_body_get_continuous_collision_detection_mode"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, uint32_t)>(&PhysicsServer2DExtension::_body_set_collision_layer)>((new std::string("_body_set_collision_layer"))->c_str())
			.fun<static_cast<uint32_t (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_body_get_collision_layer)>((new std::string("_body_get_collision_layer"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, uint32_t)>(&PhysicsServer2DExtension::_body_set_collision_mask)>((new std::string("_body_set_collision_mask"))->c_str())
			.fun<static_cast<uint32_t (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_body_get_collision_mask)>((new std::string("_body_get_collision_mask"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, double)>(&PhysicsServer2DExtension::_body_set_collision_priority)>((new std::string("_body_set_collision_priority"))->c_str())
			.fun<static_cast<double (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_body_get_collision_priority)>((new std::string("_body_get_collision_priority"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, PhysicsServer2D::BodyParameter, const Variant &)>(&PhysicsServer2DExtension::_body_set_param)>((new std::string("_body_set_param"))->c_str())
			.fun<static_cast<Variant (PhysicsServer2DExtension::*)(const RID &, PhysicsServer2D::BodyParameter) const>(&PhysicsServer2DExtension::_body_get_param)>((new std::string("_body_get_param"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &)>(&PhysicsServer2DExtension::_body_reset_mass_properties)>((new std::string("_body_reset_mass_properties"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, PhysicsServer2D::BodyState, const Variant &)>(&PhysicsServer2DExtension::_body_set_state)>((new std::string("_body_set_state"))->c_str())
			.fun<static_cast<Variant (PhysicsServer2DExtension::*)(const RID &, PhysicsServer2D::BodyState) const>(&PhysicsServer2DExtension::_body_get_state)>((new std::string("_body_get_state"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const Vector2 &)>(&PhysicsServer2DExtension::_body_apply_central_impulse)>((new std::string("_body_apply_central_impulse"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, double)>(&PhysicsServer2DExtension::_body_apply_torque_impulse)>((new std::string("_body_apply_torque_impulse"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const Vector2 &, const Vector2 &)>(&PhysicsServer2DExtension::_body_apply_impulse)>((new std::string("_body_apply_impulse"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const Vector2 &)>(&PhysicsServer2DExtension::_body_apply_central_force)>((new std::string("_body_apply_central_force"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const Vector2 &, const Vector2 &)>(&PhysicsServer2DExtension::_body_apply_force)>((new std::string("_body_apply_force"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, double)>(&PhysicsServer2DExtension::_body_apply_torque)>((new std::string("_body_apply_torque"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const Vector2 &)>(&PhysicsServer2DExtension::_body_add_constant_central_force)>((new std::string("_body_add_constant_central_force"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const Vector2 &, const Vector2 &)>(&PhysicsServer2DExtension::_body_add_constant_force)>((new std::string("_body_add_constant_force"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, double)>(&PhysicsServer2DExtension::_body_add_constant_torque)>((new std::string("_body_add_constant_torque"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const Vector2 &)>(&PhysicsServer2DExtension::_body_set_constant_force)>((new std::string("_body_set_constant_force"))->c_str())
			.fun<static_cast<Vector2 (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_body_get_constant_force)>((new std::string("_body_get_constant_force"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, double)>(&PhysicsServer2DExtension::_body_set_constant_torque)>((new std::string("_body_set_constant_torque"))->c_str())
			.fun<static_cast<double (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_body_get_constant_torque)>((new std::string("_body_get_constant_torque"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const Vector2 &)>(&PhysicsServer2DExtension::_body_set_axis_velocity)>((new std::string("_body_set_axis_velocity"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const RID &)>(&PhysicsServer2DExtension::_body_add_collision_exception)>((new std::string("_body_add_collision_exception"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const RID &)>(&PhysicsServer2DExtension::_body_remove_collision_exception)>((new std::string("_body_remove_collision_exception"))->c_str())
			.fun<static_cast<TypedArray<RID> (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_body_get_collision_exceptions)>((new std::string("_body_get_collision_exceptions"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, int32_t)>(&PhysicsServer2DExtension::_body_set_max_contacts_reported)>((new std::string("_body_set_max_contacts_reported"))->c_str())
			.fun<static_cast<int32_t (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_body_get_max_contacts_reported)>((new std::string("_body_get_max_contacts_reported"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, double)>(&PhysicsServer2DExtension::_body_set_contacts_reported_depth_threshold)>((new std::string("_body_set_contacts_reported_depth_threshold"))->c_str())
			.fun<static_cast<double (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_body_get_contacts_reported_depth_threshold)>((new std::string("_body_get_contacts_reported_depth_threshold"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, bool)>(&PhysicsServer2DExtension::_body_set_omit_force_integration)>((new std::string("_body_set_omit_force_integration"))->c_str())
			.fun<static_cast<bool (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_body_is_omitting_force_integration)>((new std::string("_body_is_omitting_force_integration"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const Callable &)>(&PhysicsServer2DExtension::_body_set_state_sync_callback)>((new std::string("_body_set_state_sync_callback"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const Callable &, const Variant &)>(&PhysicsServer2DExtension::_body_set_force_integration_callback)>((new std::string("_body_set_force_integration_callback"))->c_str())
			.fun<static_cast<bool (PhysicsServer2DExtension::*)(const RID &, int32_t, const RID &, const Transform2D &, const Vector2 &, void *, int32_t, int32_t *)>(&PhysicsServer2DExtension::_body_collide_shape)>((new std::string("_body_collide_shape"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, bool)>(&PhysicsServer2DExtension::_body_set_pickable)>((new std::string("_body_set_pickable"))->c_str())
			.fun<static_cast<PhysicsDirectBodyState2D *(PhysicsServer2DExtension::*)(const RID &)>(&PhysicsServer2DExtension::_body_get_direct_state)>((new std::string("_body_get_direct_state"))->c_str())
			.fun<static_cast<bool (PhysicsServer2DExtension::*)(const RID &, const Transform2D &, const Vector2 &, double, bool, bool, PhysicsServer2DExtensionMotionResult *) const>(&PhysicsServer2DExtension::_body_test_motion)>((new std::string("_body_test_motion"))->c_str())
			.fun<static_cast<RID (PhysicsServer2DExtension::*)()>(&PhysicsServer2DExtension::_joint_create)>((new std::string("_joint_create"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &)>(&PhysicsServer2DExtension::_joint_clear)>((new std::string("_joint_clear"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, PhysicsServer2D::JointParam, double)>(&PhysicsServer2DExtension::_joint_set_param)>((new std::string("_joint_set_param"))->c_str())
			.fun<static_cast<double (PhysicsServer2DExtension::*)(const RID &, PhysicsServer2D::JointParam) const>(&PhysicsServer2DExtension::_joint_get_param)>((new std::string("_joint_get_param"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, bool)>(&PhysicsServer2DExtension::_joint_disable_collisions_between_bodies)>((new std::string("_joint_disable_collisions_between_bodies"))->c_str())
			.fun<static_cast<bool (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_joint_is_disabled_collisions_between_bodies)>((new std::string("_joint_is_disabled_collisions_between_bodies"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const Vector2 &, const RID &, const RID &)>(&PhysicsServer2DExtension::_joint_make_pin)>((new std::string("_joint_make_pin"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const Vector2 &, const Vector2 &, const Vector2 &, const RID &, const RID &)>(&PhysicsServer2DExtension::_joint_make_groove)>((new std::string("_joint_make_groove"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, const Vector2 &, const Vector2 &, const RID &, const RID &)>(&PhysicsServer2DExtension::_joint_make_damped_spring)>((new std::string("_joint_make_damped_spring"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, PhysicsServer2D::PinJointFlag, bool)>(&PhysicsServer2DExtension::_pin_joint_set_flag)>((new std::string("_pin_joint_set_flag"))->c_str())
			.fun<static_cast<bool (PhysicsServer2DExtension::*)(const RID &, PhysicsServer2D::PinJointFlag) const>(&PhysicsServer2DExtension::_pin_joint_get_flag)>((new std::string("_pin_joint_get_flag"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, PhysicsServer2D::PinJointParam, double)>(&PhysicsServer2DExtension::_pin_joint_set_param)>((new std::string("_pin_joint_set_param"))->c_str())
			.fun<static_cast<double (PhysicsServer2DExtension::*)(const RID &, PhysicsServer2D::PinJointParam) const>(&PhysicsServer2DExtension::_pin_joint_get_param)>((new std::string("_pin_joint_get_param"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &, PhysicsServer2D::DampedSpringParam, double)>(&PhysicsServer2DExtension::_damped_spring_joint_set_param)>((new std::string("_damped_spring_joint_set_param"))->c_str())
			.fun<static_cast<double (PhysicsServer2DExtension::*)(const RID &, PhysicsServer2D::DampedSpringParam) const>(&PhysicsServer2DExtension::_damped_spring_joint_get_param)>((new std::string("_damped_spring_joint_get_param"))->c_str())
			.fun<static_cast<PhysicsServer2D::JointType (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::_joint_get_type)>((new std::string("_joint_get_type"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(const RID &)>(&PhysicsServer2DExtension::_free_rid)>((new std::string("_free_rid"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(bool)>(&PhysicsServer2DExtension::_set_active)>((new std::string("_set_active"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)()>(&PhysicsServer2DExtension::_init)>((new std::string("_init"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)(double)>(&PhysicsServer2DExtension::_step)>((new std::string("_step"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)()>(&PhysicsServer2DExtension::_sync)>((new std::string("_sync"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)()>(&PhysicsServer2DExtension::_flush_queries)>((new std::string("_flush_queries"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)()>(&PhysicsServer2DExtension::_end_sync)>((new std::string("_end_sync"))->c_str())
			.fun<static_cast<void (PhysicsServer2DExtension::*)()>(&PhysicsServer2DExtension::_finish)>((new std::string("_finish"))->c_str())
			.fun<static_cast<bool (PhysicsServer2DExtension::*)() const>(&PhysicsServer2DExtension::_is_flushing_queries)>((new std::string("_is_flushing_queries"))->c_str())
			.fun<static_cast<int32_t (PhysicsServer2DExtension::*)(PhysicsServer2D::ProcessInfo)>(&PhysicsServer2DExtension::_get_process_info)>((new std::string("_get_process_info"))->c_str())
			.fun<static_cast<bool (PhysicsServer2DExtension::*)(const RID &) const>(&PhysicsServer2DExtension::body_test_motion_is_excluding_body)>((new std::string("body_test_motion_is_excluding_body"))->c_str())
			.fun<static_cast<bool (PhysicsServer2DExtension::*)(uint64_t) const>(&PhysicsServer2DExtension::body_test_motion_is_excluding_object)>((new std::string("body_test_motion_is_excluding_object"))->c_str());
}