#include <godot_cpp/classes/cpu_particles2d.hpp>
#include <godot_cpp/classes/curve.hpp>
#include <godot_cpp/classes/gradient.hpp>
#include <godot_cpp/classes/node.hpp>

#include "qjspp.hpp"
#include "register/register_classes.h"

using namespace godot;

void register_classes_CPUParticles2D() {
	qjs::Context::Module &_module = get_Node2D_module();
	_module.class_<CPUParticles2D>("CPUParticles2D")
			.constructor<>()
			.property<&CPUParticles2D::is_emitting, &CPUParticles2D::set_emitting>("emitting")
			.property<&CPUParticles2D::get_amount, &CPUParticles2D::set_amount>("amount")
			.property<&CPUParticles2D::get_lifetime, &CPUParticles2D::set_lifetime>("lifetime")
			.property<&CPUParticles2D::get_one_shot, &CPUParticles2D::set_one_shot>("one_shot")
			.property<&CPUParticles2D::get_pre_process_time, &CPUParticles2D::set_pre_process_time>("preprocess")
			.property<&CPUParticles2D::get_speed_scale, &CPUParticles2D::set_speed_scale>("speed_scale")
			.property<&CPUParticles2D::get_explosiveness_ratio, &CPUParticles2D::set_explosiveness_ratio>("explosiveness")
			.property<&CPUParticles2D::get_randomness_ratio, &CPUParticles2D::set_randomness_ratio>("randomness")
			.property<&CPUParticles2D::get_lifetime_randomness, &CPUParticles2D::set_lifetime_randomness>("lifetime_randomness")
			.property<&CPUParticles2D::get_fixed_fps, &CPUParticles2D::set_fixed_fps>("fixed_fps")
			.property<&CPUParticles2D::get_fractional_delta, &CPUParticles2D::set_fractional_delta>("fract_delta")
			.property<&CPUParticles2D::get_use_local_coordinates, &CPUParticles2D::set_use_local_coordinates>("local_coords")
			.property<&CPUParticles2D::get_draw_order, &CPUParticles2D::set_draw_order>("draw_order")
			.property<&CPUParticles2D::get_texture, &CPUParticles2D::set_texture>("texture")
			.property<&CPUParticles2D::get_emission_shape, &CPUParticles2D::set_emission_shape>("emission_shape")
			.property<&CPUParticles2D::get_emission_sphere_radius, &CPUParticles2D::set_emission_sphere_radius>("emission_sphere_radius")
			.property<&CPUParticles2D::get_emission_rect_extents, &CPUParticles2D::set_emission_rect_extents>("emission_rect_extents")
			.property<&CPUParticles2D::get_emission_points, &CPUParticles2D::set_emission_points>("emission_points")
			.property<&CPUParticles2D::get_emission_normals, &CPUParticles2D::set_emission_normals>("emission_normals")
			.property<&CPUParticles2D::get_emission_colors, &CPUParticles2D::set_emission_colors>("emission_colors")
			.property<&CPUParticles2D::get_particle_flag, &CPUParticles2D::set_particle_flag>("particle_flag_align_y")
			.property<&CPUParticles2D::get_direction, &CPUParticles2D::set_direction>("direction")
			.property<&CPUParticles2D::get_spread, &CPUParticles2D::set_spread>("spread")
			.property<&CPUParticles2D::get_gravity, &CPUParticles2D::set_gravity>("gravity")
			.property<&CPUParticles2D::get_param_min, &CPUParticles2D::set_param_min>("initial_velocity_min")
			.property<&CPUParticles2D::get_param_max, &CPUParticles2D::set_param_max>("initial_velocity_max")
			.property<&CPUParticles2D::get_param_min, &CPUParticles2D::set_param_min>("angular_velocity_min")
			.property<&CPUParticles2D::get_param_max, &CPUParticles2D::set_param_max>("angular_velocity_max")
			.property<&CPUParticles2D::get_param_curve, &CPUParticles2D::set_param_curve>("angular_velocity_curve")
			.property<&CPUParticles2D::get_param_min, &CPUParticles2D::set_param_min>("orbit_velocity_min")
			.property<&CPUParticles2D::get_param_max, &CPUParticles2D::set_param_max>("orbit_velocity_max")
			.property<&CPUParticles2D::get_param_curve, &CPUParticles2D::set_param_curve>("orbit_velocity_curve")
			.property<&CPUParticles2D::get_param_min, &CPUParticles2D::set_param_min>("linear_accel_min")
			.property<&CPUParticles2D::get_param_max, &CPUParticles2D::set_param_max>("linear_accel_max")
			.property<&CPUParticles2D::get_param_curve, &CPUParticles2D::set_param_curve>("linear_accel_curve")
			.property<&CPUParticles2D::get_param_min, &CPUParticles2D::set_param_min>("radial_accel_min")
			.property<&CPUParticles2D::get_param_max, &CPUParticles2D::set_param_max>("radial_accel_max")
			.property<&CPUParticles2D::get_param_curve, &CPUParticles2D::set_param_curve>("radial_accel_curve")
			.property<&CPUParticles2D::get_param_min, &CPUParticles2D::set_param_min>("tangential_accel_min")
			.property<&CPUParticles2D::get_param_max, &CPUParticles2D::set_param_max>("tangential_accel_max")
			.property<&CPUParticles2D::get_param_curve, &CPUParticles2D::set_param_curve>("tangential_accel_curve")
			.property<&CPUParticles2D::get_param_min, &CPUParticles2D::set_param_min>("damping_min")
			.property<&CPUParticles2D::get_param_max, &CPUParticles2D::set_param_max>("damping_max")
			.property<&CPUParticles2D::get_param_curve, &CPUParticles2D::set_param_curve>("damping_curve")
			.property<&CPUParticles2D::get_param_min, &CPUParticles2D::set_param_min>("angle_min")
			.property<&CPUParticles2D::get_param_max, &CPUParticles2D::set_param_max>("angle_max")
			.property<&CPUParticles2D::get_param_curve, &CPUParticles2D::set_param_curve>("angle_curve")
			.property<&CPUParticles2D::get_param_min, &CPUParticles2D::set_param_min>("scale_amount_min")
			.property<&CPUParticles2D::get_param_max, &CPUParticles2D::set_param_max>("scale_amount_max")
			.property<&CPUParticles2D::get_param_curve, &CPUParticles2D::set_param_curve>("scale_amount_curve")
			.property<&CPUParticles2D::get_split_scale, &CPUParticles2D::set_split_scale>("split_scale")
			.property<&CPUParticles2D::get_scale_curve_x, &CPUParticles2D::set_scale_curve_x>("scale_curve_x")
			.property<&CPUParticles2D::get_scale_curve_y, &CPUParticles2D::set_scale_curve_y>("scale_curve_y")
			.property<&CPUParticles2D::get_color, &CPUParticles2D::set_color>("color")
			.property<&CPUParticles2D::get_color_ramp, &CPUParticles2D::set_color_ramp>("color_ramp")
			.property<&CPUParticles2D::get_color_initial_ramp, &CPUParticles2D::set_color_initial_ramp>("color_initial_ramp")
			.property<&CPUParticles2D::get_param_min, &CPUParticles2D::set_param_min>("hue_variation_min")
			.property<&CPUParticles2D::get_param_max, &CPUParticles2D::set_param_max>("hue_variation_max")
			.property<&CPUParticles2D::get_param_curve, &CPUParticles2D::set_param_curve>("hue_variation_curve")
			.property<&CPUParticles2D::get_param_min, &CPUParticles2D::set_param_min>("anim_speed_min")
			.property<&CPUParticles2D::get_param_max, &CPUParticles2D::set_param_max>("anim_speed_max")
			.property<&CPUParticles2D::get_param_curve, &CPUParticles2D::set_param_curve>("anim_speed_curve")
			.property<&CPUParticles2D::get_param_min, &CPUParticles2D::set_param_min>("anim_offset_min")
			.property<&CPUParticles2D::get_param_max, &CPUParticles2D::set_param_max>("anim_offset_max")
			.property<&CPUParticles2D::get_param_curve, &CPUParticles2D::set_param_curve>("anim_offset_curve")
			.fun<static_cast<void (CPUParticles2D::*)()>(&CPUParticles2D::restart)>("restart")
			.fun<static_cast<void (CPUParticles2D::*)(Node *)>(&CPUParticles2D::convert_from_particles)>("convert_from_particles");
}