import os

env = Environment(tools=["default"], PLATFORM="")
env.PrependENVPath("PATH", os.getenv("PATH"))

env.Append(CCFLAGS=['-O0', '-Wall', '-Wextra', '-Wno-unused-parameter'])
env.Append(CPPPATH=['./include'])
env.Append(CPPDEFINES=[
    '_GNU_SOURCE',
    'CONFIG_BIGNUM',
    'CONFIG_ALL_UNICODE',
    'CONFIG_VERSION=\\"2024-05-20\\"'
])

sources = Glob('./src/*.c')

quickjs = env.StaticLibrary(target='./bin/quickjs', source=sources)

Export('quickjs')
Return('quickjs')