#include "register/global_enum/register_global_enum.h"
#include "quickjs/env.h"
#include "quickjs/quickjs.h"

void register_global_enum() {
    JSValue global_obj = JS_GetGlobalObject(ctx);
	JSValue Side_obj = JS_NewObject(ctx);
	JS_SetPropertyStr(ctx, Side_obj, "SIDE_LEFT", JS_NewInt64(ctx, 0));
	JS_SetPropertyStr(ctx, Side_obj, "SIDE_TOP", JS_NewInt64(ctx, 1));
	JS_SetPropertyStr(ctx, Side_obj, "SIDE_RIGHT", JS_NewInt64(ctx, 2));
	JS_SetPropertyStr(ctx, Side_obj, "SIDE_BOTTOM", JS_NewInt64(ctx, 3));
	JS_SetPropertyStr(ctx, global_obj, "Side", Side_obj);
    
	JSValue Corner_obj = JS_NewObject(ctx);
	JS_SetPropertyStr(ctx, Corner_obj, "CORNER_TOP_LEFT", JS_NewInt64(ctx, 0));
	JS_SetPropertyStr(ctx, Corner_obj, "CORNER_TOP_RIGHT", JS_NewInt64(ctx, 1));
	JS_SetPropertyStr(ctx, Corner_obj, "CORNER_BOTTOM_RIGHT", JS_NewInt64(ctx, 2));
	JS_SetPropertyStr(ctx, Corner_obj, "CORNER_BOTTOM_LEFT", JS_NewInt64(ctx, 3));
	JS_SetPropertyStr(ctx, global_obj, "Corner", Corner_obj);
    
	JSValue Orientation_obj = JS_NewObject(ctx);
	JS_SetPropertyStr(ctx, Orientation_obj, "VERTICAL", JS_NewInt64(ctx, 1));
	JS_SetPropertyStr(ctx, Orientation_obj, "HORIZONTAL", JS_NewInt64(ctx, 0));
	JS_SetPropertyStr(ctx, global_obj, "Orientation", Orientation_obj);
    
	JSValue ClockDirection_obj = JS_NewObject(ctx);
	JS_SetPropertyStr(ctx, ClockDirection_obj, "CLOCKWISE", JS_NewInt64(ctx, 0));
	JS_SetPropertyStr(ctx, ClockDirection_obj, "COUNTERCLOCKWISE", JS_NewInt64(ctx, 1));
	JS_SetPropertyStr(ctx, global_obj, "ClockDirection", ClockDirection_obj);
    
	JSValue HorizontalAlignment_obj = JS_NewObject(ctx);
	JS_SetPropertyStr(ctx, HorizontalAlignment_obj, "HORIZONTAL_ALIGNMENT_LEFT", JS_NewInt64(ctx, 0));
	JS_SetPropertyStr(ctx, HorizontalAlignment_obj, "HORIZONTAL_ALIGNMENT_CENTER", JS_NewInt64(ctx, 1));
	JS_SetPropertyStr(ctx, HorizontalAlignment_obj, "HORIZONTAL_ALIGNMENT_RIGHT", JS_NewInt64(ctx, 2));
	JS_SetPropertyStr(ctx, HorizontalAlignment_obj, "HORIZONTAL_ALIGNMENT_FILL", JS_NewInt64(ctx, 3));
	JS_SetPropertyStr(ctx, global_obj, "HorizontalAlignment", HorizontalAlignment_obj);
    
	JSValue VerticalAlignment_obj = JS_NewObject(ctx);
	JS_SetPropertyStr(ctx, VerticalAlignment_obj, "VERTICAL_ALIGNMENT_TOP", JS_NewInt64(ctx, 0));
	JS_SetPropertyStr(ctx, VerticalAlignment_obj, "VERTICAL_ALIGNMENT_CENTER", JS_NewInt64(ctx, 1));
	JS_SetPropertyStr(ctx, VerticalAlignment_obj, "VERTICAL_ALIGNMENT_BOTTOM", JS_NewInt64(ctx, 2));
	JS_SetPropertyStr(ctx, VerticalAlignment_obj, "VERTICAL_ALIGNMENT_FILL", JS_NewInt64(ctx, 3));
	JS_SetPropertyStr(ctx, global_obj, "VerticalAlignment", VerticalAlignment_obj);
    
	JSValue InlineAlignment_obj = JS_NewObject(ctx);
	JS_SetPropertyStr(ctx, InlineAlignment_obj, "INLINE_ALIGNMENT_TOP_TO", JS_NewInt64(ctx, 0));
	JS_SetPropertyStr(ctx, InlineAlignment_obj, "INLINE_ALIGNMENT_CENTER_TO", JS_NewInt64(ctx, 1));
	JS_SetPropertyStr(ctx, InlineAlignment_obj, "INLINE_ALIGNMENT_BASELINE_TO", JS_NewInt64(ctx, 3));
	JS_SetPropertyStr(ctx, InlineAlignment_obj, "INLINE_ALIGNMENT_BOTTOM_TO", JS_NewInt64(ctx, 2));
	JS_SetPropertyStr(ctx, InlineAlignment_obj, "INLINE_ALIGNMENT_TO_TOP", JS_NewInt64(ctx, 0));
	JS_SetPropertyStr(ctx, InlineAlignment_obj, "INLINE_ALIGNMENT_TO_CENTER", JS_NewInt64(ctx, 4));
	JS_SetPropertyStr(ctx, InlineAlignment_obj, "INLINE_ALIGNMENT_TO_BASELINE", JS_NewInt64(ctx, 8));
	JS_SetPropertyStr(ctx, InlineAlignment_obj, "INLINE_ALIGNMENT_TO_BOTTOM", JS_NewInt64(ctx, 12));
	JS_SetPropertyStr(ctx, InlineAlignment_obj, "INLINE_ALIGNMENT_TOP", JS_NewInt64(ctx, 0));
	JS_SetPropertyStr(ctx, InlineAlignment_obj, "INLINE_ALIGNMENT_CENTER", JS_NewInt64(ctx, 5));
	JS_SetPropertyStr(ctx, InlineAlignment_obj, "INLINE_ALIGNMENT_BOTTOM", JS_NewInt64(ctx, 14));
	JS_SetPropertyStr(ctx, InlineAlignment_obj, "INLINE_ALIGNMENT_IMAGE_MASK", JS_NewInt64(ctx, 3));
	JS_SetPropertyStr(ctx, InlineAlignment_obj, "INLINE_ALIGNMENT_TEXT_MASK", JS_NewInt64(ctx, 12));
	JS_SetPropertyStr(ctx, global_obj, "InlineAlignment", InlineAlignment_obj);
    
	JSValue EulerOrder_obj = JS_NewObject(ctx);
	JS_SetPropertyStr(ctx, EulerOrder_obj, "EULER_ORDER_XYZ", JS_NewInt64(ctx, 0));
	JS_SetPropertyStr(ctx, EulerOrder_obj, "EULER_ORDER_XZY", JS_NewInt64(ctx, 1));
	JS_SetPropertyStr(ctx, EulerOrder_obj, "EULER_ORDER_YXZ", JS_NewInt64(ctx, 2));
	JS_SetPropertyStr(ctx, EulerOrder_obj, "EULER_ORDER_YZX", JS_NewInt64(ctx, 3));
	JS_SetPropertyStr(ctx, EulerOrder_obj, "EULER_ORDER_ZXY", JS_NewInt64(ctx, 4));
	JS_SetPropertyStr(ctx, EulerOrder_obj, "EULER_ORDER_ZYX", JS_NewInt64(ctx, 5));
	JS_SetPropertyStr(ctx, global_obj, "EulerOrder", EulerOrder_obj);
    
	JSValue Key_obj = JS_NewObject(ctx);
	JS_SetPropertyStr(ctx, Key_obj, "KEY_NONE", JS_NewInt64(ctx, 0));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_SPECIAL", JS_NewInt64(ctx, 4194304));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_ESCAPE", JS_NewInt64(ctx, 4194305));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_TAB", JS_NewInt64(ctx, 4194306));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_BACKTAB", JS_NewInt64(ctx, 4194307));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_BACKSPACE", JS_NewInt64(ctx, 4194308));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_ENTER", JS_NewInt64(ctx, 4194309));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_KP_ENTER", JS_NewInt64(ctx, 4194310));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_INSERT", JS_NewInt64(ctx, 4194311));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_DELETE", JS_NewInt64(ctx, 4194312));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_PAUSE", JS_NewInt64(ctx, 4194313));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_PRINT", JS_NewInt64(ctx, 4194314));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_SYSREQ", JS_NewInt64(ctx, 4194315));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_CLEAR", JS_NewInt64(ctx, 4194316));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_HOME", JS_NewInt64(ctx, 4194317));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_END", JS_NewInt64(ctx, 4194318));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_LEFT", JS_NewInt64(ctx, 4194319));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_UP", JS_NewInt64(ctx, 4194320));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_RIGHT", JS_NewInt64(ctx, 4194321));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_DOWN", JS_NewInt64(ctx, 4194322));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_PAGEUP", JS_NewInt64(ctx, 4194323));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_PAGEDOWN", JS_NewInt64(ctx, 4194324));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_SHIFT", JS_NewInt64(ctx, 4194325));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_CTRL", JS_NewInt64(ctx, 4194326));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_META", JS_NewInt64(ctx, 4194327));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_ALT", JS_NewInt64(ctx, 4194328));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_CAPSLOCK", JS_NewInt64(ctx, 4194329));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_NUMLOCK", JS_NewInt64(ctx, 4194330));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_SCROLLLOCK", JS_NewInt64(ctx, 4194331));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_F1", JS_NewInt64(ctx, 4194332));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_F2", JS_NewInt64(ctx, 4194333));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_F3", JS_NewInt64(ctx, 4194334));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_F4", JS_NewInt64(ctx, 4194335));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_F5", JS_NewInt64(ctx, 4194336));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_F6", JS_NewInt64(ctx, 4194337));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_F7", JS_NewInt64(ctx, 4194338));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_F8", JS_NewInt64(ctx, 4194339));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_F9", JS_NewInt64(ctx, 4194340));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_F10", JS_NewInt64(ctx, 4194341));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_F11", JS_NewInt64(ctx, 4194342));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_F12", JS_NewInt64(ctx, 4194343));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_F13", JS_NewInt64(ctx, 4194344));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_F14", JS_NewInt64(ctx, 4194345));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_F15", JS_NewInt64(ctx, 4194346));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_F16", JS_NewInt64(ctx, 4194347));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_F17", JS_NewInt64(ctx, 4194348));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_F18", JS_NewInt64(ctx, 4194349));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_F19", JS_NewInt64(ctx, 4194350));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_F20", JS_NewInt64(ctx, 4194351));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_F21", JS_NewInt64(ctx, 4194352));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_F22", JS_NewInt64(ctx, 4194353));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_F23", JS_NewInt64(ctx, 4194354));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_F24", JS_NewInt64(ctx, 4194355));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_F25", JS_NewInt64(ctx, 4194356));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_F26", JS_NewInt64(ctx, 4194357));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_F27", JS_NewInt64(ctx, 4194358));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_F28", JS_NewInt64(ctx, 4194359));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_F29", JS_NewInt64(ctx, 4194360));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_F30", JS_NewInt64(ctx, 4194361));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_F31", JS_NewInt64(ctx, 4194362));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_F32", JS_NewInt64(ctx, 4194363));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_F33", JS_NewInt64(ctx, 4194364));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_F34", JS_NewInt64(ctx, 4194365));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_F35", JS_NewInt64(ctx, 4194366));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_KP_MULTIPLY", JS_NewInt64(ctx, 4194433));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_KP_DIVIDE", JS_NewInt64(ctx, 4194434));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_KP_SUBTRACT", JS_NewInt64(ctx, 4194435));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_KP_PERIOD", JS_NewInt64(ctx, 4194436));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_KP_ADD", JS_NewInt64(ctx, 4194437));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_KP_0", JS_NewInt64(ctx, 4194438));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_KP_1", JS_NewInt64(ctx, 4194439));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_KP_2", JS_NewInt64(ctx, 4194440));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_KP_3", JS_NewInt64(ctx, 4194441));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_KP_4", JS_NewInt64(ctx, 4194442));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_KP_5", JS_NewInt64(ctx, 4194443));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_KP_6", JS_NewInt64(ctx, 4194444));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_KP_7", JS_NewInt64(ctx, 4194445));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_KP_8", JS_NewInt64(ctx, 4194446));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_KP_9", JS_NewInt64(ctx, 4194447));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_MENU", JS_NewInt64(ctx, 4194370));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_HYPER", JS_NewInt64(ctx, 4194371));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_HELP", JS_NewInt64(ctx, 4194373));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_BACK", JS_NewInt64(ctx, 4194376));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_FORWARD", JS_NewInt64(ctx, 4194377));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_STOP", JS_NewInt64(ctx, 4194378));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_REFRESH", JS_NewInt64(ctx, 4194379));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_VOLUMEDOWN", JS_NewInt64(ctx, 4194380));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_VOLUMEMUTE", JS_NewInt64(ctx, 4194381));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_VOLUMEUP", JS_NewInt64(ctx, 4194382));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_MEDIAPLAY", JS_NewInt64(ctx, 4194388));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_MEDIASTOP", JS_NewInt64(ctx, 4194389));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_MEDIAPREVIOUS", JS_NewInt64(ctx, 4194390));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_MEDIANEXT", JS_NewInt64(ctx, 4194391));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_MEDIARECORD", JS_NewInt64(ctx, 4194392));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_HOMEPAGE", JS_NewInt64(ctx, 4194393));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_FAVORITES", JS_NewInt64(ctx, 4194394));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_SEARCH", JS_NewInt64(ctx, 4194395));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_STANDBY", JS_NewInt64(ctx, 4194396));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_OPENURL", JS_NewInt64(ctx, 4194397));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_LAUNCHMAIL", JS_NewInt64(ctx, 4194398));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_LAUNCHMEDIA", JS_NewInt64(ctx, 4194399));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_LAUNCH0", JS_NewInt64(ctx, 4194400));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_LAUNCH1", JS_NewInt64(ctx, 4194401));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_LAUNCH2", JS_NewInt64(ctx, 4194402));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_LAUNCH3", JS_NewInt64(ctx, 4194403));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_LAUNCH4", JS_NewInt64(ctx, 4194404));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_LAUNCH5", JS_NewInt64(ctx, 4194405));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_LAUNCH6", JS_NewInt64(ctx, 4194406));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_LAUNCH7", JS_NewInt64(ctx, 4194407));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_LAUNCH8", JS_NewInt64(ctx, 4194408));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_LAUNCH9", JS_NewInt64(ctx, 4194409));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_LAUNCHA", JS_NewInt64(ctx, 4194410));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_LAUNCHB", JS_NewInt64(ctx, 4194411));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_LAUNCHC", JS_NewInt64(ctx, 4194412));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_LAUNCHD", JS_NewInt64(ctx, 4194413));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_LAUNCHE", JS_NewInt64(ctx, 4194414));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_LAUNCHF", JS_NewInt64(ctx, 4194415));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_GLOBE", JS_NewInt64(ctx, 4194416));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_KEYBOARD", JS_NewInt64(ctx, 4194417));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_JIS_EISU", JS_NewInt64(ctx, 4194418));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_JIS_KANA", JS_NewInt64(ctx, 4194419));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_UNKNOWN", JS_NewInt64(ctx, 8388607));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_SPACE", JS_NewInt64(ctx, 32));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_EXCLAM", JS_NewInt64(ctx, 33));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_QUOTEDBL", JS_NewInt64(ctx, 34));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_NUMBERSIGN", JS_NewInt64(ctx, 35));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_DOLLAR", JS_NewInt64(ctx, 36));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_PERCENT", JS_NewInt64(ctx, 37));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_AMPERSAND", JS_NewInt64(ctx, 38));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_APOSTROPHE", JS_NewInt64(ctx, 39));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_PARENLEFT", JS_NewInt64(ctx, 40));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_PARENRIGHT", JS_NewInt64(ctx, 41));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_ASTERISK", JS_NewInt64(ctx, 42));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_PLUS", JS_NewInt64(ctx, 43));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_COMMA", JS_NewInt64(ctx, 44));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_MINUS", JS_NewInt64(ctx, 45));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_PERIOD", JS_NewInt64(ctx, 46));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_SLASH", JS_NewInt64(ctx, 47));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_0", JS_NewInt64(ctx, 48));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_1", JS_NewInt64(ctx, 49));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_2", JS_NewInt64(ctx, 50));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_3", JS_NewInt64(ctx, 51));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_4", JS_NewInt64(ctx, 52));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_5", JS_NewInt64(ctx, 53));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_6", JS_NewInt64(ctx, 54));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_7", JS_NewInt64(ctx, 55));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_8", JS_NewInt64(ctx, 56));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_9", JS_NewInt64(ctx, 57));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_COLON", JS_NewInt64(ctx, 58));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_SEMICOLON", JS_NewInt64(ctx, 59));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_LESS", JS_NewInt64(ctx, 60));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_EQUAL", JS_NewInt64(ctx, 61));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_GREATER", JS_NewInt64(ctx, 62));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_QUESTION", JS_NewInt64(ctx, 63));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_AT", JS_NewInt64(ctx, 64));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_A", JS_NewInt64(ctx, 65));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_B", JS_NewInt64(ctx, 66));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_C", JS_NewInt64(ctx, 67));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_D", JS_NewInt64(ctx, 68));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_E", JS_NewInt64(ctx, 69));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_F", JS_NewInt64(ctx, 70));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_G", JS_NewInt64(ctx, 71));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_H", JS_NewInt64(ctx, 72));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_I", JS_NewInt64(ctx, 73));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_J", JS_NewInt64(ctx, 74));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_K", JS_NewInt64(ctx, 75));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_L", JS_NewInt64(ctx, 76));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_M", JS_NewInt64(ctx, 77));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_N", JS_NewInt64(ctx, 78));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_O", JS_NewInt64(ctx, 79));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_P", JS_NewInt64(ctx, 80));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_Q", JS_NewInt64(ctx, 81));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_R", JS_NewInt64(ctx, 82));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_S", JS_NewInt64(ctx, 83));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_T", JS_NewInt64(ctx, 84));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_U", JS_NewInt64(ctx, 85));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_V", JS_NewInt64(ctx, 86));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_W", JS_NewInt64(ctx, 87));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_X", JS_NewInt64(ctx, 88));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_Y", JS_NewInt64(ctx, 89));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_Z", JS_NewInt64(ctx, 90));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_BRACKETLEFT", JS_NewInt64(ctx, 91));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_BACKSLASH", JS_NewInt64(ctx, 92));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_BRACKETRIGHT", JS_NewInt64(ctx, 93));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_ASCIICIRCUM", JS_NewInt64(ctx, 94));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_UNDERSCORE", JS_NewInt64(ctx, 95));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_QUOTELEFT", JS_NewInt64(ctx, 96));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_BRACELEFT", JS_NewInt64(ctx, 123));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_BAR", JS_NewInt64(ctx, 124));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_BRACERIGHT", JS_NewInt64(ctx, 125));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_ASCIITILDE", JS_NewInt64(ctx, 126));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_YEN", JS_NewInt64(ctx, 165));
	JS_SetPropertyStr(ctx, Key_obj, "KEY_SECTION", JS_NewInt64(ctx, 167));
	JS_SetPropertyStr(ctx, global_obj, "Key", Key_obj);
    
	JSValue KeyModifierMask_obj = JS_NewObject(ctx);
	JS_SetPropertyStr(ctx, KeyModifierMask_obj, "KEY_CODE_MASK", JS_NewInt64(ctx, 8388607));
	JS_SetPropertyStr(ctx, KeyModifierMask_obj, "KEY_MODIFIER_MASK", JS_NewInt64(ctx, 532676608));
	JS_SetPropertyStr(ctx, KeyModifierMask_obj, "KEY_MASK_CMD_OR_CTRL", JS_NewInt64(ctx, 16777216));
	JS_SetPropertyStr(ctx, KeyModifierMask_obj, "KEY_MASK_SHIFT", JS_NewInt64(ctx, 33554432));
	JS_SetPropertyStr(ctx, KeyModifierMask_obj, "KEY_MASK_ALT", JS_NewInt64(ctx, 67108864));
	JS_SetPropertyStr(ctx, KeyModifierMask_obj, "KEY_MASK_META", JS_NewInt64(ctx, 134217728));
	JS_SetPropertyStr(ctx, KeyModifierMask_obj, "KEY_MASK_CTRL", JS_NewInt64(ctx, 268435456));
	JS_SetPropertyStr(ctx, KeyModifierMask_obj, "KEY_MASK_KPAD", JS_NewInt64(ctx, 536870912));
	JS_SetPropertyStr(ctx, KeyModifierMask_obj, "KEY_MASK_GROUP_SWITCH", JS_NewInt64(ctx, 1073741824));
	JS_SetPropertyStr(ctx, global_obj, "KeyModifierMask", KeyModifierMask_obj);
    
	JSValue KeyLocation_obj = JS_NewObject(ctx);
	JS_SetPropertyStr(ctx, KeyLocation_obj, "KEY_LOCATION_UNSPECIFIED", JS_NewInt64(ctx, 0));
	JS_SetPropertyStr(ctx, KeyLocation_obj, "KEY_LOCATION_LEFT", JS_NewInt64(ctx, 1));
	JS_SetPropertyStr(ctx, KeyLocation_obj, "KEY_LOCATION_RIGHT", JS_NewInt64(ctx, 2));
	JS_SetPropertyStr(ctx, global_obj, "KeyLocation", KeyLocation_obj);
    
	JSValue MouseButton_obj = JS_NewObject(ctx);
	JS_SetPropertyStr(ctx, MouseButton_obj, "MOUSE_BUTTON_NONE", JS_NewInt64(ctx, 0));
	JS_SetPropertyStr(ctx, MouseButton_obj, "MOUSE_BUTTON_LEFT", JS_NewInt64(ctx, 1));
	JS_SetPropertyStr(ctx, MouseButton_obj, "MOUSE_BUTTON_RIGHT", JS_NewInt64(ctx, 2));
	JS_SetPropertyStr(ctx, MouseButton_obj, "MOUSE_BUTTON_MIDDLE", JS_NewInt64(ctx, 3));
	JS_SetPropertyStr(ctx, MouseButton_obj, "MOUSE_BUTTON_WHEEL_UP", JS_NewInt64(ctx, 4));
	JS_SetPropertyStr(ctx, MouseButton_obj, "MOUSE_BUTTON_WHEEL_DOWN", JS_NewInt64(ctx, 5));
	JS_SetPropertyStr(ctx, MouseButton_obj, "MOUSE_BUTTON_WHEEL_LEFT", JS_NewInt64(ctx, 6));
	JS_SetPropertyStr(ctx, MouseButton_obj, "MOUSE_BUTTON_WHEEL_RIGHT", JS_NewInt64(ctx, 7));
	JS_SetPropertyStr(ctx, MouseButton_obj, "MOUSE_BUTTON_XBUTTON1", JS_NewInt64(ctx, 8));
	JS_SetPropertyStr(ctx, MouseButton_obj, "MOUSE_BUTTON_XBUTTON2", JS_NewInt64(ctx, 9));
	JS_SetPropertyStr(ctx, global_obj, "MouseButton", MouseButton_obj);
    
	JSValue MouseButtonMask_obj = JS_NewObject(ctx);
	JS_SetPropertyStr(ctx, MouseButtonMask_obj, "MOUSE_BUTTON_MASK_LEFT", JS_NewInt64(ctx, 1));
	JS_SetPropertyStr(ctx, MouseButtonMask_obj, "MOUSE_BUTTON_MASK_RIGHT", JS_NewInt64(ctx, 2));
	JS_SetPropertyStr(ctx, MouseButtonMask_obj, "MOUSE_BUTTON_MASK_MIDDLE", JS_NewInt64(ctx, 4));
	JS_SetPropertyStr(ctx, MouseButtonMask_obj, "MOUSE_BUTTON_MASK_MB_XBUTTON1", JS_NewInt64(ctx, 128));
	JS_SetPropertyStr(ctx, MouseButtonMask_obj, "MOUSE_BUTTON_MASK_MB_XBUTTON2", JS_NewInt64(ctx, 256));
	JS_SetPropertyStr(ctx, global_obj, "MouseButtonMask", MouseButtonMask_obj);
    
	JSValue JoyButton_obj = JS_NewObject(ctx);
	JS_SetPropertyStr(ctx, JoyButton_obj, "JOY_BUTTON_INVALID", JS_NewInt64(ctx, -1));
	JS_SetPropertyStr(ctx, JoyButton_obj, "JOY_BUTTON_A", JS_NewInt64(ctx, 0));
	JS_SetPropertyStr(ctx, JoyButton_obj, "JOY_BUTTON_B", JS_NewInt64(ctx, 1));
	JS_SetPropertyStr(ctx, JoyButton_obj, "JOY_BUTTON_X", JS_NewInt64(ctx, 2));
	JS_SetPropertyStr(ctx, JoyButton_obj, "JOY_BUTTON_Y", JS_NewInt64(ctx, 3));
	JS_SetPropertyStr(ctx, JoyButton_obj, "JOY_BUTTON_BACK", JS_NewInt64(ctx, 4));
	JS_SetPropertyStr(ctx, JoyButton_obj, "JOY_BUTTON_GUIDE", JS_NewInt64(ctx, 5));
	JS_SetPropertyStr(ctx, JoyButton_obj, "JOY_BUTTON_START", JS_NewInt64(ctx, 6));
	JS_SetPropertyStr(ctx, JoyButton_obj, "JOY_BUTTON_LEFT_STICK", JS_NewInt64(ctx, 7));
	JS_SetPropertyStr(ctx, JoyButton_obj, "JOY_BUTTON_RIGHT_STICK", JS_NewInt64(ctx, 8));
	JS_SetPropertyStr(ctx, JoyButton_obj, "JOY_BUTTON_LEFT_SHOULDER", JS_NewInt64(ctx, 9));
	JS_SetPropertyStr(ctx, JoyButton_obj, "JOY_BUTTON_RIGHT_SHOULDER", JS_NewInt64(ctx, 10));
	JS_SetPropertyStr(ctx, JoyButton_obj, "JOY_BUTTON_DPAD_UP", JS_NewInt64(ctx, 11));
	JS_SetPropertyStr(ctx, JoyButton_obj, "JOY_BUTTON_DPAD_DOWN", JS_NewInt64(ctx, 12));
	JS_SetPropertyStr(ctx, JoyButton_obj, "JOY_BUTTON_DPAD_LEFT", JS_NewInt64(ctx, 13));
	JS_SetPropertyStr(ctx, JoyButton_obj, "JOY_BUTTON_DPAD_RIGHT", JS_NewInt64(ctx, 14));
	JS_SetPropertyStr(ctx, JoyButton_obj, "JOY_BUTTON_MISC1", JS_NewInt64(ctx, 15));
	JS_SetPropertyStr(ctx, JoyButton_obj, "JOY_BUTTON_PADDLE1", JS_NewInt64(ctx, 16));
	JS_SetPropertyStr(ctx, JoyButton_obj, "JOY_BUTTON_PADDLE2", JS_NewInt64(ctx, 17));
	JS_SetPropertyStr(ctx, JoyButton_obj, "JOY_BUTTON_PADDLE3", JS_NewInt64(ctx, 18));
	JS_SetPropertyStr(ctx, JoyButton_obj, "JOY_BUTTON_PADDLE4", JS_NewInt64(ctx, 19));
	JS_SetPropertyStr(ctx, JoyButton_obj, "JOY_BUTTON_TOUCHPAD", JS_NewInt64(ctx, 20));
	JS_SetPropertyStr(ctx, JoyButton_obj, "JOY_BUTTON_SDL_MAX", JS_NewInt64(ctx, 21));
	JS_SetPropertyStr(ctx, JoyButton_obj, "JOY_BUTTON_MAX", JS_NewInt64(ctx, 128));
	JS_SetPropertyStr(ctx, global_obj, "JoyButton", JoyButton_obj);
    
	JSValue JoyAxis_obj = JS_NewObject(ctx);
	JS_SetPropertyStr(ctx, JoyAxis_obj, "JOY_AXIS_INVALID", JS_NewInt64(ctx, -1));
	JS_SetPropertyStr(ctx, JoyAxis_obj, "JOY_AXIS_LEFT_X", JS_NewInt64(ctx, 0));
	JS_SetPropertyStr(ctx, JoyAxis_obj, "JOY_AXIS_LEFT_Y", JS_NewInt64(ctx, 1));
	JS_SetPropertyStr(ctx, JoyAxis_obj, "JOY_AXIS_RIGHT_X", JS_NewInt64(ctx, 2));
	JS_SetPropertyStr(ctx, JoyAxis_obj, "JOY_AXIS_RIGHT_Y", JS_NewInt64(ctx, 3));
	JS_SetPropertyStr(ctx, JoyAxis_obj, "JOY_AXIS_TRIGGER_LEFT", JS_NewInt64(ctx, 4));
	JS_SetPropertyStr(ctx, JoyAxis_obj, "JOY_AXIS_TRIGGER_RIGHT", JS_NewInt64(ctx, 5));
	JS_SetPropertyStr(ctx, JoyAxis_obj, "JOY_AXIS_SDL_MAX", JS_NewInt64(ctx, 6));
	JS_SetPropertyStr(ctx, JoyAxis_obj, "JOY_AXIS_MAX", JS_NewInt64(ctx, 10));
	JS_SetPropertyStr(ctx, global_obj, "JoyAxis", JoyAxis_obj);
    
	JSValue MIDIMessage_obj = JS_NewObject(ctx);
	JS_SetPropertyStr(ctx, MIDIMessage_obj, "MIDI_MESSAGE_NONE", JS_NewInt64(ctx, 0));
	JS_SetPropertyStr(ctx, MIDIMessage_obj, "MIDI_MESSAGE_NOTE_OFF", JS_NewInt64(ctx, 8));
	JS_SetPropertyStr(ctx, MIDIMessage_obj, "MIDI_MESSAGE_NOTE_ON", JS_NewInt64(ctx, 9));
	JS_SetPropertyStr(ctx, MIDIMessage_obj, "MIDI_MESSAGE_AFTERTOUCH", JS_NewInt64(ctx, 10));
	JS_SetPropertyStr(ctx, MIDIMessage_obj, "MIDI_MESSAGE_CONTROL_CHANGE", JS_NewInt64(ctx, 11));
	JS_SetPropertyStr(ctx, MIDIMessage_obj, "MIDI_MESSAGE_PROGRAM_CHANGE", JS_NewInt64(ctx, 12));
	JS_SetPropertyStr(ctx, MIDIMessage_obj, "MIDI_MESSAGE_CHANNEL_PRESSURE", JS_NewInt64(ctx, 13));
	JS_SetPropertyStr(ctx, MIDIMessage_obj, "MIDI_MESSAGE_PITCH_BEND", JS_NewInt64(ctx, 14));
	JS_SetPropertyStr(ctx, MIDIMessage_obj, "MIDI_MESSAGE_SYSTEM_EXCLUSIVE", JS_NewInt64(ctx, 240));
	JS_SetPropertyStr(ctx, MIDIMessage_obj, "MIDI_MESSAGE_QUARTER_FRAME", JS_NewInt64(ctx, 241));
	JS_SetPropertyStr(ctx, MIDIMessage_obj, "MIDI_MESSAGE_SONG_POSITION_POINTER", JS_NewInt64(ctx, 242));
	JS_SetPropertyStr(ctx, MIDIMessage_obj, "MIDI_MESSAGE_SONG_SELECT", JS_NewInt64(ctx, 243));
	JS_SetPropertyStr(ctx, MIDIMessage_obj, "MIDI_MESSAGE_TUNE_REQUEST", JS_NewInt64(ctx, 246));
	JS_SetPropertyStr(ctx, MIDIMessage_obj, "MIDI_MESSAGE_TIMING_CLOCK", JS_NewInt64(ctx, 248));
	JS_SetPropertyStr(ctx, MIDIMessage_obj, "MIDI_MESSAGE_START", JS_NewInt64(ctx, 250));
	JS_SetPropertyStr(ctx, MIDIMessage_obj, "MIDI_MESSAGE_CONTINUE", JS_NewInt64(ctx, 251));
	JS_SetPropertyStr(ctx, MIDIMessage_obj, "MIDI_MESSAGE_STOP", JS_NewInt64(ctx, 252));
	JS_SetPropertyStr(ctx, MIDIMessage_obj, "MIDI_MESSAGE_ACTIVE_SENSING", JS_NewInt64(ctx, 254));
	JS_SetPropertyStr(ctx, MIDIMessage_obj, "MIDI_MESSAGE_SYSTEM_RESET", JS_NewInt64(ctx, 255));
	JS_SetPropertyStr(ctx, global_obj, "MIDIMessage", MIDIMessage_obj);
    
	JSValue Error_obj = JS_NewObject(ctx);
	JS_SetPropertyStr(ctx, Error_obj, "OK", JS_NewInt64(ctx, 0));
	JS_SetPropertyStr(ctx, Error_obj, "FAILED", JS_NewInt64(ctx, 1));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_UNAVAILABLE", JS_NewInt64(ctx, 2));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_UNCONFIGURED", JS_NewInt64(ctx, 3));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_UNAUTHORIZED", JS_NewInt64(ctx, 4));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_PARAMETER_RANGE_ERROR", JS_NewInt64(ctx, 5));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_OUT_OF_MEMORY", JS_NewInt64(ctx, 6));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_FILE_NOT_FOUND", JS_NewInt64(ctx, 7));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_FILE_BAD_DRIVE", JS_NewInt64(ctx, 8));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_FILE_BAD_PATH", JS_NewInt64(ctx, 9));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_FILE_NO_PERMISSION", JS_NewInt64(ctx, 10));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_FILE_ALREADY_IN_USE", JS_NewInt64(ctx, 11));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_FILE_CANT_OPEN", JS_NewInt64(ctx, 12));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_FILE_CANT_WRITE", JS_NewInt64(ctx, 13));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_FILE_CANT_READ", JS_NewInt64(ctx, 14));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_FILE_UNRECOGNIZED", JS_NewInt64(ctx, 15));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_FILE_CORRUPT", JS_NewInt64(ctx, 16));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_FILE_MISSING_DEPENDENCIES", JS_NewInt64(ctx, 17));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_FILE_EOF", JS_NewInt64(ctx, 18));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_CANT_OPEN", JS_NewInt64(ctx, 19));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_CANT_CREATE", JS_NewInt64(ctx, 20));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_QUERY_FAILED", JS_NewInt64(ctx, 21));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_ALREADY_IN_USE", JS_NewInt64(ctx, 22));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_LOCKED", JS_NewInt64(ctx, 23));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_TIMEOUT", JS_NewInt64(ctx, 24));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_CANT_CONNECT", JS_NewInt64(ctx, 25));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_CANT_RESOLVE", JS_NewInt64(ctx, 26));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_CONNECTION_ERROR", JS_NewInt64(ctx, 27));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_CANT_ACQUIRE_RESOURCE", JS_NewInt64(ctx, 28));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_CANT_FORK", JS_NewInt64(ctx, 29));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_INVALID_DATA", JS_NewInt64(ctx, 30));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_INVALID_PARAMETER", JS_NewInt64(ctx, 31));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_ALREADY_EXISTS", JS_NewInt64(ctx, 32));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_DOES_NOT_EXIST", JS_NewInt64(ctx, 33));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_DATABASE_CANT_READ", JS_NewInt64(ctx, 34));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_DATABASE_CANT_WRITE", JS_NewInt64(ctx, 35));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_COMPILATION_FAILED", JS_NewInt64(ctx, 36));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_METHOD_NOT_FOUND", JS_NewInt64(ctx, 37));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_LINK_FAILED", JS_NewInt64(ctx, 38));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_SCRIPT_FAILED", JS_NewInt64(ctx, 39));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_CYCLIC_LINK", JS_NewInt64(ctx, 40));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_INVALID_DECLARATION", JS_NewInt64(ctx, 41));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_DUPLICATE_SYMBOL", JS_NewInt64(ctx, 42));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_PARSE_ERROR", JS_NewInt64(ctx, 43));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_BUSY", JS_NewInt64(ctx, 44));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_SKIP", JS_NewInt64(ctx, 45));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_HELP", JS_NewInt64(ctx, 46));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_BUG", JS_NewInt64(ctx, 47));
	JS_SetPropertyStr(ctx, Error_obj, "ERR_PRINTER_ON_FIRE", JS_NewInt64(ctx, 48));
	JS_SetPropertyStr(ctx, global_obj, "Error", Error_obj);
    
	JSValue PropertyHint_obj = JS_NewObject(ctx);
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_NONE", JS_NewInt64(ctx, 0));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_RANGE", JS_NewInt64(ctx, 1));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_ENUM", JS_NewInt64(ctx, 2));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_ENUM_SUGGESTION", JS_NewInt64(ctx, 3));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_EXP_EASING", JS_NewInt64(ctx, 4));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_LINK", JS_NewInt64(ctx, 5));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_FLAGS", JS_NewInt64(ctx, 6));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_LAYERS_2D_RENDER", JS_NewInt64(ctx, 7));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_LAYERS_2D_PHYSICS", JS_NewInt64(ctx, 8));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_LAYERS_2D_NAVIGATION", JS_NewInt64(ctx, 9));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_LAYERS_3D_RENDER", JS_NewInt64(ctx, 10));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_LAYERS_3D_PHYSICS", JS_NewInt64(ctx, 11));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_LAYERS_3D_NAVIGATION", JS_NewInt64(ctx, 12));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_LAYERS_AVOIDANCE", JS_NewInt64(ctx, 37));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_FILE", JS_NewInt64(ctx, 13));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_DIR", JS_NewInt64(ctx, 14));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_GLOBAL_FILE", JS_NewInt64(ctx, 15));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_GLOBAL_DIR", JS_NewInt64(ctx, 16));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_RESOURCE_TYPE", JS_NewInt64(ctx, 17));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_MULTILINE_TEXT", JS_NewInt64(ctx, 18));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_EXPRESSION", JS_NewInt64(ctx, 19));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_PLACEHOLDER_TEXT", JS_NewInt64(ctx, 20));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_COLOR_NO_ALPHA", JS_NewInt64(ctx, 21));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_OBJECT_ID", JS_NewInt64(ctx, 22));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_TYPE_STRING", JS_NewInt64(ctx, 23));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_NODE_PATH_TO_EDITED_NODE", JS_NewInt64(ctx, 24));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_OBJECT_TOO_BIG", JS_NewInt64(ctx, 25));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_NODE_PATH_VALID_TYPES", JS_NewInt64(ctx, 26));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_SAVE_FILE", JS_NewInt64(ctx, 27));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_GLOBAL_SAVE_FILE", JS_NewInt64(ctx, 28));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_INT_IS_OBJECTID", JS_NewInt64(ctx, 29));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_INT_IS_POINTER", JS_NewInt64(ctx, 30));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_ARRAY_TYPE", JS_NewInt64(ctx, 31));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_LOCALE_ID", JS_NewInt64(ctx, 32));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_LOCALIZABLE_STRING", JS_NewInt64(ctx, 33));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_NODE_TYPE", JS_NewInt64(ctx, 34));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_HIDE_QUATERNION_EDIT", JS_NewInt64(ctx, 35));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_PASSWORD", JS_NewInt64(ctx, 36));
	JS_SetPropertyStr(ctx, PropertyHint_obj, "PROPERTY_HINT_MAX", JS_NewInt64(ctx, 38));
	JS_SetPropertyStr(ctx, global_obj, "PropertyHint", PropertyHint_obj);
    
	JSValue PropertyUsageFlags_obj = JS_NewObject(ctx);
	JS_SetPropertyStr(ctx, PropertyUsageFlags_obj, "PROPERTY_USAGE_NONE", JS_NewInt64(ctx, 0));
	JS_SetPropertyStr(ctx, PropertyUsageFlags_obj, "PROPERTY_USAGE_STORAGE", JS_NewInt64(ctx, 2));
	JS_SetPropertyStr(ctx, PropertyUsageFlags_obj, "PROPERTY_USAGE_EDITOR", JS_NewInt64(ctx, 4));
	JS_SetPropertyStr(ctx, PropertyUsageFlags_obj, "PROPERTY_USAGE_INTERNAL", JS_NewInt64(ctx, 8));
	JS_SetPropertyStr(ctx, PropertyUsageFlags_obj, "PROPERTY_USAGE_CHECKABLE", JS_NewInt64(ctx, 16));
	JS_SetPropertyStr(ctx, PropertyUsageFlags_obj, "PROPERTY_USAGE_CHECKED", JS_NewInt64(ctx, 32));
	JS_SetPropertyStr(ctx, PropertyUsageFlags_obj, "PROPERTY_USAGE_GROUP", JS_NewInt64(ctx, 64));
	JS_SetPropertyStr(ctx, PropertyUsageFlags_obj, "PROPERTY_USAGE_CATEGORY", JS_NewInt64(ctx, 128));
	JS_SetPropertyStr(ctx, PropertyUsageFlags_obj, "PROPERTY_USAGE_SUBGROUP", JS_NewInt64(ctx, 256));
	JS_SetPropertyStr(ctx, PropertyUsageFlags_obj, "PROPERTY_USAGE_CLASS_IS_BITFIELD", JS_NewInt64(ctx, 512));
	JS_SetPropertyStr(ctx, PropertyUsageFlags_obj, "PROPERTY_USAGE_NO_INSTANCE_STATE", JS_NewInt64(ctx, 1024));
	JS_SetPropertyStr(ctx, PropertyUsageFlags_obj, "PROPERTY_USAGE_RESTART_IF_CHANGED", JS_NewInt64(ctx, 2048));
	JS_SetPropertyStr(ctx, PropertyUsageFlags_obj, "PROPERTY_USAGE_SCRIPT_VARIABLE", JS_NewInt64(ctx, 4096));
	JS_SetPropertyStr(ctx, PropertyUsageFlags_obj, "PROPERTY_USAGE_STORE_IF_NULL", JS_NewInt64(ctx, 8192));
	JS_SetPropertyStr(ctx, PropertyUsageFlags_obj, "PROPERTY_USAGE_UPDATE_ALL_IF_MODIFIED", JS_NewInt64(ctx, 16384));
	JS_SetPropertyStr(ctx, PropertyUsageFlags_obj, "PROPERTY_USAGE_SCRIPT_DEFAULT_VALUE", JS_NewInt64(ctx, 32768));
	JS_SetPropertyStr(ctx, PropertyUsageFlags_obj, "PROPERTY_USAGE_CLASS_IS_ENUM", JS_NewInt64(ctx, 65536));
	JS_SetPropertyStr(ctx, PropertyUsageFlags_obj, "PROPERTY_USAGE_NIL_IS_VARIANT", JS_NewInt64(ctx, 131072));
	JS_SetPropertyStr(ctx, PropertyUsageFlags_obj, "PROPERTY_USAGE_ARRAY", JS_NewInt64(ctx, 262144));
	JS_SetPropertyStr(ctx, PropertyUsageFlags_obj, "PROPERTY_USAGE_ALWAYS_DUPLICATE", JS_NewInt64(ctx, 524288));
	JS_SetPropertyStr(ctx, PropertyUsageFlags_obj, "PROPERTY_USAGE_NEVER_DUPLICATE", JS_NewInt64(ctx, 1048576));
	JS_SetPropertyStr(ctx, PropertyUsageFlags_obj, "PROPERTY_USAGE_HIGH_END_GFX", JS_NewInt64(ctx, 2097152));
	JS_SetPropertyStr(ctx, PropertyUsageFlags_obj, "PROPERTY_USAGE_NODE_PATH_FROM_SCENE_ROOT", JS_NewInt64(ctx, 4194304));
	JS_SetPropertyStr(ctx, PropertyUsageFlags_obj, "PROPERTY_USAGE_RESOURCE_NOT_PERSISTENT", JS_NewInt64(ctx, 8388608));
	JS_SetPropertyStr(ctx, PropertyUsageFlags_obj, "PROPERTY_USAGE_KEYING_INCREMENTS", JS_NewInt64(ctx, 16777216));
	JS_SetPropertyStr(ctx, PropertyUsageFlags_obj, "PROPERTY_USAGE_DEFERRED_SET_RESOURCE", JS_NewInt64(ctx, 33554432));
	JS_SetPropertyStr(ctx, PropertyUsageFlags_obj, "PROPERTY_USAGE_EDITOR_INSTANTIATE_OBJECT", JS_NewInt64(ctx, 67108864));
	JS_SetPropertyStr(ctx, PropertyUsageFlags_obj, "PROPERTY_USAGE_EDITOR_BASIC_SETTING", JS_NewInt64(ctx, 134217728));
	JS_SetPropertyStr(ctx, PropertyUsageFlags_obj, "PROPERTY_USAGE_READ_ONLY", JS_NewInt64(ctx, 268435456));
	JS_SetPropertyStr(ctx, PropertyUsageFlags_obj, "PROPERTY_USAGE_SECRET", JS_NewInt64(ctx, 536870912));
	JS_SetPropertyStr(ctx, PropertyUsageFlags_obj, "PROPERTY_USAGE_DEFAULT", JS_NewInt64(ctx, 6));
	JS_SetPropertyStr(ctx, PropertyUsageFlags_obj, "PROPERTY_USAGE_NO_EDITOR", JS_NewInt64(ctx, 2));
	JS_SetPropertyStr(ctx, global_obj, "PropertyUsageFlags", PropertyUsageFlags_obj);
    
	JSValue MethodFlags_obj = JS_NewObject(ctx);
	JS_SetPropertyStr(ctx, MethodFlags_obj, "METHOD_FLAG_NORMAL", JS_NewInt64(ctx, 1));
	JS_SetPropertyStr(ctx, MethodFlags_obj, "METHOD_FLAG_EDITOR", JS_NewInt64(ctx, 2));
	JS_SetPropertyStr(ctx, MethodFlags_obj, "METHOD_FLAG_CONST", JS_NewInt64(ctx, 4));
	JS_SetPropertyStr(ctx, MethodFlags_obj, "METHOD_FLAG_VIRTUAL", JS_NewInt64(ctx, 8));
	JS_SetPropertyStr(ctx, MethodFlags_obj, "METHOD_FLAG_VARARG", JS_NewInt64(ctx, 16));
	JS_SetPropertyStr(ctx, MethodFlags_obj, "METHOD_FLAG_STATIC", JS_NewInt64(ctx, 32));
	JS_SetPropertyStr(ctx, MethodFlags_obj, "METHOD_FLAG_OBJECT_CORE", JS_NewInt64(ctx, 64));
	JS_SetPropertyStr(ctx, MethodFlags_obj, "METHOD_FLAGS_DEFAULT", JS_NewInt64(ctx, 1));
	JS_SetPropertyStr(ctx, global_obj, "MethodFlags", MethodFlags_obj);
    
    
    JSValue Type_obj = JS_NewObject(ctx);
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_NIL", JS_NewInt64(ctx, 0));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_BOOL", JS_NewInt64(ctx, 1));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_INT", JS_NewInt64(ctx, 2));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_FLOAT", JS_NewInt64(ctx, 3));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_STRING", JS_NewInt64(ctx, 4));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_VECTOR2", JS_NewInt64(ctx, 5));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_VECTOR2I", JS_NewInt64(ctx, 6));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_RECT2", JS_NewInt64(ctx, 7));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_RECT2I", JS_NewInt64(ctx, 8));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_VECTOR3", JS_NewInt64(ctx, 9));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_VECTOR3I", JS_NewInt64(ctx, 10));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_TRANSFORM2D", JS_NewInt64(ctx, 11));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_VECTOR4", JS_NewInt64(ctx, 12));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_VECTOR4I", JS_NewInt64(ctx, 13));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_PLANE", JS_NewInt64(ctx, 14));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_QUATERNION", JS_NewInt64(ctx, 15));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_AABB", JS_NewInt64(ctx, 16));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_BASIS", JS_NewInt64(ctx, 17));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_TRANSFORM3D", JS_NewInt64(ctx, 18));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_PROJECTION", JS_NewInt64(ctx, 19));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_COLOR", JS_NewInt64(ctx, 20));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_STRING_NAME", JS_NewInt64(ctx, 21));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_NODE_PATH", JS_NewInt64(ctx, 22));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_RID", JS_NewInt64(ctx, 23));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_OBJECT", JS_NewInt64(ctx, 24));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_CALLABLE", JS_NewInt64(ctx, 25));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_SIGNAL", JS_NewInt64(ctx, 26));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_DICTIONARY", JS_NewInt64(ctx, 27));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_ARRAY", JS_NewInt64(ctx, 28));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_PACKED_BYTE_ARRAY", JS_NewInt64(ctx, 29));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_PACKED_INT32_ARRAY", JS_NewInt64(ctx, 30));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_PACKED_INT64_ARRAY", JS_NewInt64(ctx, 31));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_PACKED_FLOAT32_ARRAY", JS_NewInt64(ctx, 32));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_PACKED_FLOAT64_ARRAY", JS_NewInt64(ctx, 33));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_PACKED_STRING_ARRAY", JS_NewInt64(ctx, 34));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_PACKED_VECTOR2_ARRAY", JS_NewInt64(ctx, 35));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_PACKED_VECTOR3_ARRAY", JS_NewInt64(ctx, 36));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_PACKED_COLOR_ARRAY", JS_NewInt64(ctx, 37));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_PACKED_VECTOR4_ARRAY", JS_NewInt64(ctx, 38));
	JS_SetPropertyStr(ctx, Type_obj, "TYPE_MAX", JS_NewInt64(ctx, 39));
	JS_SetPropertyStr(ctx, global_obj, "Type", Type_obj);
    
    
    JSValue Operator_obj = JS_NewObject(ctx);
	JS_SetPropertyStr(ctx, Operator_obj, "OP_EQUAL", JS_NewInt64(ctx, 0));
	JS_SetPropertyStr(ctx, Operator_obj, "OP_NOT_EQUAL", JS_NewInt64(ctx, 1));
	JS_SetPropertyStr(ctx, Operator_obj, "OP_LESS", JS_NewInt64(ctx, 2));
	JS_SetPropertyStr(ctx, Operator_obj, "OP_LESS_EQUAL", JS_NewInt64(ctx, 3));
	JS_SetPropertyStr(ctx, Operator_obj, "OP_GREATER", JS_NewInt64(ctx, 4));
	JS_SetPropertyStr(ctx, Operator_obj, "OP_GREATER_EQUAL", JS_NewInt64(ctx, 5));
	JS_SetPropertyStr(ctx, Operator_obj, "OP_ADD", JS_NewInt64(ctx, 6));
	JS_SetPropertyStr(ctx, Operator_obj, "OP_SUBTRACT", JS_NewInt64(ctx, 7));
	JS_SetPropertyStr(ctx, Operator_obj, "OP_MULTIPLY", JS_NewInt64(ctx, 8));
	JS_SetPropertyStr(ctx, Operator_obj, "OP_DIVIDE", JS_NewInt64(ctx, 9));
	JS_SetPropertyStr(ctx, Operator_obj, "OP_NEGATE", JS_NewInt64(ctx, 10));
	JS_SetPropertyStr(ctx, Operator_obj, "OP_POSITIVE", JS_NewInt64(ctx, 11));
	JS_SetPropertyStr(ctx, Operator_obj, "OP_MODULE", JS_NewInt64(ctx, 12));
	JS_SetPropertyStr(ctx, Operator_obj, "OP_POWER", JS_NewInt64(ctx, 13));
	JS_SetPropertyStr(ctx, Operator_obj, "OP_SHIFT_LEFT", JS_NewInt64(ctx, 14));
	JS_SetPropertyStr(ctx, Operator_obj, "OP_SHIFT_RIGHT", JS_NewInt64(ctx, 15));
	JS_SetPropertyStr(ctx, Operator_obj, "OP_BIT_AND", JS_NewInt64(ctx, 16));
	JS_SetPropertyStr(ctx, Operator_obj, "OP_BIT_OR", JS_NewInt64(ctx, 17));
	JS_SetPropertyStr(ctx, Operator_obj, "OP_BIT_XOR", JS_NewInt64(ctx, 18));
	JS_SetPropertyStr(ctx, Operator_obj, "OP_BIT_NEGATE", JS_NewInt64(ctx, 19));
	JS_SetPropertyStr(ctx, Operator_obj, "OP_AND", JS_NewInt64(ctx, 20));
	JS_SetPropertyStr(ctx, Operator_obj, "OP_OR", JS_NewInt64(ctx, 21));
	JS_SetPropertyStr(ctx, Operator_obj, "OP_XOR", JS_NewInt64(ctx, 22));
	JS_SetPropertyStr(ctx, Operator_obj, "OP_NOT", JS_NewInt64(ctx, 23));
	JS_SetPropertyStr(ctx, Operator_obj, "OP_IN", JS_NewInt64(ctx, 24));
	JS_SetPropertyStr(ctx, Operator_obj, "OP_MAX", JS_NewInt64(ctx, 25));
	JS_SetPropertyStr(ctx, global_obj, "Operator", Operator_obj);
    
}